// Greek lang variables by Jacaranda Bill

tinyMCE.addToLang('',{
bold_desc : '¸íôïíç ãñá&ouml;Þ',
italic_desc : 'ÐëÜãéá ãñá&ouml;Þ',
underline_desc : 'ÕðïãñÜììéóç',
striketrough_desc : '&Auml;éáêñéôÞ &auml;éáãñá&ouml;Þ',
justifyleft_desc : 'Óôïß÷éóç áñéóô&aring;ñÜ',
justifycenter_desc : 'Óôïß÷éóç óôï êÝíôñï',
justifyright_desc : 'Óôïß÷éóç &auml;&aring;îéÜ',
justifyfull_desc : 'ÐëÞñçò óôïß÷éóç',
bullist_desc : 'Êïõêêß&auml;&aring;ò',
numlist_desc : 'Áñßèìçóç',
outdent_desc : 'Ì&aring;ßùóç &aring;óï÷Þò',
indent_desc : 'Áýîçóç &aring;óï÷Þò',
undo_desc : 'Áíáßñ&aring;óç',
redo_desc : 'Áêýñùóç áíáßñ&aring;óçò',
link_desc : '&Auml;çìéïõñãßá/&Auml;éüñèùóç õð&aring;ñ-óýí&auml;&aring;óçò',
unlink_desc : '&Auml;éáãñá&ouml;Þ õð&aring;ñ-óýí&auml;&aring;óçò',
image_desc : '&Aring;éóáãùãÞ/&Auml;éüñèùóç &aring;éêüíáò',
cleanup_desc : 'ÊáèÜñéóìá êþ&auml;éêá',
focus_alert : 'ÐñÝð&aring;é íá õðÜñ÷&aring;é &aring;í&aring;ñãüò êÜðïéïò &aring;ð&aring;î&aring;ñãáóôÞò ê&aring;éìÝíïõ ðñéí íá ÷ñçóéìïðïéÞó&aring;ô&aring; áõôÞ ôçí &aring;íôïëÞ.',
edit_confirm : 'ÈÝë&aring;ô&aring; íá ÷ñçóéìïðïéÞó&aring;ô&aring; ôçí êáôÜóôáóç WYSIWYG ãéá ôï óõãê&aring;êñéìÝíï ðëáßóéï ê&aring;éìÝíïõ;',
insert_link_title : '&Auml;çìéïõñãßá/&Auml;éüñèùóç õð&aring;ñ-óýí&auml;&aring;óçò',
insert : '&Aring;éóáãùãÞ',
update : '&Aring;éóáãùãÞ',
cancel : 'Áêýñùóç',
insert_link_url : '&Auml;é&aring;ýèõíóç',
insert_link_target : 'Óôü÷ïò',
insert_link_target_same : '¢íïéãìá ôçò &auml;é&aring;ýèõíóçò óôï ß&auml;éï ðáñÜèõñï',
insert_link_target_blank : '¢íïéãìá ôçò &auml;é&aring;ýèõíóçò ó&aring; íÝï ðáñÜèõñï',
insert_image_title : '&Aring;éóáãùãÞ/&Auml;éüñèùóç &aring;éêüíáò',
insert_image_src : '&Auml;é&aring;ýèõíóç',
insert_image_alt : 'Ð&aring;ñéãñá&ouml;Þ',
help_desc : 'ÂïÞè&aring;éá',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
popup_blocked : 'Sorry, but we have noticed that your popup-blocker has disabled a window that provides application functionality. You will need to disable popup blocking on this site in order to fully utilize this tool.'
});
