// HE lang variables by Liron Newman, http://eesh.net

tinyMCE.addToLang('',{
bold_desc : 'îåãâù (Ctrl+B)',
italic_desc : 'ðèåé (Ctrl+I)',
underline_desc : '÷å úçúé (Ctrl+U)',
striketrough_desc : '÷å çåöä',
justifyleft_desc : 'éùø ìùîàì',
justifycenter_desc : 'éùø ìîøëæ',
justifyright_desc : 'éùø ìéîéï',
justifyfull_desc : 'éùø ìùðé äöããéí',
bullist_desc : 'øùéîä çñøú ñãø',
numlist_desc : 'øùéîä îñåãøú',
outdent_desc : 'ä÷èï ëðéñä',
indent_desc : 'äâãì ëðéñä',
undo_desc : 'áèì (Ctrl+Z)',
redo_desc : 'áöò ùåá (Ctrl+Y)',
link_desc : 'äëðñ/òøåê ÷éùåø',
unlink_desc : 'áèì ÷éùåø',
image_desc : 'äëðñ/òøåê úîåðä',
cleanup_desc : 'ð÷ä ÷åã îáåìâï',
focus_alert : 'éù ìáçåø áùãä òøéëä ìôðé ùðéúï ìäùúîù áô÷åãä æå.',
edit_confirm : 'äàí áøöåðê ìäùúîù áîöá òøéëä òùéøä (WYSIWYG) òáåø ùãä è÷ñè æä?',
insert_link_title : 'äëðñ/òøåê ÷éùåø',
insert : 'äëðñ',
update : 'òãëï',
cancel : 'áèì',
insert_link_url : 'ëúåáú (URL) ä÷éùåø',
insert_link_target : 'éòã',
insert_link_target_same : 'ôúç àú ä÷éùåø áàåúå çìåï',
insert_link_target_blank : 'ôúç àú ä÷éùåø áçìåï çãù',
insert_image_title : 'äëðñ/òøåê úîåðä',
insert_image_src : 'ëúåáú (URL) äúîåðä',
insert_image_alt : 'úéàåø äúîåðä',
help_desc : 'òæøä',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'ôòåìåú äòú÷ä/âæéøä/äãá÷ä àéðï ðúîëåú úçú Mozilla å-Firefox.\näàí áøöåðê ì÷áì îéãò ðåñó àåãåú ðåùà æä?',
popup_blocked : 'ñìéçä, àê ùîðå ìá ëé çåñí äçìåðåú ä÷åôöéí ùìê çñí çìåï ùîäååä çì÷ îäééùåí. úöèøê ìáèì àú çñéîú äçìåðåú ä÷åôöéí áàúø æä ëãé ìðöì ëìé æä áîìåàå.'
});
