<?php include "../config.php"; ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<title>SAXON</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta name="keywords" content="news rss" />
<meta name="Description" content="Saxon - A Simple Accessible Xhtml Online News System" />
<meta name="author" content="esmi" />
<meta name="copyright" content="Copyright 2004 quirm.net. Most rights reserved." />
<link rel="alternate" type="application/rss+xml" title="RSS" href="<?php echo $uri.$path.$xml_filename; ?>" />
<link rel="stylesheet" href="news-display.css" type="text/css" media="screen" />
</head>
<body>
<div class="xml">
<a href="<?php echo $uri.$path.$xml_filename; ?>"><img src="xml.gif" width="36" height="14" alt="XML Feed for syndication" /></a>
</div>
<h1>News</h1>

<?php include "../news.php"; ?>

<div class="archive-link"><a href="archive.php">Full News Archive</a></div>

<div id="footer">
<a href="http://feedvalidator.org/check.cgi?url=<?php echo $uri.$path.$xml_filename; ?>">
<img src="valid-rss.png" alt="[Valid RSS]" title="Validate my RSS feed" width="88" height="31" /></a><br />
Generated by <a href="http://www.quirm.net/saxon/" title="Simple Accessible XML Online News">SAXON</a>
</div>
</body>
</html>