<?php
/*
=====================================================
 ExpressionEngine - by pMachine
-----------------------------------------------------
 Nullified by GTT
-----------------------------------------------------
 Copyright (c) 2003 - 2004 pMachine, Inc.
=====================================================
 THIS IS COPYRIGHTED SOFTWARE
 PLEASE READ THE LICENSE AGREEMENT
=====================================================
 File: languages.php
-----------------------------------------------------
 Purpose: List of xml langauges
=====================================================
*/

	$languages = array(		
						'Afar'				=>	'aa',
						'Abkhazian'			=>	'ab',
						'Afrikaans'			=>	'af',
						'Amharic'			=>	'am',
						'Arabic'			=>	'ar',
						'Assamese'			=>	'as',
						'Aymara'			=>	'ay',
						'Azerbaijani'			=>	'az',
						'Bashkir'			=>	'ba',
						'Byelorussian'			=>	'be',
						'Bulgarian'			=>	'bg',
						'Bihari'			=>	'bh',
						'Bislama'			=>	'bi',
						'Bengali/Bangla'		=>	'bn',
						'Tibetan'			=>	'bo',
						'Breton'			=>	'br',
						'Catalan'			=>	'ca',
						'Corsican'			=>	'co',
						'Czech'				=>	'cs',
						'Welsh'				=>	'cy',
						'Danish'			=>	'da',
						'German'			=>	'de',
						'Bhutani'			=>	'dz',
						'Greek'				=>	'el',
						'English'			=>	'en',
						'Esperanto'			=>	'eo',
						'Spanish'			=>	'es',
						'Estonian'			=>	'et',
						'Basque'			=>	'eu',
						'Persian (Farsi)'		=>	'fa',
						'Finnish'			=>	'fi',
						'Fiji'				=>	'fj',
						'Faroese'			=>	'fo',
						'French'			=>	'fr',
						'Frisian'			=>	'fy',
						'Irish'				=>	'ga',
						'Gaelic'			=>	'gd',
						'Galician'			=>	'gl',
						'Guarani'			=>	'gn',
						'Gujarati'			=>	'gu',
						'Hausa'				=>	'ha',
						'Hebrew'			=>	'he',
						'Hindi'				=>	'hi',
						'Croatian'			=>	'hr',
						'Hungarian'			=>	'hu',
						'Armenian'			=>	'hy',
						'Interlingua'			=>	'ia',
						'Interlingue'			=>	'ie',
						'Inupiak'			=>	'ik',
						'Indonesian'			=>	'id',
						'Icelandic'			=>	'is',
						'Italian'			=>	'it',
						'Inuktitut'			=>	'iu',
						'Japanese'			=>	'ja',
						'Javanese'			=>	'jv',
						'Georgian'			=>	'ka',
						'Kazakh'			=>	'kk',
						'Greenlandic'			=>	'kl',
						'Cambodian'			=>	'km',
						'Kannada'			=>	'kn',
						'Korean'			=>	'ko',
						'Kashmiri'			=>	'ks',
						'Kurdish'			=>	'ku',
						'Kirghiz'			=>	'ky',
						'Latin'				=>	'la',
						'Lingala'			=>	'ln',
						'Laothian'			=>	'lo',
						'Lithuanian'			=>	'lt',
						'Latvian;Lettish'		=>	'lv',
						'Malagasy'			=>	'mg',
						'Maori'				=>	'mi',
						'Macedonian'			=>	'mk',
						'Malayalam'			=>	'ml',
						'Mongolian'			=>	'mn',
						'Moldavian'			=>	'mo',
						'Marathi'			=>	'mr',
						'Malay'				=>	'ms',
						'Maltese'			=>	'mt',
						'Burmese'			=>	'my',
						'Nauru'				=>	'na',
						'Nepali'			=>	'ne',
						'Dutch'				=>	'nl',
						'Norwegian'			=>	'no',
						'Occitan'			=>	'oc',
						'Afan (Oromo)'			=>	'om',
						'Oriya'				=>	'or',
						'Punjabi'			=>	'pa',
						'Polish'			=>	'pl',
						'Pashto/Pushto'			=>	'ps',
						'Portuguese'			=>	'pt',
						'Quechua'			=>	'qu',
						'Rhaeto-Romance'		=>	'rm',
						'Kurundi'			=>	'rn',
						'Romanian'			=>	'ro',
						'Russian'			=>	'ru',
						'Kinyarwanda'			=>	'rw',
						'Sanskrit'			=>	'sa',
						'Sindhi'			=>	'sd',
						'Sangho'			=>	'sg',
						'Serbo-Croatian'		=>	'sh',
						'Singhalese'			=>	'si',
						'Slovak'			=>	'sk',
						'Slovenian'			=>	'sl',
						'Samoan'			=>	'sm',
						'Shona'				=>	'sn',
						'Somali'			=>	'so',
						'Albanian'			=>	'sq',
						'Serbian'			=>	'sr',
						'Siswati'			=>	'ss',
						'Sesotho'			=>	'st',
						'Sundanese'			=>	'su',
						'Swedish'			=>	'sv',
						'Swahili'			=>	'sw',
						'Tamil'				=>	'ta',
						'Telugu'			=>	'te',
						'Tajik'				=>	'tg',
						'Thai'				=>	'th',
						'Tigrinya'			=>	'ti',
						'Turkmen'			=>	'tk',
						'Tagalog'			=>	'tl',
						'Setswana'			=>	'tn',
						'Tonga'				=>	'to',
						'Turkish'			=>	'tr',
						'Tsonga'			=>	'ts',
						'Tatar'				=>	'tt',
						'Twi'				=>	'tw',
						'Uigur'				=>	'ug',
						'Ukrainian'			=>	'uk',
						'Urdu'				=>	'ur',
						'Uzbek'				=>	'uz',
						'Vietnamese'			=>	'vi',
						'Volapuk'			=>	'vo',
						'Wolof'				=>	'wo',
						'Xhosa'				=>	'xh',
						'Yiddish'			=>	'yi',
						'Yoruba'			=>	'yo',
						'Zhuang'			=>	'za',
						'Chinese'			=>	'zh',
						'Zulu'				=>	'zu'
						);
?>