// TH lang variables Thai contributed by Innozent

tinyMCE.addToLang('',{
bold_desc : 'µÑÇË¹Ò',
italic_desc : 'µÑÇéàÍÕÂ§',
underline_desc : '¢Õ´àÊé¹ãµé',
striketrough_desc : '¢Õ´¤&Aring;èÍÁ',
justifyleft_desc : 'ªÔ´¢Íº«éÒÂ',
justifycenter_desc : '¡&Ouml;è§¡&Aring;Ò§',
justifyright_desc : 'ªÔ´¢Íº¢ÇÒ',
justifyfull_desc : '¨Ñ´ªÔ´¢Íº',
bullist_desc : 'ÊÑ­&Aring;Ñ¡É³ìáÊ´§ËÑÇ¢éÍÂèÍÂ',
numlist_desc : '&Aring;Ó´Ñºà&Aring;¢',
outdent_desc : '&Aring;´¡ÒÃàÂ×éÍ§',
indent_desc : 'à¾ÔèÁ¡ÒÃàÂ×éÍ§',
undo_desc : 'à&Aring;Ô¡·Ó',
redo_desc : '·ÓãËÁè',
link_desc : 'à¾ÔèÁ&Aring;Ô§¤ì',
unlink_desc : '&Aring;º&Aring;Ô§¤ì',
image_desc : 'ãÊèÃÙ»',
cleanup_desc : '·Ó¤ÇÒÁÊÐÍÒ´¢éÍ¤ÇÒÁ',
focus_alert : 'µéÍ§à&Aring;×Í¡¡&Aring;èÍ§¢éÍ¤ÇÒÁ¡èÍ¹·Õè¨Ðãªé¤ÓÊÑè§¹Õé',
edit_confirm : '¤Ø³µéÍ§¡ÒÃ·Õè¨Ðãªé WYSIWYG mode ÊÓËÃÑº¡&Aring;èÍ§¢éÍ¤ÇÒÁ¹ÕéËÃ×Í&auml;Áè?',
insert_link_title : 'à¾ÔèÁ/á¡é&auml;¢ &Aring;Ô§¤ì',
insert : 'à¾ÔèÁ',
cancel : 'Â¡à&Aring;Ô¡',
insert_link_url : 'Link URL',
insert_link_target : 'à»Ô´&Aring;Ô§¤ìã¹',
insert_link_target_same : 'Ë¹éÒµèÒ§à´ÕÂÇ¡Ñ¹',
insert_link_target_blank : 'Ë¹éÒµèÒ§ãËÁè',
insert_image_title : 'à¾ÔèÁ/á¡é&auml;¢ ÃÙ»',
insert_image_src : 'URL ¢Í§ÃÙ»',
insert_image_alt : '¤ÓÍ¸ÔºÒÂÃÙ»',
help_desc : 'ªèÇÂàË&Aring;×Í',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
popup_blocked : 'Sorry, but we have noticed that your popup-blocker has disabled a window that provides application functionality. You will need to disable popup blocking on this site in order to fully utilize this tool.'
});
