<table width="100%" border="0" cellspacing="1" cellpadding="0">
  <tr>
    <td align="center" valign="top" class="admintext">Modules</td>
  </tr>
  <tr>
    <td bgcolor="#333333">
      <table width="100%" border="0" cellspacing="1" cellpadding="1" height="100%">
        <tr>
          <td align="center" valign="top" bgcolor="#FFFFFF"><a href="admin.php">Main</a></td>
        </tr>
        <tr>
          <td align="center" valign="top" bgcolor="#FFFFFF"><a href="cfile.php">Create File</a></td>
        </tr>
        <tr>
          <td align="center" valign="top" bgcolor="#FFFFFF"><a href="efile.php">Edit File</a></td>
        </tr>
        <tr>
          <td align="center" valign="top" bgcolor="#FFFFFF"><a href="dpfile.php">Duplicate File</a></td>
        </tr>
        <tr>
          <td align="center" valign="top" bgcolor="#FFFFFF"><a href="mfile.php">Move File</a></td>
        </tr>
        <tr>
          <td align="center" valign="top" bgcolor="#FFFFFF"><a href="rnfile.php">Rename File</a></td>
        </tr>
        <tr>
          <td align="center" valign="top" bgcolor="#FFFFFF"><a href="dfile.php">Delete File</a></td>
        </tr>
        <tr>
          <td align="center" valign="top" bgcolor="#FFFFFF"><a href="ufile.php">Upload File</a></td>
        </tr>
        <tr>
          <td align="center" valign="top" bgcolor="#FFFFFF"><a href="chmod.php">CHMOD File</a></td>
        </tr>
        <tr>
          <td align="center" valign="top" bgcolor="#FFFFFF"><a href="cdir.php">Create Dir.</a></td>
        </tr>
        <tr>
          <td align="center" valign="top" bgcolor="#FFFFFF"><a href="ddir.php">Delete Dir.</a></td>
        </tr>
        <tr>
          <td align="center" valign="top" bgcolor="#FFFFFF"><a href="cpass.php">Change Pass</a></td>
        </tr>
        <tr>
          <td align="center" valign="top" bgcolor="#FFFFFF"><a href="logout.php">Logout</a></td>
        </tr>
      </table>
    </td>
  </tr>
</table>

<br>

<table width="100%" border="0" cellspacing="1" cellpadding="0">
  <tr>
    <td align="center" valign="top" class="admintext">EA Related</td>
  </tr>
  <tr>
    <td bgcolor="#333333">
      <table width="100%" border="0" cellspacing="1" cellpadding="1" height="100%">
        <tr>
          <td align="center" valign="top" bgcolor="#FFFFFF"><a href="efile.php?efileaction=edit&fname=incs/eacss.inc">CSS</a></td>
        </tr>
        <tr>
          <td align="center" valign="top" bgcolor="#FFFFFF"><a href="efile.php?efileaction=edit&fname=incs/footer.inc">Footer</a></td>
        </tr>
        <tr>
          <td align="center" valign="top" bgcolor="#FFFFFF"><a href="efile.php?efileaction=edit&fname=incs/module-list.inc">Nav.</a></td>
        </tr>
      </table>
    </td>
  </tr>
</table>

<br>

<table width="100%" border="0" cellspacing="1" cellpadding="0">
  <tr>
    <td align="center" valign="top" class="admintext">Dev. Links</td>
  </tr>
  <tr>
    <td bgcolor="#333333">
      <table width="100%" border="0" cellspacing="1" cellpadding="1" height="100%">
        <tr>
          <td align="center" valign="top" bgcolor="#FFFFFF"><a href="http://www.php.net">PHP</a></td>
        </tr>
        <tr>
          <td align="center" valign="top" bgcolor="#FFFFFF"><a href="http://www.devshed.com">Devshed</a></td>
        </tr>
        <tr>
          <td align="center" valign="top" bgcolor="#FFFFFF"><a href="http://www.mysql.com">Mysql</a></td>
        </tr>
        <tr>
          <td align="center" valign="top" bgcolor="#FFFFFF"><a href="http://www.gimp.org">GIMP</a></td>
        </tr>
      </table>
    </td>
  </tr>
</table>