<?php

// skin_category.php
// Skin file auto generated by RW::Download v4.0 Beta 3 [13/07/04]
// It is highly recommended you do NOT edit this file
// Doing so could break the skinning engine and the script
// This skin can be edited by using the Skin Controls in the Admin CP

class skin_category
{
function cat_head($data)
{
global $rwdInfo;
//--START--//

$SHTML .= <<<RWS
RWS;
//--END--//
return $SHTML;
}

function cat_foot($data)
{
global $rwdInfo;
//--START--//

$SHTML .= <<<RWS
RWS;
//--END--//
return $SHTML;
}

function cat_row($data)
{
global $rwdInfo;
//--START--//

$SHTML .= <<<RWS

<div class='tableborder'>
<div id="banner">
  <img id="leftcap" src="{$rwdInfo->skinurl}/images/headerleft.gif" width="18" height="29">
  <img id="rightcap" src="{$rwdInfo->skinurl}/images/headerright.gif" width="31" height="29">
  <div id='catname'>{$data['cat_name']}</div>
</div>
<table width='100%'  border='0' align='center' cellpadding='0' cellspacing='0'>

          <tr>
            <td>
			
			<table width='100%'  border='0' cellspacing='1' cellpadding='3'>
				<tr class='mainrow'>
	                  <td rowspan='2' width='120'><div align='center'>{$data['cat_thumb']}</div></td>
	                  <td>{$data['cat_desc']}</td>
					 </tr>
				  <tr class='mainrow'>
					  <td valign='bottom'>
					  <table width='100%'  border='0' cellspacing='0' cellpadding='0'>
					      <tr>
					        <td width='120'><strong>{$rwdInfo->lang['latestdl']}: </strong></td>
					        <td>{$data['cat_latest']}</td>
					      </tr>
					      <tr>
					        <td><strong>{$rwdInfo->lang['downloads']}: </strong></td>
					        <td>{$data['cat_dlcount']}</td>
					      </tr>
RWS;
//startif
if ( $data['cat_subcats'] )
{
$SHTML .= <<<RWS
<tr>
					        <td valign='bottom'><strong>{$rwdInfo->lang['subcategories']}: </strong></td>
					        <td valign='bottom'>{$data['cat_subcats']}</td>
					      </tr>
RWS;
}//endif
$SHTML .= <<<RWS
					    </table>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table></div>
RWS;
//--END--//
return $SHTML;
}

}

?>
