<?php 

// skin_files.php
// Skin file auto generated by RW::Download v4.0 lite
// It is highly recommended you do NOT edit this file
// Doing so could break the skinning engine and the script
// This skin can be edited by using the Skin Controls in the Admin CP

class skin_files
{
function mirrorrow($data=NULL)
{
global $rwdInfo;
//--START--//

$SHTML .= <<<RWS
[ {$data['mirror']} ]&nbsp;
RWS;
//--END--//
return $SHTML;
}

function cat_listing_row($data=NULL)
{
global $rwdInfo;
//--START--//

$SHTML .= <<<RWS
<tr class='mainrow'>
                  <td>&nbsp;</td>
                  <td>{$data['name']} {$data['pinned']} {$data['new']} {$data['updated']}</td>
                  <td><div align='center'>{$data['author']}</div></td>
                  <td><div align='center'>{$data['date']}</div></td>
<td><div align='center'>{$data['filesize']}</div></td>                  
<td><div align='center'>{$data['downloads']}</div></td>
</tr>
RWS;
//--END--//
return $SHTML;
}

function add_file($data=NULL)
{
global $rwdInfo;
//--START--//

$SHTML .= <<<RWS
{$data['formpost']}
<div class='tableborder'>
<div id='banner'>
  <img id='leftcap' src='{$rwdInfo->skinurl}/images/headerleft.gif' width='18' height='29'>
  <img id='rightcap' src='{$rwdInfo->skinurl}/images/headerright.gif' width='31' height='29'>
  <div id='catname'>&gt; {$data['title']}</div>
</div>
<table width='100%'  border='0 align='center' cellpadding='0' cellspacing='0'>
          <tr>
            <td colspan='3'>
			<table width='100%' border='0' cellspacing='1' cellpadding='3'>
				<tr class='mainrow'>
					<td valign='top' width='300'>{$rwdInfo->lang['dlname']}:</td>
					<td valign='top'><input style='width:99%' name='name' type='text' size='30' value='{$data['name']}'></td>
				</tr>
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['dldesc']}:</td>
					<td valign='top'><textarea style='width:99%' name='description' cols='24' rows='5'>{$data['description']}</textarea></td>
				</tr>
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['author']}:</td>
					<td valign='top'><input style='width:99%' name='author' type='text' size='30' value='{$data['author']}'></td>
				</tr>
				{$data['thumbrows']}
				{$data['downloadrows']}
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['mirror']}<br>{$rwdInfo->lang['fullurl']}</td>
					<td valign='top'>
						<table width='100%'  border='0 align='center' cellpadding='0' cellspacing='0'>
							<tr>
								<td>{$rwdInfo->lang['mirrorurl']}</td>
								<td>{$rwdInfo->lang['mirrorname']}</td>
							</tr><tr>
								<td><textarea style='width:99%' name='mirrorurls' cols='24' rows='5'>{$data['mirrors']}</textarea></td>
								<td><textarea style='width:99%' name='mirrornames' cols='24' rows='5'>{$data['mirrornames']}</textarea></td>
							</tr>
						</table>
					</td>
				</tr>
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['version']} [{$rwdInfo->lang['optional']}]:</td>
					<td valign='top'><input style='width:99%' name='version' type='text' size='30' value='{$data['version']}'></td>
				</tr>
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['cat']}:</td>
					<td valign='top'>{$data['catlistbox']}</td>
				</tr>
				<tr class='mainrow'>
				<td valign='top' colspan='2'><b><center>{$rwdInfo->lang['warn_upload']}</center></b></td>
				</tr>
			</table></td>
          </tr>
          <tr class='tablefooter'>
            <td>&nbsp;</td>
            <td>
			<input type='hidden' name='did' value='{$data['id']}'>
<input type='hidden' name='oldfile' value='{$data['download']}'>			
<input type='hidden' name='owner' value='{$data['owner']}'>
<input type='hidden' name='oldcat' value='{$data['categoryid']}'>
<input type='hidden' name='filesize' value='{$data['filesize']}'>
<input type='hidden' name='realsize' value='{$data['realsize']}'>
<input type='hidden' name='images' value='1'>
<input type='hidden' name='downloads' value='{$data['downloads']}'>
<input type='hidden' name='oldthumb' value='{$data['oldthumb']}'>
<center><input type='submit' name='preview' value='{$rwdInfo->lang['preview']}'>
<input type='reset' name='reset' value='{$rwdInfo->lang['reset']}'></center>
			</td>
            <td>&nbsp;</td>
          </tr>
  </table>
</div></form>
RWS;
//--END--//
return $SHTML;
}

function download_link($data=NULL)
{
global $rwdInfo;
//--START--//

$SHTML .= <<<RWS
<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['download']}:</td>
					<td valign='top'>{$data['dlinfo']}</td>
				</tr>
<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['filetype']}:</td>
					<td valign='top'>{$data['typeinfo']}</td>
				</tr>
RWS;
//--END--//
return $SHTML;
}

function thumb_row($data=NULL)
{
global $rwdInfo;
//--START--//

$SHTML .= <<<RWS
<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['dlthumb']}:</td>
					<td valign='top'>{$data['thumbdata']}</td>
				</tr>
RWS;
//--END--//
return $SHTML;
}

function cat_listing_foot($data=NULL)
{
global $rwdInfo;
//--START--//

$SHTML .= <<<RWS
</table></td>
          </tr>
          <tr class='tablefooter'>
            <td>&nbsp;</td>
            <td><table width='100%'  border='0' align='center' cellpadding='0' cellspacing='0'>
			<tr><td>{$data['pages']}</td><td><div align='right'>{$data['mod_options']}</div></td></tr></table></td>
            <td>&nbsp;</td>
          </tr>
  </table>
</div></form>
<div class='tableborder'>
<table width='100%'  border='0' cellspacing='0' cellpadding='0'>
  <tr class='subfooter'>
    <td>{$data['order_boxes']}</td>
    <td>&nbsp;</td>
  </tr>
</table>
</div>
RWS;
//--END--//
return $SHTML;
}

function desc_block($data=NULL)
{
global $rwdInfo;
//--START--//

$SHTML .= <<<RWS
<div class='tableborder'>
<div id='banner'>
  <img id='leftcap' src='{$rwdInfo->skinurl}/images/headerleft.gif' width='18' height='29'>
  <img id='rightcap' src='{$rwdInfo->skinurl}/images/headerright.gif' width='31' height='29'>
  <div id='catname'>&gt; {$rwdInfo->lang['description']}</div>
</div>
	<table width='100%'  border='0' align='center' cellpadding='0' cellspacing='0'>
          <tr>
            <td colspan='3'>
				<table width='100%'  border='0' cellspacing='1' cellpadding='3'>
					<tr class='mainrow'>
						<td>
						{$data['description']}
						</td>
					</tr>
				</table>
			</td>
          </tr>
  	</table>
</div>
RWS;
//--END--//
return $SHTML;
}

function empty_download($data=NULL)
{
global $rwdInfo;
//--START--//

$SHTML .= <<<RWS
<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['download']}:</td>
					<td valign='top'><input name='download' type='file' size='30'></td>
				</tr>
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['dlurl']}:</td>
					<td valign='top'><input name='downloadurl' type='text' size='30' value='http://'></td>
				</tr>
RWS;
//--END--//
return $SHTML;
}

function cat_listing_head($data=NULL)
{
global $rwdInfo;
//--START--//

$SHTML .= <<<RWS
{$data['pages']}
<form method='post' enctype='multipart/form-data' action='index.php?ACT=massmod'>
<div class='tableborder'>
<div id='banner'>
  <img id='leftcap' src='{$rwdInfo->skinurl}/images/headerleft.gif' width='18' height='29'>
  <img id='rightcap' src='{$rwdInfo->skinurl}/images/headerright.gif' width='31' height='29'>
  <div id='catname'>&gt; {$data['cat_name']}</div>
</div>
<table width='100%'  border='0' align='center' cellpadding='0' cellspacing='0'>
          <tr>
            <td colspan='3'><table width='100%'  border='0' cellspacing='1' cellpadding='3'>
                <tr class='tableheader'>
                  <td width='20'>&nbsp;</td>
                  <td>{$rwdInfo->lang['name']}</td>
                  <td><div align='center'>{$rwdInfo->lang['author']}</div></td>
                  <td><div align='center'>{$rwdInfo->lang['date']}</div></td>
                  <td><div align='center'>{$rwdInfo->lang['filesize']}</div></td>
                  <td><div align='center'>{$rwdInfo->lang['downloads']}</div></td>
                </tr>
RWS;
//--END--//
return $SHTML;
}

function file_view($data=NULL)
{
global $rwdInfo;
//--START--//

$SHTML .= <<<RWS
<div class='tableborder'>
<div id='banner'>
  <img id='leftcap' src='{$rwdInfo->skinurl}/images/headerleft.gif' width='18' height='29'>
  <img id='rightcap' src='{$rwdInfo->skinurl}/images/headerright.gif' width='31' height='29'>
  <div id='catname'>> {$data['name']}</div>
</div>
<table width='100%' border='0' align='center' cellpadding='0' cellspacing='0'>
          <tr>
            <td colspan='3'><table width='100%'  border='0' cellspacing='1' cellpadding='3'>
                <tr class='tableheader'>
                  <td colspan='3'>&nbsp;</td>
                </tr>
				<tr class='mainrow'>
                  <td width='150'>{$rwdInfo->lang['filesize']}:</td>
				  <td>{$data['filesize']}</td>
<td rowspan='4' width='150'>
RWS;
//startif
if ( $data['onethumb'] )
{
$SHTML .= <<<RWS
{$data['onethumb']}
RWS;
}//endif
$SHTML .= <<<RWS
</td>
                </tr>
				<tr class='mainrow'>
                  <td width='150'>{$rwdInfo->lang['author']}:</td>
				  <td>{$data['author']}</td>
                </tr>
				<tr class='mainrow'>
                  <td width='150'>{$rwdInfo->lang['downloads']}:</td>
				  <td>{$data['downloads']}</td>
                </tr>
				<tr class='mainrow'>
                  <td width='150'>{$rwdInfo->lang['views']}:</td>
				  <td>{$data['views']}</td>
                </tr>
RWS;
//startif
if ( $data['version'] )
{
$SHTML .= <<<RWS
<tr class='mainrow'>
                  <td width='150'>{$rwdInfo->lang['version']}:</td>
				  <td colspan='2'>{$data['version']}</td>
                </tr>
RWS;
}//endif
//startif
if ( $data['mirrors'] )
{
$SHTML .= <<<RWS
<tr class='mainrow'>
                  <td width='150'>{$rwdInfo->lang['mirrors']}:</td>
				  <td colspan='2'>{$data['mirrors']}</td>
                </tr>
RWS;
}//endif
$SHTML .= <<<RWS
	</table></td>
          </tr>
          <tr class='tablefooter'>
            <td>&nbsp;</td>
            <td><table width='100%'  border='0' align='center' cellpadding='0' cellspacing='0'>
			<tr>
			<td colspan='3'><div align='right'>
RWS;
//startif
if ( $data['download_url'] )
{
$SHTML .= <<<RWS
{$data['file_icon']} <a href='{$data['download_url']}' target='{$data['target']}'>{$rwdInfo->lang['download']}</a>
RWS;
}//endif
else
{
$SHTML .= <<<RWS
{$rwdInfo->lang['nodownload']}
RWS;
}//endelse
$SHTML .= <<<RWS
</td></tr></table></td>
            <td>&nbsp;</td>
          </tr>
  </table>
</div>
{$data['description_block']}
RWS;
//--END--//
return $SHTML;
}

}

?>
