<?php
#### Generated by Block Creator by Disipal Site (www.disipal.net) ###
if (eregi("block-Block_Creator.php",$PHP_SELF)) {
    Header("Location: index.php");
    die();
}
$content  =  "<table width=\"100%\">";
$content  .= "  <tr> ";
$content  .= "    <td>Users In Chat";
$content  .= "      <script type=\"text/javascript\" language=\"JavaScript\"src=\"http://www.everywherechat.com/users.asp?room=YOUR_CHAT_ROOM_NAME\"></script>";
$content  .= "    </td>";
$content  .= "  </tr>";
$content  .= "  <tr> ";
$content  .= "    <td> Who Is Chatting</td>";
$content  .= "  </tr>";
$content  .= "  <tr>";
$content  .= "    <td> ";
$content  .= "      <script type=\"text/javascript\" language=\"JavaScript\"src=\"http://www.everywherechat.com/members.asp?room=YOUR_CHAT_ROOM_NAME\"></script>";
$content  .= "    </td>";
$content  .= "  </tr>";
$content  .= "</table>";
?>