<FONT face="Arial, Helvetica, sans-serif" size=2>Welcome to our online store! <EM><!--store_name_begin-->MYWEBSTAR<!--store_name_end--></EM> and its associates provide their services to you subject to the following conditions. If you visit or shop within this website, you accept these conditions. Please read them carefully.</FONT> 
<P><FONT face="Arial, Helvetica, sans-serif" size=2><B>PRIVACY </B></FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2>Please review our Privacy Notice, which also governs your visit to our website, to understand our practices. </FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2><B>ELECTRONIC COMMUNICATIONS</B></FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2>When you visit <!--store_name_begin-->MYWEBSTAR<!--store_name_end--> or send e-mails to us, you are communicating with us electronically. You consent to receive communications from us electronically. We will communicate with you by e-mail or by posting notices on this site. You agree that all agreements, notices, disclosures and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing. </FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2><B>COPYRIGHT </B></FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2>All content included on this site, such as text, graphics, logos, button icons, images, audio clips, digital downloads, data compilations, and software, is the property of <!--store_name_begin-->MYWEBSTAR<!--store_name_end-->, with copyright authorship for this collection by <A href="http://www.mywebstar.com/">MYWEBSTAR Shopping Cart Software,</A> and protected by U.S. and international copyright laws. The software application provider and author for "MYWEBSTAR Shopping Cart Software", is used under the GNU GENERAL PUBLIC LICENSE and all original authorship and credit for&nbsp;MYWEBSTAR Shopping Cart Software remains the intellectual rights of <A href="http://www.mywebstar.com">www.mywebstar.com</A>.</FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2><B>TRADEMARKS </B></FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2><!--store_name_begin-->MYWEBSTAR<!--store_name_end--> or its subsidiaries. </FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2><B>LICENSE AND SITE ACCESS </B></FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2><!--store_name_begin-->MYWEBSTAR<!--store_name_end--> logo or other proprietary graphic or trademark as part of the link without express written permission. </FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2><B>YOUR MEMBERSHIP ACCOUNT</B></FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2>If you use this site, you are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer, and you agree to accept responsibility for all activities that occur under your account or password. If you are under 18, you may use our website only with involvement of a parent or guardian. <!--store_name_begin-->MYWEBSTAR<!--store_name_end--> and its associates reserve the right to refuse service, terminate accounts, remove or edit content, or cancel orders in their sole discretion. </FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2><B>REVIEWS, COMMENTS, EMAILS, AND OTHER CONTENT</B></FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2>Visitors may post reviews, comments, and other content: and submit suggestions, ideas, comments, questions, or other information, so long as the content is not illegal, obscene, threatening, defamatory, invasive of privacy, infringing of intellectual property rights, or otherwise injurious to third parties or objectionable and does not consist of or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings, or any form of ":spam.": You may not use a false e-mail address, impersonate any person or entity, or otherwise mislead as to the origin of a card or other content. <!--store_name_begin-->MYWEBSTAR<!--store_name_end--> reserves the right (but not the obligation) to remove or edit such content, but does not regularly review posted content.</FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2>If you do post content or submit material, and unless we indicate otherwise, you grant <!--store_name_begin-->MYWEBSTAR<!--store_name_end--> takes no responsibility and assumes no liability for any content posted by you or any third party. </FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2><B>RISK OF LOSS</B></FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2>All items purchased from <!--store_name_begin-->MYWEBSTAR<!--store_name_end--> are made pursuant to a shipment contract. This basically means that the risk of loss and title for such items pass to you upon our delivery to the carrier.</FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2><B>PRODUCT DESCRIPTIONS </B></FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2><!--store_name_begin-->MYWEBSTAR<!--store_name_end--> itself is not as described, your sole remedy is to return it in unused condition. </FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2>DISCLAIMER OF WARRANTIES AND LIMITATION OF LIABILITY </FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2>THIS SITE IS PROVIDED BY <!--store_name_begin-->MYWEBSTAR<!--store_name_end--> MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THIS SITE OR THE INFORMATION, CONTENT, MATERIALS, OR PRODUCTS INCLUDED ON THIS SITE. YOU EXPRESSLY AGREE THAT YOUR USE OF THIS SITE IS AT YOUR SOLE RISK. </FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2>TO THE FULL EXTENT PERMISSIBLE BY APPLICABLE LAW, <!--store_name_begin-->MYWEBSTAR<!--store_name_end--> WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING FROM THE USE OF THIS SITE, INCLUDING, BUT NOT LIMITED TO DIRECT, INDIRECT, INCIDENTAL, PUNITIVE, AND CONSEQUENTIAL DAMAGES. </FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2>CERTAIN STATE LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS, OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MIGHT HAVE ADDITIONAL RIGHTS. </FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2><B>APPLICABLE LAW </B></FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2>By visiting <!--store_name_begin-->MYWEBSTAR<!--store_name_end--> or its associates. </FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2><B>DISPUTES</B></FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2>Any dispute relating in any way to your visit to <!--store_name_begin-->MYWEBSTAR<!--store_name_end-->, and you consent to exclusive jurisdiction and venue in such courts. Arbitration under this agreement shall be conducted under the rules then prevailing of the American Arbitration Association. The arbitrators award shall be binding and may be entered as a judgment in any court of competent jurisdiction. To the fullest extent permitted by applicable law, no arbitration under this Agreement shall be joined to an arbitration involving any other party subject to this Agreement, whether through class arbitration proceedings or otherwise. </FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2><B>SITE POLICIES, MODIFICATION, AND SEVERABILITY</B></FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2>Please review our other policies, such as our Shipping and Returns policy, posted on this site. These policies also govern your visit to <!--store_name_begin-->MYWEBSTAR<!--store_name_end-->. We reserve the right to make changes to our site, policies, and these Conditions of Use at any time. If any of these conditions shall be deemed invalid, void, or for any reason unenforceable, that condition shall be deemed severable and shall not affect the validity and enforceability of any remaining condition.</FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2><B>QUESTIONS:</B></FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2>Questions regarding our Conditions of Usage, Privacy Policy, or other policy related material can be directed to our support staff by clicking on the "Contact Us" link in the side menu. Or you can email us at: <A href="mailto:admin@mywebstar.com"><STRONG>admin@mywebstar.com</STRONG></A><A href="mailto:admin@mywebstar.com"></A></FONT></P>