<FONT face="Arial, Helvetica, sans-serif" size=2><EM><!--store_name_begin-->MYWEBSTAR<!--store_name_end-->, you are accepting the practices described in this Privacy Notice. </FONT>
<P><FONT face="Arial, Helvetica, sans-serif" size=2><B><FONT size=3>What Personal Information About Customers Does <!--store_name_begin-->MYWEBSTAR<!--store_name_end--> Gather?</FONT></B></FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2>The information we learn from customers helps us personalize and continually improve your shopping experience at <!--store_name_begin-->MYWEBSTAR<!--store_name_end-->. Here are the types of information we gather. </FONT></P>
<UL>
<LI><FONT face="Arial, Helvetica, sans-serif" size=2><B>Information You Give Us:</B> We receive and store any information you enter on our Web site or give us in any other way. You can choose not to provide certain information, but then you might not be able to take advantage of many of our features. We use the information that you provide for such purposes as responding to your requests, fulfilling orders, customizing future shopping for you, improving our store features, and communication with you. </FONT>
<LI><B><FONT face="Arial, Helvetica, sans-serif" size=2>Automatic Information:</FONT></B><FONT face="Arial, Helvetica, sans-serif" size=2> We receive and store certain types of information whenever you interact with our website. For example, like many web sites, we sometimes use "cookies," and we obtain certain types of information when your Web browser accesses our website. </FONT>
<LI><FONT face="Arial, Helvetica, sans-serif" size=2><B>E-mail Communications:</B> To help us make e-mails more productive to improve service and your shopping experience, we sometimes send you newsletters of our services and products, notifications of changes to our policies, and order confirmations. If you do not want to receive e-mail from us, other than order notifications and receipts, please adjust your "Subscription" preferences by logging into your account. </FONT></LI></UL>
<P><FONT face="Arial, Helvetica, sans-serif" size=2><B><FONT size=3>What About Cookies?</FONT></B> </FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2>Cookies are alphanumeric identifier text files that we transfer to your computers hard drive through your Web browser to enable our systems to recognize your browser and to provide features such as storage of items in your Shopping Cart between visits.</FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2><B><FONT size=3>Does <!--store_name_begin-->MYWEBSTAR<!--store_name_end--> Share the Information It Receives?</FONT></B></FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2>We respect your privacy and appreciate your business. At no time do we ever provide your account contact or payment information to any third party vendor, associate or service provider unless absolutely neccessary in order to complete your transaction and order.</FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2><B><FONT size=3>How Secure Is Information About Me? </FONT></B></FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2>We work to protect the security of your information during transmission by using Secure Sockets Layer (SSL) software, which encrypts information you provide to us for purchasing of our products or services. We reveal only the last five digits of your credit card numbers when confirming an order. Of course, we transmit the entire credit card number to the appropriate credit card company during order processing. It is important for you to protect against unauthorized access to your password and to your computer. Be sure to sign off when finished using a shared computer by clicking the "log off" link located in the side menu.</FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2><B><FONT size=3>Which Information Can I Access?</FONT></B></FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2><!--store_name_begin-->MYWEBSTAR<!--store_name_end--> gives you access to a broad range of information about your account and your interactions with us for the limited purpose of viewing and, in certain cases, updating that information.</FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2><B><FONT size=3>Conditions of Use, Notices, and Revisions </FONT></B></FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2>If you choose to visit <!--store_name_begin-->MYWEBSTAR<!--store_name_end-->, your visit and any dispute over privacy is subject to this Notice and our Conditions of Use, including limitations on damages, arbitration of disputes, and application of the law of the state of our local state. If you have any concern about privacy of your personal information as used and collected within our website, please send us a thorough description by clicking on the "Contact Us" link on the side menu, and we will try to resolve it. </FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2>Our business changes constantly, and our Privacy Notice and the Conditions of Use will change also. We may e-mail periodic reminders of our notices and conditions, unless you have instructed us not to, but you should check our Web site frequently to see recent changes. Unless stated otherwise, our current Privacy Notice applies to all information that we have about you and your account. We stand behind the promises we make, however, and will never materially change our policies and practices to make them less protective of customer information collected in the past without the consent of affected customers. </FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=3><B>Information You Give Us</B></FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2>You provide most such information when you search, buy, order, post reviews, or other methods of communication via our website or email to <!--store_name_begin-->MYWEBSTAR<!--store_name_end-->. As a result of those actions, you might supply us with such information as your name, address, and phone numbers, and credit card information.</FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2><B><FONT size=3>Automatic Information</FONT></B></FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2>For security purposes <!--store_name_begin-->MYWEBSTAR<!--store_name_end--> sometimes collects and analyzes the Internet protocol (IP) address used to connect your computer to the Internet, and to our website. This is done for your protection for tracking purposes in the unfortunate event that someone gains access to your personal or financial information and opens an account, or makes purchases under your name.</FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2><B><FONT size=3>Questions</FONT></B></FONT></P>
<P><FONT face="Arial, Helvetica, sans-serif" size=2>Questions regarding our Conditions of Usage, Privacy Policy, or other policy related material can be directed to our support staff by clicking on the "Contact Us" link in the side menu. Or you can email us at: <B><!--store_owner_email_address_begin-->admin@mywebstar.com<!--store_owner_email_address_end--></B></FONT></P></EM>