CREATE TABLE dbo.EBAY_CASES (
	TRACKING_NUMBER numeric(18, 0) IDENTITY (27850, 1) NOT NULL ,
	USER_ID varchar (15) NULL ,
	ITEM_ID numeric(18, 0) NULL ,
	ABOUT_USER_NAME varchar (25) NULL ,
	WHAT_SITE varchar (50) NULL ,
	PROBLEM_CODE int NULL ,
	DATE datetime NULL ,
	OTHER_PARTY_F_NAME varchar (20) NULL ,
	OTHER_PARTY_M_NAME varchar (20) NULL ,
	OTHER_PARTY_L_NAME varchar (30) NULL ,
	OTHER_PARTY_ADD_1 varchar (50) NULL ,
	OTHER_PARTY_ADD_2 varchar (50) NULL ,
	OTHER_PARTY_CITY varchar (20) NULL ,
	OTHER_PARTY_STATE varchar (10) NULL ,
	OTHER_PARTY_ZIP varchar (20) NULL ,
	OTHER_PARTY_COUNTRY varchar (20) NULL ,
	OTHER_PARTY_EMAIL varchar (55) NULL ,
	OTHER_PARTY_PHONE varchar (55) NULL ,
	OTHER_PARTY_RESPONSES int NULL 
)

CREATE TABLE dbo.EBAY_CASES_COMMENTS (
	TRACKING_NUMBER numeric(18, 0) NULL ,
	MSG_FROM varchar (50) NULL ,
	DATE datetime NULL ,
	COMMENT_TEXT text NULL 
)

CREATE TABLE dbo.EBAY_CASES_PASS (
	EMAIL varchar (60) NULL ,
	PASSWORD varchar (10) NULL 
)

