<?
$GEOIP_COUNTRY_CODES=array(
'','US CA DE GB IT JP EU AT BE CH DK ES FI FR IE LU PT SE',
'AP','EU','AD','AE','AF','AG','AI','AL','AM','AN','AO','AQ',
'AR','AS','AT','AU','AW','AZ','BA','BB','BD','BE','BF','BG','BH',
'BI','BJ','BM','BN','BO','BR','BS','BT','BV','BW','BY','BZ','CA',
'CC','CD','CF','CG','CH','CI','CK','CL','CM','CN','CO','CR','CU',
'CV','CX','CY','CZ','DE','DJ','DK','DM','DO','DZ','EC','EE','EG',
'EH','ER','ES','ET','FI','FJ','FK','FM','FO','FR','FX','GA','GB',
'GD','GE','GF','GH','GI','GL','GM','GN','GP','GQ','GR','GS','GT',
'GU','GW','GY','HK','HM','HN','HR','HT','HU','ID','IE','IL','IN',
'IO','IQ','IR','IS','IT','JM','JO','JP','KE','KG','KH','KI','KM',
'KN','KP','KR','KW','KY','KZ','LA','LB','LC','LI','LK','LR','LS',
'LT','LU','LV','LY','MA','MC','MD','MG','MH','MK','ML','MM','MN',
'MO','MP','MQ','MR','MS','MT','MU','MV','MW','MX','MY','MZ','NA',
'NC','NE','NF','NG','NI','NL','NO','NP','NR','NU','NZ','OM','PA',
'PE','PF','PG','PH','PK','PL','PM','PN','PR','PS','PT','PW','PY',
'QA','RE','RO','RU','RW','SA','SB','SC','SD','SE','SG','SH','SI',
'SJ','SK','SL','SM','SN','SO','SR','ST','SV','SY','SZ','TC','TD',
'TF','TG','TH','TJ','TK','TM','TN','TO','TP','TR','TT','TV','TW',
'TZ','UA','UG','UM','US','UY','UZ','VA','VC','VE','VG','VI','VN',
'VU','WF','WS','YE','YT','YU','ZA','ZM','ZR','ZW','A1','A2','O1'
);

$GEOIP_COUNTRY_NAMES=array(
'','All Good Countries',
'Asia/Pacific Region','Europe','Andorra','United Arab Emirates',
'Afghanistan','Antigua and Barbuda','Anguilla','Albania','Armenia',
'Netherlands Antilles','Angola','Antarctica','Argentina','American Samoa',
'Austria','Australia','Aruba','Azerbaijan','Bosnia and Herzegovina',
'Barbados','Bangladesh','Belgium','Burkina Faso','Bulgaria','Bahrain',
'Burundi','Benin','Bermuda','Brunei Darussalam','Bolivia','Brazil',
'Bahamas','Bhutan','Bouvet Island','Botswana','Belarus','Belize',
'Canada','Cocos (Keeling) Islands','Congo',
'Central African Republic','Congo','Switzerland','Cote DIvoire','Cook Islands',
'Chile','Cameroon','China','Colombia','Costa Rica','Cuba','Cape Verde',
'Christmas Island','Cyprus','Czech Republic','Germany','Djibouti',
'Denmark','Dominica','Dominican Republic','Algeria','Ecuador','Estonia',
'Egypt','Western Sahara','Eritrea','Spain','Ethiopia','Finland','Fiji',
'Falkland Islands (Malvinas)','Micronesia, Federated States of','Faroe Islands',
'France','France, Metropolitan','Gabon','United Kingdom',
'Grenada','Georgia','French Guiana','Ghana','Gibraltar','Greenland',
'Gambia','Guinea','Guadeloupe','Equatorial Guinea','Greece',
'S. Georgia & Sandwich Islands','Guatemala','Guam','Guinea-Bissau',
'Guyana','Hong Kong','Heard Island and McDonald Islands','Honduras',
'Croatia','Haiti','Hungary','Indonesia','Ireland','Israel','India',
'British Indian Ocean Territory','Iraq','Iran, Islamic Republic of',
'Iceland','Italy','Jamaica','Jordan','Japan','Kenya','Kyrgyzstan',
'Cambodia','Kiribati','Comoros','Saint Kitts and Nevis',
'Korea, Democratic Peoples Rep','Korea, Republic of','Kuwait','Cayman Islands',
'Kazakstan','Lao Peoples Democratic Republic','Lebanon','Saint Lucia',
'Liechtenstein','Sri Lanka','Liberia','Lesotho','Lithuania','Luxembourg',
'Latvia','Libyan Arab Jamahiriya','Morocco','Monaco','Moldova, Republic of',
'Madagascar','Marshall Islands','Macedonia',
'Mali','Myanmar','Mongolia','Macau','Northern Mariana Islands',
'Martinique','Mauritania','Montserrat','Malta','Mauritius','Maldives',
'Malawi','Mexico','Malaysia','Mozambique','Namibia','New Caledonia',
'Niger','Norfolk Island','Nigeria','Nicaragua','Netherlands','Norway',
'Nepal','Nauru','Niue','New Zealand','Oman','Panama','Peru','French Polynesia',
'Papua New Guinea','Philippines','Pakistan','Poland','Saint Pierre and Miquelon',
'Pitcairn','Puerto Rico','Palestinian Territory, Occupied',
'Portugal','Palau','Paraguay','Qatar','Reunion','Romania',
'Russian Federation','Rwanda','Saudi Arabia','Solomon Islands',
'Seychelles','Sudan','Sweden','Singapore','Saint Helena','Slovenia',
'Svalbard and Jan Mayen','Slovakia','Sierra Leone','San Marino','Senegal',
'Somalia','Suriname','Sao Tome and Principe','El Salvador','Syrian Arab Republic',
'Swaziland','Turks and Caicos Islands','Chad','French Southern Territories',
'Togo','Thailand','Tajikistan','Tokelau','Turkmenistan',
'Tunisia','Tonga','East Timor','Turkey','Trinidad and Tobago','Tuvalu',
'Taiwan','Tanzania, United Republic of','Ukraine',
'Uganda','United States Minor Outlying Islands','United States','Uruguay',
'Uzbekistan','Holy See (Vatican City State)','Saint Vincent and the Grenadines',
'Venezuela','Virgin Islands, British','Virgin Islands, U.S.',
'Vietnam','Vanuatu','Wallis and Futuna','Samoa','Yemen','Mayotte',
'Yugoslavia','South Africa','Zambia','Zaire','Zimbabwe',
'Anonymous Proxy','Satellite Provider','Other'
);

$intlangs=array('English','Russian');

$TXT['English']=array(
'Submit New Site'=>'Submit New Site',
'URL of your page'=>'URL of your page',
'Fake URL'=>'Fake URL',
'Banner URL'=>'Banner URL',
'Link Back URL'=>'Link Back URL',
'where you will place our link'=>'where you will place our link',
'Category'=>'Category',
'Site type'=>'Site type',
'Site title'=>'Site title',
'Site description'=>'Site description',
'Your Email'=>'Your Email',
'Your ICQ #'=>'Your ICQ #',
'Username'=>'Username',
'Password'=>'Password',
'Re-type your password'=>'Re-type your password',
'Add Site'=>'Add Site',
'Edit Account / Check Stats'=>'Edit Account / Check Stats',
'Log In'=>'Log In',
'Forgot Password'=>'Forgot Password',
'Main page'=>'Main page',
'Download'=>'Download',
'Stats for current period'=>'Stats for current period',
'Traffic Summary'=>'Traffic Summary',
'Visits'=>'Visits',
'Out'=>'Out',
'Account Submitted to'=>'Account Submitted to',
'Your account has been added to'=>'Your account has been added to',
'Account will be listed after review'=>'Account will be listed after review',
'You may start sending hits immediately'=>'You may start sending hits immediately',
'Place this link at your page'=>'Place this link at your page',
'All hits from domain'=>'All hits from domain',
'will be counted as your hits'=>'will be counted as your hits',
'Edit account and view stats'=>'Edit account and view stats');

$TXT['Russian']=array(
'Submit New Site'=>'Äîáàâèòü âàø ñàéò',
'URL of your page'=>'URL âàøåé ñòðàíèöû',
'Fake URL'=>'Ëîæíûé URL',
'Banner URL'=>'URL áàííåðà',
'Link Back URL'=>'URL îáðàòíîé ññûëêè',
'where you will place our link'=>'ãäå âû ðàçìåñòèòå íàøó ññûëêó',
'Category'=>'Ðàçäåë',
'Site type'=>'Òèï ñàéòà',
'Site title'=>'Íàçâàíèå ñàéòà',
'Site description'=>'Îïèñàíèå ñàéòà',
'Your Email'=>'Âàø Email',
'Your ICQ #'=>'Âàø ICQ #',
'Username'=>'Èìÿ ïîëüçîâàòåëÿ',
'Password'=>'Ïàðîëü',
'Re-type your password'=>'Ïîâòîðèòå ïàðîëü',
'Add Site'=>'Äîáàâèòü ñàéò',
'Edit Account / Check Stats'=>'Èçìåíèòü îïèñàíèå / Ïðîâåðèòü ñòàòèñòèêó',
'Log In'=>'Âîéòè',
'Forgot Password'=>'Çàáûë ïàðîëü',
'Main page'=>'Ãëàâíàÿ',
'Download'=>'Ñêà÷àòü',
'Stats for current period'=>'Ñòàòèñòèêà çà ïåðèîä',
'Traffic Summary'=>'Ñóììàðíûé òðàôèê',
'Visits'=>'Ïîñåòèòåëåé',
'Account Submitted to'=>'Ñàéò äîáàâëåí â',
'Out'=>'Êëèêîâ',
'Your account has been added to'=>'Âàø ñàéò äîáàâëåí â',
'Account will be listed after review'=>'Ñàéò ïîÿâèòñÿ â ñïèñêå ïîñëå îäîáðåíèÿ',
'You may start sending hits immediately'=>'Âû ìîæåòå íà÷èíàòü îòïðàâêó òðàôèêà íåìåäëåííî',
'Place this link at your page'=>'Ðàçìåñòèòå ýòó ññûëêó íà âàøåé ñòðàíèöå',
'All hits from domain'=>'Âñå ïåðåõîäû ñ äîìåíà',
'will be counted as your hits'=>'áóäóò çàñ÷èòàíû âàøåìó ñàéòó',
'Edit account and view stats'=>'Ðåäàêòèðîâàíèå äàííûõ è ïðîñìîòð ñòàòèñòèêè');
?>