<?php
global $coo,$dbservername,$dbusername,$dbpassword,$dbname,$browser_string,$tickethandler,$password,$handlername,$contno,$speccomp,$speccharge,$cuscomp,$cuscharge,$trapcat,$depid,$depname,$cid,$name,$enab,$index1,$compname,$compadd,$comparea,$compstate,$compzip,$enable1,$session,$del,$data,$id,$type,$user,$key,$index,$recid,$userid,$cus,$mode,$numb,$txt1,$date1,$date2,$date3,$date4,$cond,$email,$phone,$pass,$catid,$login,$equname,$desc,$descp,$owner,$price,$equprice,$vendor,$slno,$no,$doa,$lop,$doe,$title,$class,$queryarea,$content,$tbl,$select,$ticket,$rec,$submitlogin,$dept,$submit,$pgno,$da1,$da2,$keyword,$updateme,$orderby,$order;  $coo= $_COOKIE[coo]; $dbservername = $_POST[dbservername]; $dbusername = $_POST[dbusername]; $dbpassword = $_POST[dbpassword]; $dbname = $_POST[dbname]; $browser_string = $_POST[browser_string]; $tickethandler = $_POST[tickethandler]; $password = $_POST[password]; $handlername = $_POST[handlername]; $contno = $_POST[contno]; $speccomp = $_POST[speccomp]; $speccharge = $_POST[speccharge]; $cuscomp = $_POST[cuscomp]; $cuscharge = $_POST[cuscharge]; $trapcat = $_POST[trapcat]; $depid = $_POST[depid]; $depname = $_POST[depname]; $cid = $_POST[cid];  $name = $_POST[name]; $enab = $_POST[enab]; $index1 = $_POST[index1]; $compname = $_POST[compname]; $compadd = $_POST[compadd]; $comparea = $_POST[comparea]; $compstate = $_POST[compstate]; $compzip = $_POST[compzip]; $enable1 = $_POST[enable1]; $session = $_POST[session];  $del = $_POST[del];  $data = $_POST[data];  $id = $_POST[id];  $type = $_POST[type];  $user = $_POST[user];  $key = $_POST[key];  $index = $_POST[index];  $recid = $_POST[recid];  $userid = $_POST[userid];  $cus = $_POST[cus];  $mode = $_POST[mode];  $numb = $_POST[numb];  $txt1 = $_POST[txt1];  $date1 = $_POST[date1];  $date2 = $_POST[date2];  $date3 = $_POST[date3];  $date4 = $_POST[date4];  $cond = $_POST[cond];  $email = $_POST[email];  $phone = $_POST[phone];  $pass = $_POST[pass];  $catid = $_POST[catid];  $login = $_POST[login];  $equname = $_POST[equname];  $desc = $_POST[desc];  $descp = $_POST[descp];  $owner = $_POST[owner];  $price = $_POST[price];  $equprice = $_POST[equprice];  $vendor = $_POST[vendor];  $slno = $_POST[slno];  $no = $_POST[no];  $doa = $_POST[doa];  $lop = $_POST[lop];  $doe = $_POST[doe];  $title = $_POST[title];  $class = $_POST["class"];  $queryarea = $_POST[queryarea];  $content = $_POST[content];  $tbl = $_POST[tbl];  $select = $_POST[select];  $ticket = $_POST[ticket];  $rec = $_POST[rec];  $submitlogin = $_POST[submitlogin];  $dept = $_POST[dept];  $submit = $_POST[submit];  $pgno = $_POST[pgno];  $da1 = $_POST[da1];  $da2 = $_POST[da2];  $keyword = $_POST[keyword];  $updateme = $_POST[updateme];
 $orderby = $_POST[orderby];
 $order = $_POST[order];
$ok = "Y";
if($session == null)
        $ok = "N";
if($ok == "Y")
        if(strlen($session) < 5)
                $ok = "N";
if( $ok == "N") { $dbservername = $_GET[dbservername]; $dbusername = $_GET[dbusername]; $dbpassword = $_GET[dbpassword]; $dbname = $_GET[dbname]; $browser_string = $_GET[browser_string]; $tickethandler = $_GET[tickethandler]; $password = $_GET[password]; $handlername = $_GET[handlername]; $contno = $_GET[contno]; $speccomp = $_GET[speccomp]; $speccharge = $_GET[speccharge]; $cuscomp = $_GET[cuscomp]; $cuscharge = $_GET[cuscharge]; $trapcat = $_GET[trapcat]; $depid = $_GET[depid]; $depname = $_GET[depname]; $cid = $_GET[cid];  $name = $_GET[name]; $enab = $_GET[enab]; $index1 = $_GET[index1]; $compname = $_GET[compname]; $compadd = $_GET[compadd]; $comparea = $_GET[comparea]; $compstate = $_GET[compstate]; $compzip = $_GET[compzip]; $enable1 = $_GET[enable1]; $session = $_GET[session];  $del = $_GET[del];  $data = $_GET[data];  $id = $_GET[id];  $type = $_GET[type];  $user = $_GET[user];  $key = $_GET[key];  $index = $_GET[index];  $recid = $_GET[recid];  $userid = $_GET[userid];  $cus = $_GET[cus];  $mode = $_GET[mode];  $numb = $_GET[numb];  $txt1 = $_GET[txt1];  $date1 = $_GET[date1];  $date2 = $_GET[date2];  $date3 = $_GET[date3];  $date4 = $_GET[date4];  $cond = $_GET[cond];  $email = $_GET[email];  $phone = $_GET[phone];  $pass = $_GET[pass];  $catid = $_GET[catid];  $login = $_GET[login];  $equname = $_GET[equname];  $desc = $_GET[desc];  $descp = $_GET[descp];  $owner = $_GET[owner];  $price = $_GET[price];  $equprice = $_GET[equprice];  $vendor = $_GET[vendor];  $slno = $_GET[slno];  $no = $_GET[no];  $doa = $_GET[doa];  $lop = $_GET[lop];  $doe = $_GET[doe];  $title = $_GET[title];  $class = $_GET["class"];  $queryarea = $_GET[queryarea];  $content = $_GET[content];  $tbl = $_GET[tbl];  $select = $_GET[select];  $ticket = $_GET[ticket];  $rec = $_GET[rec];  $submitlogin = $_GET[submitlogin];  $dept = $_GET[dept];  $submit = $_GET[submit];  $pgno = $_GET[pgno];  $da1 = $_GET[da1];  $da2 = $_GET[da2];  $keyword = $_GET[keyword];  $updateme = $_GET[updateme];
 $orderby = $_GET[orderby];
 $order = $_GET[order];  }
 //CopyRight 2004 BaalSystems Free Software, see http://baalsystems.com for details, you may NOT redistribute or resell this free software.
 ?>