<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta content="text/html; charset=windows-1252" http-equiv="Content-Type">
<meta http-equiv="MSThemeCompatible" content="Yes">
<title>$site[name] - $site[title]</title>
<link rel="stylesheet" href="$cssfile">
</head>
<body topmargin="10" leftmargin="10">

<table border=0 cellpadding=3 cellspacing=0 align=center width=600>
<tr>
<td>
<h1 style='font-family: Trebuchet MS'> Setup </h1><br />
</td>
</tr>
<tr>
<td>
$content
</td>
</tr>
</table><br />
</body>
</html>