/*	$Id: ebay_combined_users_move.sql,v 1.2 1999/02/21 02:57:44 josh Exp $	*/
create table ebay_combined_users_move(
 id                  number(38) not null,
 userid              varchar2(64),
 user_state          number(8),
 password            varchar2(64),
 last_modified       date,
 name                varchar2(64),
 company             varchar2(64),
 address             varchar2(64),
 city                varchar2(64),
 state               varchar2(64),
 zip                 varchar2(64),
 country             varchar2(64),
 dayphone            varchar2(32),
 nightphone          varchar2(32),
 faxphone            varchar2(32),
 creation            date,
 email               varchar2(64),
 count               number(8),
 credit_card_on_file char(1),
 good_credit         char(1),
 gender              char(1),
 partner_id          NUMBER(3))
/
insert into ebay_combined_users_move(
 id,
 userid,
 user_state,
 password,
 last_modified,
 name,
 company,
 address,
 city,
 state,
 zip,
 country,
 dayphone,
 nightphone,
 faxphone,
 creation,
 email,
 count,
 credit_card_on_file,
 good_credit,
 gender,
 partner_id)
select a.id,
       a.userid,
       a.user_state,
       a.password,
       a.last_modified,
       b.id,
       b.name,
       b.company,
       b.address,
       b.city,
       b.state,
       b.zip,
       b.country,
       b.dayphone,
       b.nightphone,
       b.faxphone,
       b.creation,
       b.email,
       b.count,
       b.credit_card_on_file,
       b.good_credit,
       b.gender,
       b.partner_id
from   ebay_user_info b,ebay_users a
where  b.id = a.id
and    (trunc(a.last_modified) = trunc(sysdate - 1)
or      trunc(b.creation) = trunc(sysdate - 1))
/
