<?php
/***************************************************************************
 * (c)2001-2005 Boesch IT-Consulting (info@boesch-it.de)
 ***************************************************************************/
$l_menus =
array(
	array(
		array("entry"=>$l_mainmenu,"url"=>"index.php?$langvar=$act_lang#top","level"=>0),
		array("entry"=>$l_logout,"url"=>"logout.php?$langvar=$act_lang","level"=>0)
	),
	array(
		array("entry"=>$l_general,"url"=>"index.php?$langvar=$act_lang#general","level"=>1),
		array("entry"=>$l_oslist,"url"=>"os.php?$langvar=$act_lang","level"=>1),
		array("entry"=>$l_editprogs,"url"=>"program.php?$langvar=$act_lang","level"=>1),
		array("entry"=>$l_reorder_prog,"url"=>"reorder_prog.php?$langvar=$act_lang","level"=>2)
	),
	array(
		array("entry"=>$l_faq,"url"=>"index.php?$langvar=$act_lang#faq","level"=>1),
		array("entry"=>$l_editcats,"url"=>"categories.php?$langvar=$act_lang","level"=>1),
		array("entry"=>$l_editsubcats,"url"=>"subcategories.php?$langvar=$act_lang","level"=>1),
		array("submenu"=>"1","entries"=>array(
			array("entry"=>$l_faq,"url"=>"index.php?$langvar=$act_lang#faq","level"=>1),
			array("entry"=>$l_editfaq,"url"=>"faq.php?$langvar=$act_lang","level"=>1),
			array("entry"=>$l_newfaq,"url"=>"faq.php?$langvar=$act_lang&mode=new&override=1","level"=>1),
			array("entry"=>$l_faqsearch,"url"=>"faqsearch.php?$langvar=$act_lang","level"=>2)
		)),
		array("submenu"=>"1","entries"=>array(
			array("entry"=>$l_offlinefunctions,"url"=>"index.php?$langvar=$act_lang#offline","level"=>3),
			array("entry"=>$l_offlinelists,"url"=>"offlinelists.php?$langvar=$act_lang","level"=>3),
			array("entry"=>$l_faqupload,"url"=>"faq_upload.php?$langvar=$act_lang","level"=>3),
			array("entry"=>$l_faqdownload,"url"=>"faq_download.php?$langvar=$act_lang","level"=>3)
		)),
		array("submenu"=>"1","entries"=>array(
			array("entry"=>$l_rearrange,"url"=>"index.php?$langvar=$act_lang#reorder1","level"=>2),
			array("entry"=>$l_reorder_cat,"url"=>"reorder_cat.php?$langvar=$act_lang","level"=>2),
			array("entry"=>$l_reorder_subcat,"url"=>"reorder_subcat.php?$langvar=$act_lang","level"=>2),
			array("entry"=>$l_reorder_faq,"url"=>"reorder_faq.php?$langvar=$act_lang","level"=>2)
		)),
		array("submenu"=>"1","entries"=>array(
			array("entry"=>$l_tools,"url"=>"index.php?$langvar=$act_lang#stats1","level"=>1),
			array("entry"=>$l_treeview,"url"=>"treeview.php?$langvar=$act_lang","level"=>1),
			array("entry"=>$l_statistics,"url"=>"stats.php?$langvar=$act_lang","level"=>1)
		)),
		array("submenu"=>"1","entries"=>array(
			array("entry"=>$l_subscriptions,"url"=>"index.php?$langvar=$act_lang#subs","level"=>$nllevel),
			array("entry"=>$l_subscribers,"url"=>"subscribers.php?$langvar=$act_lang","level"=>$nllevel),
			array("entry"=>$l_emailfaq,"url"=>"faqmail.php?$langvar=$act_lang","level"=>$nllevel)
		))
	),
	array(
		array("entry"=>$l_userposts,"url"=>"index.php?$langvar=$act_lang#userposts","level"=>1),
		array("entry"=>$l_userquestions,"url"=>"userquestions.php?$langvar=$act_lang","level"=>1),
		array("entry"=>$l_usercomments,"url"=>"usercomments.php?$langvar=$act_lang","level"=>1)
	),
	array(
		array("entry"=>$l_kb,"url"=>"index.php?$langvar=$act_lang#kb","level"=>1),
		array("entry"=>$l_editcats,"url"=>"kb_cats.php?$langvar=$act_lang","level"=>1),
		array("entry"=>$l_editsubcats,"url"=>"kb_subcats.php?$langvar=$act_lang","level"=>1),
		array("submenu"=>"1", "entries"=>array(
			array("entry"=>$l_articles,"url"=>"index.php?$langvar=$act_lang#kb","level"=>1),
			array("entry"=>$l_editarticles,"url"=>"kb.php?$langvar=$act_lang","level"=>1),
			array("entry"=>$l_newarticle,"url"=>"kb.php?$langvar=$act_lang&mode=new&override=1","level"=>1),
			array("entry"=>$l_kbsearch,"url"=>"kbsearch.php?$langvar=$act_lang","level"=>2),
		)),
		array("submenu"=>"1","entries"=>array(
			array("entry"=>$l_offlinefunctions,"url"=>"index.php?$langvar=$act_lang#offline","level"=>3),
			array("entry"=>$l_offlinelists,"url"=>"offlinelists_kb.php?$langvar=$act_lang","level"=>3),
			array("entry"=>$l_kbupload,"url"=>"kb_upload.php?$langvar=$act_lang","level"=>3),
			array("entry"=>$l_kbdownload,"url"=>"kb_download.php?$langvar=$act_lang","level"=>3)
		)),
		array("submenu"=>"1","entries"=>array(
			array("entry"=>$l_rearrange,"url"=>"index.php?$langvar=$act_lang#reorder2","level"=>2),
			array("entry"=>$l_reorder_cat,"url"=>"reorder_kb_cats.php?$langvar=$act_lang","level"=>2),
			array("entry"=>$l_reorder_subcat,"url"=>"reorder_kb_subcats.php?$langvar=$act_lang","level"=>2),
			array("entry"=>$l_reorder_kb,"url"=>"reorder_kb.php?$langvar=$act_lang","level"=>2)
		)),
		array("submenu"=>"1","entries"=>array(
			array("entry"=>$l_tools,"url"=>"index.php?$langvar=$act_lang#stats2","level"=>1),
			array("entry"=>$l_treeview,"url"=>"kb_treeview.php?$langvar=$act_lang","level"=>1),
			array("entry"=>$l_statistics,"url"=>"kb_stats.php?$langvar=$act_lang","level"=>1)
		))
	),
	array(
		array("entry"=>$l_files,"url"=>"index.php?$langvar=$act_lang#files","level"=>1),
		array("entry"=>$l_adminfiles,"url"=>"attachs.php?$langvar=$act_lang","level"=>1),
		array("entry"=>$l_admingfx,"url"=>"admin_gfx.php?$langvar=$act_lang","level"=>1),
		array("entry"=>$l_files_cleanup,"url"=>"files_cleanup.php?$langvar=$act_lang","level"=>3),
		array("entry"=>$l_filetypes,"url"=>"mimetypes.php?$langvar=$act_lang","level"=>3)
	),
	array(
		array("entry"=>$l_user,"url"=>"index.php?$langvar=$act_lang#users","level"=>1),
		array("entry"=>$l_editadmins,"url"=>"users.php?$langvar=$act_lang","level"=>1),
		array("entry"=>$l_failed_logins,"url"=>"loginfailures.php?$langvar=$act_lang","level"=>3),
		array("entry"=>$l_ipbanlist,"url"=>"banlist.php?$langvar=$act_lang","level"=>1),
		array("entry"=>$l_freemailerlist,"url"=>"freemailer.php?$langvar=$act_lang","level"=>1)
	),
	array(
		array("entry"=>$l_settings,"url"=>"index.php?$langvar=$act_lang#settings","level"=>3),
		array("entry"=>$l_editlayout,"url"=>"layout.php?$langvar=$act_lang","level"=>3),
		array("entry"=>$l_editsettings,"url"=>"settings.php?$langvar=$act_lang","level"=>3),
		array("entry"=>$l_texts,"url"=>"texts.php?$langvar=$act_lang","level"=>3),
		array("entry"=>$l_badwordlist,"url"=>"badwords.php?$langvar=$act_lang","level"=>3)
	),
	array(
		array("entry"=>$l_administration2,"url"=>"index.php?$langvar=$act_lang#admin","level"=>3),
		array("entry"=>$l_diraccess,"url"=>"diraccess.php?$langvar=$act_lang","level"=>3),
		array("entry"=>$l_hostcache,"url"=>"hostcache.php?$langvar=$act_lang","level"=>3),
		array("entry"=>$l_leacherlist,"url"=>"leacher.php?$langvar=$act_lang","level"=>3),
		array("entry"=>$l_cleansession,"url"=>"sessions.php?$langvar=$act_lang","level"=>3),
		array("entry"=>$l_shutdownsys,"url"=>"shutdown.php?$langvar=$act_lang","level"=>4),
		array("entry"=>$l_searchlogs,"url"=>"searchlogs.php?$langvar=$act_lang","level"=>$searchlogaccess),
		array("entry"=>$l_internalinfo,"url"=>"internalinfo.php?$langvar=$act_lang","level"=>4),
		array("submenu"=>"3","entries"=>array(
			array("entry"=>$l_database,"url"=>"index.php?$langvar=$act_lang#database","level"=>3),
			array("entry"=>$l_dbbackup,"url"=>"backup.php?$langvar=$act_lang","level"=>3),
			array("entry"=>$l_dbrestore,"url"=>"restore.php?$langvar=$act_lang","level"=>3),
			array("entry"=>$l_repairtables,"url"=>"tblrepair.php?$langvar=$act_lang","level"=>3),
			array("entry"=>$l_optimizetables,"url"=>"tblpack.php?$langvar=$act_lang","level"=>3)
		))
	)
);
?>