<?PHP
; /*
; -- BEGIN PROTECTED_MODE
; This files was automagically generated by ConfigMagik
; Do not edit this file by hand, use ConfigMagik instead.
; Last modified: 21 Jan 2005 15:14 37

; -- END PROTECTED_MODE
; */
?>
