<?php
/***************************************************************************
 * (c)2002-2005 Boesch IT-Consulting (info@boesch-it.de)
 ***************************************************************************/
$copyright_note = "&copy;2002-2005 B&ouml;sch EDV-Consulting";
$copyright_url = "<a class=\"copyright\" target=\"_blank\" href=\"$snpurl\">$snprogname</a> V$version";
$copyright_asc = "(c)2002-2005 by Boesch EDV-Consulting";
?>