<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>$site[name] - $site[title] </title>
<style type='text/css'>
$cssfile
</style>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
{custom_meta_tags}

$layout[head]
$layout[wysiwyg]
</head>
<body>

<table border="0" cellpadding="0" cellspacing="0" width="100%" id="wrapper" align="center">
<tr>
  <td colspan="2">
    <div id="header" style="background-image:url($script[imgfolder]top_bg.gif);background-position:right;background-repeat:no-repeat">
      <img src="$script[imgfolder]logo.gif" alt="" />
    </div>
    <div id="navbar">
      <div style="float:right;font-weight:bold;"><a href="index.php">Home</a> | <a href="index.php?advsearch">Advance Search</a> | <a href="index.php?topart">Most Popular</a> | <a href="index.php?toprated">Top Rated</a> | <a href="index.php?rss">RSS Syndicate</a> | <a href="index.php?do=sitemap">Sitemap</a>
      [<a href="index.php?login">Author CP</a>]</div>
    </div>
  </td>
</tr>
<tr style="height:100%" valign="top">
  <td id="nav_left" width="150">
   $leftnav
  </td>
  <td id="content" width="100%">
