<table border="0" cellpadding="0" cellspacing="0" align="center" class="article_loop" width="98%">
<tr>
<td>
  <div style="float:right"><b>$evoLANG[views]: $article[views]</b></div>
  $article[artimg]

  $featured <img src="$script[imgfolder]article.gif" alt="" />
  <a href="$art_link"><span class="subject">$article[subject]</span></a><br />
  <span class="author"> $article[author]</span>, $article[date] $article[category]<br />
  $article[rating]<br />
  <br />

    <div class="summary">
      $article[summary]
    </div>
</td>
</tr>
</table>
<br />

