// Greek lang variables by Jacaranda Bill

tinyMCE.addToLang('',{
theme_style_select : 'ÈÝìáôá',
theme_code_desc : '&Aring;ð&aring;î&aring;ñãáóßá HTML êþ&auml;éêá',
theme_code_title : '&Aring;ð&aring;î&aring;ñãáóôÞò HTML',
theme_code_wordwrap : 'Word wrap',
theme_sub_desc : '&Auml;&aring;ßêôçò',
theme_sup_desc : '&Aring;êèÝôçò',
theme_hr_desc : '&Aring;éóáãùãÞ ïñéæüíôéáò ãñáììÞò',
theme_removeformat_desc : 'Áðáëïé&ouml;Þ ìïñ&ouml;ïðïßçóçò',
theme_custom1_desc : 'Ð&aring;ñéãñá&ouml;Þ',
insert_image_border : 'Ð&aring;ñßãñáììá',
insert_image_dimensions : '&Auml;éáóôÜó&aring;éò',
insert_image_vspace : 'ÊÜè. ð&aring;ñéèþñéï',
insert_image_hspace : 'Ïñéæ. ð&aring;ñéèþñéï',
insert_image_align : 'Óôïß÷éóç',
insert_image_align_default : 'ÐñïêáèïñéóìÝíç',
insert_image_align_baseline : 'Ó&aring; &aring;õèõãñÜììéóç ì&aring; ôï ê&aring;ßì&aring;íï',
insert_image_align_top : 'ÐÜíù',
insert_image_align_middle : 'Óôï êÝíôñï',
insert_image_align_bottom : 'ÊÜôù',
insert_image_align_texttop : 'Ôï ê&aring;ßì&aring;íï ðÜíù',
insert_image_align_absmiddle : 'Áðüëõôá óôï êÝíôñï',
insert_image_align_absbottom : 'Áðüëõôá êÜôù',
insert_image_align_left : 'Áñéóô&aring;ñÜ',
insert_image_align_right : '&Auml;&aring;îéÜ',
theme_font_size : '-- Font size --',
theme_fontdefault : '-- Font family --',
theme_block : '-- Format --',
theme_paragraph : 'ÐáñÜãñá&ouml;ïò',
theme_div : 'Div',
theme_address : '&Auml;é&aring;ýèõíóç',
theme_pre : 'Preformatted',
theme_h1 : '&Aring;ðéê&aring;&ouml;áëß&auml;á 1',
theme_h2 : '&Aring;ðéê&aring;&ouml;áëß&auml;á 2',
theme_h3 : '&Aring;ðéê&aring;&ouml;áëß&auml;á 3',
theme_h4 : '&Aring;ðéê&aring;&ouml;áëß&auml;á 4',
theme_h5 : '&Aring;ðéê&aring;&ouml;áëß&auml;á 5',
theme_h6 : '&Aring;ðéê&aring;&ouml;áëß&auml;á 6',
theme_colorpicker_title : '×ñþìáôá',
theme_colorpicker_apply : '&Aring;&ouml;áñìïãÞ',
theme_forecolor_desc : '&Aring;ðéëïãÞ ÷ñþìáôïò ãñáììáôïó&aring;éñÜò',
theme_backcolor_desc : 'Select background color',
theme_charmap_title : '&Aring;ðéëïãÞ &aring;é&auml;éêïý ÷áñáêôÞñá',
theme_charmap_desc : '&Aring;éóáãùãÞ &aring;é&auml;éêïý ÷áñáêôÞñá',
theme_visualaid_desc : '&Aring;ì&ouml;Üíéóç/Áðüêñõøç ãñáììþí',
insert_anchor_title : '&Aring;éóáãùãÞ/&Auml;éüñèùóç Üãêõñáò',
insert_anchor_name : 'Ïíïìáóßá Üãêõñáò',
theme_anchor_desc : '&Aring;éóáãùãÞ/&Auml;éüñèùóç Üãêõñáò',
theme_insert_link_titlefield : 'Ôßôëïò',
theme_clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
theme_path : 'Path',
cut_desc : 'Cut',
copy_desc : 'Copy',
paste_desc : 'Paste',
link_list : 'Link list',
image_list : 'Image list',
browse : 'Browse',
image_props_desc : 'Image properties',
newdocument_desc : 'New document',
class_name : 'ÊëÜóç', 
newdocument : 'Are you sure you want clear all contents?'
});
