<?php
/************************************************************************
SAXON: Simple Accessible XHTML Online News/RSS Creation system
Module: config.php
Version 4.6
Developed by Black Widow
Copyright (c) 2004 by Black Widow
Support: www.forum.quirm.net
Commercial Site: www.blackwidows.co.uk
************************************************************************/
/* Start MySQL settings
If you have any database connection problems, check this section. */

/* Database name */
$mdb = "database_name";

/* MySQL Host name */
$mhost = "your_host";

/* MySQL Username */
$muser = "your_username";

/* MySQL Password */
$mpass = "your_password";

/* MySQL table prefix. Use to prefix SAXON tables. 
Handy if you want to run multiple implemextations of SAXON from the one db
Just make the table prefix unique for each implementation. */
$prefix = "SX_";

/* End MySQL settings
Start Path settings
If you encounter 'fopen' or 'couldn't locate' errors, check this section. */

/* The URL of your site. This should be the TOP LEVEL for the domain.
Example: 
	Your site is at http:/* www.your_domain.com/website/
	Set $uri to e.g. http:/* www.your_domain.com/ and NOT http:/* www.your_domain.com/website/
DO NOT FORGET THE TRAILING SLASH!! */
$uri = "http://www.your_site.invalid/";

/*The path to your SAXON directory from the TOP LEVEL
Using the example above, $path should be set to 'website/"path_to_SAXON/'
DO NOT FORGET THE TRAILING SLASH!! */
$path = "saxon/";

/* End Path settings
Start Template settings

This section defines the templates which will be used to display your news
Look in your templates folder to see what templates you have and amend if necessary.
I'd suggest making a copy of the originals, first, though.
If your news isn't being displayed proeprly, check this section.
If you've amended the original Template files, check for any syntax errors or try re-instating the original Templates.
If re-instating the originals solves your problem, you almost certainly have a syntax error in your amended Templates.*/

/* Template for the main news page */
$template = "templates/saxon-main-template.php";

/* Template for displaying a single news item */
$singleItem = "templates/saxon-item-template.php";

/* End Template settings
Start RSS settings 
If you encounter RSS news 404 errors, check this section. */

/* Filename of your xml RSS file */
$xml_filename = "templates/news.xml";

/* The title of your RSS feed, or web site */
$xml_title = "SAXON Development";

// URL of your Main News page
$news_url ="http://www.your_site.invalid/saxon/templates/index.php";

/* The description of your RSS feed */
$xml_desc = "A News Feed Generated By SAXON";

/* The language you are using. Make sure you use the correct XML language code */
$xml_lang = "en-uk";

/* The number of words to output, per news item, in the RSS feed */
$xml_chr = 30;

/* End RSS settings
Start Display settings */

/* The number of items to output on the main news page. Set to 0 to display all news items */
$max_items = 5;

/* The number of words to output on the main news page. Set to 0 to display full news items */
$newslength = 50;

/* HTML allowed? (0 for no, 1 for yes) */
$html = 1;

/* End Display settings
Start Admin settings */

/* Do you want an email sent each time a news item is added? (0 for no, 1 for yes) */
$notify = 1;

/* Admin email address - used to notify addition/editing of news items or fake cron errors */
$admin_email = "you@domain.invalid";

/* Server email address. 
You can set this to the same address as $admin_email but some spam filters trip on identical To and From addresses */
$server_email = "you@domain.invalid";

/* End Admin settings */

/* DO NOT CHANGE ANYTHING BELOW THIS LINE! */

/* SAXON version */
$version='4.6';

?>