<?php 
$pop['trennzeichen']['german'] = "Der Inhalt der Tabelle wird in eine Datei gespeichert. Die einzelnen Felder werden durch das <b>Trennzeichen</b> voneinander getrennt, sodass man sie auch eindeutig wieder trennen kann.<p>Daher ist es sinnvoll ein Zeichen zu w&auml;hlen, welches nicht innerhalb der Nutzdaten vorkommt.<p>Es bietet sich das Pipe-Zeichen (\"|\") an. M&ouml;chte man den Tabulator als Trennzeichen verwenden, dann muss man \"tab\" in das Textfeld eintragen.";
$pop['trennzeichen']['english'] = "The table contents is written to a file. The table fields will be separated by the <b>separator</b> so that they can be split correctly later.<p>It makes sense to choose a separator which does not appear in the data itself.<p>The pipe symbol (\"|\") seems to be a good choice. If you wish to use the tab character as the separater just type \"tab\" into the input field.";

$pop['sichere_def']['german'] = "Wenn die Checkbox aktiviert ist, wird die Tabellendefinition in eine seperate Textdatei gespeichert. Der Name der Textdatei beginnt mit \"create_\".<p>Die Tabellendefinition ist der SQL-Befehl, der die Tabelle erzeugt. Die Datei befindet sich im Unterverzeichnis \"data/{Datenbankname}/\".<p>Beispiel einer Tabellendefinition:<br>\"CREATE TABLE xy { id INT(10), marke VARCHAR(20) NOT NULL, ...\" ";
$pop['sichere_def']['english'] = "If the check box is checked the table definition will be written to a separate text file. The name of that file starts with \"crate_\".<p>The table definition is the SQL command that creates the table. The file is located in the subdirectory \"data/{data_base_name}\".<p>Example of a table definition:<br>\"CREATE TABLE xy { id INT(10), tag VARCHAR(20) NOT NULL, ...\" ";

$pop['sichere_inhalt']['german'] = "Wenn die Checkbox aktiviert ist, wird der Inhalt der Tabelle in eine seperate Textdatei gespeichert. Der Name der Textdatei lautet \"{Tabellenname}.txt\".<p>Eine Zeile in der Textdatei stellt einen Datensatz dar. Dieser Datensatz wird durch das Trennzeichen in die Datenfelder unterteilt. Die Datei befindet sich im Unterverzeichnis \"data/{Datenbankname}/\".<p>Beispiel einer Datei mit zwei Datens&auml;tzen und drei Datenfeldern:<br>1|Horst|45.9<br>2|Peter|23.4 ";
$pop['sichere_inhalt']['english'] = "If the check box is checked the table contents will be written to a separate text file. The name of that file is \"{table_name}.txt\".<p>Each line in the file represents a data record. Each record is consists of data fields separated by the separator. The file is located in the subdirectory \"data/{data_base_name}\".<p>Example of a file containing to data records of 3 fields each:<br>1|Adam|45.9<br>2|Peter|23.4 ";

$pop['ueberschreibe']['german'] = "Wenn die Checkbox aktiviert ist, werden alle vorhandenen Dateien &uuml;berschrieben, falls sie schon existieren.<p>Ist die Checkbox nicht aktiviert, werden nur die Dateien geschrieben, die nicht im Dateisystem existieren.";
$pop['ueberschreibe']['english'] = "If the check box is checked any existing files will be overwritten.<p>If the check box is unchecked only those files are created which do not already exist, existing files are left untouched. ";

$pop['zu_email']['german'] = "Wird in das Textfeld eine e-Mail Adresse eingetragen, so werden die Textdateien als Attachment versendet.<p>Das funktioniert leider nicht auf allen Servern.";
$pop['zu_email']['english'] = "Type your eMail in the textbox and you get the textfiles per mail with the attachment.<p>Unfortunately, it doesn't work with all servers.";

$pop['loesche_tab']['german'] = "Wenn die Checkbox aktiviert ist, werden alle vorhandenen Daten gel&ouml;scht, falls welche existieren.<p>Ist die Checkbox nicht aktiviert, werden die Daten angeh&auml;ngt. Das heisst, es sind hinterher m&ouml;glicherweise mehr Datens&auml;tze in der Tabelle, als in der Textdatei aus der gelesen wurde.";
$pop['loesche_tab']['english'] = "If the check box is checked any existing datasets will be deleted.<p>If the check box is unchecked the new datasets will enlarge the table. It could be, that the will be more datasets the table, as in the textfiles from which the script was reading.";

$pop['loesche_tabdef']['german'] = "Wenn die Checkbox aktiviert ist, werden alle vorhandenen Tabellen gel&ouml;scht, falls welche existieren. Also werden auch alle Datens&auml;tze gel&ouml;scht.<p>Ist die Checkbox nicht aktiviert, werden die Tabellen erstellt. Falls sie schon exisiterten, wird eine Fehlermeldung ausgegeben.";
$pop['loesche_tabdef']['english'] = "If the check box is checked any existing tables will be deleted. So, all datasets get lost.<p>If the check box is unchecked the table will be generated. An errormessage appears, if the tables are existing.";

$pop['gzip']['german'] = "Wenn die Checkbox aktiviert ist, werden alle Backup Dateien als gzip-Dateien gepackt. Es werden Dateien mit der Endung \".gz\" generiert.<p>WICHTIG: Die \"zlib\"-Bibliothek ist im PHP-Modul einzubinden.<p>Ist die Checkbox nicht aktiviert, werden die Dateien auch nicht gepackt.";
$pop['gzip']['english'] = "If the check box is checked all backup files will be compressed as gzip files. \".gz\"-files are the result.<p>IMPORTANT: To use this feature, you have to compile your PHP with the zlib library.<p>If the check box is unchecked any file won't be compressed.";

$pop['zipping']['german'] = "Wenn die Checkbox aktiviert ist, werden alle Backup Dateien in eine ZIP-Datei gepackt. Es wird eine Datei mit der Endung \".zip\" generiert.<p>Die Datei bekommt im Dateinamen das aktuelle Datum mitgeliefert, sowie den Datenbanknamen.<br>Beispiel: \"2003_04_25_mydb.zip\"<p>WICHTIG: Die \"zlib\"-Bibliothek ist im PHP-Modul einzubinden.<p>Ist die Checkbox nicht aktiviert, wird die ZIP-Datei nicht erzeugt.";
$pop['zipping']['english'] = "If the check box is checked all backup files will be compressed into one zipfile. A \".zip\"-file is the result.<p>The name of the file consists of the actual date and the databasename.<br>Example: \"2003_04_25_mydb.zip\"<p>IMPORTANT: To use this feature, you have to compile your PHP with the zlib library.<p>If the check box is unchecked the file won't be written.";

$pop['anzahldatasets']['german'] = "Hiermit wird die Anzahl der Datensätze pro Datei bestimmt. Wählt Ihr einen hohen Wert, werden weniger Dateien generiert, als bei einem niedrigen Wert.<br><br>Wählt Ihr die Anzahl zu hoch, kann möglicherweise wieder ein Timeout kommen.<br><br>Die Dateien werden mit \"001\"-beginnend durchnummeriert. Es muss experimentiert werden.";
$pop['anzahldatasets']['english'] = "Set the number of datasets in one file. A high value will produce a low amount of files. A lower value instead will produce more files.<br><br>A high value raises the possibillity of a timeout. The files gets the extension from \"001\" to \"nnn\".<br><br>You have to experiment.";

$pop['blob']['german'] = "Ein BLOB ist großes Binärobjekt (Binary Large OBject), das eine variable Menge von Daten enthalten kann. Dieser Datentyp enthält oft Dateien.<p>Wenn die Checkbox aktiviert ist, werden alle Inhalte in BLOB-Feldern als Dateien im Verzeichnis 'blobs' gespeichert. Dies kann auch zu unerwünschten Ergebnissen führen, falls die Inhalte in den Blobfeldern keine Dateien sind.<p>Ist die Checkbox nicht aktiviert, werden die Inhalte in den Blobfeldern ganz normal wie jeder andere Datentyp behandelt. Es werden also keine neuen Dateien erzeugt.";
$pop['blob']['english'] = "A BLOB is a binary large object that can hold a variable amount of data. This datatyp often contains files.<p>If the check box is checked all content in the BLOB-Fields will be saved in single files. The script creates a directory named 'blobs'. Attention: You can get unwanted results, if the content in the blob-fields are no files.<p>If the check box is unchecked the blob-fields will be treated as every datatyp. No seperate files will be produced.";

$pop['parameter']['german'] = "Wähle hier AND, OR oder XOR.<br>Falls oben mindestens zwei Parameter gesetzt werden, wird die Abfrage mit diesem Logikoperator verknüpft.";
$pop['parameter']['english'] = "Choose AND, OR or XOR. If you set above at least two parameters, the query will be combined with this logic operator.";
?>