<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
	<title>Automated Link Exchange - LNKX</title>
	<meta name="revisit-after" content="2 Weeks">
	<meta name="Robot" content="ALL">
	<meta name="rating" content="General">
	<link rel="stylesheet" type="text/css" href="/main.css" />
</head>
<body>
<div style="background-image:url(http://www.citypost.ca/img/panorama2a.jpg)">

<table cellpadding="0px" cellspacing="0px" border="0px" width=750px height=80px>
	<tr>
		<td style="text-align:center;">
      <a href="http://tech.citypost.ca"><img border=0 src="http://www.citypost.ca/img/logo.gif"></a></td>
		<td style="text-align:center">
      <script type="text/javascript"><!--
      google_ad_client = "pub-6448205169656720";
      google_ad_width = 468;
      google_ad_height = 60;
      google_ad_format = "468x60_as";
      google_ad_channel ="";
      google_ad_type = "text_image";
      google_color_border = "FFFFFF";
      google_color_bg = "FFFFFF";
      google_color_link = "0000FF";
      google_color_url = "EEEEEE";
      google_color_text = "000000";
      //--></script>
      <script type="text/javascript"
        src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
      </script>
		</td>
	<tr>
</table>
<table width="100%" height="3px" cellpadding="0px" cellspacing="0px" bgcolor="#ff5500"
		 style="font-size:1px;background-color:#ff5500;">
	<tr><td>&nbsp;</td></tr>
</table>
</div>
