// UK lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'ëììé',
popup_tab : 'çìåï ÷åôõ',
events_tab : 'àøåòéí',
advanced_tab : 'îú÷ãí',
general_props : 'îàôééðéí ëììééí',
popup_props : 'îàôééðé äçìåï ä÷åôõ',
event_props : 'àøåòéí',
advanced_props : 'îàôééðéí îú÷ãîéí',
popup_opts : 'àôùøåéåú',
anchor_names : 'òåâðéí',
target_same : 'ôúç áçìåï æä àå îñâøú æå',
target_parent : 'ôúç áçìåï àå áîñâøú äî÷åøééí',
target_top : 'ôúç áîñâøú äøàùéú (îçìéó àú ëì äîñâøåú)',
target_blank : 'ôúç áçìåï çãù',
popup : 'çìåï ÷åôõ ùì Javascript',
popup_url : 'ëúåáú äçìåï ä÷åôõ',
popup_name : 'ùí äçìåï',
popup_return : 'äëðñ \'return false\'',
popup_scrollbars : 'äöâ ôñé âìéìä',
popup_statusbar : 'äöâ ùåøú îöá',
popup_toolbar : 'äöâ ñøâìé ëìåí',
popup_menubar : 'äöâ àú ùåøú äúôøéèéí',
popup_location : 'äöâ àú ùåøú äëúåáú',
popup_resizable : 'çìåï ùðéúï ìùðåú àú âåãìå',
popup_dependent : 'úìåé (Mozilla/Firefox áìáã)',
popup_size : 'âåãì',
popup_position : 'îé÷åí (X/Y)',
id : 'Id',
style: 'ñâðåï',
classes : 'Classéí',
target_name : 'ùí éòã',
langdir : 'ëéååï ùôä',
target_langcode : 'ùôú éòã',
langcode : '÷åã ùôä',
encoding : '÷éãåã úååéí ùì äéòã',
mime : 'ñåâ MIME ùì äéòã',
rel : 'éçñ ùì ãó ìéòã',
rev : 'éçñ ùì éòã ìãó',
tabindex : 'ñãø èàáéí',
accesskey : 'î÷ù âéùä',
ltr : 'ùîàì ìéîéï',
rtl : 'éîéï ìùîàì'
});