// RU cp1251 lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'Îñíîâíûå',
popup_tab : 'Âñïëûâàþùèå',
events_tab : 'Ñîáûòèÿ',
advanced_tab : 'Ðàñøèðåííûå',
general_props : 'Îñíîâíûå ñâîéñòâà',
popup_props : 'Ñâîéñòâà Popup ýëåìåíòîâ',
event_props : 'Ñîáûòèÿ',
advanced_props : 'Ðàñøèðåííûå íàñòðîéêè',
popup_opts : 'Îïöèè',
anchor_names : 'ßêîðÿ',
target_same : 'Îòêðûâàòü â ýòîì îêíå / ôðåéìå',
target_parent : 'Îòêðûâàòü â ðîäèòåëüñêîì îêíå / ôðåéìå',
target_top : 'Îòêðûâàòü â âåðõíåì ôðåéìå (çàìåíÿòü âñå ôðåéìû)',
target_blank : 'Îòêðûâàòü â íîâîì îêíå',
popup : 'Javascript popup',
popup_url : 'Popup URL',
popup_name : 'Èìÿ îêíà',
popup_return : 'Insert \'return false\'',
popup_scrollbars : 'Ïîêàçûâàòü ëèíåéêè ïðîêðóòêè',
popup_statusbar : 'Ïîêàçûâàòü status bar',
popup_toolbar : 'Ïîêàçûâàòü ïàíåëè èíñòðóìåíòîâ',
popup_menubar : 'Ïîêàçûâàòü ïàíåëü ìåíþ',
popup_location : 'Ïîêàçûâàòü location bar',
popup_resizable : 'Ïîçâîëèòü èçìåíÿòü ðàçìåðû îêíà',
popup_dependent : 'Çàâèñèìîñòü (òîëüêî Mozilla/Firefox)',
popup_size : 'Ðàçìåð',
popup_position : 'Ðàñïîëîæåíèå (X/Y)',
id : 'Id',
style: 'Ñòèëü',
classes : 'Êëàññû',
target_name : 'Èìÿ öåëè',
langdir : 'Íàïðàâëåíèå ïèñüìà â ÿçûêå',
target_langcode : 'Öåëåâîé ÿçûê',
langcode : 'Êîä ÿçûêà',
encoding : 'Öåëåâàÿ êîäèðîâêà',
mime : 'Öåëåâîé MIME òèï',
rel : 'Çàâèñèìîñòü page -> target',
rev : 'Çàâèñèìîñòü target -> page',
tabindex : 'Tabindex',
accesskey : 'Accesskey',
ltr : 'Ñëåâà íàïðàâî',
rtl : 'Ñïðàâà íàëåâî',
delta_width : 40
});
