// RU KOI8-R lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'ïÓÎÏ×ÎÙÅ',
popup_tab : '÷ÓÐÌÙ×ÁÀÝÉÅ',
events_tab : 'óÏÂÙÔÉÑ',
advanced_tab : 'òÁÓÛÉÒÅÎÎÙÅ',
general_props : 'ïÓÎÏ×ÎÙÅ Ó×ÏÊÓÔ×Á',
popup_props : 'ó×ÏÊÓÔ×Á Popup ÜÌÅÍÅÎÔÏ×',
event_props : 'óÏÂÙÔÉÑ',
advanced_props : 'òÁÓÛÉÒÅÎÎÙÅ ÎÁÓÔÒÏÊËÉ',
popup_opts : 'ïÐÃÉÉ',
anchor_names : 'ñËÏÒÑ',
target_same : 'ïÔËÒÙ×ÁÔØ × ÜÔÏÍ ÏËÎÅ / ÆÒÅÊÍÅ',
target_parent : 'ïÔËÒÙ×ÁÔØ × ÒÏÄÉÔÅÌØÓËÏÍ ÏËÎÅ / ÆÒÅÊÍÅ',
target_top : 'ïÔËÒÙ×ÁÔØ × ×ÅÒÈÎÅÍ ÆÒÅÊÍÅ (ÚÁÍÅÎÑÔØ ×ÓÅ ÆÒÅÊÍÙ)',
target_blank : 'ïÔËÒÙ×ÁÔØ × ÎÏ×ÏÍ ÏËÎÅ',
popup : 'Javascript popup',
popup_url : 'Popup URL',
popup_name : 'éÍÑ ÏËÎÁ',
popup_return : 'Insert \'return false\'',
popup_scrollbars : 'ðÏËÁÚÙ×ÁÔØ ÌÉÎÅÊËÉ ÐÒÏËÒÕÔËÉ',
popup_statusbar : 'ðÏËÁÚÙ×ÁÔØ status bar',
popup_toolbar : 'ðÏËÁÚÙ×ÁÔØ ÐÁÎÅÌÉ ÉÎÓÔÒÕÍÅÎÔÏ×',
popup_menubar : 'ðÏËÁÚÙ×ÁÔØ ÐÁÎÅÌØ ÍÅÎÀ',
popup_location : 'ðÏËÁÚÙ×ÁÔØ location bar',
popup_resizable : 'ðÏÚ×ÏÌÉÔØ ÉÚÍÅÎÑÔØ ÒÁÚÍÅÒÙ ÏËÎÁ',
popup_dependent : 'úÁ×ÉÓÉÍÏÓÔØ (ÔÏÌØËÏ Mozilla/Firefox)',
popup_size : 'òÁÚÍÅÒ',
popup_position : 'òÁÓÐÏÌÏÖÅÎÉÅ (X/Y)',
id : 'Id',
style: 'óÔÉÌØ',
classes : 'ëÌÁÓÓÙ',
target_name : 'éÍÑ ÃÅÌÉ',
langdir : 'îÁÐÒÁ×ÌÅÎÉÅ ÐÉÓØÍÁ × ÑÚÙËÅ',
target_langcode : 'ãÅÌÅ×ÏÊ ÑÚÙË',
langcode : 'ëÏÄ ÑÚÙËÁ',
encoding : 'ãÅÌÅ×ÁÑ ËÏÄÉÒÏ×ËÁ',
mime : 'ãÅÌÅ×ÏÊ MIME ÔÉÐ',
rel : 'úÁ×ÉÓÉÍÏÓÔØ page -> target',
rev : 'úÁ×ÉÓÉÍÏÓÔØ target -> page',
tabindex : 'Tabindex',
accesskey : 'Accesskey',
ltr : 'óÌÅ×Á ÎÁÐÒÁ×Ï',
rtl : 'óÐÒÁ×Á ÎÁÌÅ×Ï'
});
