<html>
<head>
<title>edgesupport.com</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<style type="text/css">
<!--
input {  font-family: Verdana; font-size: 11px; background-image: url(gfx/textfield-back.jpg); border: 0px #8EA0AA solid; padding-top: 1px; padding-right: 0px; padding-bottom: 0px; padding-left: 3px; margin-top: 2px; margin-right: 2px; margin-bottom: 2px; margin-left: 2px; filter: Chroma(Color=#8EA0AA); color: #778890; clip:  rect(2px 2px 2px 2px); font-weight: bold}
-->
</style>
<script language="JavaScript">
<!--
function MM_swapImgRestore() { //v3.0
  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;
}

function MM_preloadImages() { //v3.0
  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_swapImage() { //v3.0
  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)
   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}
}
//-->
</script>
</head>
<body bgcolor="#FFFFFF" text="#000000" leftmargin="0" onLoad="MM_preloadImages('gfx/submitover.jpg','gfx/resetover.jpg')">
<table width="100%" border="0" cellspacing="0" cellpadding="0" height="100%">
  <tr> 
    <td colspan="3">&nbsp;</td>
  </tr>
  <tr> 
    <td height="290" rowspan="3">&nbsp;</td>
    <td height="37" width="501"><a href="http://forum.edgesupport.com/"><img src="gfx/forums.jpg" width="67" height="37" border="0"></a><a href="https://www.edgebilling.com/"><img src="gfx/billingcontrol.jpg" width="151" height="37" border="0"></a><a href="http://www.edgesupport.com/cgi-bin/pdesk.cgi"><img src="gfx/supportdesk.jpg" width="101" height="37" border="0"></a><img src="gfx/dedicated.jpg" width="182" height="37"></td>
    <td height="290" rowspan="3">&nbsp;</td>
  </tr>
  <tr> 
    <td height="150" width="501"> 
      <table width="100%" border="0" cellspacing="0" cellpadding="0" height="100%">
        <tr> 
          <td height="44"><img src="gfx/toppanel.jpg" width="501" height="44"></td>
        </tr>
        <tr> 
		<form action="login.php" method="post" name="theForm">
          <td height="88"> 
		  
            <table width="100%" border="0" cellspacing="0" cellpadding="0" height="100%">
              <tr> 
                <td width="151" height="51"><img src="gfx/username.jpg" width="175" height="51"></td>
                <td width="350" background="gfx/usernameback.jpg" valign="top"> 
                  
                    <table width="100%" border="0" cellspacing="0" cellpadding="0" height="100%">
                      <tr> 
                        <td height="21">&nbsp;</td>
                      </tr>
                      <tr> 
                        <td> 
                          <input type="text" name="username">
                        </td>
                      </tr>
                    </table>
                
                </td>
              </tr>
              <tr> 
                <td width="151" height="37"><img src="gfx/password.jpg" width="175" height="37"></td>
                <td width="350" background="gfx/passwordback.jpg"> 
                  <input type="password" name="password">
                </td>
              </tr>
            </table>

          </td>
		    </form>
        </tr>
        <tr> 
          <td height="18"><img src="gfx/bottompanel.jpg" width="501" height="18"></td>
        </tr>
      </table>
    </td>
  </tr>
  <tr> 
    <td height="103" width="501"><img src="gfx/bottombar.jpg" width="333" height="103"><a href="#" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image11','','gfx/submitover.jpg',1)"><img name="Image11" border="0" src="gfx/submit.jpg" width="83" height="103" onClick="document.theForm.submit()"></a><a href="#" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image12','','gfx/resetover.jpg',1)"><img name="Image12" border="0" src="gfx/reset.jpg" width="85" height="103" onClick="document.theForm.reset();"></a></td>
  </tr>
  <tr> 
    <td colspan="3">&nbsp;</td>
  </tr>
</table>
</body>
</html>