CREATE TABLE profile (
	email char(35) DEFAULT 'email' NOT NULL,
	name char(35) DEFAULT 'name' NOT NULL,
	address char(50) DEFAULT 'address' NOT NULL,
	city char(35) DEFAULT 'city' NOT NULL,
	state char(35) DEFAULT 'state' NOT NULL,
	country char(50) DEFAULT 'country' NOT NULL,
	zip char(16) DEFAULT 'zip' NOT NULL,
	phone char(35) DEFAULT 'phone' NOT NULL,
	username char(12) DEFAULT 'username' NOT NULL,
	password char(12) DEFAULT 'password' NOT NULL,
	PRIMARY KEY(username,email)
);

CREATE TABLE feedback (
	username char(12) DEFAULT 'username' NOT NULL,
	losername char(12) DEFAULT 'losername' NOT NULL,
	comments char(100) DEFAULT 'comments' NOT NULL,
	rating char(1) DEFAULT 'rating' NOT NULL,
	date char(5) DEFAULT 'date' NOT NULL,
	itemnumber char(25) DEFAULT 'itemnumber' NOT NULL,
	PRIMARY KEY(itemnumber)
);

CREATE TABLE items (
	itemnumber char(25) DEFAULT 'itemnumber' NOT NULL,
	title char(35) DEFAULT 'title' NOT NULL,
	category char(35) DEFAULT 'category' NOT NULL,
	description char(250) DEFAULT 'description' NOT NULL,
	reserve char(12) DEFAULT 'reserve' NOT NULL,
	getnoticed char(16) DEFAULT 'getnoticed' NOT NULL,
	pictureurl char(50) DEFAULT 'pictureurl' NOT NULL,
	username char(12) DEFAULT 'username' NOT NULL,
	password char(12) DEFAULT 'password' NOT NULL,
	startprice char(16) DEFAULT 'startprice' NOT NULL,
	duration char(1) DEFAULT 'duration' NOT NULL,
	buyerpaymentmethod char(50) DEFAULT 'buyerpaymentmethod' NOT NULL,
	shipinternationally char(50) DEFAULT 'shipinternationally' NOT NULL,
	whopaysshipping char(50) DEFAULT 'whopaysshipping' NOT NULL,
	paymentmethodbyseller char(50) DEFAULT 'paymentmethodbyseller' NOT NULL,
	cardnumber char(21) DEFAULT 'cardnumber' NOT NULL,
	expirationdate char(6) DEFAULT 'expirationdate' NOT NULL,
	startday char(6) DEFAULT 'startday' NOT NULL,
	starttime char(12) DEFAULT 'starttime' NOT NULL,
	currenthibid char(16) DEFAULT 'currenthibid' NOT NULL,
	currenthibidder char(12) DEFAULT 'currenthibidder' NOT NULL,
	currenthibidemail char(50) DEFAULT 'currenthibidemail' NOT NULL,
	maxbid char(16) DEFAULT 'maxbid' NOT NULL,
	finalbid char(16) DEFAULT 'finalbid' NOT NULL,
	itemstatus char(12) DEFAULT 'itemstatus' NOT NULL,
	PRIMARY KEY(itemnumber)
);
CREATE TABLE closeditems (
	itemnumber char(25) DEFAULT 'itemnumber' NOT NULL,
	title char(35) DEFAULT 'title' NOT NULL,
	category char(35) DEFAULT 'category' NOT NULL,
	description char(250) DEFAULT 'description' NOT NULL,
	reserve char(12) DEFAULT 'reserve' NOT NULL,
	getnoticed char(16) DEFAULT 'getnoticed' NOT NULL,
	pictureurl char(50) DEFAULT 'pictureurl' NOT NULL,
	username char(12) DEFAULT 'username' NOT NULL,
	password char(12) DEFAULT 'password' NOT NULL,
	startprice char(16) DEFAULT 'startprice' NOT NULL,
	duration char(1) DEFAULT 'duration' NOT NULL,
	buyerpaymentmethod char(50) DEFAULT 'buyerpaymentmethod' NOT NULL,
	shipinternationally char(50) DEFAULT 'shipinternationally' NOT NULL,
	whopaysshipping char(50) DEFAULT 'whopaysshipping' NOT NULL,
	paymentmethodbyseller char(50) DEFAULT 'paymentmethodbyseller' NOT NULL,
	cardnumber char(21) DEFAULT 'cardnumber' NOT NULL,
	expirationdate char(6) DEFAULT 'expirationdate' NOT NULL,
	startday char(6) DEFAULT 'startday' NOT NULL,
	starttime char(12) DEFAULT 'starttime' NOT NULL,
	currenthibid char(16) DEFAULT 'currenthibid' NOT NULL,
	currenthibidder char(12) DEFAULT 'currenthibidder' NOT NULL,
	currenthibidemail char(50) DEFAULT 'currenthibidemail' NOT NULL,
	maxbid char(16) DEFAULT 'maxbid' NOT NULL,
	finalbid char(16) DEFAULT 'finalbid' NOT NULL,
	itemstatus char(12) DEFAULT 'itemstatus' NOT NULL,
	PRIMARY KEY(itemnumber)
);