<?php 

// skin_global.php
// Skin file auto generated by RW::Download v4.0 Beta 3 [14/05/04]
// It is highly recommended you do NOT edit this file
// Doing so could break the skinning engine and the script
// This skin can be edited by using the Skin Controls in the Admin CP

class skin_global
{
function warning($data)
{
global $rwdInfo;
//--START--//
$SHTML = "<table width='70%' border='0' align='center' cellpadding='3' cellspacing='3' class='dashed'>
            <tr> 
              <td><img src='{$rwdInfo->skinurl}/images/warning.jpg' width='50' height='50'></td>
              <td class='red'>{$rwdInfo->lang['warning']}: {$data['message']}
		</td>
            </tr>
          </table>";
//--END--//
return $SHTML;
}

function info($data)
{
global $rwdInfo;
//--START--//
$SHTML = "<table width='70%' border='0' align='center' cellpadding='3' cellspacing='3' class='dashed'>
            <tr> 
              <td><img src='{$rwdInfo->skinurl}/images/info.jpg' width='50' height='50'></td>
              <td><b>{$rwdInfo->lang['info']}: {$data['message']}</b>
		</td>
            </tr>
          </table>";
//--END--//
return $SHTML;
}

function error($data)
{
global $rwdInfo;
//--START--//
$SHTML = "<table width='70%' border='0' align='center' cellpadding='3' cellspacing='3' class='dashed'>
            <tr> 
              <td><img src='{$rwdInfo->skinurl}/images/error.jpg' width='50' height='50'></td>
              <td><b>{$rwdInfo->lang['error']}: {$data['message']}</b>
		</td>
            </tr>
          </table>";
//--END--//
return $SHTML;
}

}

?>
