<?php

$smileTags=array();
$smileTags[0] = '[s:wink.gif]';
$smileTags[1] = '[s:angry.gif]';
$smileTags[2] = '[s:biggrin.gif]';
$smileTags[3] = '[s:bigsmile.gif]';
$smileTags[4] = '[s:cool.gif]';
$smileTags[5] = '[s:crazy.gif]';
$smileTags[6] = '[s:dozingoff.gif]';
$smileTags[7] = '[s:eh.gif]';
$smileTags[8] = '[s:laugh.gif]';
$smileTags[9] = '[s:omg.gif]';
$smileTags[10] = '[s:rolleyes.gif]';
$smileTags[11] = '[s:smile.gif]';
$smileTags[12] = '[s:tounge.gif]';
$smileTags[13] = '[s:unhappy.gif]';
$smileTags[14] = '[s:mrgreen.gif]';
$smileTags[15] = '[s:neutral.gif]';
$smileTags[16] = '[s:question.gif]';
$smileTags[17] = '[s:redface.gif]';
$smileTags[18] = '[s:sad.gif]';
$smileTags[19] = '[s:twisted.gif]';
$smileTags[20] = '[s:arrow.gif]';
$smileTags[21] = '[s:arrowd.gif]';
$smileTags[22] = '[s:arrowl.gif]';
$smileTags[23] = '[s:arrowu.gif]';
$smileTags[24] = '[s:cry.gif]';
$smileTags[25] = '[s:evil.gif]';
$smileTags[26] = '[s:exclaim.gif]';
$smileTags[27] = '[s:idea.gif]';
$smileTags[28] = '[s:mad.gif]';
$smileImgs=array();
$smileImgs[0] = '<img src=images/smiles/wink.gif border=0>';
$smileImgs[1] = '<img src=images/smiles/angry.gif border=0>';
$smileImgs[2] = '<img src=images/smiles/biggrin.gif border=0>';
$smileImgs[3] = '<img src=images/smiles/bigsmile.gif border=0>';
$smileImgs[4] = '<img src=images/smiles/cool.gif border=0>';
$smileImgs[5] = '<img src=images/smiles/crazy.gif border=0>';
$smileImgs[6] = '<img src=images/smiles/dozingoff.gif border=0>';
$smileImgs[7] = '<img src=images/smiles/eh.gif border=0>';
$smileImgs[8] = '<img src=images/smiles/laugh.gif border=0>';
$smileImgs[9] = '<img src=images/smiles/omg.gif border=0>';
$smileImgs[10] = '<img src=images/smiles/rolleyes.gif border=0>';
$smileImgs[11] = '<img src=images/smiles/smile.gif border=0>';
$smileImgs[12] = '<img src=images/smiles/tounge.gif border=0>';
$smileImgs[13] = '<img src=images/smiles/unhappy.gif border=0>';
$smileImgs[14] = '<img src=images/smiles/mrgreen.gif border=0>';
$smileImgs[15] = '<img src=images/smiles/neutral.gif border=0>';
$smileImgs[16] = '<img src=images/smiles/question.gif border=0>';
$smileImgs[17] = '<img src=images/smiles/redface.gif border=0>';
$smileImgs[18] = '<img src=images/smiles/sad.gif border=0>';
$smileImgs[19] = '<img src=images/smiles/twisted.gif border=0>';
$smileImgs[20] = '<img src=images/smiles/arrow.gif border=0>';
$smileImgs[21] = '<img src=images/smiles/arrowd.gif border=0>';
$smileImgs[22] = '<img src=images/smiles/arrowl.gif border=0>';
$smileImgs[23] = '<img src=images/smiles/arrowu.gif border=0>';
$smileImgs[24] = '<img src=images/smiles/cry.gif border=0>';
$smileImgs[25] = '<img src=images/smiles/evil.gif border=0>';
$smileImgs[26] = '<img src=images/smiles/exclaim.gif border=0>';
$smileImgs[27] = '<img src=images/smiles/idea.gif border=0>';
$smileImgs[28] = '<img src=images/smiles/mad.gif border=0>';
