<div style="padding:4px;border-bottom:1px solid #333"><span class="title"><A href="$_SERVER[PHPSELF]?do=add"><b>Add New Styles</b></a></span></div><br />
<table border="0" cellpadding="0" cellspacing="0" align="center" width="95%">
<tr>
<td class="tblborder">
<table border="0" cellspacing="1" cellpadding="4" align="center" width="100%">
<tr>
<td class="tblhead" colspan="2">
$evoLANG[styles_main]
</td>
</tr>
$loop
</table>
</td>
</tr>
</table>