<?php
/***************************************************************************
 * (c)2002-2004 Boesch IT-Consulting (info@boesch-it.de)
 ***************************************************************************/
?>
<script type="text/javascript" language="javascript">
<!--
function do_add()
{
	document.inputform.destmode.value='add';
	document.inputform.submit();
}
function do_edit()
{
	document.inputform.destmode.value='edit';
	document.inputform.submit();
}
//-->
</script>
