INSERT INTO groups VALUES (1,-1,'Arts & Humanities');
INSERT INTO groups VALUES (2,-1,'Business & Economy');
INSERT INTO groups VALUES (3,-1,'Computers & Internet');
INSERT INTO groups VALUES (4,-1,'Education');
INSERT INTO groups VALUES (5,-1,'Entertainment');
INSERT INTO groups VALUES (6,-1,'Government');
INSERT INTO groups VALUES (7,-1,'Health');
INSERT INTO groups VALUES (8,-1,'News & Media');
INSERT INTO groups VALUES (9,-1,'Recreation & Sports');
INSERT INTO groups VALUES (10,-1,'Reference');
INSERT INTO groups VALUES (11,-1,'Regional');
INSERT INTO groups VALUES (12,-1,'Science');
INSERT INTO groups VALUES (13,-1,'Social Science');
INSERT INTO groups VALUES (14,-1,'Society & Culture');
INSERT INTO groups VALUES (15,1,'Literature');
INSERT INTO groups VALUES (16,1,'Photography');
INSERT INTO groups VALUES (17,2,'B2B');
INSERT INTO groups VALUES (18,2,'Finance');
INSERT INTO groups VALUES (19,2,'Shopping');
INSERT INTO groups VALUES (20,2,'Jobs');
INSERT INTO groups VALUES (21,3,'Internet');
INSERT INTO groups VALUES (22,3,'WWW');
INSERT INTO groups VALUES (23,3,'Software');
INSERT INTO groups VALUES (24,3,'Games');
INSERT INTO groups VALUES (25,4,'College and University');
INSERT INTO groups VALUES (26,4,'K-12');
INSERT INTO groups VALUES (27,5,'Cool Links');
INSERT INTO groups VALUES (28,5,'Movies');
INSERT INTO groups VALUES (29,5,'Humor');
INSERT INTO groups VALUES (30,5,'Music');
INSERT INTO groups VALUES (31,6,'Elections');
INSERT INTO groups VALUES (32,6,'Military');
INSERT INTO groups VALUES (33,6,'Law');
INSERT INTO groups VALUES (34,6,'Taxes');
INSERT INTO groups VALUES (35,7,'Medicine');
INSERT INTO groups VALUES (36,7,'Diseases');
INSERT INTO groups VALUES (37,7,'Drugs');
INSERT INTO groups VALUES (38,7,'Fitness');
INSERT INTO groups VALUES (39,8,'Full Coverage');
INSERT INTO groups VALUES (40,8,'Newspapers');
INSERT INTO groups VALUES (41,8,'TV');
INSERT INTO groups VALUES (42,9,'Sports');
INSERT INTO groups VALUES (43,9,'Travel');
INSERT INTO groups VALUES (44,9,'Autos');
INSERT INTO groups VALUES (45,9,'Outdoors');
INSERT INTO groups VALUES (46,10,'Libraries');
INSERT INTO groups VALUES (47,10,'Dictionaries');
INSERT INTO groups VALUES (48,10,'Quotations');
INSERT INTO groups VALUES (49,11,'Countries');
INSERT INTO groups VALUES (50,11,'Regions');
INSERT INTO groups VALUES (51,11,'US States');
INSERT INTO groups VALUES (52,12,'Animals');
INSERT INTO groups VALUES (53,12,'Astronomy');
INSERT INTO groups VALUES (54,12,'Engineering');
INSERT INTO groups VALUES (55,13,'Archaeology');
INSERT INTO groups VALUES (56,13,'Economics');
INSERT INTO groups VALUES (57,13,'Languages');
INSERT INTO groups VALUES (58,14,'People');
INSERT INTO groups VALUES (59,14,'Environment');
INSERT INTO groups VALUES (60,14,'Religion');