<?
   $age=Array(
        "18"=>"<18",
        "21"=>"18-21",
        "25"=>"22-25",
        "30"=>"26-30",
        "35"=>"31-35",
        "40"=>"36-40",
        "45"=>"41-45",
        "50"=>"46-50",
        "55"=>"51-55",
        "60"=>"56-60",
        "65"=>"61-65",
        "70"=>"66-70",
        "70+"=>"70+"
   );

   $marital=Array(
        "single"=>"Single",
        "married"=>"Married",
        "cohabiting"=>"Domestic Partnership",
        "divorced"=>"Divorced",
        "widowed"=>"Widowed",
        "separated"=>"Separated"
   );

   $household=Array(
        "1"=>"1",
        "2"=>"2",
        "3"=>"3",
        "4"=>"4",
        "5"=>"5",
        "6+"=>"6+"
   );

   $children=Array(
        "0"=>"0",
        "1"=>"1",
        "2"=>"2",
        "3"=>"3",
        "4"=>"4",
        "5+"=>"5+"
   );

   $income=Array(
        "10000"=>"Under $10,000",
        "20000"=>"$10,000 to $19,999",
        "30000"=>"$20,000 to $29,999",
        "40000"=>"$30,000 to $39,999",
        "50000"=>"$40,000 to $49,999",
        "75000"=>"$50,000 to $74,999",
        "100000"=>"$75,000 to $99,999",
        "150000"=>"$100,000 to $149,999",
        "150000+"=>"$150,000+"
   );

   $housestatus=Array(
        "owned"=>"Owned",
        "rented"=>"Rented"
   );

   $learning=Array(
        "school"=>"Some High School",
        "hsdiploma"=>"High School Diploma",
        "college"=>"Some College",
        "collegedegree"=>"College Degree",
        "graduatedegree"=>"Graduate Degree"
   );


   $occupation=Array(
        "academic"=>"Academic",
        "admin"=>"Administrative",
        "Banking"=>"Banking",
        "Consulting"=>"Consulting",
        "Engineering"=>"Engineering",
        "Investment"=>"Investment",
        "Managerial"=>"Managerial",
        "Military"=>"Military",
        "Professional"=>"Professional",
        "Student"=>"Student",
        "Sales"=>"Sales/Marketing",
        "Retired"=>"Retired",
        "Unemployed"=>"Between Jobs",
        "Other"=>"Other"
   );

   $vehicles=Array(
        "0"=>"0",
        "1"=>"1",
        "2"=>"2",
        "3+"=>"3+"
   );

   $spentonline=Array(
        "20"=>"Under $20",
        "50"=>"$20 to $49",
        "100"=>"$50 to $99",
        "100+"=>"$100+"
   );


   $interests=Array(
        "advertising"=>"Advertising",
        "affiliate"=>"Affiliate Programs",
        "arts"=>"Arts",
        "auto"=>"Automotive",
        "books"=>"Books",
        "business"=>"Business",
        "businessops"=>"Business Ops",
        "careers"=>"Careers",
        "computers"=>"Computers",
        "contests"=>"Contests & Lotteries",
        "creditcards"=>"Credit Cards",
        "dating"=>"Dating/Personals",
        "debt"=>"Debt Consolidation",
        "ecommerce"=>"E-Commerce",
        "education"=>"Education",
        "entertainment"=>"Entertainment",
        "fashion"=>"Fashion",
        "family"=>"Family",
        "food"=>"Food & Drink",
        "free"=>"Free Stuff",
        "gambling"=>"Gambling/Casinos",
        "gifts"=>"Gifts",
        "graphics"=>"Graphics",
        "health"=>"Health",
        "home"=>"Home & Garden",
        "homebusiness"=>"Home Business",
        "internet"=>"Internet",
        "legal"=>"Legal",
        "marketing"=>"Marketing",
        "media"=>"Media",
        "mlm"=>"MLM",
        "music"=>"Music",
        "news"=>"News",
        "finance"=>"Personal Finance",
        "pets"=>"Pets",
        "estate"=>"Real Estate",
        "reference"=>"Reference",
        "shopping"=>"Shopping",
        "smallbus"=>"Small Business",
        "sports"=>"Sports & Recreation",
        "sweepstakes"=>"Sweepstakes",
        "technology"=>"Technology",
        "travel"=>"Travel",
        "webmasters"=>"Webmasters",
        "webdesign"=>"Web Design"
   );



$Country=array('United States of America',
      'Malaysia',
      'Singapore',
      'Canada',
      'United Kingdom',
       'Afghanistan',
       'Albania',
       'Algeria',
      'American Samoa',
      'Andorra',
      'Angola',
      'Anguilla',
      'Antarctica',
      'Antigua and Barbuda',
      'Argentina',
      'Armenia',
      'Aruba',
      'Australia',
       'Austria',
      'Azerbaijan',
      'Bahamas',
      'Bahrain',
      'Bangladesh',
      'Barbados',
      'Belarus',
      'Belgium',
      'Belize',
      'Benin',
       'Bermuda',
      'Bhutan',
      'Bolivia',
      'Bosnia and Herzegovina',
      'Botswana',
      'Bouvet Island',
      'Brazil',
      'British Indian Ocean Territory',
      'British Virgin Islands',
      'Brunei',
      'Bulgaria',
      'Burkina Faso',
      'Burundi',
      'Cambodia',
      'Cameroon',
      'Canada',
      'Congo',
      'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
'Denmark',
'Djibouti',
'Dominica',
'Dominican Republic',
'East Timor',
'Ecuador',
'Egypt',
'El Salvador',
'Equatorial Guinea',
'Eritrea',
'Estonia',
'Ethiopia',
'Falkland Islands',
'Faroe Islands',
'Fiji',
'Finland',
'France',
'French Guiana',
'French Polynesia',
'French Southern Territories',
'Gabon',
'Gambia',
'Georgia',
 'Germany',
'Ghana',
'Gibraltar',
'Greece',
'Greenland',
'Grenada',
'Guadeloupe',
'Guam',
'Guatemala',
'Guinea',
'Guinea-Bissau',
'Guyana',
'Haiti',
'Heard and McDonald Islands',
'Honduras',
'Hong Kong',
'Hungary',
'Iceland',
'India',
'Indonesia',
'Iran',
'Iraq',
'Ireland',
'Israel',
'Italy',
'Ivory Coast',
'Jamaica',
'Japan',
'Jordan',
'Kazakhstan',
'Kenya',
'Kiribati',
'Korea, North',
'Korea, South',
'Kuwait',
'Kwyrgyzstan',
'Laos',
'Latvia',
'Lebanon',
'Lesotho',
'Liberia',
'Libya',
'Liechtenstein',
'Lithuania',
'Luxembourg',
'Macau',
'Macedonia',
'Former Yugoslav',
'Republic of Madagascar',
'Malawi',
'Malaysia',
'Maldives',
'Mali',
'Malta',
'Marshall Islands',
'Martinique',
'Mauritania',
'Mauritius',
'Mayotte',
'Mexico',
'Micronesia',
'Federated States of Moldova',
'Monaco',
'Mongolia',
'Montserrat',
'Morocco',
'Mozambique',
'Myanmar',
'Namibia',
'Nauru',
'Nepal',
'Netherlands',
'Netherlands Antilles',
'New Caledonia',
'New Zealand',
'Nicaragua',
'Niger',
'Nigeria',
'Niue',
'Norfolk Island',
'Northern Mariana Islands',
'Norway',
'Oman',
'Pakistan',
'Palau',
'Panama',
'Papua New Guinea',
'Paraguay',
'Peru',
'Philippines',
'Pitcairn Island',
'Poland',
'Portugal',
'Puerto Rico',
'Qatar',
'Reunion',
'Romania',
'Russia',
'Rwanda',
'S. Georgia and S. Sandwich Isls',
'Saint Kitts & Nevis',
'Saint Lucia',
'Saint Vincent and The Grenadines',
'Samoa',
      'Togo',
     'Tokelau',
     'Tonga',
    'Trinidad and Tobago',
     'Tunisia',
     'Turkey',
    'Turkmenistan',
    'Turks and Caicos Islands',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States of America',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Vatican City',
    'Venezuela',
    'Vietnam',
    'Virgin Islands',
    'Wallis and Futuna Islands',
      'Western Sahara',
      'Yemen',
      'Yugoslavia (Former)',
      'Zaire',
      'Zambia',
      'Zimbabwe',
'None'
);

$State=array("None",
"Alabama",
"Alaska",
"Alberta",
"Arizona",
"Arkansas",
"British Columbia",
"California",
"Colorado",
"Delaware",
"District Of Columbia",
"Florida",
"Georgia",
"Hawaii",
"Idaho",
"Illinois",
"Indiana",
"Iowa",
"Kansas",
"Kentucky",
"Louisiana",
"Maine",
"Manitoba",
"Maryland",
"Massachusetts",
"Michigan",
"Minnesota",
"Mississippi",
"Missouri",
"Montana",
"Nebraska",
"Nevada",
"New Brunswick",
"New Hampshire",
"New Jersey",
"New Mexico",
"New York",
"Newfoundland",
"North Carolina",
"North Dakota",
"Northern Mariana Is",
"NorthwestTerritories",
"Nova Scotia",
"Ohio",
"Oklahoma",
"Ontario",
"Oregon",
"Palau",
"Pennsylvania",
"Prince Edward Island",
"Province du Quebec",
"Puerto Rico",
"Rhode Island",
"Saskatchewan",
"South Carolina",
"South Dakota",
"Tennessee",
"Texas",
"Utah",
"Vermont",
"Virgin Islands",
"Virginia",
"Washington",
"West Virginia",
"Wisconsin",
"Wyoming",
"Yukon Territory"
);

?>