<script type="text/javascript" src="incl/vts.js"></script>
<form name="y" action="http://www.hotscripts.com/rate/19081.html" method="post" target="_blank">
<input type="hidden" name="external" value="1" />
<input type="hidden" name="rating" value="5" /></form></td><td align="right">
<table border="0" cellpadding="0" cellspacing="0"><tr>
<td><a href="#" onclick="cho(1);return false" title="POOR" onmouseover="mov(document.a1)" onmouseout="mot(document.a1)"><img name="a1" src="pics/of.png" width="10" height="9" alt="POOR" hspace="1" border="0" /></a></td>
<td><a href="#" onclick="cho(2);return false" title="FAIR" onmouseover="mov(document.a2)" onmouseout="mot(document.a2)"><img name="a2" src="pics/of.png" width="10" height="9" alt="FAIR" hspace="0" border="0" /></a></td>
<td><a href="#" onclick="cho(3);return false" title="GOOD" onmouseover="mov(document.a3)" onmouseout="mot(document.a3)"><img name="a3" src="pics/of.png" width="10" height="9" alt="GOOD" hspace="1" border="0" /></a></td>
<td><a href="#" onclick="cho(4);return false" title="VERY GOOD" onmouseover="mov(document.a4)" onmouseout="mot(document.a4)"><img name="a4" src="pics/of.png" width="10" height="9" alt="VERY GOOD" hspace="0" border="0" /></a></td>
<td><a href="#" onclick="cho(5);return false" title="EXCELLENT!" onmouseover="mov(document.a5)" onmouseout="mot(document.a5)"><img name="a5" src="pics/on.png" width="10" height="9" alt="EXCELLENT!" hspace="1" border="0" /></a></td>
<td align="right"><a href="#" onclick="ssm('EasyForum');return false" title="Cast My Vote!" onmouseover="document.a6.src=rr.src" onmouseout="document.a6.src=qq.src"><img name="a6" hspace="0" src="pics/sbm.png" width="29" height="9" alt="Cast My Vote!" border="0" /></a></td>
</tr></table>