<?php
/***************************************************************************
 * (c)2002-2004 Boesch IT-Consulting (info@boesch-it.de)
 ***************************************************************************/
?>
<tr class="listheading0"><td align="left" colspan="2"><b><?php echo $l_grafiks?></b></td>
<tr class="inputrow"><td align="right" width="30%"><?php echo $l_searchpic?>:</td>
<?php echo gfx_selector("searchpic",$searchpic)?>
<tr class="inputrow"><td align="right"><?php echo $l_backpic?>:</td>
<?php echo gfx_selector("backpic",$backpic)?>
<tr class="inputrow"><td align="right"><?php echo $l_help?>:</td>
<?php echo gfx_selector("helppic",$helppic)?>
<tr class="inputrow"><td align="right"><?php echo $l_attachement?>:</td>
<?php echo gfx_selector("attachpic",$attachpic)?>
<tr class="inputrow"><td align="right"><?php echo $l_newentry?>:</td>
<?php echo gfx_selector("newentrypic",$newentrypic)?>
<tr class="inputrow"><td align="right"><?php echo $l_pagetoppic?>:</td>
<?php echo gfx_selector("pagetoppic",$pagetoppic)?>
<tr class="inputrow"><td align="right"><?php echo $l_pagepicback?>:</td>
<?php echo gfx_selector("pagepic_back",$pagepic_back)?>
<tr class="inputrow"><td align="right"><?php echo $l_pagepicnext?>:</td>
<?php echo gfx_selector("pagepic_next",$pagepic_next)?>
<tr class="inputrow"><td align="right"><?php echo $l_pagepicfirst?>:</td>
<?php echo gfx_selector("pagepic_first",$pagepic_first)?>
<tr class="inputrow"><td align="right"><?php echo $l_pagepiclast?>:</td>
<?php echo gfx_selector("pagepic_last",$pagepic_last)?>
<tr class="inputrow"><td align="right"><?php echo $l_newssignal_on?>:</td>
<?php echo gfx_selector("newssignal_on",$newssignal_on)?>
<tr class="inputrow"><td align="right"><?php echo $l_newssignal_off?>:</td>
<?php echo gfx_selector("newssignal_off",$newssignal_off)?>
<tr class="inputrow"><td align="right"><?php echo $l_pagebgpic?>:</td>
<?php echo gfx_selector("pagebgpic",$pagebgpic)?>
<tr class="inputrow"><td align="right"><?php echo $l_propose_news?>:</td>
<?php echo gfx_selector("proposepic",$proposepic)?>
<tr class="inputrow"><td align="right"><?php echo $l_caltab?>:</td>
<?php echo gfx_selector("caltabpic",$caltabpic)?>
<tr class="inputrow"><td align="right"><?php echo $l_print?>:</td>
<?php echo gfx_selector("printpic",$printpic)?>
<tr class="inputrow"><td align="right"><?php echo $l_print." (".$l_small.")"?>:</td>
<?php echo gfx_selector("printpic_small",$printpic_small)?>
<tr class="inputrow"><td align="right"><?php echo $l_csvexport?>:</td>
<?php echo gfx_selector("csvexportpic",$csvexportpic)?>
<tr class="inputrow"><td align="right"><?php echo $l_asclist?>:</td>
<?php echo gfx_selector("asclistpic",$asclistpic)?>
<tr class="inputrow"><td align="right"><?php echo $l_morepic?>:</td>
<?php echo gfx_selector("morepic",$morepic)?>
<tr class="inputrow"><td align="right"><?php echo $l_announce?>:</td>
<?php echo gfx_selector("announcepic",$announcepic)?>
<tr class="inputrow"><td align="right"><?php echo $l_gannounce?>:</td>
<?php echo gfx_selector("gannouncepic",$gannouncepic)?>
<tr class="inputrow"><td align="right"><?php echo $l_highlightentry?>:</td>
<?php echo gfx_selector("highlightmarker",$highlightmarker)?>
<tr class="inputrow"><td align="right"><?php echo $l_emailpic?>:</td>
<?php echo gfx_selector("emailpic",$emailpic)?>
<tr class="inputrow"><td align="right"><?php echo $l_displaycomments?>:</td>
<?php echo gfx_selector("commentspic",$commentspic)?>
<tr class="inputrow"><td align="right"><?php echo $l_writecomment?>:</td>
<?php echo gfx_selector("writecommentpic",$writecommentpic)?>
<tr class="inputrow"><td align="right"><?php echo $l_expand?>:</td>
<?php echo gfx_selector("expandpic",$expandpic)?>
<tr class="inputrow"><td align="right"><?php echo $l_collapse?>:</td>
<?php echo gfx_selector("collapsepic",$collapsepic)?>
<tr class="inputrow"><td align="right"><?php echo $l_rss_newsfeed?>:</td>
<?php echo gfx_selector("rsspic",$rsspic)?>
