<?php
/***************************************************************************
 * (c)2002-2004 Boesch IT-Consulting (info@boesch-it.de)
 ***************************************************************************/
?>
<tr class="listheading0"><td align="left" colspan="2"><b><?php echo $l_linkcolors?></b></td>
<tr class="listheading1"><td align="left" colspan="2"><b><?php echo $l_general?></b></td>
<tr class="inputrow"><td align="right" width="30%"><?php echo $l_normal?>:</td>
<?php echo color_chooser("linkcolor",$linkcolor)?>
<tr class="inputrow"><td align="right"><?php echo $l_visited?>:</td>
<?php echo color_chooser("vlinkcolor",$vlinkcolor)?>
<tr class="inputrow"><td align="right"><?php echo $l_activ?>:</td>
<?php echo color_chooser("alinkcolor",$alinkcolor)?>
<tr class="listheading1"><td align="left" colspan="2"><b><?php echo $l_morelink?></b></td>
<tr class="inputrow"><td align="right"><?php echo $l_normal?>:</td>
<?php echo color_chooser("morelinkcolor",$morelinkcolor)?>
<tr class="inputrow"><td align="right"><?php echo $l_visited?>:</td>
<?php echo color_chooser("morevlinkcolor",$morevlinkcolor)?>
<tr class="inputrow"><td align="right"><?php echo $l_activ?>:</td>
<?php echo color_chooser("morealinkcolor",$morealinkcolor)?>
<tr class="inputrow"><td align="right"><?php echo $l_fontsize?>:</td>
<td align="left"><input class="sninput" type="text" name="morelinkfontsize" value="<?php echo $morelinkfontsize?>" size="10" maxlength="20"></td></tr>
<tr class="listheading1"><td align="left" colspan="2"><b><?php echo $l_catlink2?></b></td>
<tr class="inputrow"><td align="right"><?php echo $l_normal?>:</td>
<?php echo color_chooser("catlinkcolor",$catlinkcolor)?>
<tr class="inputrow"><td align="right"><?php echo $l_visited?>:</td>
<?php echo color_chooser("catvlinkcolor",$catvlinkcolor)?>
<tr class="inputrow"><td align="right"><?php echo $l_activ?>:</td>
<?php echo color_chooser("catalinkcolor",$catalinkcolor)?>
<tr class="listheading1"><td align="left" colspan="2"><b><?php echo $l_comment?></b></td>
<tr class="inputrow"><td align="right"><?php echo $l_normal?>:</td>
<?php echo color_chooser("commentlinkcolor",$commentlinkcolor)?>
<tr class="inputrow"><td align="right"><?php echo $l_visited?>:</td>
<?php echo color_chooser("commentvlinkcolor",$commentvlinkcolor)?>
<tr class="inputrow"><td align="right"><?php echo $l_activ?>:</td>
<?php echo color_chooser("commentalinkcolor",$commentalinkcolor)?>
<tr class="listheading1"><td align="left" colspan="2"><b><?php echo $l_attachement?></b></td>
<tr class="inputrow"><td align="right"><?php echo $l_normal?>:</td>
<?php echo color_chooser("attachlinkcolor",$attachlinkcolor)?>
<tr class="inputrow"><td align="right"><?php echo $l_visited?>:</td>
<?php echo color_chooser("attachvlinkcolor",$attachvlinkcolor)?>
<tr class="inputrow"><td align="right"><?php echo $l_activ?>:</td>
<?php echo color_chooser("attachalinkcolor",$attachalinkcolor)?>
<tr class="listheading1"><td align="left" colspan="2"><b><?php echo $l_pagenav?></b></td>
<tr class="inputrow"><td align="right"><?php echo $l_normal?>:</td>
<?php echo color_chooser("pagenavlinkcolor",$pagenavlinkcolor)?>
<tr class="inputrow"><td align="right"><?php echo $l_visited?>:</td>
<?php echo color_chooser("pagenavvlinkcolor",$pagenavvlinkcolor)?>
<tr class="inputrow"><td align="right"><?php echo $l_activ?>:</td>
<?php echo color_chooser("pagenavalinkcolor",$pagenavalinkcolor)?>
<tr class="listheading1"><td align="left" colspan="2"><b><?php echo $l_eventlink?></b></td>
<tr class="inputrow"><td align="right"><?php echo $l_normal?>:</td>
<?php echo color_chooser("eventlinkcolor",$eventlinkcolor)?>
<tr class="inputrow"><td align="right"><?php echo $l_visited?>:</td>
<?php echo color_chooser("eventvlinkcolor",$eventvlinkcolor)?>
<tr class="inputrow"><td align="right"><?php echo $l_activ?>:</td>
<?php echo color_chooser("eventalinkcolor",$eventalinkcolor)?>
<tr class="inputrow"><td align="right"><?php echo $l_fontsize?>:</td>
<td align="left"><input class="sninput" type="text" name="eventlinkfontsize" value="<?php echo $eventlinkfontsize?>" size="10" maxlength="20"></td></tr>
<tr class="listheading1"><td align="left" colspan="2"><b><?php echo $l_actionlink?></b></td>
<tr class="inputrow"><td align="right"><?php echo $l_normal?>:</td>
<?php echo color_chooser("actionlinkcolor",$actionlinkcolor)?>
<tr class="inputrow"><td align="right"><?php echo $l_visited?>:</td>
<?php echo color_chooser("actionvlinkcolor",$actionvlinkcolor)?>
<tr class="inputrow"><td align="right"><?php echo $l_activ?>:</td>
<?php echo color_chooser("actionalinkcolor",$actionalinkcolor)?>
