<?php
//============================================================+
// File name   : cp_extension.inc                                 
// Begin       : 2001-09-02                                    
// Last Update : 2001-10-27                                    
//                                                             
// Description : This File holds the file extention for 
//               your PHP files
//                                                             
// Author: Nicola Asuni                                        
//                                                             
// (c) Copyright:                                              
//               Tecnick.com S.r.l.                            
//               Via Ugo Foscolo n.19                          
//               09045 Quartu Sant'Elena (CA)                  
//               ITALY                                         
//               www.tecnick.com                               
//               info@tecnick.com                              
//============================================================+

/**
 * database congiguration file for php extension
 * @author Nicola Asuni
 * @copyright Copyright &copy; 2004, Tecnick.com S.r.l. - Via Ugo Foscolo n.19 - 09045 Quartu Sant'Elena (CA) - ITALY - www.tecnick.com - info@tecnick.com
 * @link www.tecnick.com
 * @since 2001-09-02
 */
 
// Extension of PHP files
define("CP_EXT","php");

//============================================================+
// END OF FILE                                                 
//============================================================+
?>
