<p><font size="4" face="Arial, Helvetica, sans-serif"><strong>Software License<font size="3"><b><font size="3"><b><font size="2" face="Arial, Helvetica, sans-serif"><b><font size="2" face="Arial, Helvetica, sans-serif"><b><font size="2" face="Arial, Helvetica, sans-serif"><font size="4" face="Arial, Helvetica, sans-serif"> 
  </font></font></b></font></b></font></b></font></b></font></strong></font></p>
<form name="form1" method="post" action="">
  <font size="2" face="Arial, Helvetica, sans-serif">USE OF ACTIVEMANAGER SOFTWARE 
  IS SUBJECT TO THE TERMS OF THE LICENSE AGREEMENT. BY USING THIS SOFTWARE YOU 
  SIGNIFY THAT YOU HAVE READ THE LICENSE AGREEMENT AND ACCEPT ITS TERMS. YOUR 
  PURCHASE OF AN ACTIVEMANAGER SOFTWARE LICENSE ENTITLES YOU TO ONE (1) WORKING 
  COPY OF THE SCRIPT PER LICENSE. ONE LICENSE IS GOOD FOR ONE (1) DOMAIN ONLY. 
  IT MAY BE HOSTED ON ONLY ONE (1) DOMAIN NAME. THIS INCLUDES SUB-DOMAINS AS BEING 
  A SEPARATE DOMAIN NAME. YOU MAY NOT COPY, REPRODUCE, RESELL, OR GIVE AWAY COPIES 
  OF THE SCRIPT IN ANY WAY SHAPE OR FORM WITHOUT FIRST PURCHASING ADDITIONAL LICENSES. 
  YOU MAY MAKE ONE BACK UP COPY SHOULD SOMETHING HAPPEN TO THE WORKING COPY ON 
  YOUR HOST. YOU MAY NOT MAKE ANY INTERNAL / NON-ASTHETIC MODIFICATIONS TO THE 
  ACTIVEMANAGER SCRIPT EXCEPT AS INSTRUCTED IN ACTIVEMANAGER SETUP / DOCUMENTATION. 
  ACTIVEMANAGER RESERVES THE RIGHT TO MONITOR YOUR LICENSE USAGE AND MAY DEACTIVATE 
  YOUR SCRIPT UPON VIOLATION WITH OUR LICENSE AGREEMENT. VIOLATION OF THIS LICENSE 
  AGREEMENT MAY VOID YOUR RIGHT TO TECHNICAL SUPPORT AND SUBJECT YOU TO LEGAL 
  ACTION. </font> 
</form>
