<?php
/***************************************************************************
 * (c)2002-2004 Boesch IT-Consulting (info@boesch-it.de)
 ***************************************************************************/
$path_simpnews=dirname(__FILE__);
require_once($path_simpnews.'/config.php');
require_once($path_simpnews.'/functions.php');
require_once($path_simpnews.'/includes/entry_functions.inc');
if(!isset($category))
	$category=0;
if(!isset($$langvar) || !$$langvar)
	$act_lang=$default_lang;
else
	$act_lang=$$langvar;
include($path_simpnews.'/language/lang_'.$act_lang.'.php');
include($path_simpnews.'/includes/get_settings.inc');
include($path_simpnews.'/includes/styles2.inc');
$heading=$eventheading;
$pageheading=$l_announcements;
$actdate = date("Y-m-d H:i:00");
if(!isset($srcscript))
	$srcscript=$url_simpnews."/announce.php";
if($sncatlink=="source script")
	$catlink=$srcscript;
else
	$catlink=$sncatlink;
?>
<!-- code generated by SimpNews begin -->
<div align="<?php echo $tblalign?>">
<table width="<?php echo $aninc_tablewidth?>" border="0" CELLPADDING="1" CELLSPACING="0" ALIGN="<?php echo $tblalign?>" class="sntable">
<tr><TD BGCOLOR="<?php echo $bordercolor?>">
<a name="top"></a>
<TABLE BORDER="0" CELLPADDING="1" CELLSPACING="1" WIDTH="100%">
<?php
if($category<0)
	$enablepropose=0;
if(isset($backurl) || $category>0)
{
	echo "<tr bgcolor=\"$headingbgcolor\" width=\"5%\">";
	echo "<td align=\"center\">";
	if(isset($backurl))
		echo "<a href=\"$backurl\"><img src=\"$url_gfx/$backpic\" border=\"0\" align=\"absmiddle\" title=\"$l_back\" alt=\"$l_back\"></a>";
	else
		echo "&nbsp;";
	echo "</td>";
	echo "<td align=\"center\">";
	if(bittst($aninc_options,BIT_1))
	{
		if($category>0)
		{
			$sql = "select * from ".$tableprefix."_categories where catnr='$category'";
			if(!$result = mysql_query($sql, $db))
				die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
			if($myrow=mysql_fetch_array($result))
			{
				$cattext=display_encoded(stripslashes($myrow["catname"]));
				$tmpsql="select * from ".$tableprefix."_catnames where catnr=".$myrow["catnr"]." and lang='".$act_lang."'";
				if(!$tmpresult=mysql_query($tmpsql,$db))
					die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
				if($tmprow=mysql_fetch_array($tmpresult))
				{
					if(strlen($tmprow["catname"])>0)
						$cattext=display_encoded(stripslashes($tmprow["catname"]));
				}
				if($enablepropose==1)
					$enablepropose=$myrow["enablepropose"];
				echo "<font face=\"$headingfont\" size=\"$contentfontsize\" color=\"$headingfontcolor\">";
				if(bittst($aninc_options,BIT_2))
					echo "<a title=\"$l_showcategory\" class=\"catlink\" href=\"".$catlink."?$langvar=$act_lang&amp;layout=$layout&amp;category=".$myrow["catnr"]."\">";
				echo "<b>".$cattext."</b>";
				if(bittst($aninc_options,BIT_2))
					echo "</a>";
				echo "</font>";
				if(bittst($aninc_options,BIT_10) && ($myrow["headertext"]))
				{
					echo "<tr bgcolor=\"$catinfobgcolor\">";
					echo "<td class=\"catinfo\" align=\"left\" colspan=\"2\">";
					echo "<font face=\"$catinfofont\" size=\"$catinfofontsize\" color=\"$catinfofontcolor\">";
					$displaytext=stripslashes($myrow["headertext"]);
					$displaytext = undo_htmlspecialchars($displaytext);
					echo $displaytext;
					echo "</font></td></tr>";
				}
				$catfooteroptions=$myrow["footeroptions"];
				$catfooter=$myrow["customfooter"];
				if(!$catfooter)
					$catfooteroptions=0;
				if(bittst($catfooteroptions,BIT_1) && bittst($catfooteroptions,BIT_2))
				{
					$customfooter=$catfooter;
					$usecustomfooter=1;
					$footerfile="";
				}
			}
		}
		else if($category==0)
		{
			echo "<font face=\"$headingfont\" size=\"$contentfontsize\" color=\"$headingfontcolor\">";
			if(bittst($aninc_options,BIT_2))
				echo "<a title=\"$l_showcategory\" class=\"catlink\" href=\"".$catlink."?$langvar=$act_lang&amp;layout=$layout&amp;category=0\">";
			echo "<b>".$l_general."</b>";
			if(bittst($aninc_options,BIT_2))
				echo "</a>";
			echo "</font>";
		}
	}
	else
		echo "&nbsp;";
	echo "</td></tr>";
}
$acttime=transposetime(time(),$servertimezone,$displaytimezone);
if(!isset($srcscript))
	$srcscript=$url_simpnews."/announce.php";
if($sncatlink=="source script")
	$catlink=$srcscript;
else
	$catlink=$sncatlink;
$sql = "select * from ".$tableprefix."_announce where (expiredate>=$acttime or expiredate=0) and (firstdate<=$acttime or firstdate=0)";
if(isset($announcenr))
{
	$sql.="and entrynr=$announcenr";
	if($useviewcounts==1)
	{
		$tmpsql = "UPDATE ".$tableprefix."_announce SET views = views + 1 WHERE (entrynr = $announcenr)";
		@mysql_query($tmpsql, $db);
	}
}
else
{
	if(isset($link_date))
		$sql.=" and DATE_FORMAT(date,'%Y-%m-%d')='$link_date' ";
	else
	{
		if(isset($startdate))
			$sql.= "and DATE_FORMAT(date,'%Y-%m-%d')>='$startdate' ";
		if(isset($enddate))
			$sql.= "and DATE_FORMAT(date,'%Y-%m-%d')<='$enddate' ";
	}
	if($separatebylang==1)
		$sql.="and lang='$act_lang' ";
	if($category>0)
		$sql.= "and (category='$category' or category=0)";
	else if($category==0)
		$sql.= "and category=0";
	if(!isset($link_date))
		$sql.=" order by date desc";
	else
		$sql.=" order by category asc";
}
if(!$result = mysql_query($sql, $db))
		die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
if(mysql_num_rows($result)>0)
{
	while($myrow=mysql_fetch_array($result))
	{
		echo "<tr><td width=\"2%\" height=\"100%\" align=\"center\" bgcolor=\"$contentbgcolor\">";
		if($myrow["headingicon"])
			echo "<img src=\"$url_icons/".$myrow["headingicon"]."\" border=\"0\" align=\"middle\"> ";
		else
			echo "&nbsp;";
		echo "</td>";
		echo "<td align=\"center\"><table class=\"eventbox\" width=\"100%\" align=\"center\" bgcolor=\"$contentbgcolor\" cellspacing=\"0\" cellpadding=\"0\">";
		list($mydate,$mytime)=explode(" ",$myrow["date"]);
		list($year, $month, $day) = explode("-", $mydate);
		list($hour, $min, $sec) = explode(":",$mytime);
		if($month>0)
		{
			$temptime=mktime($hour,$min,$sec,$month,$day,$year);
			$temptime=transposetime($temptime,$servertimezone,$displaytimezone);
			$displaydate=date($dateformat,$temptime);
		}
		else
			$displaydate="";
		if(bittst($aninc_options,BIT_3))
		{
			echo "<tr><td align=\"left\" bgcolor=\"$timestampbgcolor\" colspan=\"3\">";
			if($myrow["category"]==0)
				echo "<img src=\"$url_gfx/$gannouncepic\" border=\"0\" align=\"absmiddle\" alt=\"$l_global_announcement\" title=\"$l_global_announcement\"> ";
			else
				echo "<img src=\"$url_gfx/$announcepic\" border=\"0\" align=\"absmiddle\" alt=\"$l_announcement\" title=\"$l_announcement\"> ";
			echo "<font face=\"$timestampfont\" size=\"$timestampfontsize\" color=\"$timestampfontcolor\">";
			echo get_start_tag($timestampstyle);
			echo $displaydate;
			echo get_end_tag($timestampstyle);
			echo "</font></td>";
			echo "</tr>";
		}
		if((strlen($myrow["heading"])>0) && bittst($aninc_options,BIT_4))
		{
			echo "<tr bgcolor=\"$newsheadingbgcolor\"><td align=\"left\" colspan=\"3\">";
			echo "<font face=\"$newsheadingfont\" size=\"$newsheadingfontsize\" color=\"$newsheadingfontcolor\">";
			echo get_start_tag($newsheadingstyle);
			echo display_encoded($myrow["heading"]);
			echo get_end_tag($newsheadingstyle);
			echo "</font></td></tr>";
		}
		echo "<tr bgcolor=\"$contentbgcolor\"><td align=\"left\" colspan=\"3\">";
		echo "<font face=\"$contentfont\" size=\"$contentfontsize\" color=\"$contentfontcolor\">";
		$displaytext=stripslashes($myrow["text"]);
		$displaytext = undo_htmlspecialchars($displaytext);
		echo $displaytext."</font></td></tr>";
		if(bittst($aninc_options,BIT_5) && (strlen($myrow["poster"])>0) && ($attachpos==0))
			posterline2($myrow["posterid"], $myrow["poster"], bittst($aninc_options,BIT_6));
		if($attachpos==0)
			echo "<tr bgcolor=\"$contentbgcolor\"><td align=\"left\">";
		displayattachs_announce($myrow["entrynr"],$attachpos, $nofileinfo);
		if($attachpos==1)
		{
			if(bittst($aninc_options,BIT_5) && (strlen($myrow["poster"])>0))
				posterline2($myrow["posterid"], $myrow["poster"], bittst($aninc_options,BIT_6));
			echo "<tr bgcolor=\"$contentbgcolor\"><td>&nbsp;</td>";
		}
		echo "<td align=\"right\" colspan=\"2\">";
		echo "<font face=\"$contentfont\" size=\"1\" color=\"$contentfontcolor\">";
		if(bittst($aninc_options,BIT_7))
		{
			echo "<a href=\"".$url_simpnews."/announceprint.php?$langvar=$act_lang&layout=$layout&announcenr=".$myrow["entrynr"]."\" target=\"printwindow\">";
			if($printpic_small)
				echo "<img class=\"iconbutton\" src=\"$url_gfx/$printpic_small\" border=\"0\" align=\"absmiddle\" title=\"$l_print\" alt=\"$l_print\">";
			else
				echo "[$l_print]";
			echo "</a>";
		}
		if(bittst($aninc_options,BIT_8))
			echo "<a href=\"#top\"><img class=\"iconbutton\" src=\"$url_gfx/$pagetoppic\" border=\"0\" align=\"absmiddle\" title=\"$l_gotop\" alt=\"$l_gotop\"></a>";
		if(bittst($aninc_options,BIT_9))
			echo "<a href=\"".$url_simpnews."/anmail.php?$langvar=$act_lang&layout=$layout&announcenr=".$myrow["entrynr"]."\" target=\"mailwindow\"><img class=\"iconbutton\" src=\"$url_gfx/$emailpic\" border=\"0\" align=\"absmiddle\" title=\"$l_emailentry\" alt=\"$l_emailentry\"></a>";
		echo "</td></tr>";
		echo "</table></td></tr>";
	}
}
echo "</table></td></tr></table></div>";
$footer_tablewidth=$aninc_tablewidth;
include($path_simpnews.'/includes/footer4.inc');
?>