<?php
/***************************************************************************
 * (c)2002-2004 Boesch IT-Consulting (info@boesch-it.de)
 ***************************************************************************/
// begin user editable part
$linktarget="newscontent";
// end user editable part
//
$path_simpnews=dirname(__FILE__);
require_once($path_simpnews.'/config.php');
require_once($path_simpnews.'/functions.php');
if(!isset($category))
	$category=0;
if(!isset($$langvar) || !$$langvar)
	$act_lang=$default_lang;
else
	$act_lang=$$langvar;
include($path_simpnews.'/language/lang_'.$act_lang.'.php');
include($path_simpnews.'/includes/get_settings.inc');
if(isset($cinewslist))
	$catframenewslist=$cinewslist;
switch($catframenewslist)
{
	case 1:
		$newsscript = "news4.php";
		break;
	case 2:
		$newsscript = "news5.php";
		if(!isset($sortorder))
			$sortorder=1;
		break;
	case 3:
		$newsscript = "hotnews.php";
		break;
	default:
		$newsscript = "news.php";
		break;
}
if(!isset($sortorder))
	$sortorder=0;
$baseurl=$url_simpnews."/".$newsscript."?$langvar=$act_lang&catframe=1&sortorder=$sortorder";
?>
<!-- code generated by SimpNews begin -->
<table width="<?php echo $TableWidth?>" border="0" CELLPADDING="1" CELLSPACING="0" class="sntable" align="<?php echo $tblalign?>">
<tr><TD BGCOLOR="<?php echo $bordercolor?>">
<TABLE BORDER="0" CELLPADDING="1" CELLSPACING="1" WIDTH="100%">
<tr bgcolor="<?php echo $clcontentbgcolor?>"><td align="left">
<?php
$catlink="$baseurl&layout=$layout&category=0";
?>
<a class="catlistlink" href="<?php echo $catlink?>" target="<?php echo $linktarget?>">
<font size="<?php echo $clcontentfontsize?>" face="<?php echo $clcontentfont?>" color="<?php echo $clcontentfontcolor?>">
<?php echo $l_general?></font></a></td></tr>
<?php
$sql = "select * from ".$tableprefix."_categories where hideincatlist=0 order by displaypos asc";
if(!$result = mysql_query($sql, $db))
    die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
while($myrow=mysql_fetch_array($result))
{
	$catlink=$baseurl;
	if($myrow["newsframelayout"])
		$catlink.="&layout=".$myrow["newsframelayout"];
	else
		$catlink.="&layout=$layout";
	$catlink.="&category=".$myrow["catnr"];
	$cattext=display_encoded(stripslashes($myrow["catname"]));
	$tmpsql="select * from ".$tableprefix."_catnames where catnr=".$myrow["catnr"]." and lang='".$act_lang."'";
	if(!$tmpresult=mysql_query($tmpsql,$db))
		die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
	if($tmprow=mysql_fetch_array($tmpresult))
	{
		if(strlen($tmprow["catname"])>0)
			$cattext=display_encoded(stripslashes($tmprow["catname"]));
	}
?>
<tr bgcolor="<?php echo $clcontentbgcolor?>"><td align="left">
<a class="catlistlink" href="<?php echo $catlink?>" target="<?php echo $linktarget?>">
<font size="<?php echo $clcontentfontsize?>" face="<?php echo $clcontentfont?>" color="<?php echo $clcontentfontcolor?>">
<?php echo $cattext?></font></a></td></tr>
<?php
}
?>
</table></td></tr></table>
<!-- code generated by SimpNews end -->
