<?php
/***************************************************************************
 * (c)2002-2005 Boesch IT-Consulting (info@boesch-it.de)
 ***************************************************************************/
$path_simpnews=dirname(__FILE__);
require_once($path_simpnews.'/config.php');
require_once($path_simpnews.'/functions.php');
if(!isset($category))
	$category=0;
if(!isset($$langvar) || !$$langvar)
	$act_lang=$default_lang;
else
	$act_lang=$$langvar;
if(!isset($sortorder))
	$sortorder=0;
include($path_simpnews.'/language/lang_'.$act_lang.'.php');
include($path_simpnews.'/includes/get_settings.inc');
include($path_simpnews.'/includes/styles2.inc');
$today = date("Y-m-d");
if(isset($limitentries))
	$hotevmaxentries=$limitentries;
if(isset($limitdays))
	$hotevmaxdays=$limitdays;
if($hn_linklayout)
	$layout=$hn_linklayout;
?>
<!-- code generated by SimpNews begin -->
<table width="<?php echo $TableWidth2?>" border="0" CELLPADDING="1" CELLSPACING="0" ALIGN="<?php echo $tblalign?>" class="sntable">
<tr><TD BGCOLOR="<?php echo $bordercolor?>">
<TABLE BORDER="0" CELLPADDING="1" CELLSPACING="1" WIDTH="100%">
<?php
if($eventheading && ($hotscriptsnoheading==0))
{
?>
<TR BGCOLOR="<?php echo $headingbgcolor?>" ALIGN="CENTER">
<TD ALIGN="CENTER" VALIGN="MIDDLE" colspan="2"><font face="<?php echo $headingfont?>" size="<?php echo $headingfontsize?>" color="<?php echo $headingfontcolor?>"><b><?php echo $eventheading?></b></font></td></tr>
<?php
}
$sql = "select * from ".$tableprefix."_misc";
if(!$result = mysql_query($sql, $db)) {
    die("<tr class=\"errorrow\"><td>Could not connect to the database.");
}
if ($myrow = mysql_fetch_array($result))
{
	if($myrow["shutdown"]==1)
	{
?>
</tr></table></td></tr>
<tr><TD BGCOLOR="<?php echo $bordercolor?>">
<TABLE BORDER="0" CELLPADDING="1" CELLSPACING="1" WIDTH="100%">
<tr BGCOLOR="<?php echo $contentbgcolor?>" ALIGN="CENTER">
<TD ALIGN="CENTER" VALIGN="MIDDLE" colspan="2"><font face="<?php echo $contentfont?>" size="<?php echo $contentfontsize?>" color="<?php echo $contentfontcolor?>">
<?php
		$shutdowntext=stripslashes($myrow["shutdowntext"]);
		$shutdowntext = undo_htmlspecialchars($shutdowntext);
		echo $shutdowntext;
		echo "</font></td></tr></table></td></tr></table>";
?>
</td></tr></table>
<?php
		include($path_simpnews.'/includes/footer2.inc');
		echo "</body></html>";
		exit;
	}
}
$announceavail=false;
if(bittst($announceoptions,BIT_9))
{
		$acttime=transposetime(time(),$servertimezone,$displaytimezone);
		$sql = "select * from ".$tableprefix."_announce where (expiredate>=$acttime or expiredate=0) and (firstdate<=$acttime or firstdate=0)";
		$sql.= "and DATE_FORMAT(date,'%Y-%m-%d')>='$today' ";
		if($hotevmaxdays>0)
			$sql.= "and DATE_FORMAT(date,'%Y-%m-%d') <= date_add('$today', INTERVAL $hotevmaxdays DAY) ";
		if($separatebylang==1)
			$sql.="and lang='$act_lang' ";
		if($category>0)
			$sql.= "and (category='$category' or category=0)";
		else if($category==0)
			$sql.= "and category=0";
		switch($sortorder)
		{
			case 0:
				$sql.=" order by date desc";
				break;
			case 1:
				$sql.=" order by date asc";
				break;
			case 2:
				$sql.=" order by heading asc";
				break;
			case 3:
				$sql.=" order by heading desc";
				break;
		}
		if(isset($maxannounce))
			$sql.=" limit $maxannounce";
		else if($hotevmaxentries>0)
			$sql .=" limit $hotevmaxentries";
		if(!$result = mysql_query($sql, $db))
		    die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
		if(mysql_num_rows($result)>0)
		{
			if(!bittst($announceoptions,BIT_10))
			{
				echo "<tr bgcolor=\"$contentbgcolor\"><td align=\"left\" colspan=\"2\">";
				echo "<font face=\"$contentfont\" size=\"$contentfontsize\" color=\"$contentfontcolor\">";
				if($usehnlinkdest==1)
					$announceurl="$hnlinkdestan?$langvar=$act_lang&category=$category&startdate=$today";
				else
					$announceurl=$url_simpnews."/announce.php?$langvar=$act_lang&category=$category&startdate=$today";
				if($hotevmaxdays>0)
				{
					$temptime=time();
					$temptime=$temptime+($hotevmaxdays*24*60*60);
					$enddate=date("Y-m-d",$temptime);
					$announceurl.="&enddate=$enddate";
				}
				echo " <a href=\"$announceurl\"";
				if($hotevtarget)
					echo " target=\"$hotevtarget\"";
				echo ">";
				echo "<img src=\"$url_gfx/$announcepic\" border=\"0\" align=\"absmiddle\" alt=\"$l_announcements\" title=\"$l_announcements\"></a>";
				echo " <a href=\"$announceurl\"";
				if($hotevtarget)
					echo " target=\"$hotevtarget\"";
				echo ">";
				echo "$l_announcements</a></td></tr>";
			}
			else
			{
				$announceavail=true;
				while($myrow=mysql_fetch_array($result))
				{
					list($mydate,$mytime)=explode(" ",$myrow["date"]);
					list($year, $month, $day) = explode("-", $mydate);
					list($hour, $min, $sec) = explode(":",$mytime);
					$link_date="";
					if($month>0)
					{
						$temptime=mktime($hour,$min,$sec,$month,$day,$year);
						$link_date=date("Y-m-d",$temptime);
						$temptime=transposetime($temptime,$servertimezone,$displaytimezone);
						$displaydate=date($dateformat,$temptime);
					}
					else
						$displaydate="";
					if(!bittst($announceoptions,BIT_1))
					{
						if($usehnlinkdest==1)
							$announceurl="$hnlinkdestan?$langvar=$act_lang&category=$category";
						else
							$announceurl=$url_simpnews."/announce.php?$langvar=$act_lang&category=$category";
					}
					else
					{
						if($usehnlinkdest==1)
							$announceurl="$hnlinkdestev?$langvar=$act_lang&layout=$layout&category=$category";
						else
							$announceurl=$url_simpnews."/events.php?$langvar=$act_lang&layout=$layout&category=$category";
					}
					if($link_date)
						$announceurl.="&linkdate=$link_date";
					echo "<tr>";
					if($hotevicons==1)
					{
						echo "<td width=\"2%\" height=\"100%\" align=\"center\" bgcolor=\"$contentbgcolor\">";
						if($myrow["headingicon"])
							echo "<img src=\"$url_icons/".$myrow["headingicon"]."\" border=\"0\" align=\"middle\"> ";
						echo "</td>";
					}
					echo "<td align=\"center\"><table width=\"100%\" align=\"center\" bgcolor=\"$contentbgcolor\" cellspacing=\"0\" cellpadding=\"0\">";
					echo "<tr><td align=\"left\" bgcolor=\"$timestampbgcolor\">";
					if($myrow["category"]==0)
						echo "<img src=\"$url_gfx/$gannouncepic\" border=\"0\" align=\"absmiddle\" alt=\"$l_global_announcement\" title=\"$l_global_announcement\"> ";
					else
						echo "<img src=\"$url_gfx/$announcepic\" border=\"0\" align=\"absmiddle\" alt=\"$l_announcement\" title=\"$l_announcement\"> ";
					echo "<font face=\"$timestampfont\" size=\"$timestampfontsize\" color=\"$timestampfontcolor\">";
					echo get_start_tag($timestampstyle);
					echo $displaydate;
					echo get_end_tag($timestampstyle);
					echo "</font></td></tr>";
					if(strlen($myrow["heading"])>0)
					{
						echo "<tr bgcolor=\"$newsheadingbgcolor\"><td align=\"left\">";
						echo "<font face=\"$newsheadingfont\" size=\"$hn_newsheadingfontsize\" color=\"$newsheadingfontcolor\">";
						if($hotevmaxchars<1)
						{
							echo " <a href=\"$announceurl\"";
							if($hotevtarget)
								echo " target=\"$hotevtarget\"";
							echo ">";
						}
						$displayheading=$myrow["heading"];
						if($hotevnohtmlformatting==1)
							$displayheading=strip_tags($displayheading);
						$displayheading=do_htmlentities($displayheading);
						$displayheading=undo_htmlspecialchars($displayheading);
						if($hotevnohtmlformatting==0)
							echo get_start_tag($newsheadingstyle);
						echo $displayheading;
						if($hotevnohtmlformatting==0)
							echo get_end_tag($newsheadingstyle);
						if($hotevmaxchars<1)
							echo "</a>";
						echo "</font></td></tr>";
					}
					if($hotevmaxchars!=0)
					{
						echo "<tr bgcolor=\"$contentbgcolor\"><td align=\"left\">";
						echo "<font face=\"$contentfont\" size=\"$contentfontsize\" color=\"$contentfontcolor\">";
						$displaytext=stripslashes($myrow["text"]);
						$displaytext = undo_htmlspecialchars($displaytext);
						if(($hotevmaxchars>0) && strlen($displaytext>$hotevmaxchars))
						{
							$displaytext=strip_tags($displaytext);
							$displaytext=substr($displaytext,0,$hotevmaxchars);
							$displaytext.=" <a href=\"$announceurl\"";
							if($hotevtarget)
								$displaytext.=" target=\"$hotevtarget\"";
							$displaytext.=">[...]</a>";
						} else if($hotevnohtmlformatting==1)
							strip_tags($displaytext);
						echo $displaytext."</font></td></tr>";
					}
					if($hotevdisplayposter && (strlen($myrow["poster"])>0))
					{
						echo "<tr bgcolor=\"$posterbgcolor\"><td align=\"left\">";
						echo "<font face=\"$posterfont\" size=\"$posterfontsize\" color=\"$posterfontcolor\">";
						if($hotevnohtmlformatting==0)
							echo get_start_tag($posterstyle);
						echo "$l_poster: ".do_htmlentities($myrow["poster"]);
						if($hotevnohtmlformatting==0)
							echo get_end_tag($posterstyle);
						echo "</font>";
						echo "</td></tr>";
					}
					echo "</table></td></tr>";
				}
			}
		}
}
$sql = "select * from ".$tableprefix."_events where date>='$today' ";
if($separatebylang==1)
	$sql.="and lang='$act_lang' ";
if($category>=0)
	$sql.= "and category='$category' ";
else
{
	$sql.= "and linkeventnr=0 ";
	$tmpsql="select * from ".$tableprefix."_categories where hideintotallist=1";
	if(!$tmpresult = mysql_query($tmpsql, $db))
	    die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
	while($tmprow=mysql_fetch_array($tmpresult))
		$sql.="and category!=".$tmprow["catnr"]." ";
}
if($hotevmaxdays>0)
	$sql.= "and date <= date_add('$today', INTERVAL $hotevmaxdays DAY) ";
switch($sortorder)
{
	case 0:
		$sql.=" order by date desc";
		break;
	case 1:
		$sql.=" order by date asc";
		break;
	case 2:
		$sql.=" order by heading asc";
		break;
	case 3:
		$sql.=" order by heading desc";
		break;
}
if(!$result = mysql_query($sql, $db))
	die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
$numentries=mysql_numrows($result);
if($hotevmaxentries>0)
	$sql .=" limit $hotevmaxentries";
if(!$result = mysql_query($sql, $db))
	die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
if(!$myrow=mysql_fetch_array($result))
{
	if(!$announceavail)
	{
		echo "<tr>";
		echo "<td align=\"center\" bgcolor=\"$contentbgcolor\">";
		echo $l_noevents;
		echo "<font face=\"$contentfont\" size=\"$contentfontsize\" color=\"$contentfontcolor\">";
		echo "</font></td></tr>";
	}
}
else
{
do
{
	if($myrow["linkeventnr"]==0)
		$entrydata=$myrow;
	else
	{
		$tmpsql="select * from ".$tableprefix."_events where eventnr=".$myrow["linkeventnr"];
		if(!$tmpresult = mysql_query($tmpsql, $db))
			die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
		if(!$tmprow=mysql_fetch_array($tmpresult))
			die("<tr class=\"errorrow\"><td>Unable to get data");
		$entrydata=$tmprow;
	}
	list($mydate,$mytime)=explode(" ",$entrydata["date"]);
	list($year, $month, $day) = explode("-", $mydate);
	list($hour, $min, $sec) = explode(":",$mytime);
	$temptime=mktime($hour,$min,$sec,$month,$day,$year);
	$link_date=date("Y-m-d",$temptime);
	echo "<tr>";
	if($hotevicons==1)
	{
		echo "<td width=\"2%\" height=\"100%\" align=\"center\" bgcolor=\"$contentbgcolor\">";
		if($entrydata["headingicon"])
			echo "<img src=\"$url_icons/".$entrydata["headingicon"]."\" border=\"0\" align=\"middle\"> ";
		echo "</td>";
	}
	echo "<td align=\"center\"><table width=\"100%\" align=\"center\" bgcolor=\"$contentbgcolor\" cellspacing=\"0\" cellpadding=\"0\">";
	list($tmpdate, $tmptime)=explode(" ",$entrydata["date"]);
	list($year, $month, $day) = explode("-", $tmpdate);
	list($hour, $min, $null) = explode(":", $tmptime);
	if(($hour>0) || ($min>0))
		$displaydate=date($event_dateformat2,mktime($hour,$min,0,$month,$day,$year));
	else
		$displaydate=date($event_dateformat,mktime(0,0,0,$month,$day,$year));
	echo "<tr><td align=\"left\" bgcolor=\"$timestampbgcolor\">";
	echo "<font face=\"$timestampfont\" size=\"$timestampfontsize\" color=\"$timestampfontcolor\">";
	echo get_start_tag($timestampstyle);
	echo $displaydate;
	echo get_end_tag($timestampstyle);
	if(isset($lastvisitdate))
	{
		list($mydate,$mytime)=explode(" ",$myrow["added"]);
		list($year, $month, $day) = explode("-", $mydate);
		list($hour, $min, $sec) = explode(":",$mytime);
		$thisentrydate=mktime($hour,$min,$sec,$month,$day,$year);
		if($thisentrydate>=$lastvisitdate)
			echo "&nbsp;&nbsp;<img src=\"$url_gfx/$newentrypic\" border=\"0\" align=\"absmiddle\">";
	}
	echo "</font></td></tr>";
	if(strlen($entrydata["heading"])>0)
	{
		echo "<tr bgcolor=\"$newsheadingbgcolor\"><td align=\"left\">";
		echo "<font face=\"$newsheadingfont\" size=\"$hn_newsheadingfontsize\" color=\"$newsheadingfontcolor\">";
		if($hotevmaxchars<1)
		{
			if($usehnlinkdest==1)
				$linkdest="$hnlinkdestev?$langvar=$act_lang&layout=$layout&category=$category&link_date=".$link_date;
			else
				$linkdest=$url_simpnews."/events.php?$langvar=$act_lang&layout=$layout&category=$category&link_date=".$link_date;
			echo " <a href=\"$linkdest\"";
			if($hotevtarget)
				echo " target=\"$hotevtarget\"";
			echo ">";
		}
		$displayheading=$entrydata["heading"];
		if($hotevnohtmlformatting==1)
			$displayheading=strip_tags($displayheading);
		$displayheading=do_htmlentities($displayheading);
		$displayheading=undo_htmlspecialchars($displayheading);
		if($hotevnohtmlformatting==0)
			echo get_start_tag($newsheadingstyle);
		echo $displayheading;
		if($hotevnohtmlformatting==0)
			echo get_end_tag($newsheadingstyle);
		if($hotevmaxchars<1)
			echo "</a>";
		echo "</font></td></tr>";
	}
	if($hotevmaxchars!=0)
	{
		echo "<tr bgcolor=\"$contentbgcolor\"><td align=\"left\">";
		echo "<font face=\"$contentfont\" size=\"$contentfontsize\" color=\"$contentfontcolor\">";
		$displaytext=stripslashes($entrydata["text"]);
		$displaytext = undo_htmlspecialchars($displaytext);
		if(($hotevmaxchars>0) && strlen($displaytext>$hotevmaxchars))
		{
			$displaytext=strip_tags($displaytext);
			$displaytext=substr($displaytext,0,$hotevmaxchars);
			if($usehnlinkdestev==1)
				$linkdest="$hnlinkdestev?$langvar=$act_lang&layout=$layout&category=$category&link_date=".$link_date;
			else
				$linkdest=$url_simpnews."/events.php?$langvar=$act_lang&layout=$layout&category=$category&link_date=".$link_date;
			$displaytext.=" <a href=\"$linkdest\"";
			if($hotevtarget)
				$displaytext.=" target=\"$hotevtarget\"";
			$displaytext.=">[...]</a>";
		} else if($hotevnohtmlformatting==1)
			strip_tags($displaytext);
		echo $displaytext."</font></td></tr>";
	}
	if($hotevdisplayposter && (strlen($entrydata["poster"])>0))
	{
		echo "<tr bgcolor=\"$posterbgcolor\"><td align=\"left\">";
		echo "<font face=\"$posterfont\" size=\"$posterfontsize\" color=\"$posterfontcolor\">";
		if($hotevnohtmlformatting==0)
			echo get_start_tag($posterstyle);
		echo "$l_poster: ".do_htmlentities($entrydata["poster"]);
		if($hotevnohtmlformatting==0)
			echo get_end_tag($posterstyle);
		echo "</font>";
		echo "</td></tr>";
	}
	echo "</table></td></tr>";
}while($myrow=mysql_fetch_array($result));
}
echo "</table></td></tr></table>";
include($path_simpnews.'/includes/footer2.inc');
?>