<?php
/***************************************************************************
 * (c)2002-2005 Boesch IT-Consulting (info@boesch-it.de)
 ***************************************************************************/
$path_simpnews=dirname(__FILE__);
require_once($path_simpnews.'/config.php');
require_once($path_simpnews.'/functions.php');
if(!isset($category))
	$category=0;
if(!isset($$langvar) || !$$langvar)
	$act_lang=$default_lang;
else
	$act_lang=$$langvar;
if(!isset($sortorder))
	$sortorder=0;
include($path_simpnews.'/language/lang_'.$act_lang.'.php');
include($path_simpnews.'/includes/get_settings.inc');
include($path_simpnews.'/includes/block_leacher.inc');
include($path_simpnews.'/includes/entry_functions.inc');
$heading=$eventheading;
if($eventheading)
	$pageheading=$eventheading;
else
	$pageheading=$l_events;
$baseurl="$act_script_url?$langvar=$act_lang&layout=$layout&category=$category&sortorder=$sortorder";
if(isset($startdate))
	$baseurl.="&startdate=$startdate";
if(isset($enddate))
	$baseurl.="&enddate=$enddate";
$localbackurl=urlencode($baseurl);
$actdate = date("Y-m-d H:i:00");
$propdisplayed=false;
if(!isset($srcscript))
	$srcscript=$url_simpnews."/events.php";
if($sncatlink=="source script")
	$catlink=$srcscript;
else
	$catlink=$sncatlink;
?>
<!-- code generated by SimpNews begin -->
<div style="clear:both" align="<?php echo $tblalign?>">
<table width="<?php echo $evinc_tablewidth?>" border="0" CELLPADDING="1" CELLSPACING="0" ALIGN="<?php echo $tblalign?>" class="sntable">
<tr><TD BGCOLOR="<?php echo $bordercolor?>">
<a name="top"></a>
<TABLE BORDER="0" CELLPADDING="1" CELLSPACING="1" WIDTH="100%">
<?php
if(bittst($evinc_options,BIT_1) && (strlen($eventheading)>0))
{
?>
<TR BGCOLOR="<?php echo $headingbgcolor?>" ALIGN="CENTER">
<TD ALIGN="CENTER" VALIGN="MIDDLE" colspan="2"><font face="<?php echo $headingfont?>" size="<?php echo $headingfontsize?>" color="<?php echo $headingfontcolor?>"><b><?php echo $eventheading?></b></font></td></tr>
<?php
}
if(bittst($evinc_options,BIT_9) && ($category!=-1))
{
	if($category>0)
	{
		$cattext=display_encoded(stripslashes($myrow["catname"]));
		$tmpsql="select * from ".$tableprefix."_catnames where catnr=".$myrow["catnr"]." and lang='".$act_lang."'";
		if(!$tmpresult=mysql_query($tmpsql,$db))
			die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
		if($tmprow=mysql_fetch_array($tmpresult))
		{
			if(strlen($tmprow["catname"])>0)
				$cattext=display_encoded(stripslashes($tmprow["catname"]));
		}
		$sql = "select * from ".$tableprefix."_categories where catnr='$category'";
		if(!$result = mysql_query($sql, $db))
			die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
		if($myrow=mysql_fetch_array($result))
		{
			echo "<tr bgcolor=\"$headingbgcolor\">";
			echo "<td align=\"center\" colspan=\"2\">";
			echo "<font face=\"$headingfont\" size=\"$contentfontsize\" color=\"$headingfontcolor\">";
			if(bittst($evinc_options,BIT_10))
					echo "<a title=\"$l_showcategory\" class=\"catlink\" href=\"".$catlink."?$langvar=$act_lang&amp;layout=$layout&amp;category=".$myrow["catnr"]."\">";
			echo "<b>".$cattext."</b>";
			if(bittst($evinc_options,BIT_10))
				echo "</a>";
			echo "</font></td></tr>";
			if(bittst($evinc_options,BIT_8) && ($myrow["headertext"]))
			{
				echo "<tr bgcolor=\"$catinfobgcolor\">";
				echo "<td class=\"catinfo\" align=\"left\" colspan=\"2\">";
				echo "<font face=\"$catinfofont\" size=\"$catinfofontsize\" color=\"$catinfofontcolor\">";
				$displaytext=stripslashes($myrow["headertext"]);
				$displaytext = undo_htmlspecialchars($displaytext);
				echo $displaytext;
				echo "</font></td></tr>";
			}
			$catfooteroptions=$myrow["footeroptions"];
			$catfooter=$myrow["customfooter"];
			if(!$catfooter)
				$catfooteroptions=0;
			if(bittst($catfooteroptions,BIT_1) && bittst($catfooteroptions,BIT_2))
			{
				$customfooter=$catfooter;
				$usecustomfooter=1;
				$footerfile="";
			}
		}
	}
}
if(isset($backurl) || isset($link_date))
{
	echo "<tr bgcolor=\"$headingbgcolor\">";
	echo "<td align=\"center\" width=\"5%\">";
	if(isset($backurl))
	{
		if(isset($backurl))
			echo "<a href=\"$backurl\"><img src=\"$url_gfx/$backpic\" border=\"0\" align=\"absmiddle\" title=\"$l_back\" alt=\"$l_back\"></a>";
	}
	echo "&nbsp;";
	echo "</td>";
	if(isset($link_date))
	{
		list($year, $month, $day) = explode("-", $link_date);
		if($month>0)
			$displaydate=date($event_dateformat,mktime(0,0,0,$month,$day,$year));
		else
			$displaydate="";
		echo "<td align=\"center\">";
		echo "<font face=\"$headingfont\" size=\"$contentfontsize\" color=\"$headingfontcolor\">";
		echo "<b>$displaydate</b></font></td></tr>";
	}
	else
		echo "<td>&nbsp;</td></tr>";
}
$announceavail=false;
if(bittst($announceoptions,BIT_1))
{
		$acttime=transposetime(time(),$servertimezone,$displaytimezone);
		$sql = "select * from ".$tableprefix."_announce where (expiredate>=$acttime or expiredate=0) and (firstdate<=$acttime or firstdate=0)";
		if(isset($link_date))
			$sql.=" and DATE_FORMAT(date,'%Y-%m-%d')='$link_date' ";
		if($separatebylang==1)
			$sql.="and lang='$act_lang' ";
		if($category>0)
			$sql.= "and (category='$category' or category=0)";
		else if($category==0)
			$sql.= "and category=0";
		if(isset($link_date))
			$sql.=" order by category asc";
		else
		{
			switch($sortorder)
			{
				case 0:
					$sql.=" order by date desc";
					break;
				case 1:
					$sql.=" order by date asc";
					break;
				case 2:
					$sql.=" order by heading asc";
					break;
				case 3:
					$sql.=" order by heading desc";
					break;
			}
		}
		if(isset($maxannounce))
			$sql.=" limit $maxannounce";
		if(!$result = mysql_query($sql, $db))
		    die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
		if(mysql_num_rows($result)>0)
		{
			$announceavail=true;
			while($myrow=mysql_fetch_array($result))
			{
				if(($useviewcounts==1) && isset($link_date))
				{
					$tmpsql = "UPDATE ".$tableprefix."_announce SET views = views + 1 WHERE (entrynr = ".$myrow["entrynr"].")";
					@mysql_query($tmpsql, $db);
				}
				echo "<tr><td width=\"2%\" height=\"100%\" align=\"center\" bgcolor=\"$contentbgcolor\">";
				if($myrow["headingicon"])
					echo "<img src=\"$url_icons/".$myrow["headingicon"]."\" border=\"0\" align=\"middle\"> ";
				else
					echo "&nbsp;";
				echo "</td>";
				echo "<td align=\"center\"><table class=\"eventbox\" width=\"100%\" align=\"center\" bgcolor=\"$contentbgcolor\" cellspacing=\"0\" cellpadding=\"0\">";
				list($mydate,$mytime)=explode(" ",$myrow["date"]);
				list($year, $month, $day) = explode("-", $mydate);
				list($hour, $min, $sec) = explode(":",$mytime);
				if($month>0)
				{
					$temptime=mktime($hour,$min,$sec,$month,$day,$year);
					$temptime=transposetime($temptime,$servertimezone,$displaytimezone);
					$displaydate=date($dateformat,$temptime);
				}
				else
					$displaydate="";
				if(bittst($evinc_options,BIT_2))
				{
					echo "<tr><td align=\"left\" bgcolor=\"$timestampbgcolor\" colspan=\"3\">";
					if($myrow["category"]==0)
						echo "<img src=\"$url_gfx/$gannouncepic\" border=\"0\" align=\"absmiddle\" alt=\"$l_global_announcement\" title=\"$l_global_announcement\"> ";
					else
						echo "<img src=\"$url_gfx/$announcepic\" border=\"0\" align=\"absmiddle\" alt=\"$l_announcement\" title=\"$l_announcement\"> ";
					echo "<font face=\"$timestampfont\" size=\"$timestampfontsize\" color=\"$timestampfontcolor\">";
					echo get_start_tag($timestampstyle);
					echo $displaydate;
					echo get_end_tag($timestampstyle);
					echo "</font></td>";
					echo "</tr>";
				}
				if(bittst($evinc_options,BIT_3) && (strlen($myrow["heading"])>0))
				{
					echo "<tr bgcolor=\"$newsheadingbgcolor\"><td align=\"left\" colspan=\"3\">";
					echo "<font face=\"$newsheadingfont\" size=\"$newsheadingfontsize\" color=\"$newsheadingfontcolor\">";
					echo get_start_tag($newsheadingstyle);
					echo undo_html_ampersand(do_htmlentities($myrow["heading"]));
					echo get_end_tag($newsheadingstyle);
					echo "</font></td></tr>";
				}
				echo "<tr bgcolor=\"$contentbgcolor\"><td align=\"left\" colspan=\"3\">";
				echo "<font face=\"$contentfont\" size=\"$contentfontsize\" color=\"$contentfontcolor\">";
				$displaytext=stripslashes($myrow["text"]);
				$displaytext = undo_htmlspecialchars($displaytext);
				echo $displaytext."</font></td></tr>";
				if(bittst($evinc_options,BIT_4) && (strlen($myrow["poster"])>0) && ($attachpos==0))
					posterline2($myrow["posterid"], $myrow["poster"], bittst($evinc_options,BIT_5));
				if($attachpos==0)
					echo "<tr bgcolor=\"$contentbgcolor\"><td align=\"left\">";
				displayattachs_announce($myrow["entrynr"],$attachpos, $nofileinfo);
				if($attachpos==1)
				{
					if(bittst($evinc_options,BIT_4) && (strlen($myrow["poster"])>0))
						posterline2($myrow["posterid"], $myrow["poster"], bittst($evinc_options,BIT_5));
					echo "<tr bgcolor=\"$contentbgcolor\"><td>&nbsp;</td>";
				}
				echo "<td align=\"right\" colspan=\"2\">";
				if(bittst($evinc_options,BIT_6))
				{
					echo "<a href=\"announceprint.php?$langvar=$act_lang&layout=$layout&announcenr=".$myrow["entrynr"]."\" target=\"printwindow\">";
					if($printpic_small)
						echo "<img class=\"iconbutton\" src=\"$url_gfx/$printpic_small\" border=\"0\" align=\"absmiddle\" title=\"$l_print\" alt=\"$l_print\">";
					else
						echo "[$l_print]";
					echo "</a>";
				}
				if(bittst($evinc_options,BIT_7))
					echo "<a href=\"#top\"><img class=\"iconbutton\" src=\"$url_gfx/$pagetoppic\" border=\"0\" align=\"absmiddle\" title=\"$l_gotop\" alt=\"$l_gotop\"></a>";
				echo "</td></tr>";
				echo "</table></td></tr>";
			}
		}
}
$eventsavail=false;
$sql = "select * from ".$tableprefix."_events";
if($category>=0)
	$sql.=" where category='$category'";
else
{
	$sql.=" where linkeventnr=0";
	$tmpsql="select * from ".$tableprefix."_categories where hideintotallist=1";
	if(!$tmpresult = mysql_query($tmpsql, $db))
	    die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
	while($tmprow=mysql_fetch_array($tmpresult))
		$sql.=" and category!=".$tmprow["catnr"];
}
if(isset($link_date))
	$sql.=" and DATE_FORMAT(date,'%Y-%m-%d')='$link_date'";
else
{
	if(isset($startdate))
		$sql.= "and DATE_FORMAT(date,'%Y-%m-%d')>='$startdate' ";
	if(isset($enddate))
		$sql.= " and DATE_FORMAT(date,'%Y-%m-%d')<='$enddate'";
}
if($separatebylang==1)
	$sql.=" and lang='$act_lang'";
if(!isset($link_date))
{
	switch($sortorder)
	{
		case 0:
			$sql.=" order by date desc";
			break;
		case 1:
			$sql.=" order by date asc";
			break;
		case 2:
			$sql.=" order by heading asc";
			break;
		case 3:
			$sql.=" order by heading desc";
			break;
	}
}
if(!$result = mysql_query($sql, $db))
    die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
if(mysql_num_rows($result)>0)
{
	$eventsavail=true;
	echo "<tr bgcolor=\"$headingbgcolor\">";
	echo "<td align=\"center\" width=\"5%\">";
	if(bittst($announceoptions,BIT_1) && ($announceavail==true))
	{
		if(isset($backurl))
			echo "<a href=\"$backurl\"><img src=\"$url_gfx/$backpic\" border=\"0\" align=\"absmiddle\" title=\"$l_back\" alt=\"$l_back\"></a>";
		else
			echo "&nbsp;";
	}
	else
		echo "&nbsp;";
	echo "</td>";
	if(isset($link_date))
	{
		echo "<td align=\"center\">";
		echo "<font face=\"$headingfont\" size=\"$contentfontsize\" color=\"$headingfontcolor\">";
		echo "<b>$l_eventsforthisdate</b></font>";
	}
	else
	{
		echo "<td align=\"center\">";
		echo "<font face=\"$headingfont\" size=\"$contentfontsize\" color=\"$headingfontcolor\">";
		echo "<b>$l_events</b></font>";
	}
	echo "</td></tr>";
}
while($myrow=mysql_fetch_array($result))
{
	if($myrow["linkeventnr"]==0)
		$entrydata=$myrow;
	else
	{
		$tmpsql="select * from ".$tableprefix."_events where eventnr=".$myrow["linkeventnr"];
		if(!$tmpresult = mysql_query($tmpsql, $db))
			die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
		if(!$tmprow=mysql_fetch_array($tmpresult))
			die("<tr class=\"errorrow\"><td>Unable to get data");
		$entrydata=$tmprow;
	}
	if(($useviewcounts==1) && isset($link_date))
	{
		$tmpsql = "UPDATE ".$tableprefix."_events SET views = views + 1 WHERE (eventnr = ".$entrydata["eventnr"].")";
		@mysql_query($tmpsql, $db);
	}
	echo "<tr>";
	echo "<td width=\"2%\" height=\"100%\" align=\"center\" bgcolor=\"$contentbgcolor\">";
	echo "<a name=\"".$myrow["eventnr"]."\">";
	if($entrydata["headingicon"])
		echo "<img src=\"$url_icons/".$entrydata["headingicon"]."\" border=\"0\" align=\"middle\"> ";
	else
		echo "&nbsp;";
	echo "</a>";
	echo "</td>";
	echo "<td align=\"center\"><table class=\"eventbox\" width=\"100%\" align=\"center\" bgcolor=\"$contentbgcolor\" cellspacing=\"0\" cellpadding=\"0\">";
	list($tmpdate, $tmptime)=explode(" ",$entrydata["date"]);
	list($year, $month, $day) = explode("-", $tmpdate);
	list($hour, $min, $null) = explode(":", $tmptime);
	if(($hour>0) || ($min>0))
		$displaydate=date($event_dateformat2,mktime($hour,$min,0,$month,$day,$year));
	else
		$displaydate=date($event_dateformat,mktime(0,0,0,$month,$day,$year));
	if(bittst($evinc_options,BIT_2))
	{
		echo "<tr><td align=\"left\" bgcolor=\"$timestampbgcolor\" colspan=\"3\">";
		if(isset($highlight) && ($highlight==$myrow["eventnr"]))
			echo "<img src=\"$url_gfx/$highlightmarker\" border=\"0\"> ";
		echo "<font face=\"$timestampfont\" size=\"$timestampfontsize\" color=\"$timestampfontcolor\">";
		echo get_start_tag($timestampstyle);
		echo $displaydate;
		echo get_end_tag($timestampstyle);
		if(isset($lastvisitdate))
		{
			list($mydate,$mytime)=explode(" ",$myrow["added"]);
			list($year, $month, $day) = explode("-", $mydate);
			list($hour, $min, $sec) = explode(":",$mytime);
			$thisentrydate=mktime($hour,$min,$sec,$month,$day,$year);
			if($thisentrydate>=$lastvisitdate)
				echo "&nbsp;&nbsp;<img src=\"$url_gfx/$newentrypic\" border=\"0\" align=\"absmiddle\">";
		}
		echo "</font></td>";
		echo "</tr>";
	}
	if(bittst($evinc_options,BIT_3) && (strlen($entrydata["heading"])>0))
	{
		echo "<tr bgcolor=\"$newsheadingbgcolor\"><td align=\"left\" colspan=\"3\">";
		echo "<font face=\"$newsheadingfont\" size=\"$newsheadingfontsize\" color=\"$newsheadingfontcolor\">";
		echo get_start_tag($newsheadingstyle);
		echo undo_html_ampersand(do_htmlentities($entrydata["heading"]));
		echo get_end_tag($newsheadingstyle);
		echo "</font></td></tr>";
	}
	echo "<tr bgcolor=\"$contentbgcolor\"><td align=\"left\" colspan=\"3\">";
	echo "<font face=\"$contentfont\" size=\"$contentfontsize\" color=\"$contentfontcolor\">";
	$displaytext=stripslashes($entrydata["text"]);
	$displaytext = undo_htmlspecialchars($displaytext);
	echo $displaytext."</font></td></tr>";
	if(bittst($evinc_options,BIT_4) && (strlen($entrydata["poster"])>0) && ($attachpos==0))
		posterline2($entrydata["posterid"], $entrydata["poster"], bittst($evinc_options,BIT_5), $entrydata["exposter"]);
	if($attachpos==0)
		echo "<tr bgcolor=\"$contentbgcolor\"><td align=\"left\">";
	displayattachs_events($entrydata["eventnr"],$attachpos, $nofileinfo);
	if($attachpos==1)
	{
		posterline2($entrydata["posterid"], $entrydata["poster"], bittst($evinc_options,BIT_5), $entrydata["exposter"]);
		echo "<tr bgcolor=\"$contentbgcolor\"><td>&nbsp;</td>";
	}
	echo "<td align=\"right\" colspan=\"2\">";
	if(bittst($evinc_options,BIT_6))
	{
		echo "<a href=\"evprint.php?$langvar=$act_lang&layout=$layout&eventnr=".$entrydata["eventnr"]."\" target=\"printwindow\">";
		if($printpic_small)
			echo "<img src=\"$url_gfx/$printpic_small\" class=\"iconbutton\" border=\"0\" align=\"absmiddle\" title=\"$l_print\" alt=\"$l_print\">";
		else
			echo "[$l_print]";
		echo "</a>";
	}
	if(bittst($evinc_options,BIT_7))
		echo "<a href=\"#top\"><img class=\"iconbutton\" src=\"$url_gfx/$pagetoppic\" border=\"0\" align=\"absmiddle\" title=\"$l_gotop\" alt=\"$l_gotop\"></a>";
	echo "</td></tr>";
	echo "</table></td></tr>";
}
if(($newsineventcal==1) && isset($link_date))
{
$sql = "select * from ".$tableprefix."_data where DATE_FORMAT(date,'%Y-%m-%d')='$link_date' ";
if($separatebylang==1)
	$sql.="and lang='$act_lang' ";
if($category>=0)
	$sql.= "and category='$category' ";
else
	$sql.= "and linknewsnr=0 ";
if(!isset($link_date))
{
	switch($sortorder)
	{
		case 0:
			$sql.=" order by date desc";
			break;
		case 1:
			$sql.=" order by date asc";
			break;
		case 2:
			$sql.=" order by heading asc";
			break;
		case 3:
			$sql.=" order by heading desc";
			break;
	}
}
if(!$result = mysql_query($sql, $db))
    die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
if(mysql_num_rows($result)>0)
{
	echo "<tr bgcolor=\"$headingbgcolor\">";
	echo "<td align=\"center\">";
	if((bittst($announceoptions,BIT_1) && $announceavail) || ($eventsavail))
	{
		if(isset($backurl))
			echo "<a href=\"$backurl\"><img src=\"$url_gfx/$backpic\" border=\"0\" align=\"absmiddle\" title=\"$l_back\" alt=\"$l_back\"></a>";
		else
			echo "&nbsp;";
	}
	else
		echo "&nbsp;";
	echo "</td>";
	echo "<td align=\"center\">";
	echo "<font face=\"$headingfont\" size=\"$contentfontsize\" color=\"$headingfontcolor\">";
	echo "<b>$l_newsforthisdate</b></font></td></tr>";
}
while($myrow=mysql_fetch_array($result))
{
	if($myrow["linknewsnr"]==0)
		$entrydata=$myrow;
	else
	{
		$tmpsql="select * from ".$tableprefix."_data where newsnr=".$myrow["linknewsnr"];
		if(!$tmpresult = mysql_query($tmpsql, $db))
			die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
		if(!$tmprow=mysql_fetch_array($tmpresult))
			die("<tr class=\"errorrow\"><td>Unable to get data");
		$entrydata=$tmprow;
	}
	echo "<tr><td width=\"2%\" height=\"100%\" align=\"center\" bgcolor=\"$contentbgcolor\">";
	if($entrydata["headingicon"])
		echo "<img src=\"$url_icons/".$entrydata["headingicon"]."\" border=\"0\" align=\"middle\"> ";
	else
		echo "&nbsp;";
	echo "</td>";
	echo "<td align=\"center\"><table class=\"eventbox\" width=\"100%\" align=\"center\" bgcolor=\"$contentbgcolor\" cellspacing=\"0\" cellpadding=\"0\">";
	list($mydate,$mytime)=explode(" ",$myrow["date"]);
	list($year, $month, $day) = explode("-", $mydate);
	list($hour, $min, $sec) = explode(":",$mytime);
	if($month>0)
	{
		$temptime=mktime($hour,$min,$sec,$month,$day,$year);
		$temptime=transposetime($temptime,$servertimezone,$displaytimezone);
		$displaydate=date($dateformat,$temptime);
	}
	else
		$displaydate="";
	if(bittst($evinc_options,BIT_2) || (($allowcomments==1) && ($entrydata["allowcomments"]==1)))
	{
		echo "<tr><td align=\"left\" bgcolor=\"$timestampbgcolor\"";
		if(($allowcomments==0) || ($myrow["allowcomments"]==0))
			echo " colspan=\"3\"";
		else
			echo " width=\"80%\"";
		echo ">";
		echo "<font face=\"$timestampfont\" size=\"$timestampfontsize\" color=\"$timestampfontcolor\">";
		echo get_start_tag($timestampstyle);
		echo $displaydate;
		echo get_end_tag($timestampstyle);
		if(isset($lastvisitdate))
		{
			list($mydate,$mytime)=explode(" ",$myrow["date"]);
			list($year, $month, $day) = explode("-", $mydate);
			list($hour, $min, $sec) = explode(":",$mytime);
			$thisentrydate=mktime($hour,$min,$sec,$month,$day,$year);
			if($thisentrydate>=$lastvisitdate)
				echo "&nbsp;&nbsp;<img src=\"$url_gfx/$newentrypic\" border=\"0\" align=\"absmiddle\">";
		}
		echo "</font></td>";
	}
	if(($allowcomments==1) && ($entrydata["allowcomments"]==1))
	{
		echo "<td align=\"right\" bgcolor=\"$timestampbgcolor\" width=\"10%\" valign=\"top\">";
		echo "<font face=\"$timestampfont\" size=\"$timestampfontsize\" color=\"$timestampfontcolor\">";
		$tempsql="select * from ".$tableprefix."_comments where entryref=".$entrydata["newsnr"];
		if(!$tempresult = mysql_query($tempsql, $db))
		    die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
		$numcomments=mysql_num_rows($tempresult);
		if($numcomments>0)
			echo "<a class=\"commentlink\" href=\"comment.php?mode=display&amp;$langvar=$act_lang&amp;entryref=".$entrydata["newsnr"]."\">$l_comments:&nbsp;$numcomments</a>&nbsp;&nbsp;";
		else
			echo "&nbsp;";
		echo "</font></td>";
		echo "<td align=\"center\" bgcolor=\"$timestampbgcolor\" width=\"10%\">";
		echo "<font face=\"$timestampfont\" size=\"$timestampfontsize\" color=\"$timestampfontcolor\">";
		echo "<a class=\"commentlink\" href=\"comment.php?$langvar=$act_lang&amp;mode=new&amp;entryref=".$entrydata["newsnr"]."\">$l_writecomment</a>";
		echo "</font></td>";
	}
	echo "</tr>";
	if(bittst($evinc_options,BIT_3) && (strlen($entrydata["heading"])>0))
	{
		echo "<tr bgcolor=\"$newsheadingbgcolor\"><td align=\"left\" colspan=\"3\">";
		echo "<font face=\"$newsheadingfont\" size=\"$newsheadingfontsize\" color=\"$newsheadingfontcolor\">";
		echo get_start_tag($newsheadingstyle);
		echo undo_html_ampersand(do_htmlentities($entrydata["heading"]));
		echo get_end_tag($newsheadingstyle);
		echo "</font></td></tr>";
	}
	echo "<tr bgcolor=\"$contentbgcolor\"><td align=\"left\" colspan=\"3\">";
	echo "<font face=\"$contentfont\" size=\"$contentfontsize\" color=\"$contentfontcolor\">";
	$displaytext=stripslashes($entrydata["text"]);
	$displaytext = undo_htmlspecialchars($displaytext);
	echo $displaytext."</font></td></tr>";
	if(bittst($evinc_options,BIT_4) && (strlen($entrydata["poster"])>0) && ($attachpos==0))
		posterline2($entrydata["posterid"], $entrydata["poster"], bittst($evinc_options,BIT_5), $entrydata["exposter"]);
	if($attachpos==0)
		echo "<tr bgcolor=\"$contentbgcolor\"><td align=\"left\">";
	displayattachs_news($entrydata["newsnr"],$attachpos, $nofileinfo);
	if($attachpos==1)
	{
		posterline2($entrydata["posterid"], $entrydata["poster"], bittst($evinc_options,BIT_5), $entrydata["exposter"]);
		echo "<tr bgcolor=\"$contentbgcolor\"><td>&nbsp;</td>";
	}
	echo "<td align=\"right\" colspan=\"2\">";
	if(bittst($evinc_options,BIT_6))
	{
		echo "<a href=\"print.php?$langvar=$act_lang&layout=$layout&newsnr=".$entrydata["newsnr"]."\" target=\"printwindow\">";
		if($printpic_small)
			echo "<img class=\"iconbutton\" src=\"$url_gfx/$printpic_small\" border=\"0\" align=\"absmiddle\" title=\"$l_print\" alt=\"$l_print\">";
		else
			echo "[$l_print]";
		echo "</a>";
	}
	if(bittst($evinc_options,BIT_7))
		echo "<a href=\"#top\"><img class=\"iconbutton\" src=\"$url_gfx/$pagetoppic\" border=\"0\" align=\"absmiddle\" title=\"$l_gotop\" alt=\"$l_gotop\"></a>";
	echo "</td></tr>";
	echo "</table></td></tr>";
}
}
echo "</table></td></tr></table></div>";
$footer_tablewidth=$evinc_tablewidth;
include($path_simpnews.'/includes/footer4.inc');
?>