<?php
/***************************************************************************
 * (c)2002-2005 Boesch IT-Consulting (info@boesch-it.de)
 ***************************************************************************/
$path_simpnews=dirname(__FILE__);
require_once($path_simpnews.'/config.php');
require_once($path_simpnews.'/functions.php');
if(!isset($category))
	$category=0;
if(!isset($$langvar) || !$$langvar)
	$act_lang=$default_lang;
else
	$act_lang=$$langvar;
include($path_simpnews.'/language/lang_'.$act_lang.'.php');
include($path_simpnews.'/includes/get_settings.inc');
?>
<!-- code generated by SimpNews begin -->
<table style="clear:both" width="<?php echo $TableWidth2?>" border="0" CELLPADDING="1" CELLSPACING="0" class="sntable" align="<?php echo $tblalign?>">
<tr><TD BGCOLOR="<?php echo $bordercolor?>">
<TABLE BORDER="0" CELLPADDING="1" CELLSPACING="1" WIDTH="100%">
<TR BGCOLOR="<?php echo $copyrightbgcolor?>" ALIGN="CENTER">
<TD ALIGN="CENTER" VALIGN="MIDDLE" colspan="2"><font face="<?php echo $copyrightfont?>" size="<?php echo $copyrightfontsize?>" color="<?php echo $copyrightfontcolor?>">
<?php
if($showcurrtime==1)
{
	$acttime=transposetime(time(),$servertimezone,$displaytimezone);
	$displaytime=date("H:i",$acttime);
	echo "$l_timeonserver: $displaytime";
	echo "<br><span class=\"timezone\">$l_timezone_note ".timezonename($displaytimezone);
	$gmtoffset=tzgmtoffset($displaytimezone);
	if($gmtoffset)
		echo " (".$gmtoffset.")";
	echo "</span><br>";
}
if($contentcopy)
{
	echo $l_content." ".undo_htmlspecialchars(do_htmlentities(stripslashes($contentcopy)))."<br>";
}
else
{
	echo $l_content." ".$simpnewssitename."<br>";
}
echo "$l_generated_with $copyright_url $copyright_note";
if($l_translationnote)
	echo "<br>$l_translationnote";
?>
</font></td></tr></table></td></tr></table>
<!-- code generated by SimpNews end -->
