<?php
/***************************************************************************
 * (c)2002-2005 Boesch IT-Consulting (info@boesch-it.de)
 ***************************************************************************/
$path_simpnews=dirname(__FILE__);
require_once($path_simpnews.'/config.php');
require_once($path_simpnews.'/functions.php');
if(!isset($sortorder))
	$sortorder=0;
if(!isset($$langvar) || !$$langvar)
	$act_lang=$default_lang;
else
	$act_lang=$$langvar;
include($path_simpnews.'/language/lang_'.$act_lang.'.php');
include($path_simpnews.'/includes/get_settings.inc');
include($path_simpnews.'/includes/styles2.inc');
if(isset($limitentries))
	$numhotnews=$limitentries;
if(!isset($maxannounce))
	$maxannounce=0;
if($hn_linklayout)
	$layout=$hn_linklayout;
$actdate = date("Y-m-d 23:59:59");
?>
<!-- code generated by SimpNews begin -->
<table width="<?php echo $TableWidth2?>" border="0" CELLPADDING="1" CELLSPACING="0" ALIGN="<?php echo $tblalign?>" class="sntable">
<tr><TD BGCOLOR="<?php echo $bordercolor?>">
<TABLE BORDER="0" CELLPADDING="1" CELLSPACING="1" WIDTH="100%">
<?php
if((strlen($heading)>0) && ($hotscriptsnoheading==0))
{
?>
<TR BGCOLOR="<?php echo $headingbgcolor?>" ALIGN="CENTER">
<TD ALIGN="CENTER" VALIGN="MIDDLE" colspan="2"><font face="<?php echo $headingfont?>" size="<?php echo $headingfontsize?>" color="<?php echo $headingfontcolor?>"><b><?php echo $heading?></b></font></td></tr>
<?php
}
$sql = "select * from ".$tableprefix."_misc";
if(!$result = mysql_query($sql, $db)) {
    die("<tr class=\"errorrow\"><td>Could not connect to the database.");
}
if ($myrow = mysql_fetch_array($result))
{
	if($myrow["shutdown"]==1)
	{
?>
</tr></table></td></tr>
<tr><TD BGCOLOR="<?php echo $bordercolor?>">
<TABLE BORDER="0" CELLPADDING="1" CELLSPACING="1" WIDTH="100%">
<tr BGCOLOR="<?php echo $contentbgcolor?>" ALIGN="CENTER">
<TD ALIGN="CENTER" VALIGN="MIDDLE" colspan="2"><font face="<?php echo $contentfont?>" size="<?php echo $contentfontsize?>" color="<?php echo $contentfontcolor?>">
<?php
		$shutdowntext=stripslashes($myrow["shutdowntext"]);
		$shutdowntext = undo_htmlspecialchars($shutdowntext);
		echo $shutdowntext;
		echo "</font></td></tr></table></td></tr></table>";
?>
</td></tr></table></div>
<?php
		include($path_simpnews.'/includes/footer2.inc');
		echo "</body></html>";
		exit;
	}
}
if(!isset($category))
	$category=0;
echo "<tr bgcolor=\"$categorybgcolor\"><td align=\"left\" colspan=\"2\">";
echo "<font face=\"$categoryfont\" size=\"$categoryfontsize\" color=\"$categoryfontcolor\">";
if(!bittst($hn_catlinking,BIT_3))
	echo "<a title=\"$l_showcategory\" class=\"catlink\" href=\"".$url_simpnews."/news.php?$langvar=$act_lang&amp;layout=$layout&amp;category=0\" target=\"$hotnews2target\">";
echo get_start_tag($categorystyle);
echo "$l_general";
echo get_end_tag($categorystyle);
if(!bittst($hn_catlinking,BIT_3))
	echo "</a>";
echo "</font></td></tr>";
$announceavail=false;
if(bittst($announceoptions,BIT_12))
{
		$acttime=transposetime(time(),$servertimezone,$displaytimezone);
		$tmpsql = "select * from ".$tableprefix."_announce where (expiredate>=$acttime or expiredate=0)  and (firstdate<=$acttime or firstdate=0)";
		if($separatebylang==1)
			$tmpsql.="and lang='$act_lang' ";
		if($maxage>0)
			$tmpsql.= "and date >= date_sub('$actdate', INTERVAL $maxage DAY) ";
		$tmpsql.= "and category=0";
		switch($sortorder)
		{
			case 0:
				$tmpsql.=" order by date desc";
				break;
			case 1:
				$tmpsql.=" order by date asc";
				break;
			case 2:
				$tmpsql.=" order by heading asc";
				break;
			case 3:
				$tmpsql.=" order by heading desc";
				break;
		}
		if($maxannounce>0)
			$tmpsql.=" limit $maxannounce";
		else
			$tmpsql.= " limit $numhotnews";
		if(!$tmpresult = mysql_query($tmpsql, $db))
			die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
		if(mysql_num_rows($tmpresult)>0)
		{
			$announceavail=true;
			while($tmprow=mysql_fetch_array($tmpresult))
			{
				echo "<tr>";
				if($hotnewsicons==1)
				{
					echo "<td width=\"2%\" height=\"100%\" align=\"center\" bgcolor=\"$contentbgcolor\">";
					if($tmprow["headingicon"])
						echo "<img src=\"$url_icons/".$tmprow["headingicon"]."\" border=\"0\" align=\"middle\"> ";
					echo "</td>";
				}
				echo "<td align=\"center\"><table class=\"newsbox\" width=\"100%\" align=\"center\" bgcolor=\"$contentbgcolor\" cellspacing=\"0\" cellpadding=\"0\">";
				list($mydate,$mytime)=explode(" ",$tmprow["date"]);
				list($year, $month, $day) = explode("-", $mydate);
				list($hour, $min, $sec) = explode(":",$mytime);
				if($month>0)
				{
					$displaytime=mktime($hour,$min,$sec,$month,$day,$year);
					$displaytime=transposetime($displaytime,$servertimezone,$displaytimezone);
					$displaydate=date($dateformat,$displaytime);
				}
				else
					$displaydate="";
				echo "<tr><td align=\"left\" bgcolor=\"$timestampbgcolor\">";
				echo "<font face=\"$timestampfont\" size=\"$timestampfontsize\" color=\"$timestampfontcolor\">";
				if($tmprow["category"]==0)
					echo "<img style=\"margin: 1px\" src=\"$url_gfx/$gannouncepic\" border=\"0\" align=\"absmiddle\" alt=\"$l_global_announcement\" title=\"$l_global_announcement\"> ";
				else
					echo "<img style=\"margin: 1px\" src=\"$url_gfx/$announcepic\" border=\"0\" align=\"absmiddle\" alt=\"$l_announcement\" title=\"$l_announcement\"> ";
				echo get_start_tag($timestampstyle);
				echo $displaydate;
				echo get_end_tag($timestampstyle);
				echo "</font></td></tr>";
				if(strlen($tmprow["heading"])>0)
				{
					echo "<tr bgcolor=\"$newsheadingbgcolor\"><td align=\"left\">";
					echo "<font face=\"$newsheadingfont\" size=\"$hn_newsheadingfontsize\" color=\"$newsheadingfontcolor\">";
					if(($hotnewsmaxchars<1) && ($hnnolinking==0))
					{
						if($usehnlinkdest==1)
							$linkdest="$hnlinkdestan?$langvar=$act_lang&layout=$layout&category=$category&announcenr=".$tmprow["entrynr"];
						else
							$linkdest=$url_simpnews."/announce.php?$langvar=$act_lang&layout=$layout&category=$category&announcenr=".$tmprow["entrynr"];
						echo " <a href=\"$linkdest\"";
						if($hotnewstarget)
							echo " target=\"$hotnewstarget\"";
						echo ">";
					}
					$displayheading=$tmprow["heading"];
					if($hotnewsnohtmlformatting==1)
						$displayheading=strip_tags($displayheading);
					$displayheading=do_htmlentities($displayheading);
					$displayheading=undo_htmlspecialchars($displayheading);
					if($hotnewsnohtmlformatting==0)
						echo get_start_tag($newsheadingstyle);
					echo $displayheading;
					if($hotnewsnohtmlformatting==0)
						echo get_end_tag($newsheadingstyle);
					if(($hotnewsmaxchars<1) && ($hnnolinking==0))
						echo "</a>";
					echo "</font></td></tr>";
				}
				if($hotnewsmaxchars!=0)
				{
					echo "<tr bgcolor=\"$contentbgcolor\"><td align=\"left\">";
					echo "<font face=\"$contentfont\" size=\"$contentfontsize\" color=\"$contentfontcolor\">";
					$displaytext=stripslashes($tmprow["text"]);
					$displaytext = undo_htmlspecialchars($displaytext);
					if(($hotnewsmaxchars>0) && strlen($displaytext)>$hotnewsmaxchars)
					{
						$displaytext=str_replace("<BR>"," ",$displaytext);
						$displaytext=undo_htmlentities($displaytext);
						$displaytext=strip_tags($displaytext);
						$displaytext=substr($displaytext,0,$hotnewsmaxchars);
						$displaytext=do_htmlentities($displaytext);
						if($usehnlinkdest==1)
							$linkdest="$hnlinkdestan?$langvar=$act_lang&layout=$layout&category=$category&announcenr=".$tmprow["entrynr"];
						else
							$linkdest=$url_simpnews."/announce.php?$langvar=$act_lang&layout=$layout&category=$category&announcenr=".$tmprow["entrynr"];
						$displaytext.=" <a href=\"$linkdest\"";
						if($hotnewstarget)
							$displaytext.=" target=\"$hotnewstarget\"";
						$displaytext.=">[...]</a>";
					} else if($hotnewsnohtmlformatting==1)
						strip_tags($displaytext);
					echo $displaytext."</font></td></tr>";
				}
				if($hotnewsdisplayposter && (strlen($tmprow["poster"])>0))
				{
					echo "<tr bgcolor=\"$posterbgcolor\"><td align=\"left\">";
					echo "<font face=\"$posterfont\" size=\"$posterfontsize\" color=\"$posterfontcolor\">";
					if($hotnewsnohtmlformatting==0)
						echo get_start_tag($posterstyle);
					echo "$l_poster: ".do_htmlentities($tmprow["poster"]);
					if($hotnewsnohtmlformatting==0)
						echo get_end_tag($posterstyle);
					echo "</font></td></tr>";
				}
				echo "</table></td></tr>";
			}
		}
}
$sql = "select * from ".$tableprefix."_data where category=0 and linknewsnr=0 ";
if($separatebylang==1)
	$sql.="and lang='$act_lang' ";
if($maxage>0)
	$sql.= "and date >= date_sub('$actdate', INTERVAL $maxage DAY) ";
if($showfuturenews==0)
	$sql.="and date<='$actdate' ";
switch($sortorder)
{
	case 0:
		$sql.=" order by date desc";
		break;
	case 1:
		$sql.=" order by date asc";
		break;
	case 2:
		$sql.=" order by heading asc";
		break;
	case 3:
		$sql.=" order by heading desc";
		break;
}
if(!$result = mysql_query($sql, $db))
    die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
$numentries=mysql_numrows($result);
$sql .=" limit $numhotnews";
if(!$result = mysql_query($sql, $db))
	die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
$numdisplayed=mysql_numrows($result);
while($myrow=mysql_fetch_array($result))
{
	echo "<tr>";
	if($hotnewsicons==1)
	{
		echo "<td width=\"2%\" height=\"100%\" align=\"center\" bgcolor=\"$contentbgcolor\">";
		if($myrow["headingicon"])
			echo "<img src=\"$url_icons/".$myrow["headingicon"]."\" border=\"0\" align=\"middle\"> ";
		echo "</td>";
	}
	echo "<td align=\"center\"><table class=\"newsbox\" width=\"100%\" align=\"center\" bgcolor=\"$contentbgcolor\" cellspacing=\"0\" cellpadding=\"0\">";
	list($mydate,$mytime)=explode(" ",$myrow["date"]);
	list($year, $month, $day) = explode("-", $mydate);
	list($hour, $min, $sec) = explode(":",$mytime);
	if($month>0)
	{
		$displaytime=mktime($hour,$min,$sec,$month,$day,$year);
		$displaytime=transposetime($displaytime,$servertimezone,$displaytimezone);
		$displaydate=date($dateformat,$displaytime);
	}
	else
		$displaydate="";
	echo "<tr><td align=\"left\" bgcolor=\"$timestampbgcolor\">";
	echo "<font face=\"$timestampfont\" size=\"$timestampfontsize\" color=\"$timestampfontcolor\">";
	echo get_start_tag($timestampstyle);
	echo $displaydate;
	echo get_end_tag($timestampstyle);
	if(isset($lastvisitdate))
	{
		list($mydate,$mytime)=explode(" ",$myrow["date"]);
		list($year, $month, $day) = explode("-", $mydate);
		list($hour, $min, $sec) = explode(":",$mytime);
		$thisentrydate=mktime($hour,$min,$sec,$month,$day,$year);
		if($thisentrydate>=$lastvisitdate)
			echo "&nbsp;&nbsp;<img src=\"$url_gfx/$newentrypic\" border=\"0\" align=\"absmiddle\">";
	}
	echo "</font></td>";
	$srcscript=$url_simpnews."/news2.php";
	if(($allowcomments==1) && ($myrow["allowcomments"]==1) && ($hotnewscommentslink==1))
	{
		$tempsql="select * from ".$tableprefix."_comments where entryref=".$myrow["newsnr"];
		if(!$tempresult = mysql_query($tempsql, $db))
			die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
		$numcomments=mysql_num_rows($tempresult);
		if($numcomments>0)
		{
			echo "<td align=\"right\" bgcolor=\"$timestampbgcolor\" width=\"10%\" valign=\"top\">";
			echo "<font face=\"$timestampfont\" size=\"$timestampfontsize\" color=\"$timestampfontcolor\">";
			if($commentsinline==0)
				$commentlink=$url_simpnews."/comment.php?mode=display&amp;$langvar=$act_lang&amp;entryref=".$myrow["newsnr"];
			else
			{
				if($usehnlinkdest)
					$commentlink=$hnlinkdest;
				else
					$commentlink=$url_simpnews."/singlenews.php";
				$commentlink.="?$langvar=$act_lang&layout=$layout&category=".$myrow["category"]."&newsnr=".$myrow["newsnr"]."&srcscript=$srcscript";
			}
			echo "<a class=\"commentlink\" href=\"$commentlink\">";
			if($commentspic)
				echo "<img style=\"margin: 1px\" src=\"".$url_gfx."/$commentspic\" border=\"0\" alt=\"$l_comments: $numcomments\" title=\"$l_comments: $numcomments\">";
			else
				echo "$l_comments:&nbsp;$numcomments";
			echo "</a>&nbsp;</font></td>";
		}
	}
	echo "</tr>";
	if(strlen($myrow["heading"])>0)
	{
		echo "<tr bgcolor=\"$newsheadingbgcolor\"><td align=\"left\">";
		echo "<font face=\"$newsheadingfont\" size=\"$hn_newsheadingfontsize\" color=\"$newsheadingfontcolor\">";
		$displayheading=$myrow["heading"];
		if($hotnewsnohtmlformatting==1)
			$displayheading=strip_tags($displayheading);
		$displayheading=do_htmlentities($displayheading);
		$displayheading=undo_htmlspecialchars($displayheading);
		if(($hotnewsmaxchars<1) && ($hnnolinking==0))
		{
			if($usehnlinkdest==1)
				$linkdest="$hnlinkdest?$langvar=$act_lang&layout=$layout&category=".$myrow["category"]."&newsnr=".$myrow["newsnr"]."&srcscript=$srcscript";
			else
				$linkdest="$url_simpnews/singlenews.php?$langvar=$act_lang&layout=$layout&category=".$myrow["category"]."&newsnr=".$myrow["newsnr"]."&srcscript=$srcscript";
			echo " <a href=\"$linkdest\"";
			if($hotnewstarget)
				echo " target=\"$hotnewstarget\"";
			echo ">";
		}
		if($hotnewsnohtmlformatting==0)
			echo get_start_tag($newsheadingstyle);
		echo $displayheading;
		if($hotnewsnohtmlformatting==0)
			echo get_end_tag($newsheadingstyle);
		if(($hotnewsmaxchars<1) && ($hnnolinking==0))
			echo "</a>";
		echo "</font></td></tr>";
	}
	if($hotnewsmaxchars!=0)
	{
		echo "<tr bgcolor=\"$contentbgcolor\"><td align=\"left\">";
		echo "<font face=\"$contentfont\" size=\"$contentfontsize\" color=\"$contentfontcolor\">";
		$displaytext=stripslashes($myrow["text"]);
		$displaytext = undo_htmlspecialchars($displaytext);
		if(($hotnewsmaxchars>0) && strlen($displaytext)>$hotnewsmaxchars)
		{
			$displaytext=str_replace("<BR>"," ",$displaytext);
			$displaytext=undo_htmlentities($displaytext);
			$displaytext=strip_tags($displaytext);
			$displaytext=substr($displaytext,0,$hotnewsmaxchars);
			$displaytext=do_htmlentities($displaytext);
			$srcscript=$url_simpnews."/news2.php";
			if($usehnlinkdest==1)
				$linkdest="$hnlinkdest?$langvar=$act_lang&layout=$layout&category=".$myrow["category"]."&newsnr=".$myrow["newsnr"]."&srcscript=$srcscript";
			else
				$linkdest="$url_simpnews/singlenews.php?$langvar=$act_lang&layout=$layout&category=".$myrow["category"]."&newsnr=".$myrow["newsnr"]."&srcscript=$srcscript";
			$displaytext.=" <a href=\"$linkdest\"";
			if($hotnewstarget)
				$displaytext.=" target=\"$hotnewstarget\"";
			$displaytext.=">[...]</a>";
		}
		else if($hotnewsnohtmlformatting==1)
			$displaytext=strip_tags($displaytext);
		echo $displaytext."</font></td></tr>";
	}
	if($hotnewsdisplayposter && (strlen($myrow["poster"])>0))
	{
		echo "<tr bgcolor=\"$posterbgcolor\"><td align=\"left\">";
		echo "<font face=\"$posterfont\" size=\"$posterfontsize\" color=\"$posterfontcolor\">";
		if($hotnewsnohtmlformatting==0)
			echo get_start_tag($posterstyle);
		echo "$l_poster: ".do_htmlentities($myrow["poster"]);
		if($hotnewsnohtmlformatting==0)
			echo get_end_tag($posterstyle);
		echo "</font></td></tr>";
	}
	echo "</table></td></tr>";
}
if(($numdisplayed==0) && !$announceavail)
{
	echo "<tr bgcolor=\"$contentbgcolor\"><td align=\"center\" colspan=\"2\">";
	echo "<font face=\"$contentfont\" size=\"$contentfontsize\" color=\"$contentfontcolor\">";
	echo $l_nonewnews;
	echo "</font></td></tr>";
}
if($numdisplayed<$numentries)
{
?>
<tr bgcolor="<?php echo $headingbgcolor?>"><td align="right" colspan="2">
<font face="<?php echo $contentfont?>" size="<?php echo $contentfontsize?>" color="<?php echo $contentfontcolor?>">
<a href="<?php echo $url_simpnews?>/news.php?<?php echo "$langvar=$act_lang"?>&amp;layout=<?php echo $layout?>&amp;category=0" target="<?php echo $hotnews2target?>">
<?php echo "[$l_morenews]"?></a></font></td></tr>
<?php
}
echo "<tr bgcolor=\"$bordercolor\"><td colspan=\"2\">";
echo "<img src=\"$url_gfx/space.gif\" border=\"0\" width=\"1\" height=\"1\">";
echo "</td></tr>";
$sql = "select * from ".$tableprefix."_categories";
if(!$result = mysql_query($sql, $db))
    die("<tr class=\"errorrow\"><td>Could not connect to the database.");
while($myrow=mysql_fetch_array($result))
{
	$cattext=display_encoded(stripslashes($myrow["catname"]));
	$tmpsql="select * from ".$tableprefix."_catnames where catnr=".$myrow["catnr"]." and lang='".$act_lang."'";
	if(!$tmpresult=mysql_query($tmpsql,$db))
		die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
	if($tmprow=mysql_fetch_array($tmpresult))
	{
		if(strlen($tmprow["catname"])>0)
			$cattext=display_encoded(stripslashes($tmprow["catname"]));
	}
	echo "<tr bgcolor=\"$categorybgcolor\"><td align=\"left\" colspan=\"2\">";
	echo "<font face=\"$categoryfont\" size=\"$categoryfontsize\" color=\"$categoryfontcolor\">";
	if(!bittst($hn_catlinking,BIT_3))
		echo "<a title=\"$l_showcategory\" class=\"catlink\" href=\"".$url_simpnews."/news.php?$langvar=$act_lang&amp;layout=$layout&amp;category=".$myrow["catnr"]."\" target=\"$hotnews2target\">";
	echo get_start_tag($categorystyle);
	echo $cattext;
	echo get_end_tag($categorystyle);
	if(!bittst($hn_catlinking,BIT_3))
		echo "</a>";
	echo "</font></td></tr>";
	$announceavail=false;
	if(bittst($announceoptions,BIT_12))
	{
			$acttime=transposetime(time(),$servertimezone,$displaytimezone);
			$tmpsql = "select * from ".$tableprefix."_announce where (expiredate>=$acttime or expiredate=0)  and (firstdate<=$acttime or firstdate=0)";
			if($separatebylang==1)
				$tmpsql.="and lang='$act_lang' ";
			if($maxage>0)
				$tmpsql.= "and date >= date_sub('$actdate', INTERVAL $maxage DAY) ";
			$tmpsql.=" and category=".$myrow["catnr"];
			switch($sortorder)
			{
				case 0:
					$tmpsql.=" order by date desc";
					break;
				case 1:
					$tmpsql.=" order by date asc";
					break;
				case 2:
					$tmpsql.=" order by heading asc";
					break;
				case 3:
					$tmpsql.=" order by heading desc";
					break;
			}
			$tmpsql.=" limit $numhotnews";
			if(!$tmpresult = mysql_query($tmpsql, $db))
				die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
			if(mysql_num_rows($tmpresult)>0)
			{
				$announceavail=true;
				while($tmprow=mysql_fetch_array($tmpresult))
				{
					echo "<tr>";
					if($hotnewsicons==1)
					{
						echo "<td width=\"2%\" height=\"100%\" align=\"center\" bgcolor=\"$contentbgcolor\">";
						if($tmprow["headingicon"])
							echo "<img src=\"$url_icons/".$tmprow["headingicon"]."\" border=\"0\" align=\"middle\"> ";
						echo "</td>";
					}
					echo "<td align=\"center\"><table class=\"newsbox\" width=\"100%\" align=\"center\" bgcolor=\"$contentbgcolor\" cellspacing=\"0\" cellpadding=\"0\">";
					list($mydate,$mytime)=explode(" ",$tmprow["date"]);
					list($year, $month, $day) = explode("-", $mydate);
					list($hour, $min, $sec) = explode(":",$mytime);
					if($month>0)
					{
						$displaytime=mktime($hour,$min,$sec,$month,$day,$year);
						$displaytime=transposetime($displaytime,$servertimezone,$displaytimezone);
						$displaydate=date($dateformat,$displaytime);
					}
					else
						$displaydate="";
					echo "<tr><td align=\"left\" bgcolor=\"$timestampbgcolor\">";
					echo "<font face=\"$timestampfont\" size=\"$timestampfontsize\" color=\"$timestampfontcolor\">";
					if($tmprow["category"]==0)
						echo "<img style=\"margin: 1px\" src=\"$url_gfx/$gannouncepic\" border=\"0\" align=\"absmiddle\" alt=\"$l_global_announcement\" title=\"$l_global_announcement\"> ";
					else
						echo "<img style=\"margin: 1px\" src=\"$url_gfx/$announcepic\" border=\"0\" align=\"absmiddle\" alt=\"$l_announcement\" title=\"$l_announcement\"> ";
					echo get_start_tag($timestampstyle);
					echo $displaydate;
					echo get_end_tag($timestampstyle);
					echo "</font></td></tr>";
					if(strlen($tmprow["heading"])>0)
					{
						echo "<tr bgcolor=\"$newsheadingbgcolor\"><td align=\"left\">";
						echo "<font face=\"$newsheadingfont\" size=\"$hn_newsheadingfontsize\" color=\"$newsheadingfontcolor\">";
						if($hotnewsmaxchars<1)
						{
							echo " <a href=\"".$url_simpnews."/announce.php?$langvar=$act_lang&layout=$layout&category=$category&announcenr=".$tmprow["entrynr"]."\"";
							if($hotnewstarget)
								echo " target=\"$hotnewstarget\"";
							echo ">";
						}
						$displayheading=$tmprow["heading"];
						if($hotnewsnohtmlformatting==1)
							$displayheading=strip_tags($displayheading);
						$displayheading=do_htmlentities($displayheading);
						$displayheading=undo_htmlspecialchars($displayheading);
						if($hotnewsnohtmlformatting==0)
							echo get_start_tag($newsheadingstyle);
						echo $displayheading;
						if($hotnewsnohtmlformatting==0)
							echo get_end_tag($newsheadingstyle);
						if($hotnewsmaxchars<1)
							echo "</a>";
						echo "</font></td></tr>";
					}
					if($hotnewsmaxchars!=0)
					{
						echo "<tr bgcolor=\"$contentbgcolor\"><td align=\"left\">";
						echo "<font face=\"$contentfont\" size=\"$contentfontsize\" color=\"$contentfontcolor\">";
						$displaytext=stripslashes($tmprow["text"]);
						$displaytext = undo_htmlspecialchars($displaytext);
						if(($hotnewsmaxchars>0) && strlen($displaytext)>$hotnewsmaxchars)
						{
							$displaytext=str_replace("<BR>"," ",$displaytext);
							$displaytext=undo_htmlentities($displaytext);
							$displaytext=strip_tags($displaytext);
							$displaytext=substr($displaytext,0,$hotnewsmaxchars);
							$displaytext=display_encoded($displaytext);
							$displaytext.=" <a href=\"".$url_simpnews."/announce.php?$langvar=$act_lang&layout=$layout&category=$category&announcenr=".$tmprow["entrynr"]."\"";
							if($hotnewstarget)
								$displaytext.=" target=\"$hotnewstarget\"";
							$displaytext.=">[...]</a>";
						} else if($hotnewsnohtmlformatting==1)
							strip_tags($displaytext);
						echo $displaytext."</font></td></tr>";
					}
					if($hotnewsdisplayposter && (strlen($tmprow["poster"])>0))
					{
						echo "<tr bgcolor=\"$posterbgcolor\"><td align=\"left\">";
						echo "<font face=\"$posterfont\" size=\"$posterfontsize\" color=\"$posterfontcolor\">";
						if($hotnewsnohtmlformatting==0)
							echo get_start_tag($posterstyle);
						echo "$l_poster: ".display_encoded($tmprow["poster"]);
						if($hotnewsnohtmlformatting==0)
							echo get_end_tag($posterstyle);
						echo "</font></td></tr>";
					}
					echo "</table></td></tr>";
				}
			}
	}
	$sql2 = "select * from ".$tableprefix."_data where category=".$myrow["catnr"]." and linknewsnr=0 ";
	if($separatebylang==1)
	{
		$sql2.="and lang='$act_lang' ";
	}
	if($maxage>0)
		$sql2.= "and date >= date_sub('$actdate', INTERVAL $maxage DAY) ";
	$sql2.="and date<='$actdate' ";
	switch($sortorder)
	{
		case 0:
			$sql2.=" order by date desc";
			break;
		case 1:
			$sql2.=" order by date asc";
			break;
		case 2:
			$sql2.=" order by heading asc";
			break;
		case 3:
			$sql2.=" order by heading desc";
			break;
	}
	if(!$dataresult = mysql_query($sql2, $db))
		die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
	$numentries=mysql_numrows($dataresult);
	$sql2 .=" limit $numhotnews";
	if(!$dataresult = mysql_query($sql2, $db))
		die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
	$numdisplayed=mysql_numrows($dataresult);
	while($datarow=mysql_fetch_array($dataresult))
	{
		echo "<tr>";
		if($hotnewsicons==1)
		{
			echo "<td width=\"2%\" height=\"100%\" align=\"center\" bgcolor=\"$contentbgcolor\">";
			if($datarow["headingicon"])
			echo "<img src=\"$url_icons/".$datarow["headingicon"]."\" border=\"0\" align=\"middle\"> ";
			echo "</td>";
		}
		echo "<td align=\"center\"><table class=\"newsbox\" width=\"100%\" align=\"center\" bgcolor=\"$contentbgcolor\" cellspacing=\"0\" cellpadding=\"0\">";
		list($mydate,$mytime)=explode(" ",$datarow["date"]);
		list($year, $month, $day) = explode("-", $mydate);
		list($hour, $min, $sec) = explode(":",$mytime);
		if($month>0)
		{
			$displaytime=mktime($hour,$min,$sec,$month,$day,$year);
			$displaytime=transposetime($displaytime,$servertimezone,$displaytimezone);
			$displaydate=date($dateformat,$displaytime);
		}
		else
			$displaydate="";
		echo "<tr><td align=\"left\" bgcolor=\"$timestampbgcolor\">";
		echo "<font face=\"$timestampfont\" size=\"$timestampfontsize\" color=\"$timestampfontcolor\">";
		echo get_start_tag($timestampstyle);
		echo $displaydate;
		echo get_end_tag($timestampstyle);
		if(isset($lastvisitdate))
		{
			list($mydate,$mytime)=explode(" ",$datarow["date"]);
			list($year, $month, $day) = explode("-", $mydate);
			list($hour, $min, $sec) = explode(":",$mytime);
			$thisentrydate=mktime($hour,$min,$sec,$month,$day,$year);
			if($thisentrydate>=$lastvisitdate)
				echo "&nbsp;&nbsp;<img src=\"$url_gfx/$newentrypic\" border=\"0\" align=\"absmiddle\">";
		}
		echo "</font></td>";
		$srcscript=$url_simpnews."/news2.php";
		if(($allowcomments==1) && ($datarow["allowcomments"]==1) && ($hotnewscommentslink==1))
		{
			$tempsql="select * from ".$tableprefix."_comments where entryref=".$datarow["newsnr"];
			if(!$tempresult = mysql_query($tempsql, $db))
				die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
			$numcomments=mysql_num_rows($tempresult);
			if($numcomments>0)
			{
				echo "<td align=\"right\" bgcolor=\"$timestampbgcolor\" width=\"10%\" valign=\"top\">";
				echo "<font face=\"$timestampfont\" size=\"$timestampfontsize\" color=\"$timestampfontcolor\">";
				if($commentsinline==0)
					$commentlink=$url_simpnews."/comment.php?mode=display&amp;$langvar=$act_lang&amp;entryref=".$datarow["newsnr"];
				else
				{
					if($usehnlinkdest)
						$commentlink=$hnlinkdest;
					else
						$commentlink=$url_simpnews."/singlenews.php";
					$commentlink.="?$langvar=$act_lang&layout=$layout&category=".$datarow["category"]."&newsnr=".$datarow["newsnr"]."&srcscript=$srcscript";
				}
				echo "<a class=\"commentlink\" href=\"$commentlink\">";
				if($commentspic)
					echo "<img style=\"margin: 1px\" src=\"".$url_gfx."/$commentspic\" border=\"0\" alt=\"$l_comments: $numcomments\" title=\"$l_comments: $numcomments\">";
				else
					echo "$l_comments:&nbsp;$numcomments";
				echo "</a>&nbsp;</font></td>";
			}
		}
		echo "</tr>";
		if(strlen($datarow["heading"])>0)
		{
			echo "<tr bgcolor=\"$newsheadingbgcolor\"><td align=\"left\">";
			echo "<font face=\"$newsheadingfont\" size=\"$newsheadingfontsize\" color=\"$newsheadingfontcolor\">";
			$displayheading=$datarow["heading"];
			if($hotnewsnohtmlformatting==1)
				$displayheading=strip_tags($displayheading);
			$displayheading=display_encoded($displayheading);
			$displayheading=undo_htmlspecialchars($displayheading);
			if($hotnewsmaxchars<1)
			{
				$srcscript=$url_simpnews."/news2.php";
				if($usehnlinkdest==1)
					$linkdest="$hnlinkdest?$langvar=$act_lang&layout=$layout&category=-1&newsnr=".$datarow["newsnr"]."&srcscript=$srcscript";
				else
					$linkdest="$url_simpnews/singlenews.php?$langvar=$act_lang&layout=$layout&category=-1&newsnr=".$datarow["newsnr"]."&srcscript=$srcscript";
				echo " <a href=\"$linkdest\"";
				if($hotnewstarget)
					echo " target=\"$hotnewstarget\"";
				echo ">";
			}
			if($hotnewsnohtmlformatting==0)
				echo get_start_tag($newsheadingstyle);
			echo $displayheading;
			if($hotnewsnohtmlformatting==0)
				echo get_end_tag($newsheadingstyle);
			echo "</font></td></tr>";
		}
		if($hotnewsmaxchars!=0)
		{
			echo "<tr bgcolor=\"$contentbgcolor\"><td align=\"left\">";
			echo "<font face=\"$contentfont\" size=\"$contentfontsize\" color=\"$contentfontcolor\">";
			$displaytext=stripslashes($datarow["text"]);
			$displaytext = undo_htmlspecialchars($displaytext);
			if(($hotnewsmaxchars>0) && strlen($displaytext)>$hotnewsmaxchars)
			{
				$displaytext=str_replace("<BR>"," ",$displaytext);
				$displaytext=undo_htmlentities($displaytext);
				$displaytext=strip_tags($displaytext);
				$displaytext=substr($displaytext,0,$hotnewsmaxchars);
				$displaytext=display_encoded($displaytext);
				$srcscript=$url_simpnews."/news2.php";
				if($usehnlinkdest==1)
					$linkdest="$hnlinkdest?$langvar=$act_lang&layout=$layout&category=-1&newsnr=".$datarow["newsnr"]."&srcscript=$srcscript";
				else
					$linkdest="$url_simpnews/singlenews.php?$langvar=$act_lang&layout=$layout&category=-1&newsnr=".$datarow["newsnr"]."&srcscript=$srcscript";
				$displaytext.=" <a href=\"$linkdest\"";
				if($hotnewstarget)
					$displaytext.=" target=\"$hotnewstarget\"";
				$displaytext.=">[...]</a>";
			} else if($hotnewsnohtmlformatting==1)
				$displaytext=strip_tags($displaytext);
			echo $displaytext."</font></td></tr>";
		}
		if($hotnewsdisplayposter && (strlen($datarow["poster"])>0))
		{
			echo "<tr bgcolor=\"$posterbgcolor\"><td align=\"left\">";
			echo "<font face=\"$posterfont\" size=\"$posterfontsize\" color=\"$posterfontcolor\">";
			if($hotnewsnohtmlformatting==0)
				echo get_start_tag($posterstyle);
			echo "$l_poster: ".display_encoded($datarow["poster"]);
			if($hotnewsnohtmlformatting==0)
				echo get_end_tag($posterstyle);
			echo "</font></td></tr>";
		}
		echo "</table></td></tr>";
	}
	if(($numdisplayed==0) && !$announceavail)
	{
		echo "<tr bgcolor=\"$contentbgcolor\"><td align=\"center\" colspan=\"2\">";
		echo "<font face=\"$contentfont\" size=\"$contentfontsize\" color=\"$contentfontcolor\">";
		echo $l_nonewnews;
		echo "</font></td></tr>";
	}
	if($numdisplayed<$numentries)
	{
?>
<tr bgcolor="<?php echo $headingbgcolor?>"><td align="right" colspan="2">
<font face="<?php echo $contentfont?>" size="<?php echo $contentfontsize?>" color="<?php echo $contentfontcolor?>">
<a href="<?php echo $url_simpnews?>/news2.php?<?php echo "$langvar=$act_lang"?>&amp;layout=<?php echo $layout?>&amp;category=<?php echo $myrow["catnr"]?>" target="<?php echo $hotnews2target?>">
<?php echo "[$l_morenews]"?></a></font></td></tr>
<?php
	}
	echo "<tr bgcolor=\"$bordercolor\"><td colspan=\"2\">";
	echo "<img src=\"$url_gfx/space.gif\" border=\"0\" width=\"1\" height=\"1\">";
	echo "</td></tr>";
}
echo "</td></tr></table></td></tr></table>";
include($path_simpnews.'/includes/footer2.inc');
?>
