<?php
/***************************************************************************
 * (c)2002-2005 Boesch IT-Consulting (info@boesch-it.de)
 ***************************************************************************/
$path_simpnews=dirname(__FILE__);
require_once($path_simpnews.'/config.php');
require_once($path_simpnews.'/functions.php');
if(!isset($sortorder))
	$sortorder=0;
if(!isset($category))
	$category=0;
if(!isset($$langvar) || !$$langvar)
	$act_lang=$default_lang;
else
	$act_lang=$$langvar;
include($path_simpnews.'/language/lang_'.$act_lang.'.php');
include($path_simpnews.'/includes/get_settings.inc');
include($path_simpnews.'/includes/styles2.inc');
setlocale(LC_TIME, $def_locales[$act_lang]);
if(isset($limitentries))
	$numhotnews=$limitentries;
if(!isset($maxannounce))
	$maxannounce=0;
if($hn_linklayout)
	$layout=$hn_linklayout;
$actdate = date("Y-m-d 23:59:59");
?>
<!-- code generated by SimpNews begin -->
<table width="<?php echo $TableWidth2?>" border="0" CELLPADDING="1" CELLSPACING="0" ALIGN="<?php echo $tblalign?>" class="sntable">
<tr><TD BGCOLOR="<?php echo $bordercolor?>">
<TABLE BORDER="0" CELLPADDING="1" CELLSPACING="1" WIDTH="100%">
<?php
if((strlen($heading)>0) && ($hotscriptsnoheading==0))
{
?>
<TR BGCOLOR="<?php echo $headingbgcolor?>" ALIGN="CENTER">
<TD ALIGN="CENTER" VALIGN="MIDDLE" colspan="2"><font face="<?php echo $headingfont?>" size="<?php echo $headingfontsize?>" color="<?php echo $headingfontcolor?>"><b><?php echo $heading?></b></font></td></tr>
<?php
}
$sql = "select * from ".$tableprefix."_misc";
if(!$result = mysql_query($sql, $db)) {
    die("<tr class=\"errorrow\"><td>Could not connect to the database.");
}
if ($myrow = mysql_fetch_array($result))
{
	if($myrow["shutdown"]==1)
	{
?>
</tr></table></td></tr>
<tr><TD BGCOLOR="<?php echo $bordercolor?>">
<TABLE BORDER="0" CELLPADDING="1" CELLSPACING="1" WIDTH="100%">
<tr BGCOLOR="<?php echo $contentbgcolor?>" ALIGN="CENTER">
<TD ALIGN="CENTER" VALIGN="MIDDLE" colspan="2"><font face="<?php echo $contentfont?>" size="<?php echo $contentfontsize?>" color="<?php echo $contentfontcolor?>">
<?php
		$shutdowntext=stripslashes($myrow["shutdowntext"]);
		$shutdowntext = undo_htmlspecialchars($shutdowntext);
		echo $shutdowntext;
		echo "</font></td></tr></table></td></tr></table>";
?>
</td></tr></table>
<?php
		include($path_simpnews.'/includes/footer2.inc');
		echo "</body></html>";
		exit;
	}
}
$announceavail=false;
if(bittst($announceoptions,BIT_12))
{
		$acttime=transposetime(time(),$servertimezone,$displaytimezone);
		$tmpsql = "select * from ".$tableprefix."_announce where (expiredate>=$acttime or expiredate=0)  and (firstdate<=$acttime or firstdate=0)";
		if($separatebylang==1)
			$tmpsql.="and lang='$act_lang' ";
		if($maxage>0)
			$tmpsql.= "and date >= date_sub('$actdate', INTERVAL $maxage DAY) ";
		if($category>0)
			$tmpsql.= "and (category='$category' or category=0)";
		else if($category==0)
			$tmpsql.= "and category=0";
		switch($sortorder)
		{
			case 0:
				$tmpsql.=" order by date desc";
				break;
			case 1:
				$tmpsql.=" order by date asc";
				break;
			case 2:
				$tmpsql.=" order by heading asc";
				break;
			case 3:
				$tmpsql.=" order by heading desc";
				break;
		}
		if($maxannounce>0)
			$tmpsql.= " limit $maxannounce";
		else
			$tmpsql .=" limit $numhotnews";
		if(!$tmpresult = mysql_query($tmpsql, $db))
		    die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
		if(mysql_num_rows($tmpresult)>0)
		{
			$announceavail=true;
			while($tmprow=mysql_fetch_array($tmpresult))
			{
				echo "<tr><td align=\"right\" width=\"15%\" bgcolor=\"$timestampbgcolor\">";
				list($mydate,$mytime)=explode(" ",$tmprow["date"]);
				list($year, $month, $day) = explode("-", $mydate);
				list($hour, $min, $sec) = explode(":",$mytime);
				if($month>0)
				{
					$displaytime=mktime($hour,$min,$sec,$month,$day,$year);
					$displaytime=transposetime($displaytime,$servertimezone,$displaytimezone);
					$displaydate=strftime($news4dateformat,$displaytime);
				}
				else
					$displaydate="";
				echo "<font face=\"$timestampfont\" size=\"$timestampfontsize\" color=\"$timestampfontcolor\">";
				if($tmprow["category"]==0)
					echo "<img src=\"$url_gfx/$gannouncepic\" border=\"0\" align=\"absmiddle\" alt=\"$l_global_announcement\" title=\"$l_global_announcement\"> ";
				else
					echo "<img src=\"$url_gfx/$announcepic\" border=\"0\" align=\"absmiddle\" alt=\"$l_announcement\" title=\"$l_announcement\"> ";
				echo get_start_tag($timestampstyle);
				echo $displaydate;
				echo get_end_tag($timestampstyle);
				echo "</font></td>";
				if(strlen($tmprow["heading"])>0)
					$displaytext=do_htmlentities($tmprow["heading"]);
				else
				{
					$displaytext = stripslashes($tmprow["text"]);
					$displaytext = undo_htmlspecialchars($displaytext);
					$displaytext = strip_tags($displaytext);
					if(strlen($displaytext)>$news4maxchars)
						$displaytext = subwords($displaytext,$news4maxchars);
				}
				echo "<td class=\"newsbox\" bgcolor=\"$newsheadingbgcolor\" align=\"left\">";
				echo "<font face=\"$newsheadingfont\" size=\"$hn_newsheadingfontsize\" color=\"$newsheadingfontcolor\">";
				if($tmprow["tickerurl"])
					$linkdest=$tmprow["tickerurl"];
				else if($usehnlinkdest==1)
					$linkdest="$hnlinkdestan?$langvar=$act_lang&layout=$layout&category=$category&announcenr=".$tmprow["entrynr"];
				else
					$linkdest="$url_simpnews/announce.php?$langvar=$act_lang&layout=$layout&category=$category&announcenr=".$tmprow["entrynr"];
				echo "<a title=\"$l_showentry\" class=\"newslink\" href=\"$linkdest\"";
				if($hotnewstarget)
					echo " target=\"$hotnewstarget\"";
				echo ">";
				echo $displaytext;
				echo "</a></font></td></tr>";
			}
		}
}
$sql = "select * from ".$tableprefix."_data ";
if($category>=0)
	$sql.= "where category='$category' ";
else
{
	$sql.="where linknewsnr=0 ";
	$tmpsql="select * from ".$tableprefix."_categories where hideintotallist=1";
	if(!$tmpresult = mysql_query($tmpsql, $db))
	    die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
	while($tmprow=mysql_fetch_array($tmpresult))
		$sql.="and category!=".$tmprow["catnr"]." ";
}
if($separatebylang==1)
	$sql.="and lang='$act_lang' ";
if($maxage>0)
	$sql.= "and date >= date_sub('$actdate', INTERVAL $maxage DAY) ";
if($showfuturenews==0)
	$sql.="and date<='$actdate' ";
switch($sortorder)
{
	case 0:
		$sql.=" order by date desc";
		break;
	case 1:
		$sql.=" order by date asc";
		break;
	case 2:
		$sql.=" order by heading asc";
		break;
	case 3:
		$sql.=" order by heading desc";
		break;
}
if(!$result = mysql_query($sql, $db))
    die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
$numentries=mysql_numrows($result);
$sql .=" limit $numhotnews";
if(!$result = mysql_query($sql, $db))
	die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
if(!$myrow=mysql_fetch_array($result))
{
	if(!$announceavail)
	{
		echo "<tr>";
		echo "<td align=\"center\" bgcolor=\"$contentbgcolor\">";
		echo $l_nonewnews;
		echo "<font face=\"$contentfont\" size=\"$contentfontsize\" color=\"$contentfontcolor\">";
		echo "</font></td></tr>";
	}
}
else
{
do
{
	if($myrow["linknewsnr"]==0)
		$entrydata=$myrow;
	else
	{
		$tmpsql="select * from ".$tableprefix."_data where newsnr=".$myrow["linknewsnr"];
		if(!$tmpresult = mysql_query($tmpsql, $db))
			die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
		if(!$tmprow=mysql_fetch_array($tmpresult))
			die("<tr class=\"errorrow\"><td>Unable to get data");
		$entrydata=$tmprow;
	}
	echo "<tr><td align=\"right\" width=\"15%\" bgcolor=\"$timestampbgcolor\">";
	list($mydate,$mytime)=explode(" ",$myrow["date"]);
	list($year, $month, $day) = explode("-", $mydate);
	list($hour, $min, $sec) = explode(":",$mytime);
	if($month>0)
	{
		$displaytime=mktime($hour,$min,$sec,$month,$day,$year);
		$displaytime=transposetime($displaytime,$servertimezone,$displaytimezone);
		$displaydate=strftime($news4dateformat,$displaytime);
	}
	else
		$displaydate="";
	echo "<font face=\"$timestampfont\" size=\"$timestampfontsize\" color=\"$timestampfontcolor\">";
	echo get_start_tag($timestampstyle);
	echo $displaydate;
	echo get_end_tag($timestampstyle);
	echo "</font></td>";
	if(strlen($entrydata["heading"])>0)
		$displaytext=display_encoded($entrydata["heading"]);
	else
	{
		$displaytext = stripslashes($entrydata["text"]);
		$displaytext = undo_htmlspecialchars($displaytext);
		$displaytext = strip_tags($displaytext);
		if(strlen($displaytext)>$news4maxchars)
			$displaytext = subwords($displaytext,$news4maxchars);
	}
	echo "<td class=\"newsbox\" bgcolor=\"$newsheadingbgcolor\" align=\"left\">";
	echo "<font face=\"$newsheadingfont\" size=\"$hn_newsheadingfontsize\" color=\"$newsheadingfontcolor\">";
	if($entrydata["tickerurl"])
		$linkdest=$entrydata["tickerurl"];
	else
	{
		$srcscript=$url_simpnews."/news4.php";
		if($usehnlinkdest==1)
			$linkdest="$hnlinkdest?$langvar=$act_lang&layout=$layout&category=$category&newsnr=".$entrydata["newsnr"]."&srcscript=$srcscript";
		else
			$linkdest=$url_simpnews."/singlenews.php?$langvar=$act_lang&layout=$layout&category=$category&newsnr=".$entrydata["newsnr"]."&srcscript=$srcscript";
	}
	if($news4useddlink)
	{
		$tempsql="select f.filename, f.filesize, f.mimetype, na.* from ".$tableprefix."_news_attachs na, ".$tableprefix."_files f where f.entrynr=na.attachnr and na.newsnr=".$entrydata["newsnr"]." order by na.entrynr asc";
		if(!$tempresult=mysql_query($tempsql,$db))
		    die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
		if($temprow=mysql_fetch_array($tempresult))
			$linkdest=$url_simpnews."/sndownload.php?entrynr=".$temprow["attachnr"];
	}
	echo "<a title=\"$l_showentry\" class=\"newslink\" href=\"$linkdest\"";
	if($hotnewstarget)
		echo " target=\"$hotnewstarget\"";
	echo ">";
	echo $displaytext;
	echo "</a></font></td></tr>";
}while($myrow=mysql_fetch_array($result));
}
echo "</table></td></tr></table>";
include($path_simpnews.'/includes/footer2.inc');
?>