<?php
/***************************************************************************
 * (c)2002-2005 Boesch IT-Consulting (info@boesch-it.de)
 ***************************************************************************/
$path_simpnews=dirname(__FILE__);
require_once($path_simpnews.'/config.php');
require_once($path_simpnews.'/functions.php');
if(!isset($sortorder))
	$sortorder=0;
if(!isset($$langvar) || !$$langvar)
	$act_lang=$default_lang;
else
	$act_lang=$$langvar;
include($path_simpnews.'/language/lang_'.$act_lang.'.php');
include($path_simpnews.'/includes/get_settings.inc');
include($path_simpnews.'/includes/styles2.inc');
setlocale(LC_TIME, $def_locales[$act_lang]);
$announceavail=false;
if(!isset($maxannounce))
	$maxannounce=0;
if($hn_linklayout)
	$layout=$hn_linklayout;
$actdate = date("Y-m-d 23:59:59");
?>
<!-- code generated by SimpNews begin -->
<table width="<?php echo $TableWidth2?>" border="0" CELLPADDING="1" CELLSPACING="0" ALIGN="<?php echo $tblalign?>" class="sntable">
<tr><TD BGCOLOR="<?php echo $bordercolor?>">
<TABLE BORDER="0" CELLPADDING="1" CELLSPACING="1" WIDTH="100%">
<?php
if((strlen($heading)>0) && ($hotscriptsnoheading==0))
{
?>
<TR BGCOLOR="<?php echo $headingbgcolor?>" ALIGN="CENTER">
<TD ALIGN="CENTER" VALIGN="MIDDLE" colspan="2"><font face="<?php echo $headingfont?>" size="<?php echo $headingfontsize?>" color="<?php echo $headingfontcolor?>"><b><?php echo $heading?></b></font></td></tr>
<?php
}
$sql = "select * from ".$tableprefix."_misc";
if(!$result = mysql_query($sql, $db)) {
    die("<tr class=\"errorrow\"><td>Could not connect to the database.");
}
if ($myrow = mysql_fetch_array($result))
{
	if($myrow["shutdown"]==1)
	{
?>
</tr></table></td></tr>
<tr><TD BGCOLOR="<?php echo $bordercolor?>">
<TABLE BORDER="0" CELLPADDING="1" CELLSPACING="1" WIDTH="100%">
<tr BGCOLOR="<?php echo $contentbgcolor?>" ALIGN="CENTER">
<TD ALIGN="CENTER" VALIGN="MIDDLE" colspan="2"><font face="<?php echo $contentfont?>" size="<?php echo $contentfontsize?>" color="<?php echo $contentfontcolor?>">
<?php
		$shutdowntext=stripslashes($myrow["shutdowntext"]);
		$shutdowntext = undo_htmlspecialchars($shutdowntext);
		echo $shutdowntext;
		echo "</font></td></tr></table></td></tr></table>";
?>
</td></tr></table>
<?php
		include($path_simpnews.'/includes/footer2.inc');
		echo "</body></html>";
		exit;
	}
}
if(bittst($announceoptions,BIT_14))
{
	$acttime=transposetime(time(),$servertimezone,$displaytimezone);
	$tmpsql = "select an.* from ".$tableprefix."_announce an, ".$tableprefix."_hn6cats hn6 where (an.expiredate>=$acttime or an.expiredate=0)  and (an.firstdate<=$acttime or an.firstdate=0) and (an.category=hn6.catnr or an.category=0) and hn6.catnr!=0";
	if($separatebylang==1)
		$tmpsql.=" and an.lang='$act_lang'";
	switch($sortorder)
	{
		case 0:
			$tmpsql.=" order by an.date desc";
			break;
		case 1:
			$tmpsql.=" order by an.date asc";
			break;
		case 2:
			$tmpsql.=" order by an.heading asc";
			break;
		case 3:
			$tmpsql.=" order by an.heading desc";
			break;
	}
	if($maxannounce>0)
		$tmpsql.=" limit $maxannounce";
	else
		$tmpsql.=" limit $anhn6numentries";
	if(!$tmpresult = mysql_query($tmpsql, $db))
		die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
	if(mysql_num_rows($tmpresult)>0)
	{
		$announceavail=true;
		while($tmprow=mysql_fetch_array($tmpresult))
		{
			echo "<tr><td align=\"right\" width=\"15%\" bgcolor=\"$timestampbgcolor\">";
			list($mydate,$mytime)=explode(" ",$tmprow["date"]);
			list($year, $month, $day) = explode("-", $mydate);
			list($hour, $min, $sec) = explode(":",$mytime);
			if($month>0)
			{
				$displaytime=mktime($hour,$min,$sec,$month,$day,$year);
				$displaytime=transposetime($displaytime,$servertimezone,$displaytimezone);
				$displaydate=strftime($news4dateformat,$displaytime);
			}
			else
				$displaydate="";
			echo "<font face=\"$timestampfont\" size=\"$timestampfontsize\" color=\"$timestampfontcolor\">";
			if($tmprow["category"]==0)
				echo "<img src=\"$url_gfx/$gannouncepic\" border=\"0\" align=\"absmiddle\" alt=\"$l_global_announcement\" title=\"$l_global_announcement\"> ";
			else
				echo "<img src=\"$url_gfx/$announcepic\" border=\"0\" align=\"absmiddle\" alt=\"$l_announcement\" title=\"$l_announcement\"> ";
			echo get_start_tag($timestampstyle);
			echo $displaydate;
			echo get_end_tag($timestampstyle);
			echo "</font></td>";
			if(strlen($tmprow["heading"])>0)
				$displaytext=display_encoded($tmprow["heading"]);
			else
			{
				$displaytext = stripslashes($tmprow["text"]);
				$displaytext = undo_htmlspecialchars($displaytext);
				$displaytext = strip_tags($displaytext);
				if(strlen($displaytext)>$news4maxchars)
					$displaytext = subwords($displaytext,$news4maxchars);
			}
			echo "<td class=\"newsbox\" bgcolor=\"$newsheadingbgcolor\" align=\"left\">";
			echo "<font face=\"$newsheadingfont\" size=\"$hn_newsheadingfontsize\" color=\"$newsheadingfontcolor\">";
			if($tmprow["tickerurl"])
				$linkdest=$tmprow["tickerurl"];
			else if($usehnlinkdest==1)
				$linkdest="$hnlinkdestan?$langvar=$act_lang&layout=$layout&category=".$tmprow["category"]."&announcenr=".$tmprow["entrynr"];
			else
				$linkdest="$url_simpnews/announce.php?$langvar=$act_lang&layout=$layout&category=".$tmprow["category"]."&announcenr=".$tmprow["entrynr"];
			echo "<a title=\"$l_showentry\" class=\"newslink\" href=\"$linkdest\"";
			if($hotnews6target)
				echo " target=\"$hotnews6target\"";
			echo ">";
			echo $displaytext;
			echo "</a></font></td></tr>";
		}
	}
}
$sql = "select dat.* from ".$tableprefix."_data dat, ".$tableprefix."_hn6cats cat where dat.category=cat.catnr";
if($separatebylang==1)
	$sql.=" and dat.lang='$act_lang'";
$sql.=" and dat.date<='$actdate'";
switch($sortorder)
{
	case 0:
		$sql.=" order by dat.date desc";
		break;
	case 1:
		$sql.=" order by dat.date asc";
		break;
	case 2:
		$sql.=" order by dat.heading asc";
		break;
	case 3:
		$sql.=" order by dat.heading desc";
		break;
}
$sql.=" limit $hn6_numentries";
if(!$result = mysql_query($sql, $db))
	die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
if(!$myrow=mysql_fetch_array($result))
{
	if(!$announceavail)
	{
		echo "<tr>";
		echo "<td align=\"center\" bgcolor=\"$contentbgcolor\">";
		echo $l_nonewnews;
		echo "<font face=\"$contentfont\" size=\"$contentfontsize\" color=\"$contentfontcolor\">";
		echo "</font></td></tr>";
	}
}
else
{
	do
	{
		if($myrow["linknewsnr"]==0)
			$entrydata=$myrow;
		else
		{
			$tmpsql="select * from ".$tableprefix."_data where newsnr=".$myrow["linknewsnr"];
			if(!$tmpresult = mysql_query($tmpsql, $db))
				die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
			if(!$tmprow=mysql_fetch_array($tmpresult))
				die("<tr class=\"errorrow\"><td>Unable to get data");
			$entrydata=$tmprow;
		}
		echo "<tr><td align=\"right\" width=\"15%\" bgcolor=\"$timestampbgcolor\">";
		list($mydate,$mytime)=explode(" ",$myrow["date"]);
		list($year, $month, $day) = explode("-", $mydate);
		list($hour, $min, $sec) = explode(":",$mytime);
		if($month>0)
		{
			$displaytime=mktime($hour,$min,$sec,$month,$day,$year);
			$displaytime=transposetime($displaytime,$servertimezone,$displaytimezone);
			$displaydate=strftime($news4dateformat,$displaytime);
		}
		else
			$displaydate="";
		echo "<font face=\"$timestampfont\" size=\"$timestampfontsize\" color=\"$timestampfontcolor\">";
		echo get_start_tag($timestampstyle);
		echo $displaydate;
		echo get_end_tag($timestampstyle);
		if(isset($lastvisitdate))
		{
			list($mydate,$mytime)=explode(" ",$myrow["date"]);
			list($year, $month, $day) = explode("-", $mydate);
			list($hour, $min, $sec) = explode(":",$mytime);
			$thisentrydate=mktime($hour,$min,$sec,$month,$day,$year);
			if($thisentrydate>=$lastvisitdate)
				echo "&nbsp;&nbsp;<img src=\"$url_gfx/$newentrypic\" border=\"0\" align=\"absmiddle\">";
		}
		echo "</font></td>";
		if(strlen($entrydata["heading"])>0)
			$displaytext=display_encoded($entrydata["heading"]);
		else
		{
			$displaytext = stripslashes($entrydata["text"]);
			$displaytext = undo_htmlspecialchars($displaytext);
			$displaytext = strip_tags($displaytext);
			if(strlen($displaytext)>$news4maxchars)
				$displaytext = subwords($displaytext,$news4maxchars);
		}
		echo "<td class=\"newsbox\" bgcolor=\"$newsheadingbgcolor\" align=\"left\">";
		echo "<font face=\"$newsheadingfont\" size=\"$hn_newsheadingfontsize\" color=\"$newsheadingfontcolor\">";
		if($entrydata["tickerurl"])
			$linkdest=$entrydata["tickerurl"];
		else
		{
			$srcscript=$url_simpnews."/news4.php";
			if($usehnlinkdest==1)
				$linkdest="$hnlinkdest?$langvar=$act_lang&layout=$layout&category=".$entrydata["category"]."&newsnr=".$entrydata["newsnr"]."&srcscript=$srcscript";
			else
				$linkdest=$url_simpnews."/singlenews.php?$langvar=$act_lang&layout=$layout&category=".$entrydata["category"]."&newsnr=".$entrydata["newsnr"]."&srcscript=$srcscript";
		}
		if($hotnews7useddlink)
		{
			$tempsql="select f.filename, f.filesize, f.mimetype, na.* from ".$tableprefix."_news_attachs na, ".$tableprefix."_files f where f.entrynr=na.attachnr and na.newsnr=".$entrydata["newsnr"]." order by na.entrynr asc";
			if(!$tempresult=mysql_query($tempsql,$db))
				die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
			if($temprow=mysql_fetch_array($tempresult))
				$linkdest=$url_simpnews."/sndownload.php?entrynr=".$temprow["attachnr"];
		}
		echo "<a title=\"$l_showentry\" class=\"newslink\" href=\"$linkdest\"";
		if($hotnews6target)
			echo " target=\"$hotnews6target\"";
		echo ">";
		echo $displaytext;
		echo "</a></font></td></tr>";
	}while($myrow=mysql_fetch_array($result));
}
echo "</table></td></tr></table>";
include($path_simpnews.'/includes/footer2.inc');
?>