<?php
/***************************************************************************
 * (c)2002-2005 Boesch IT-Consulting (info@boesch-it.de)
 ***************************************************************************/
$path_simpnews=dirname(__FILE__);
require_once($path_simpnews.'/config.php');
require_once($path_simpnews.'/functions.php');
if(!isset($category))
	$category=0;
if(!isset($$langvar) || !$$langvar)
	$act_lang=$default_lang;
else
	$act_lang=$$langvar;
if(!isset($sortorder))
	$sortorder=0;
include($path_simpnews.'/language/lang_'.$act_lang.'.php');
include($path_simpnews.'/includes/get_settings.inc');
include($path_simpnews.'/includes/styles2.inc');
if(bittst($announceoptions,BIT_13))
	include_once('./includes/an_disp.inc');
setlocale(LC_TIME, $def_locales[$act_lang]);
if(isset($limitentries))
	$numhotnews=$limitentries;
if(!isset($maxannounce))
	$maxannounce=0;
if($hn_linklayout)
	$layout=$hn_linklayout;
$actdate = date("Y-m-d 23:59:59");
?>
<!-- code generated by SimpNews begin -->
<table width="<?php echo $TableWidth2?>" border="0" CELLPADDING="1" CELLSPACING="0" ALIGN="<?php echo $tblalign?>" class="sntable">
<tr><TD BGCOLOR="<?php echo $bordercolor?>">
<TABLE BORDER="0" CELLPADDING="1" CELLSPACING="1" WIDTH="100%">
<?php
if((strlen($heading)>0) && ($hotscriptsnoheading==0))
{
?>
<TR BGCOLOR="<?php echo $headingbgcolor?>" ALIGN="CENTER">
<TD ALIGN="CENTER" VALIGN="MIDDLE" colspan="2"><font face="<?php echo $headingfont?>" size="<?php echo $headingfontsize?>" color="<?php echo $headingfontcolor?>"><b><?php echo $heading?></b></font></td></tr>
<?php
}
$sql = "select * from ".$tableprefix."_misc";
if(!$result = mysql_query($sql, $db)) {
    die("<tr class=\"errorrow\"><td>Could not connect to the database.");
}
if ($myrow = mysql_fetch_array($result))
{
	if($myrow["shutdown"]==1)
	{
?>
</tr></table></td></tr>
<tr><TD BGCOLOR="<?php echo $bordercolor?>">
<TABLE BORDER="0" CELLPADDING="1" CELLSPACING="1" WIDTH="100%">
<tr BGCOLOR="<?php echo $contentbgcolor?>" ALIGN="CENTER">
<TD ALIGN="CENTER" VALIGN="MIDDLE" colspan="2"><font face="<?php echo $contentfont?>" size="<?php echo $contentfontsize?>" color="<?php echo $contentfontcolor?>">
<?php
		$shutdowntext=stripslashes($myrow["shutdowntext"]);
		$shutdowntext = undo_htmlspecialchars($shutdowntext);
		echo $shutdowntext;
		echo "</font></td></tr></table></td></tr></table>";
?>
</td></tr></table>
<?php
		include($path_simpnews.'/includes/footer2.inc');
		echo "</body></html>";
		exit;
	}
}
if(bittst($announceoptions,BIT_12) && !bittst($announceoptions,BIT_13))
{
	$acttime=transposetime(time(),$servertimezone,$displaytimezone);
	$tmpsql = "select * from ".$tableprefix."_announce where (expiredate>=$acttime or expiredate=0)  and (firstdate<=$acttime or firstdate=0)";
	if($maxage>0)
		$tmpsql.= "and date >= date_sub('$actdate', INTERVAL $maxage DAY) ";
	if($separatebylang==1)
		$tmpsql.="and lang='$act_lang' ";
	if($category>0)
		$tmpsql.= "and (category='$category' or category=0)";
	else if($category==0)
		$tmpsql.= "and category=0";
	switch($sortorder)
	{
		case 0:
			$tmpsql.=" order by date desc";
			break;
		case 1:
			$tmpsql.=" order by date asc";
			break;
		case 2:
			$tmpsql.=" order by heading asc";
			break;
		case 3:
			$tmpsql.=" order by heading desc";
			break;
	}
	if($maxannounce>0)
		$tmpsql.=" limit $maxannounce";
	else
		$tmpsql.=" limit $numhotnews";
	if(!$tmpresult = mysql_query($tmpsql, $db))
	    die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
	if(mysql_num_rows($tmpresult)>0)
	{
		$announceavail=true;
		while($tmprow=mysql_fetch_array($tmpresult))
		{
			echo "<tr>";
			list($mydate,$mytime)=explode(" ",$tmprow["date"]);
			list($year, $month, $day) = explode("-", $mydate);
			list($hour, $min, $sec) = explode(":",$mytime);
			if($month>0)
			{
				$displaytime=mktime($hour,$min,$sec,$month,$day,$year);
				$displaytime=transposetime($displaytime,$servertimezone,$displaytimezone);
				$displaydate=strftime($news5dateformat,$displaytime);
			}
			else
				$displaydate="";
			if($hotnewsicons==1)
			{
				echo "<td width=\"2%\" height=\"100%\" align=\"center\" bgcolor=\"$contentbgcolor\">";
				if($tmprow["headingicon"])
					echo "<img src=\"$url_icons/".$tmprow["headingicon"]."\" border=\"0\" align=\"middle\"> ";
				echo "</td>";
			}
			echo "<td align=\"center\"><table class=\"newsbox\" width=\"100%\" align=\"center\" bgcolor=\"$contentbgcolor\" cellspacing=\"0\" cellpadding=\"0\">";
			echo "<tr><td align=\"left\" bgcolor=\"$timestampbgcolor\">";
			echo "<font face=\"$timestampfont\" size=\"$timestampfontsize\" color=\"$timestampfontcolor\">";
			if($tmprow["category"]==0)
				echo "<img style=\"margin: 1px\" src=\"$url_gfx/$gannouncepic\" border=\"0\" align=\"absmiddle\" alt=\"$l_global_announcement\" title=\"$l_global_announcement\"> ";
			else
				echo "<img style=\"margin: 1px\" src=\"$url_gfx/$announcepic\" border=\"0\" align=\"absmiddle\" alt=\"$l_announcement\" title=\"$l_announcement\"> ";
			echo get_start_tag($timestampstyle);
			echo $displaydate;
			echo get_end_tag($timestampstyle);
			echo "</font></td></tr>";
			if(strlen($tmprow["heading"])>0)
			{
				echo "<tr bgcolor=\"$newsheadingbgcolor\"><td align=\"left\">";
				echo "<font face=\"$newsheadingfont\" size=\"$hn_newsheadingfontsize\" color=\"$newsheadingfontcolor\">";
				if(($hotnewsmaxchars<1) && ($hnnolinking==0))
				{
					if($usehnlinkdest==1)
						$linkdest="$hnlinkdestan?$langvar=$act_lang&layout=$layout&category=$category&announcenr=".$tmprow["entrynr"];
					else
						$linkdest=$url_simpnews."/announce.php?$langvar=$act_lang&layout=$layout&category=$category&announcenr=".$tmprow["entrynr"];
					echo " <a href=\"$linkdest\"";
					if($hotnewstarget)
						echo " target=\"$hotnewstarget\"";
					echo ">";
				}
				$displayheading=$tmprow["heading"];
				if($hotnewsnohtmlformatting==1)
					$displayheading=strip_tags($displayheading);
				$displayheading=do_htmlentities($displayheading);
				$displayheading=undo_htmlspecialchars($displayheading);
				if($hotnewsnohtmlformatting==0)
					echo get_start_tag($newsheadingstyle);
				echo $displayheading;
				if($hotnewsnohtmlformatting==0)
					echo get_end_tag($newsheadingstyle);
				if(($hotnewsmaxchars<1) && ($hnnolinking==0))
					echo "</a>";
				echo "</font></td></tr>";
			}
			if($hotnewsmaxchars!=0)
			{
				echo "<tr bgcolor=\"$contentbgcolor\"><td align=\"left\">";
				echo "<font face=\"$contentfont\" size=\"$contentfontsize\" color=\"$contentfontcolor\">";
				$displaytext=stripslashes($tmprow["text"]);
				$displaytext = undo_htmlspecialchars($displaytext);
				if(($hotnewsmaxchars>0) && strlen($displaytext)>$hotnewsmaxchars)
				{
					$displaytext=str_replace("<BR>"," ",$displaytext);
					$displaytext=undo_htmlentities($displaytext);
					$displaytext=strip_tags($displaytext);
					$displaytext=substr($displaytext,0,$hotnewsmaxchars);
					$displaytext=do_htmlentities($displaytext);
					if($usehnlinkdest==1)
						$linkdest="$hnlinkdestan?$langvar=$act_lang&layout=$layout&category=$category&announcenr=".$tmprow["entrynr"];
					else
						$linkdest=$url_simpnews."/announce.php?$langvar=$act_lang&layout=$layout&category=$category&announcenr=".$tmprow["entrynr"];
					$displaytext.=" <a href=\"$linkdest\"";
					if($hotnewstarget)
						$displaytext.=" target=\"$hotnewstarget\"";
					$displaytext.=">[...]</a>";
				} else if($hotnewsnohtmlformatting==1)
					strip_tags($displaytext);
				echo $displaytext."</font></td></tr>";
			}
			if($hotnewsdisplayposter && (strlen($tmprow["poster"])>0))
			{
				echo "<tr bgcolor=\"$posterbgcolor\"><td align=\"left\">";
				echo "<font face=\"$posterfont\" size=\"$posterfontsize\" color=\"$posterfontcolor\">";
				if($hotnewsnohtmlformatting==0)
					echo get_start_tag($posterstyle);
				echo "$l_poster: ".do_htmlentities($tmprow["poster"]);
				if($hotnewsnohtmlformatting==0)
					echo get_end_tag($posterstyle);
				echo "</font></td></tr>";
			}
			echo "</table></td></tr>";
		}
	}
}
$sql = "select * from ".$tableprefix."_data ";
if($category>=0)
	$sql.= "where category='$category' ";
else
{
	$sql.="where linknewsnr=0 ";
	$tmpsql="select * from ".$tableprefix."_categories where hideintotallist=1";
	if(!$tmpresult = mysql_query($tmpsql, $db))
	    die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
	while($tmprow=mysql_fetch_array($tmpresult))
		$sql.="and category!=".$tmprow["catnr"]." ";
}
if($separatebylang==1)
	$sql.="and lang='$act_lang' ";
if($maxage>0)
	$sql.= "and date >= date_sub('$actdate', INTERVAL $maxage DAY) ";
if($showfuturenews==0)
	$sql.="and date<='$actdate' ";
switch($sortorder)
{
	case 0:
		$sql.=" order by date desc";
		break;
	case 1:
		$sql.=" order by date asc";
		break;
	case 2:
		$sql.=" order by heading asc";
		break;
	case 3:
		$sql.=" order by heading desc";
		break;
}
if(!$result = mysql_query($sql, $db))
	die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
$numentries=mysql_numrows($result);
$sql .=" limit $numhotnews";
if(!$result = mysql_query($sql, $db))
	die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
$currentyear=0;
$currentmonth=0;
if(!$myrow=mysql_fetch_array($result))
{
	echo "<tr>";
	echo "<td align=\"center\" bgcolor=\"$contentbgcolor\">";
	echo $l_nonewnews;
	echo "<font face=\"$contentfont\" size=\"$contentfontsize\" color=\"$contentfontcolor\">";
	echo "</font></td></tr>";
}
else
{
	do
	{
		if($myrow["linknewsnr"]==0)
			$entrydata=$myrow;
		else
		{
			$tmpsql="select * from ".$tableprefix."_data where newsnr=".$myrow["linknewsnr"];
			if(!$tmpresult = mysql_query($tmpsql, $db))
				die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
			if(!$tmprow=mysql_fetch_array($tmpresult))
				die("<tr class=\"errorrow\"><td>Unable to get data");
			$entrydata=$tmprow;
		}
		list($mydate,$mytime)=explode(" ",$myrow["date"]);
		list($year, $month, $day) = explode("-", $mydate);
		list($hour, $min, $sec) = explode(":",$mytime);
		if($month>0)
		{
			$displaytime=mktime($hour,$min,$sec,$month,$day,$year);
			$displaytime=transposetime($displaytime,$servertimezone,$displaytimezone);
			$displaydate=strftime($news5dateformat,$displaytime);
		}
		else
			$displaydate="";
		if($currentyear!=$year)
		{
			$currentyear=$year;
			echo "<tr><td align=\"left\" colspan=\"2\" bgcolor=\"$news5yearbgcolor\">";
			echo "<font face=\"$news5yearfont\" size=\"$news5yearfontsize\" color=\"$news5yearfontcolor\">";
			echo get_start_tag($news5yearfontstyle);
			echo $year;
			echo get_end_tag($news5yearfontstyle);
			echo "</td></tr></font>";
		}
		if($currentmonth!=$month)
		{
			$currentmonth=$month;
			echo "<tr><td align=\"left\" colspan=\"2\" bgcolor=\"$news5monthbgcolor\">";
			echo "<font face=\"$news5monthfont\" size=\"$news5monthfontsize\" color=\"$news5monthfontcolor\">";
			echo get_start_tag($news5monthfontstyle);
			echo $l_monthname[$month-1];
			if($news5monthdisplayyear==1)
				echo " ".$year;
			echo get_end_tag($news5monthfontstyle);
			echo "</font></td></tr>";
			if(bittst($announceoptions,BIT_12) && bittst($announceoptions,BIT_13))
				display_announcements3($year,$month,$category, $act_lang, $layout, $maxannounce);
		}
		echo "<tr>";
		if($hotnewsicons==1)
		{
			echo "<td width=\"2%\" height=\"100%\" align=\"center\" bgcolor=\"$contentbgcolor\">";
			if($entrydata["headingicon"])
				echo "<img src=\"$url_icons/".$entrydata["headingicon"]."\" border=\"0\" align=\"middle\"> ";
			echo "</td>";
		}
		echo "<td align=\"center\"><table class=\"newsbox\" width=\"100%\" align=\"center\" bgcolor=\"$contentbgcolor\" cellspacing=\"0\" cellpadding=\"0\">";
		echo "<tr><td align=\"left\" bgcolor=\"$timestampbgcolor\">";
		echo "<font face=\"$timestampfont\" size=\"$timestampfontsize\" color=\"$timestampfontcolor\">";
		echo get_start_tag($timestampstyle);
		echo $displaydate;
		echo get_end_tag($timestampstyle);
		if(isset($lastvisitdate))
		{
			list($mydate,$mytime)=explode(" ",$myrow["date"]);
			list($year, $month, $day) = explode("-", $mydate);
			list($hour, $min, $sec) = explode(":",$mytime);
			$thisentrydate=mktime($hour,$min,$sec,$month,$day,$year);
			if($thisentrydate>=$lastvisitdate)
				echo "&nbsp;&nbsp;<img src=\"$url_gfx/$newentrypic\" border=\"0\" align=\"absmiddle\">";
		}
		echo "</font></td>";
		$srcscript=$url_simpnews."/news5.php";
		if(($allowcomments==1) && ($entrydata["allowcomments"]==1) && ($hotnewscommentslink==1))
		{
			$tempsql="select * from ".$tableprefix."_comments where entryref=".$entrydata["newsnr"];
			if(!$tempresult = mysql_query($tempsql, $db))
				die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
			$numcomments=mysql_num_rows($tempresult);
			if($numcomments>0)
			{
				echo "<td align=\"right\" bgcolor=\"$timestampbgcolor\" width=\"10%\" valign=\"top\">";
				echo "<font face=\"$timestampfont\" size=\"$timestampfontsize\" color=\"$timestampfontcolor\">";
				if($commentsinline==0)
					$commentlink=$url_simpnews."/comment.php?mode=display&amp;$langvar=$act_lang&amp;entryref=".$entrydata["newsnr"];
				else
				{
					if($usehnlinkdest)
						$commentlink=$hnlinkdest;
					else
						$commentlink=$url_simpnews."/singlenews.php";
					$commentlink.="?$langvar=$act_lang&layout=$layout&category=".$entrydata["category"]."&newsnr=".$entrydata["newsnr"]."&srcscript=$srcscript";
				}
				echo "<a class=\"commentlink\" href=\"$commentlink\">";
				if($commentspic)
					echo "<img style=\"margin: 1px\" src=\"".$url_gfx."/$commentspic\" border=\"0\" alt=\"$l_comments: $numcomments\" title=\"$l_comments: $numcomments\">";
				else
					echo "$l_comments:&nbsp;$numcomments";
				echo "</a>&nbsp;</font></td>";
			}
		}
		echo "</tr>";
		if(strlen($entrydata["heading"])>0)
		{
			echo "<tr bgcolor=\"$newsheadingbgcolor\"><td align=\"left\">";
			echo "<font face=\"$newsheadingfont\" size=\"$hn_newsheadingfontsize\" color=\"$newsheadingfontcolor\">";
			if(($hotnewsmaxchars<1) && ($hnnolinking==0))
			{
				if($usehnlinkdest==1)
					$linkdest="$hnlinkdest?$langvar=$act_lang&layout=$layout&category=$category&newsnr=".$entrydata["newsnr"]."&srcscript=$srcscript";
				else
					$linkdest=$url_simpnews."/singlenews.php?$langvar=$act_lang&layout=$layout&category=$category&newsnr=".$entrydata["newsnr"]."&srcscript=$srcscript";
				echo " <a href=\"$linkdest\"";
				if($hotnewstarget)
					echo " target=\"$hotnewstarget\"";
				echo ">";
			}
			$displayheading=$entrydata["heading"];
			if($hotnewsnohtmlformatting==1)
				$displayheading=strip_tags($displayheading);
			$displayheading=do_htmlentities($displayheading);
			$displayheading=undo_htmlspecialchars($displayheading);
			if($hotnewsnohtmlformatting==0)
				echo get_start_tag($newsheadingstyle);
			echo $displayheading;
			if($hotnewsnohtmlformatting==0)
				echo get_end_tag($newsheadingstyle);
			if(($hotnewsmaxchars<1) && ($hnnolinking==0))
				echo "</a>";
			echo "</font></td></tr>";
		}
		if($hotnewsmaxchars!=0)
		{
			echo "<tr bgcolor=\"$contentbgcolor\"><td align=\"left\">";
			echo "<font face=\"$contentfont\" size=\"$contentfontsize\" color=\"$contentfontcolor\">";
			$displaytext=stripslashes($entrydata["text"]);
			$displaytext = undo_htmlspecialchars($displaytext);
			if(($hotnewsmaxchars>0) && strlen($displaytext)>$hotnewsmaxchars)
			{
				$displaytext=str_replace("<BR>"," ",$displaytext);
				$displaytext=undo_htmlentities($displaytext);
				$displaytext=strip_tags($displaytext);
				$displaytext=substr($displaytext,0,$hotnewsmaxchars);
				$displaytext=display_encoded($displaytext);
				$srcscript=$url_simpnews."/news5.php";
				if($usehnlinkdest==1)
					$linkdest="$hnlinkdest?$langvar=$act_lang&layout=$layout&category=$category&newsnr=".$entrydata["newsnr"]."&srcscript=$srcscript";
				else
					$linkdest=$url_simpnews."/singlenews.php?$langvar=$act_lang&layout=$layout&category=$category&newsnr=".$entrydata["newsnr"]."&srcscript=$srcscript";
				$displaytext.=" <a href=\"$linkdest\"";
				if($hotnewstarget)
					$displaytext.=" target=\"$hotnewstarget\"";
				$displaytext.=">[...]</a>";
			} else if($hotnewsnohtmlformatting==1)
				strip_tags($displaytext);
			echo $displaytext."</font></td></tr>";
		}
		if($hotnewsdisplayposter && (strlen($entrydata["poster"])>0))
		{
			echo "<tr bgcolor=\"$posterbgcolor\"><td align=\"left\">";
			echo "<font face=\"$posterfont\" size=\"$posterfontsize\" color=\"$posterfontcolor\">";
			if($hotnewsnohtmlformatting==0)
				echo get_start_tag($posterstyle);
			echo "$l_poster: ".do_htmlentities($entrydata["poster"]);
			if($hotnewsnohtmlformatting==0)
				echo get_end_tag($posterstyle);
			echo "</font></td></tr>";
		}
		echo "</table></td></tr>";
	}while($myrow=mysql_fetch_array($result));
}
echo "</table></td></tr></table>";
include($path_simpnews.'/includes/footer2.inc');
?>