<?php
// If you want to provide your own header data, please place in this file.
// If you want to use the headerdata generated by SimpeNews, please delete this file.
?>

<meta http-equiv="Content-Type" content="text/html; charset=<?php echo $contentcharset?>">
<title><?php echo $pageheading?></title>
