<?php
/***************************************************************************
 * (c)2002-2004 Boesch IT-Consulting (info@boesch-it.de)
 ***************************************************************************/
$path_simpnews=dirname(__FILE__);
require_once($path_simpnews.'/config.php');
require_once($path_simpnews.'/functions.php');
if(!isset($category))
	$category=0;
if(!isset($$langvar) || !$$langvar)
	$act_lang=$default_lang;
else
	$act_lang=$$langvar;
include($path_simpnews.'/language/lang_'.$act_lang.'.php');
include($path_simpnews.'/includes/get_settings.inc');
$sql = "select * from ".$tableprefix."_misc";
if(!$result = mysql_query($sql, $db)) {
    die("Could not connect to the database.");
}
if ($myrow = mysql_fetch_array($result))
{
	if($myrow["shutdown"]==1)
	{
		include_once($path_simpnews.'/includes/styles2.inc');
?>
<table width="<?php echo $TableWidth?>" border="0" CELLPADDING="1" CELLSPACING="0" ALIGN="<?php echo $tblalign?>" class="sntable">
<tr><TD BGCOLOR="<?php echo $bordercolor?>">
<TABLE BORDER="0" CELLPADDING="1" CELLSPACING="1" WIDTH="100%">
<?php
if(strlen($heading)>0)
{
?>
<TR BGCOLOR="<?php echo $headingbgcolor?>" ALIGN="CENTER">
<TD ALIGN="CENTER" VALIGN="MIDDLE" colspan="2"><font face="<?php echo $headingfont?>" size="<?php echo $headingfontsize?>" color="<?php echo $headingfontcolor?>"><b><?php echo $heading?></b></font></td></tr>
<?php
}
?>
</tr></table></td></tr>
<tr><TD BGCOLOR="<?php echo $bordercolor?>">
<TABLE BORDER="0" CELLPADDING="1" CELLSPACING="1" WIDTH="100%">
<tr BGCOLOR="<?php echo $contentbgcolor?>" ALIGN="CENTER">
<TD ALIGN="CENTER" VALIGN="MIDDLE" colspan="2"><font face="<?php echo $contentfont?>" size="<?php echo $contentfontsize?>" color="<?php echo $contentfontcolor?>">
<?php
		$shutdowntext=stripslashes($myrow["shutdowntext"]);
		$shutdowntext = undo_htmlspecialchars($shutdowntext);
		echo $shutdowntext;
		echo "</font></td></tr></table></td></tr></table>";
		echo "</td></tr></table>";
		include($path_simpnews.'/includes/footer2.inc');
		echo "</body></html>";
		exit;
	}
}
if(isset($download))
{
	header('Content-Type: application/octetstream');
	header('Content-Disposition: filename="newsticker_'.$act_lang.'.ht"');
}
if(!isset($limitentries))
	$limitentries=$newstickermaxentries;
if(!isset($limitdays))
	$limitdays=$newstickermaxdays;
$datasourceurl="$url_simpnews/newsticker2.php?limitentries=$limitentries&limitdays=$limitdays&$langvar=$act_lang&layout=$layout&category=$category";
if(isset($maxannounce))
	$datasourceurl.="&maxannounce=$maxannounce";
?>
<!-- code generated by SimpNews begin -->
<applet archive="<?php echo $url_simpnews?>/applet/ticker.jar"
	codebase="<?php echo $url_simpnews?>/applet"
	code="de.boesch_it.simpnews.ticker.NewsTicker"
	width="<?php echo $newstickerwidth?>"
	height="<?php echo $newstickerheight?>">
<param name="datasource" value="<?php echo $datasourceurl?>">
<param name="separator" value="<?php echo $sep_char?>">
<param name="scrollspeed" value="<?php echo $newstickerscrollspeed?>">
<param name="scrolldelay" value="<?php echo $newstickerscrolldelay?>">
<?php
	if(isset($dodebug))
		echo "<param name=\"debugmode\" value=\"on\">";
	$bgcolor=str_replace("#","",$newstickerbgcolor);
	$bgcolor=hexdec($bgcolor);
	$fontcolor=str_replace("#","",$newstickerfontcolor);
	$fontcolor=hexdec($fontcolor);
	$highlightcolor=str_replace("#","",$newstickerhighlightcolor);
	$highlightcolor=hexdec($highlightcolor);
?>
<param name="bgcolor" value="<?php echo $bgcolor?>">
<param name="Font1" value="<?php echo $newstickerfont?>, <?php echo $newstickerfontsize?>, 0, <?php echo $fontcolor?>">
<param name="Font2" value="<?php echo $newstickerfont?>, <?php echo $newstickerfontsize?>, 0, <?php echo $highlightcolor?>">
</applet>
<!-- code generated by SimpNews end -->
