<?php
/***************************************************************************
 * (c)2002-2004 Boesch IT-Consulting (info@boesch-it.de)
 ***************************************************************************/
$path_simpnews=dirname(__FILE__);
require_once($path_simpnews.'/config.php');
require_once($path_simpnews.'/functions.php');
if(!isset($category))
	$category=0;
if(!isset($$langvar) || !$$langvar)
	$act_lang=$default_lang;
else
	$act_lang=$$langvar;
include($path_simpnews.'/language/lang_'.$act_lang.'.php');
include($path_simpnews.'/includes/get_settings.inc');
$sql = "select * from ".$tableprefix."_misc";
if(!$result = mysql_query($sql, $db)) {
    die("Could not connect to the database.");
}
if ($myrow = mysql_fetch_array($result))
{
	if($myrow["shutdown"]==1)
	{
		include_once($path_simpnews.'/includes/styles2.inc');
?>
<table width="<?php echo $TableWidth?>" border="0" CELLPADDING="1" CELLSPACING="0" ALIGN="<?php echo $tblalign?>" class="sntable">
<tr><TD BGCOLOR="<?php echo $bordercolor?>">
<TABLE BORDER="0" CELLPADDING="1" CELLSPACING="1" WIDTH="100%">
<?php
if(strlen($heading)>0)
{
?>
<TR BGCOLOR="<?php echo $headingbgcolor?>" ALIGN="CENTER">
<TD ALIGN="CENTER" VALIGN="MIDDLE" colspan="2"><font face="<?php echo $headingfont?>" size="<?php echo $headingfontsize?>" color="<?php echo $headingfontcolor?>"><b><?php echo $heading?></b></font></td></tr>
<?php
}
?>
</tr></table></td></tr>
<tr><TD BGCOLOR="<?php echo $bordercolor?>">
<TABLE BORDER="0" CELLPADDING="1" CELLSPACING="1" WIDTH="100%">
<tr BGCOLOR="<?php echo $contentbgcolor?>" ALIGN="CENTER">
<TD ALIGN="CENTER" VALIGN="MIDDLE" colspan="2"><font face="<?php echo $contentfont?>" size="<?php echo $contentfontsize?>" color="<?php echo $contentfontcolor?>">
<?php
		$shutdowntext=stripslashes($myrow["shutdowntext"]);
		$shutdowntext = undo_htmlspecialchars($shutdowntext);
		echo $shutdowntext;
		echo "</font></td></tr></table></td></tr></table>";
		echo "</td></tr></table>";
		include($path_simpnews.'/includes/footer2.inc');
		echo "</body></html>";
		exit;
	}
}
if(isset($download))
{
	header('Content-Type: application/octetstream');
	header('Content-Disposition: filename="newsmsgtyper_'.$act_lang.'.ht"');
}
if(!isset($limitentries))
	$limitentries=$newstyper2maxentries;
if(!isset($limitdays))
	$limitdays=$newstyper2maxdays;
$datasourceurl="$url_simpnews/newsmsgtyper2.php?limitentries=$limitentries&limitdays=$limitdays&$langvar=$act_lang&layout=$layout&category=$category";
if(isset($lastvisitdate))
	$datasourceurl.="&lastvisitdate=$lastvisitdate";
if(isset($maxannounce))
	$datasourceurl.="&maxannounce=$maxannounce";
?>
<!-- code generated by SimpNews begin -->
<applet archive="<?php echo $url_simpnews?>/applet/msgtyper.jar"
	codebase="<?php echo $url_simpnews?>/applet"
	code="de.boesch_it.simpnews.msgtyper.MsgTyper"
	width="<?php echo $newstyper2width?>"
	height="<?php echo $newstyper2height?>">
<param name="datasource" value="<?php echo $datasourceurl?>">
<param name="fontcolor" value="<?php echo $newstyper2fontcolor?>">
<param name="bgcolor" value="<?php echo $newstyper2bgcolor?>">
<param name="moremsg" value="<?php echo "$l_more..."?>">
<param name="characterpause" value="<?php echo $newstyper2charpause?>">
<param name="linepause" value="<?php echo $newstyper2linepause?>">
<param name="screenpause" value="<?php echo $newstyper2screenpause?>">
<param name="linespace" value="<?php echo $newstyper2linespace?>">
<param name="indent" value="<?php echo $newstyper2indent?>">
<param name="fontsize" value="<?php echo $newstyper2fontsize?>">
<?php
if($newstyper2sound)
	echo "<param name=\"audioclip\" value=\"$newstyper2sound\">";
if($newstyper2bgimage)
	echo "<param name=\"backgroundimage\" value=\"$newstyper2bgimage\">";
?>
</applet>
<!-- code generated by SimpNews end -->
