<?php
/***************************************************************************
 * (c)2002-2004 Boesch IT-Consulting (info@boesch-it.de)
 ***************************************************************************/
$path_simpnews=dirname(__FILE__);
require_once($path_simpnews.'/config.php');
require_once($path_simpnews.'/functions.php');
if(!isset($category))
	$category=0;
if(!isset($$langvar) || !$$langvar)
	$act_lang=$default_lang;
else
	$act_lang=$$langvar;
include($path_simpnews.'/language/lang_'.$act_lang.'.php');
include($path_simpnews.'/includes/get_settings.inc');
$sql = "select * from ".$tableprefix."_misc";
if(!$result = mysql_query($sql, $db)) {
    die("Could not connect to the database.");
}
if ($myrow = mysql_fetch_array($result))
{
	if($myrow["shutdown"]==1)
	{
		include_once($path_simpnews.'/includes/styles2.inc');
?>
<table width="<?php echo $TableWidth?>" border="0" CELLPADDING="1" CELLSPACING="0" ALIGN="<?php echo $tblalign?>" class="sntable">
<tr><TD BGCOLOR="<?php echo $bordercolor?>">
<TABLE BORDER="0" CELLPADDING="1" CELLSPACING="1" WIDTH="100%">
<?php
if(strlen($heading)>0)
{
?>
<TR BGCOLOR="<?php echo $headingbgcolor?>" ALIGN="CENTER">
<TD ALIGN="CENTER" VALIGN="MIDDLE" colspan="2"><font face="<?php echo $headingfont?>" size="<?php echo $headingfontsize?>" color="<?php echo $headingfontcolor?>"><b><?php echo $heading?></b></font></td></tr>
<?php
}
?>
</tr></table></td></tr>
<tr><TD BGCOLOR="<?php echo $bordercolor?>">
<TABLE BORDER="0" CELLPADDING="1" CELLSPACING="1" WIDTH="100%">
<tr BGCOLOR="<?php echo $contentbgcolor?>" ALIGN="CENTER">
<TD ALIGN="CENTER" VALIGN="MIDDLE" colspan="2"><font face="<?php echo $contentfont?>" size="<?php echo $contentfontsize?>" color="<?php echo $contentfontcolor?>">
<?php
		$shutdowntext=stripslashes($myrow["shutdowntext"]);
		$shutdowntext = undo_htmlspecialchars($shutdowntext);
		echo $shutdowntext;
		echo "</font></td></tr></table></td></tr></table>";
		echo "</td></tr></table>";
		include($path_simpnews.'/includes/footer2.inc');
		echo "</body></html>";
		exit;
	}
}
if(isset($download))
{
	header('Content-Type: application/octetstream');
	header('Content-Disposition: filename="newstyper_'.$act_lang.'.ht"');
}
if(!isset($limitentries))
	$limitentries=$newstypermaxentries;
if(!isset($limitdays))
	$limitdays=$newstypermaxdays;
$sql = "select * from ".$tableprefix."_data where lang='$act_lang' ";
if($category>=0)
	$sql.= "and category='$category' ";
if($limitdays>=0)
{
	$actdate = date("Y-m-d H:i:s");
	$sql.= "and date >= date_sub('$actdate', INTERVAL $limitdays DAY) ";
}
$sql.= "order by date desc";
if($limitentries > 0)
	$sql.=" limit $limitentries";
if(!$result = mysql_query($sql, $db))
    die("unable to connect to database".mysql_error());
$bgcolor=str_replace("#","",$newstyperbgcolor);
$fontcolor=str_replace("#","",$newstyperfontcolor);
$datasourceurl="$url_simpnews/newstyper2.php?limitentries=$limitentries&limitdays=$limitdays&$langvar=$act_lang&layout=$layout&category=$category";
if(isset($lastvisitdate))
	$datasourceurl.="&lastvisitdate=$lastvisitdate";
if(isset($maxannounce))
	$datasourceurl.="&maxannounce=$maxannounce";
?>
<!-- code generated by SimpNews begin -->
<applet archive="<?php echo $url_simpnews?>/applet/typer.jar"
	codebase="<?php echo $url_simpnews?>/applet"
	code="de.boesch_it.simpnews.typer.TeleTyper"
	width="<?php echo $newstyperwidth?>"
	height="<?php echo $newstyperheight?>">
<param name="datasource" value="<?php echo $datasourceurl?>">
<param name="fontcolor" value="<?php echo $fontcolor?>">
<param name="bgcolor" value="<?php echo $bgcolor?>">
<param name="font" value="<?php echo $newstyperfont?>">
<param name="fontsize" value="<?php echo $newstyperfontsize?>">
<param name="fontstyle" value="<?php echo $typerfontstyles[$newstyperfontstyle]?>">
<param name="xoffset" value="<?php echo $newstyperxoffset?>">
<param name="yoffset" value="<?php echo $newstyperyoffset?>">
<?php
if($newstyperscroll)
	echo "<param name=\"scroll\" value=\"yes\">\n";
else
	echo "<param name=\"scroll\" value=\"no\">\n";
if($newstyperbgimage)
	echo "<param name=\"backgroundimage\" value=\"$newstyperbgimage\">\n";
?>
</applet>
<!-- code generated by SimpNews end -->
