<?php
/***************************************************************************
 * (c)2002-2004 Boesch IT-Consulting (info@boesch-it.de)
 ***************************************************************************/
$path_simpnews=dirname(__FILE__);
require_once($path_simpnews.'/config.php');
require_once($path_simpnews.'/functions.php');
if(!isset($category))
	$category=-1;
if(!isset($$langvar) || !$$langvar)
	$act_lang=$default_lang;
else
	$act_lang=$$langvar;
include($path_simpnews.'/language/lang_'.$act_lang.'.php');
include($path_simpnews.'/includes/get_settings.inc');
include($path_simpnews.'/includes/styles2.inc');
setlocale(LC_TIME, $def_locales[$act_lang]);
?>
<!-- code generated by SimpNews begin -->
<table width="<?php echo $TableWidth2?>" border="0" CELLPADDING="1" CELLSPACING="0" ALIGN="<?php echo $tblalign?>" class="sntable">
<tr><TD BGCOLOR="<?php echo $bordercolor?>">
<TABLE BORDER="0" CELLPADDING="1" CELLSPACING="1" WIDTH="100%">
<?php
if((strlen($nlsend_heading)>0) && ($hotscriptsnoheading==0))
{
?>
<TR BGCOLOR="<?php echo $headingbgcolor?>" ALIGN="CENTER">
<TD ALIGN="CENTER" VALIGN="MIDDLE" colspan="2"><font face="<?php echo $headingfont?>" size="<?php echo $headingfontsize?>" color="<?php echo $headingfontcolor?>"><b><?php echo $nlsend_heading?></b></font></td></tr>
<?php
}
$sql = "select * from ".$tableprefix."_misc";
if(!$result = mysql_query($sql, $db)) {
    die("<tr class=\"errorrow\"><td>Could not connect to the database.");
}
if ($myrow = mysql_fetch_array($result))
{
	if($myrow["shutdown"]==1)
	{
?>
</tr></table></td></tr>
<tr><TD BGCOLOR="<?php echo $bordercolor?>">
<TABLE BORDER="0" CELLPADDING="1" CELLSPACING="1" WIDTH="100%">
<tr BGCOLOR="<?php echo $contentbgcolor?>" ALIGN="CENTER">
<TD ALIGN="CENTER" VALIGN="MIDDLE" colspan="2"><font face="<?php echo $contentfont?>" size="<?php echo $contentfontsize?>" color="<?php echo $contentfontcolor?>">
<?php
		$shutdowntext=stripslashes($myrow["shutdowntext"]);
		$shutdowntext = undo_htmlspecialchars($shutdowntext);
		echo $shutdowntext;
		echo "</font></td></tr></table></td></tr></table>";
?>
</td></tr></table>
<?php
		include($path_simpnews.'/includes/footer2.inc');
		echo "</body></html>";
		exit;
	}
}
if($category<1)
{
		echo "<tr bgcolor=\"$nlsend_bgcolor\">";
		echo "<td width=\"50%\" align=\"left\">";
		echo "<font face=\"$nlsend_font\" size=\"$nlsend_fontsize\" color=\"$nlsend_fontcolor\">";
		echo "$l_general</font></td>";
		$sql="select max(lastsent) as nlsenddate from ".$tableprefix."_subscriptions where category=0";
		if(!$result = mysql_query($sql, $db))
		    die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
		$displaydate="";
		if($myrow=mysql_fetch_array($result))
		{
			list($mydate,$mytime)=explode(" ",$myrow["nlsenddate"]);
			list($year, $month, $day) = explode("-", $mydate);
			list($hour, $min, $sec) = explode(":",$mytime);
			if($month>0)
			{
				$displaytime=mktime($hour,$min,$sec,$month,$day,$year);
				$displaytime=transposetime($displaytime,$servertimezone,$displaytimezone);
				$displaydate=strftime($nlsend_dateformat,$displaytime);
			}
			else
				$displaydate="";
		}
		echo "<td align=\"left\">";
		echo "<font face=\"$nlsend_font\" size=\"$nlsend_fontsize\" color=\"$nlsend_fontcolor\">";
		echo "$displaydate</font></td></tr>";
}
if($category!=0)
{
	$sql= "select * from ".$tableprefix."_categories";
	if($category>0)
		$sql.=" where catnr='$category'";
	$sql.=" order by displaypos asc";
	if(!$result = mysql_query($sql, $db))
	    die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
	while($myrow=mysql_fetch_array($result))
	{
		$cattext=display_encoded(stripslashes($myrow["catname"]));
		$tmpsql="select * from ".$tableprefix."_catnames where catnr=".$myrow["catnr"]." and lang='".$act_lang."'";
		if(!$tmpresult=mysql_query($tmpsql,$db))
			die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
		if($tmprow=mysql_fetch_array($tmpresult))
		{
			if(strlen($tmprow["catname"])>0)
				$cattext=display_encoded(stripslashes($tmprow["catname"]));
		}
		echo "<tr bgcolor=\"$nlsend_bgcolor\">";
		echo "<td width=\"50%\" align=\"left\">";
		echo "<font face=\"$nlsend_font\" size=\"$nlsend_fontsize\" color=\"$nlsend_fontcolor\">";
		echo $cattext."</font></td>";
		list($mydate,$mytime)=explode(" ",$myrow["nlsenddate"]);
		list($year, $month, $day) = explode("-", $mydate);
		list($hour, $min, $sec) = explode(":",$mytime);
		if($month>0)
		{
			$displaytime=mktime($hour,$min,$sec,$month,$day,$year);
			$displaytime=transposetime($displaytime,$servertimezone,$displaytimezone);
			$displaydate=strftime($nlsend_dateformat,$displaytime);
		}
		else
			$displaydate="";
		echo "<td align=\"left\">";
		echo "<font face=\"$nlsend_font\" size=\"$nlsend_fontsize\" color=\"$nlsend_fontcolor\">";
		echo "$displaydate</font></td></tr>";
	}
}
echo "</table></td></tr></table>";
include($path_simpnews.'/includes/footer2.inc');
?>