<?php
/***************************************************************************
 * (c)2002-2005 Boesch IT-Consulting (info@boesch-it.de)
 ***************************************************************************/
$path_simpnews=dirname(__FILE__);
require_once($path_simpnews.'/config.php');
require_once($path_simpnews.'/functions.php');
require_once($path_simpnews.'/includes/entry_functions.inc');
if(!isset($category))
	$category=0;
if(!isset($$langvar) || !$$langvar)
	$act_lang=$default_lang;
else
	$act_lang=$$langvar;
include($path_simpnews.'/language/lang_'.$act_lang.'.php');
include($path_simpnews.'/includes/get_settings.inc');
include($path_simpnews.'/includes/styles2.inc');
if($commentsinline==1)
	include($path_simpnews.'/includes/com_inline.inc');
if(!isset($newsnr))
	die($l_callingerror);
$actdate = date("Y-m-d H:i:00");
if($heading)
	$pageheading=$heading;
else
	$pageheading=$l_news;
if(!isset($srcscript))
	$srcscript=$url_simpnews."/news.php";
if($sncatlink=="source script")
	$catlink=$srcscript;
else
	$catlink=$sncatlink;
?>
<!-- code generated by SimpNews begin -->
<div style="clear:both" align="<?php echo $tblalign?>">
<table width="<?php echo $sns_tablewidth?>" border="0" CELLPADDING="1" CELLSPACING="0" ALIGN="<?php echo $tblalign?>" class="sntable">
<tr><TD BGCOLOR="<?php echo $bordercolor?>">
<a name="top"></a>
<TABLE BORDER="0" CELLPADDING="1" CELLSPACING="1" WIDTH="100%">
<?php
if((strlen($heading)>0) && bittst($sns_options,BIT_4))
{
?>
<TR BGCOLOR="<?php echo $headingbgcolor?>" ALIGN="CENTER">
<TD ALIGN="CENTER" VALIGN="MIDDLE" colspan="2"><font face="<?php echo $headingfont?>" size="<?php echo $headingfontsize?>" color="<?php echo $headingfontcolor?>"><b><?php echo $heading?></b></font></td></tr>
<?php
}
$sql = "select * from ".$tableprefix."_data where newsnr=$newsnr";
if(!$result = mysql_query($sql, $db))
    die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
if(!$myrow=mysql_fetch_array($result))
	die("<tr class=\"errorrow\"><td>".$l_nosuchentry);
if(($myrow["category"]>0) && ($enablerating==1))
{
	$sql = "select * from ".$tableprefix."_categories where catnr=".$myrow["category"];
	if(!$result2 = mysql_query($sql, $db))
		die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
	if($myrow2=mysql_fetch_array($result2))
		$enablerating=$myrow2["enablerating"];
}
if(bittst($sns_options,BIT_6))
{
	if($myrow["category"]>0)
	{
		$sql = "select * from ".$tableprefix."_categories where catnr=".$myrow["category"];
		if(!$result2 = mysql_query($sql, $db))
			die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
		if($myrow2=mysql_fetch_array($result2))
		{
			$cattext=display_encoded(stripslashes($myrow2["catname"]));
			$tmpsql="select * from ".$tableprefix."_catnames where catnr=".$myrow2["catnr"]." and lang='".$act_lang."'";
			if(!$tmpresult=mysql_query($tmpsql,$db))
				die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
			if($tmprow=mysql_fetch_array($tmpresult))
			{
				if(strlen($tmprow["catname"])>0)
					$cattext=display_encoded(stripslashes($tmprow["catname"]));
			}
			echo "<tr bgcolor=\"$headingbgcolor\">";
			echo "<td align=\"center\" colspan=\"2\">";
			echo "<font face=\"$headingfont\" size=\"$contentfontsize\" color=\"$headingfontcolor\">";
			if(bittst($sns_options,BIT_1))
				echo "<a title=\"$l_showcategory\" class=\"catlink\" href=\"".$catlink."?$langvar=$act_lang&amp;layout=$layout&amp;category=".$myrow2["catnr"]."\">";
			echo "<b>".$cattext."</b>";
			if(bittst($sns_options,BIT_1))
				echo "</a>";
			echo "</font></td></tr>";
			if(bittst($sns_options,BIT_13) && ($myrow2["headertext"]))
			{
				echo "<tr bgcolor=\"$catinfobgcolor\">";
				echo "<td class=\"catinfo\" align=\"left\" colspan=\"2\">";
				echo "<font face=\"$catinfofont\" size=\"$catinfofontsize\" color=\"$catinfofontcolor\">";
				$displaytext=stripslashes($myrow2["headertext"]);
				$displaytext = undo_htmlspecialchars($displaytext);
				echo $displaytext;
				echo "</font></td></tr>";
			}
			$catfooteroptions=$myrow2["footeroptions"];
			$catfooter=$myrow2["customfooter"];
			if(!$catfooter)
				$catfooteroptions=0;
			if(bittst($catfooteroptions,BIT_1) && bittst($catfooteroptions,BIT_2))
			{
				$customfooter=$catfooter;
				$usecustomfooter=1;
				$footerfile="";
			}
		}
	}
	else if($myrow["category"]==0)
	{
		echo "<tr bgcolor=\"$headingbgcolor\">";
		echo "<td align=\"center\" colspan=\"2\">";
		echo "<font face=\"$headingfont\" size=\"$contentfontsize\" color=\"$headingfontcolor\">";
		if(bittst($sns_options,BIT_1))
			echo "<a title=\"$l_showcategory\" class=\"catlink\" href=\"".$catlink."?$langvar=$act_lang&amp;layout=$layout&amp;category=0\">";
		echo "<b>".$l_general."</b>";
		if(bittst($sns_options,BIT_1))
			echo "</a>";
		echo "</font></td></tr>";
	}
}
if($myrow["norating"]==1)
	$enablerating=0;
echo "<tr><td width=\"2%\" height=\"100%\" align=\"center\" bgcolor=\"$contentbgcolor\">";
if($myrow["headingicon"])
	echo "<img src=\"$url_icons/".$myrow["headingicon"]."\" border=\"0\" align=\"middle\"> ";
else
	echo "&nbsp;";
echo "</td>";
echo "<td align=\"center\"><table class=\"newsbox\" width=\"100%\" align=\"center\" bgcolor=\"$contentbgcolor\" cellspacing=\"0\" cellpadding=\"0\">";
list($mydate,$mytime)=explode(" ",$myrow["date"]);
list($year, $month, $day) = explode("-", $mydate);
list($hour, $min, $sec) = explode(":",$mytime);
if($month>0)
{
	$displaytime=mktime($hour,$min,$sec,$month,$day,$year);
	$displaytime=transposetime($displaytime,$servertimezone,$displaytimezone);
	$displaydate=date($dateformat,$displaytime);
}
else
	$displaydate="";
if((($allowcomments==1) && ($myrow["allowcomments"]==1)) || bittst($sns_options,BIT_2))
{
	echo "<tr><td align=\"left\" bgcolor=\"$timestampbgcolor\"";
	if(($allowcomments==0) || ($myrow["allowcomments"]==0))
		echo "colspan=\"3\"";
	else
		echo "width=\"80%\"";
	echo ">";
	echo "<font face=\"$timestampfont\" size=\"$timestampfontsize\" color=\"$timestampfontcolor\">";
	if(bittst($sns_options,BIT_2))
	{
		echo get_start_tag($timestampstyle);
		echo $displaydate;
		echo get_end_tag($timestampstyle);
	}
	else
		echo "&nbsp;";
	if(isset($lastvisitdate))
	{
		list($mydate,$mytime)=explode(" ",$myrow["date"]);
		list($year, $month, $day) = explode("-", $mydate);
		list($hour, $min, $sec) = explode(":",$mytime);
		$thisentrydate=mktime($hour,$min,$sec,$month,$day,$year);
		if($thisentrydate>=$lastvisitdate)
			echo "&nbsp;&nbsp;<img src=\"$url_gfx/$newentrypic\" border=\"0\" align=\"absmiddle\">";
	}
	echo "</font></td>";
	if(($allowcomments==1) && ($myrow["allowcomments"]==1))
	{
		echo "<td class=\"commentaction\" align=\"right\" bgcolor=\"$timestampbgcolor\" width=\"1%\" valign=\"top\">";
		echo "<font face=\"$timestampfont\" size=\"$timestampfontsize\" color=\"$timestampfontcolor\">";
		$tempsql="select * from ".$tableprefix."_comments where entryref=".$myrow["newsnr"];
		if(!$tempresult = mysql_query($tempsql, $db))
		    die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
		$numcomments=mysql_num_rows($tempresult);
		if(($numcomments>0) && ($commentsinline==0))
		{
			echo "<a class=\"commentlink\" href=\"".$url_simpnews."/comment.php?mode=display&amp;$langvar=$act_lang&amp;entryref=".$myrow["newsnr"]."\">";
			if($commentspic)
				echo "<img style=\"margin: 1px\" src=\"".$url_gfx."/$commentspic\" border=\"0\" alt=\"$l_comments: $numcomments\" title=\"$l_comments: $numcomments\">";
			else
				echo "$l_comments:&nbsp;$numcomments";
			echo "</a>";
		}
		else
			echo "&nbsp;";
		echo "</font></td>";
		echo "<td class=\"commentaction\" align=\"right\" bgcolor=\"$timestampbgcolor\" width=\"1%\">";
		echo "<font face=\"$timestampfont\" size=\"$timestampfontsize\" color=\"$timestampfontcolor\">";
		echo "<a class=\"commentlink\" href=\"".$url_simpnews."/comment.php?$langvar=$act_lang&amp;mode=new&amp;entryref=".$myrow["newsnr"]."\">";
		if($writecommentpic)
			echo "<img style=\"margin: 1px\" src=\"".$url_gfx."/$writecommentpic\" border=\"0\" alt=\"$l_writecomment\" title=\"$l_writecomment\">";
		else
			echo "$l_writecomment";
		echo "</a></font></td>";
	}
	echo "</tr>";
}
if((strlen($myrow["heading"])>0) && bittst($sns_options,BIT_3))
{
	echo "<tr bgcolor=\"$newsheadingbgcolor\"><td align=\"left\" colspan=\"3\">";
	echo "<font face=\"$newsheadingfont\" size=\"$newsheadingfontsize\" color=\"$newsheadingfontcolor\">";
	echo get_start_tag($newsheadingstyle);
	echo undo_html_ampersand(do_htmlentities($myrow["heading"]));
	echo get_end_tag($newsheadingstyle);
	echo "</font></td></tr>";
}
echo "<tr bgcolor=\"$contentbgcolor\"><td align=\"left\" colspan=\"3\">";
echo "<font face=\"$contentfont\" size=\"$contentfontsize\" color=\"$contentfontcolor\">";
$displaytext=stripslashes($myrow["text"]);
$displaytext = undo_htmlspecialchars($displaytext);
echo $displaytext."</font></td></tr>";
if(bittst($sns_options,BIT_5) && (strlen($myrow["poster"])>0) && ($attachpos==0))
	posterline2($myrow["posterid"], $myrow["poster"], bittst($sns_options,BIT_7), $myrow["exposter"]);
if($attachpos==0)
	echo "<tr bgcolor=\"$contentbgcolor\"><td align=\"left\">";
displayattachs_news($myrow["newsnr"],$attachpos, $nofileinfo);
if($attachpos==1)
{
	if(bittst($sns_options,BIT_5) && (strlen($myrow["poster"])>0))
		posterline2($myrow["posterid"], $myrow["poster"], bittst($sns_options,BIT_7), $myrow["exposter"]);
	echo "<tr bgcolor=\"$contentbgcolor\"><td>&nbsp;</td>";
}
echo "<td align=\"right\" colspan=\"2\">";
echo "<font face=\"$contentfont\" size=\"1\" color=\"$contentfontcolor\">";
if(bittst($sns_options,BIT_8))
{
	echo "<a href=\"".$url_simpnews."/print.php?$langvar=$act_lang&layout=$layout&newsnr=".$myrow["newsnr"]."\" target=\"printwindow\">";
	if($printpic_small)
		echo "<img class=\"iconbutton\" src=\"$url_gfx/$printpic_small\" border=\"0\" align=\"absmiddle\" title=\"$l_print\" alt=\"$l_print\">";
	else
		echo "[$l_print]";
	echo "</a>";
}
if(bittst($sns_options,BIT_9))
	echo "<a href=\"#top\"><img class=\"iconbutton\" src=\"$url_gfx/$pagetoppic\" border=\"0\" align=\"absmiddle\" title=\"$l_gotop\" alt=\"$l_gotop\"></a>";
if(($emailnews==1) && bittst($sns_options,BIT_10))
	echo "<a href=\"".$url_simpnews."/newsmail.php?$langvar=$act_lang&layout=$layout&newsnr=".$myrow["newsnr"]."\" target=\"mailwindow\"><img class=\"iconbutton\" src=\"$url_gfx/$emailpic\" border=\"0\" align=\"absmiddle\" title=\"$l_emailentry\" alt=\"$l_emailentry\"></a>";
echo "</td></tr>";
if(($allowcomments==1) && ($myrow["allowcomments"]==1) && ($commentsinline==1))
	display_inline_comments($myrow["newsnr"]);
echo "</table></td></tr>";
if($useviewcounts==1)
{
	$tmpsql = "UPDATE ".$tableprefix."_data SET views = views + 1 WHERE (newsnr = $newsnr)";
	@mysql_query($tmpsql, $db);
}
$preventry="";
$nextentry="";
if(bittst($sns_options,BIT_12))
{
	$tempsql="select * from ".$tableprefix."_data ";
	$firstarg=1;
	if($category>=0)
	{
		$firstarg=0;
		$tempsql.="where category='$category' ";
	}
	if($separatebylang==1)
	{
		if($firstarg==1)
		{
			$firstarg=0;
			$tempsql.="where lang='$act_lang' ";
		}
		else
			$tempsql.="and lang='$act_lang' ";
	}
	$tempsql.="order by date desc";
	if(!$tempresult=mysql_query($tempsql,$db))
		die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
	$entryfound=0;
	if($temprow=mysql_fetch_array($tempresult))
	{
		do{
			if($entryfound==1)
			{
				$nextentry=$temprow;
				$entryfound=2;
			}
			if($temprow["newsnr"]==$newsnr)
				$entryfound=1;
			if($entryfound<1)
				$preventry=$temprow;
		}while($temprow=mysql_fetch_array($tempresult));
	}
?>
<tr bgcolor="<?php echo $headingbgcolor?>"><td align="center" colspan="2">
<font face="<?php echo $contentfont?>" size="<?php echo $contentfontsize?>" color="<?php echo $contentfontcolor?>">
<?php
if($preventry)
{
	echo "<a class=\"pagenav\" href=\"$act_script_url?$langvar=$act_lang&amp;layout=$layout&amp;category=$category&amp;newsnr=".$preventry["newsnr"];
	if($backurl)
		echo "&amp;backurl=".urlencode($backurl);
	echo "\">";
	if($pagepic_back)
		echo "<img src=\"$url_gfx/$pagepic_back\" border=\"0\" align=\"absmiddle\" title=\"$l_back\" alt=\"$l_back\">";
	else
		echo "<b>[&lt;]</b>";
	echo "</a>&nbsp;&nbsp;";

}
if($nextentry)
{
	echo "&nbsp;&nbsp;<a class=\"pagenav\" href=\"$act_script_url?$langvar=$act_lang&amp;layout=$layout&amp;category=$category&amp;newsnr=".$nextentry["newsnr"];
	if($backurl)
		echo "&amp;backurl=".urlencode($backurl);
	echo "\">";
	if($pagepic_next)
		echo "<img src=\"$url_gfx/$pagepic_next\" border=\"0\" align=\"absmiddle\" title=\"$l_more\" alt=\"$l_more\">";
	else
		echo "<b>[&gt;]</b>";
	echo "</a>";

}
echo "</font></td></tr>";
}
if(($enablerating==1) && bittst($sns_options,BIT_11))
{
	if(!isset($dorating))
	{
		echo "<form method=\"post\" action=\"$act_script_url\">";
		echo "<input type=\"hidden\" name=\"$langvar\" value=\"$act_lang\">";
		echo "<input type=\"hidden\" name=\"layout\" value=\"$layout\">";
		echo "<input type=\"hidden\" name=\"category\" value=\"category\">";
		echo "<input type=\"hidden\" name=\"newsnr\" value=\"$newsnr\">";
		echo "<input type=\"hidden\" name=\"dorating\" value=\"1\">";
		if(isset($srcscript))
			echo "<input type=\"hidden\" name=\"srcscript\" value=\"".do_htmlentities($srcscript)."\">";
		echo "<tr bgcolor=\"$contentbgcolor\"><td align=\"left\" colspan=\"2\">";
		include($path_simpnews."/includes/ratingbox.inc");
		echo "&nbsp;";
		echo "<input type=\"submit\" name=\"submit\" value=\"$l_ok\" class=\"snewsbutton\">";
		echo "</font></td></tr></form>";
	}
	else
	{
		$ratingsql="update ".$tableprefix."_data set ratingcount=ratingcount+1, ratings=ratings+$ratingvalue where newsnr=$newsnr";
		if(!$ratingresult=mysql_query($ratingsql,$db))
			die("<tr class=\"errorrow\"><td>Unable to connect to database.".mysql_error());
		echo "<tr bgcolor=\"$contentbgcolor\"><td align=\"center\" colspan=\"2\">";
		echo "<font face=\"$contentfont\" size=\"$contentfontsize\" color=\"$contentfontcolor\">";
		echo $l_ratingadded;
		echo "</font></td></tr>";
	}
}
echo "</table></td></tr></table></div>";
$footer_tablewidth=$sns_tablewidth;
include($path_simpnews.'/includes/footer4.inc');
?>