<?php
/***************************************************************************
 * (c)2002-2004 Boesch IT-Consulting (info@boesch-it.de)
 ***************************************************************************/
require_once('./config.php');
require_once('./functions.php');
if(!isset($$langvar) || !$$langvar)
	$act_lang=$default_lang;
else
	$act_lang=$$langvar;
require_once('./language/lang_'.$act_lang.'.php');
require_once('./includes/get_settings.inc');
require_once('./includes/block_leacher.inc');
if($heading)
	$pageheading=$heading;
else
	$pageheading=$l_news;
if(!isset($newscat))
	$newscat=0;
if(isset($mode))
{
	if($mode=="subscribe")
	{
		include_once("./includes/sub_subscribe.inc");
	}
	if($mode=="confirm")
	{
		include_once("./includes/sub_confirm.inc");
	}
	if($mode=="remove")
	{
		include_once("./includes/sub_remove.inc");
	}
	if($mode=="unsubscribe")
	{
		include_once("./includes/sub_unsub.inc");
	}
	if($mode=="delete")
	{
		include_once("./includes/sub_del.inc");
	}
}
else
{
	include_once("./includes/sub_main.inc");
}
?>
