// RU cp1251 lang variables

tinyMCE.addToLang('table',{
general_tab : 'Îñíîâíûå',
advanced_tab : 'Ðàñøèðåííûå',
general_props : 'Îñíîâíûå ñâîéñòâà',
advanced_props : 'Ðàñøèðåííûå ñâîéñòâà',
desc : 'Âñòàâèòü íîâóþ òàáëèöó',
row_before_desc : 'Âñòàâèòü ñòðîêó ïåðåä',
row_after_desc : 'Âñòàâèòü ñòðîêó ïîñëå',
delete_row_desc : 'Óäàëèòü ñòðîêó',
col_before_desc : 'Âñòàâèòü êîëîíêó ïåðåä',
col_after_desc : 'Âñòàâèòü êîëîíêó ïîñëå',
delete_col_desc : 'Óäàëèòü êîëîíêó',
rowtype : 'Ñòðîêà â ÷àñòè òàáëèöû',
title : 'Âñòàâèòü/Èçìåíèòü òàáëèöó',
width : 'Øèðèíà',
height : 'Âûñîòà',
cols : 'Êîëîíêè',
rows : 'Ñòðîêè',
cellspacing : 'Ðàññòîÿíèå ìåæäó ÿ÷åéêàìè',
cellpadding : 'Îòñòóï â ÿ÷åéêàõ',
border : 'Ãðàíèöà',
align : 'Âûðàâíèâàíèå',
align_default : 'Ïî-óìîë÷àíèþ',
align_left : 'Âñåâî',
align_right : 'Âïðàâî',
align_middle : 'Ïî öåíòðó',
row_title : 'Ñâîéñòâà ñòðîêè òàáëèöû',
cell_title : 'Ñâîéñòâà ÿ÷åéêè òàáëèöû',
cell_type : 'Òèï ÿ÷åéêè',
row_desc : 'Ñâîéñòâà ñòðîêè òàáëèöû',
cell_desc : 'Ñâîéñòâà ÿ÷åéêè òàáëèöû',
valign : 'Âåðòèêàëüíîå âûðàâíèâàíèå',
align_top : 'Ïî âåðõó',
align_bottom : 'Ïî íèçó',
props_desc : 'Ñâîéñòâà òàáëèöû',
bordercolor : 'Öâåò ðàìêè',
bgcolor : 'Öâåò ôîíà',
merge_cells_title : 'Îáúåäèíèòü ÿ÷åéêè òàáëèöû',
split_cells_desc : 'Ðàçäåëèòü ÿ÷åéêè òàáëèöû',
merge_cells_desc : 'Îáúåäèíèòü ÿ÷åéêè òàáëèöû',
cut_row_desc : 'Âûëåçàòü ñòðîêó òàáëèöû',
copy_row_desc : 'Ñêîïèðîâàòü ñòðîêó òàáëèöû',
paste_row_before_desc : 'Âñòàâèòü ñòðîêó òàáëèöû ïåðåä',
paste_row_after_desc : 'Âñòàâèòü ñòðîêó òàáëèöû ïîñëå',
id : 'Id',
style: 'Ñòèëü',
langdir : 'Îïèñàíèå ÿçûêà',
langcode : 'Êîä ÿçûêà',
mime : 'Öåëåâîé MIME òèï',
ltr : 'Ñëåâà íàïðàâî',
rtl : 'Ñïðàâà íàëåâî',
bgimage : 'Ôîíîâîå èçîáðàæåíèå',
summary : 'Êðàòêîå îïèñàíèå',
td : "Òåëî",
th : "Çàãîëîâîê",
cell_cell : 'Îáíîâèòü òåêóùóþ ÿ÷åéêó',
cell_row : 'Îáíîâèòü òåêóùóþ ñòðîêó',
cell_all : 'Îáíîâèòü âñå ÿ÷åéêè â òàáëèöå',
row_row : 'Îáíîâèòü òåêóùóþ ñòðîêó',
row_odd : 'Update odd rows in table',
row_even : 'Update even rows in table',
row_all : 'Îáíîâèòü âñå ñòðîêè â òàáëèöå',
thead : 'Çàãîëîâîê òàáëèöû',
tbody : 'Òåëî òàáëèöû',
tfoot : 'Ôóòåð òàáëèöû',
del : 'Óäàëèòü òàáëèöó',
scope : 'Ãðàíèöû',
row : 'Ñòðîêà',
col : 'Êîëîíêà',
rowgroup : 'Ãðóïïà ñòðîê',
colgroup : 'Ãðóïïà êîëîíîê',
missing_scope: 'Âû óâåðåíû, ÷òî õîòèòå ïðîäîëæàòü íå îáîçíà÷èâ ãðàíèöû ÿ÷ååê øàïêè òàáëèöû? Áåç ýòîãî, âîçìîæíî, íåêîòîðûì ïîëüçîâàòåëÿì áóäåò çàòðóäíèòåëüíî ïîíÿòü, ÷òî çà äàííûå íàõîäÿòñÿ â òàáëèöå.',
table_delta_width : 30,
cellprops_delta_width : 130
});
