// RU KOI8-R lang variables

tinyMCE.addToLang('table',{
general_tab : 'ïÓÎÏ×ÎÙÅ',
advanced_tab : 'òÁÓÛÉÒÅÎÎÙÅ',
general_props : 'ïÓÎÏ×ÎÙÅ Ó×ÏÊÓÔ×Á',
advanced_props : 'òÁÓÛÉÒÅÎÎÙÅ Ó×ÏÊÓÔ×Á',
desc : '÷ÓÔÁ×ÉÔØ ÎÏ×ÕÀ ÔÁÂÌÉÃÕ',
row_before_desc : '÷ÓÔÁ×ÉÔØ ÓÔÒÏËÕ ÐÅÒÅÄ',
row_after_desc : '÷ÓÔÁ×ÉÔØ ÓÔÒÏËÕ ÐÏÓÌÅ',
delete_row_desc : 'õÄÁÌÉÔØ ÓÔÒÏËÕ',
col_before_desc : '÷ÓÔÁ×ÉÔØ ËÏÌÏÎËÕ ÐÅÒÅÄ',
col_after_desc : '÷ÓÔÁ×ÉÔØ ËÏÌÏÎËÕ ÐÏÓÌÅ',
delete_col_desc : 'õÄÁÌÉÔØ ËÏÌÏÎËÕ',
rowtype : 'óÔÒÏËÁ × ÞÁÓÔÉ ÔÁÂÌÉÃÙ',
title : '÷ÓÔÁ×ÉÔØ/éÚÍÅÎÉÔØ ÔÁÂÌÉÃÕ',
width : 'ûÉÒÉÎÁ',
height : '÷ÙÓÏÔÁ',
cols : 'ëÏÌÏÎËÉ',
rows : 'óÔÒÏËÉ',
cellspacing : 'òÁÓÓÔÏÑÎÉÅ ÍÅÖÄÕ ÑÞÅÊËÁÍÉ',
cellpadding : 'ïÔÓÔÕÐ × ÑÞÅÊËÁÈ',
border : 'çÒÁÎÉÃÁ',
align : '÷ÙÒÁ×ÎÉ×ÁÎÉÅ',
align_default : 'ðÏ-ÕÍÏÌÞÁÎÉÀ',
align_left : '÷ÓÅ×Ï',
align_right : '÷ÐÒÁ×Ï',
align_middle : 'ðÏ ÃÅÎÔÒÕ',
row_title : 'ó×ÏÊÓÔ×Á ÓÔÒÏËÉ ÔÁÂÌÉÃÙ',
cell_title : 'ó×ÏÊÓÔ×Á ÑÞÅÊËÉ ÔÁÂÌÉÃÙ',
cell_type : 'ôÉÐ ÑÞÅÊËÉ',
row_desc : 'ó×ÏÊÓÔ×Á ÓÔÒÏËÉ ÔÁÂÌÉÃÙ',
cell_desc : 'ó×ÏÊÓÔ×Á ÑÞÅÊËÉ ÔÁÂÌÉÃÙ',
valign : '÷ÅÒÔÉËÁÌØÎÏÅ ×ÙÒÁ×ÎÉ×ÁÎÉÅ',
align_top : 'ðÏ ×ÅÒÈÕ',
align_bottom : 'ðÏ ÎÉÚÕ',
props_desc : 'ó×ÏÊÓÔ×Á ÔÁÂÌÉÃÙ',
bordercolor : 'ã×ÅÔ ÒÁÍËÉ',
bgcolor : 'ã×ÅÔ ÆÏÎÁ',
merge_cells_title : 'ïÂßÅÄÉÎÉÔØ ÑÞÅÊËÉ ÔÁÂÌÉÃÙ',
split_cells_desc : 'òÁÚÄÅÌÉÔØ ÑÞÅÊËÉ ÔÁÂÌÉÃÙ',
merge_cells_desc : 'ïÂßÅÄÉÎÉÔØ ÑÞÅÊËÉ ÔÁÂÌÉÃÙ',
cut_row_desc : '÷ÙÌÅÚÁÔØ ÓÔÒÏËÕ ÔÁÂÌÉÃÙ',
copy_row_desc : 'óËÏÐÉÒÏ×ÁÔØ ÓÔÒÏËÕ ÔÁÂÌÉÃÙ',
paste_row_before_desc : '÷ÓÔÁ×ÉÔØ ÓÔÒÏËÕ ÔÁÂÌÉÃÙ ÐÅÒÅÄ',
paste_row_after_desc : '÷ÓÔÁ×ÉÔØ ÓÔÒÏËÕ ÔÁÂÌÉÃÙ ÐÏÓÌÅ',
id : 'Id',
style: 'óÔÉÌØ',
langdir : 'ïÐÉÓÁÎÉÅ ÑÚÙËÁ',
langcode : 'ëÏÄ ÑÚÙËÁ',
mime : 'ãÅÌÅ×ÏÊ MIME ÔÉÐ',
ltr : 'óÌÅ×Á ÎÁÐÒÁ×Ï',
rtl : 'óÐÒÁ×Á ÎÁÌÅ×Ï',
bgimage : 'æÏÎÏ×ÏÅ ÉÚÏÂÒÁÖÅÎÉÅ',
summary : 'ëÒÁÔËÏÅ ÏÐÉÓÁÎÉÅ',
td : "ôÅÌÏ",
th : "úÁÇÏÌÏ×ÏË",
cell_cell : 'ïÂÎÏ×ÉÔØ ÔÅËÕÝÕÀ ÑÞÅÊËÕ',
cell_row : 'ïÂÎÏ×ÉÔØ ÔÅËÕÝÕÀ ÓÔÒÏËÕ',
cell_all : 'ïÂÎÏ×ÉÔØ ×ÓÅ ÑÞÅÊËÉ × ÔÁÂÌÉÃÅ',
row_row : 'ïÂÎÏ×ÉÔØ ÔÅËÕÝÕÀ ÓÔÒÏËÕ',
row_odd : 'Update odd rows in table',
row_even : 'Update even rows in table',
row_all : 'ïÂÎÏ×ÉÔØ ×ÓÅ ÓÔÒÏËÉ × ÔÁÂÌÉÃÅ',
thead : 'úÁÇÏÌÏ×ÏË ÔÁÂÌÉÃÙ',
tbody : 'ôÅÌÏ ÔÁÂÌÉÃÙ',
tfoot : 'æÕÔÅÒ ÔÁÂÌÉÃÙ',
del : 'õÄÁÌÉÔØ ÔÁÂÌÉÃÕ',
scope : 'çÒÁÎÉÃÙ',
row : 'óÔÒÏËÁ',
col : 'ëÏÌÏÎËÁ',
rowgroup : 'çÒÕÐÐÁ ÓÔÒÏË',
colgroup : 'çÒÕÐÐÁ ËÏÌÏÎÏË',
missing_scope: '÷Ù Õ×ÅÒÅÎÙ, ÞÔÏ ÈÏÔÉÔÅ ÐÒÏÄÏÌÖÁÔØ ÎÅ ÏÂÏÚÎÁÞÉ× ÇÒÁÎÉÃÙ ÑÞÅÅË ÛÁÐËÉ ÔÁÂÌÉÃÙ? âÅÚ ÜÔÏÇÏ, ×ÏÚÍÏÖÎÏ, ÎÅËÏÔÏÒÙÍ ÐÏÌØÚÏ×ÁÔÅÌÑÍ ÂÕÄÅÔ ÚÁÔÒÕÄÎÉÔÅÌØÎÏ ÐÏÎÑÔØ, ÞÔÏ ÚÁ ÄÁÎÎÙÅ ÎÁÈÏÄÑÔÓÑ × ÔÁÂÌÉÃÅ.'
});
