// TW lang variables contributed by Jim Kou

tinyMCE.addToLang('',{
insert_table_align : '¹ï»ô',
insert_table_align_default : '¼Ð·Ç',
insert_table_align_left : '»ô¥ª',
insert_table_align_middle : '¸m¤¤',
insert_table_align_right : '»ô¥k',
insert_table_border : '®Ø½u',
insert_table_cellpadding : '¦r&Aring;é»PÀx¦s®æ¶¡»Ø',
insert_table_cellspacing : 'Àx¦s®æ¶¡»Ø',
insert_table_class : '¼Ë¦¡',
insert_table_cols : '¦æ',
insert_table_height : '°ª«×',
insert_table_rows : '¦C',
insert_table_title : 'ªí®æ¼ÐÃD',
insert_table_width : '¼e«×',
table_delete_col_desc : '§R°£¤@¦æÀx¦s®æ',
table_delete_row_desc : '§R°£¤@¦CÀx¦s®æ',
table_desc : 'ªí®æ',
table_insert_col_after_desc : '·s¼W¤@¦æÀx¦s®æ(«á)',
table_insert_col_before_desc : '·s¼W¤@¦æÀx¦s®æ(«e)',
table_insert_row_after_desc : '·s¼W¤@¦CÀx¦s®æ(«á)',
table_insert_row_before_desc : '·s¼W¤@¦CÀx¦s®æ(«e)',
table_row_title : 'Table row properties',
table_cell_title : 'Table cell properties',
table_row_desc : 'Table row properties',
table_cell_desc : 'Table cell properties',
insert_table_valign : 'Vertical alignment',
insert_table_align_top : 'Top',
insert_table_align_bottom : 'Bottom',
table_props_desc : 'Table properties',
table_bordercolor : 'Border color',
table_bgcolor : 'Bg color',
table_merge_cells_title : 'Merge table cells',
table_split_cells_desc : 'Split table cells',
table_merge_cells_desc : 'Merge table cells',
table_cut_row_desc : 'Cut table row',
table_copy_row_desc : 'Copy table row',
table_paste_row_before_desc : 'Paste table row before',
table_paste_row_after_desc : 'Paste table row after',
table_insert_desc : 'Insert a new table'
});
