<?php
//////////////////////////////////////////////////////////////////////
//       PHPAntiSpamForm v1.0 - sebflipper Copyright 2002           //
//                   http://www.sebflipper.com                      //
//                        Main Script File                          //
//                                                                  //
// Please DO NOT edit this file unless you know what you are doing  //
//                                                                  //
//        By using this script you agree to the Licence             //
//                                                                  //
//      !!!  Last updated by Seb Flipper on 01/03/2002 !!!          //
//////////////////////////////////////////////////////////////////////


// Beginning php

// Loading Config file
include ("mail.config.inc.php");

// Set up variables that will be saved in the cookies
// Name of cookie that holds the user's name
$n_name = $ID . "_Name";
// Name of cookie that holds the user's email
$n_email = $ID . "_Email";
// Name of cookie that holds the user's last login
$n_last = $ID . "_Last";

// These lines print the form with user input and mails to the webmaster.
if( isset($submit)) {
    Setcookie($n_last,Date("H:i d/m/Y"),time()+$cookie_life);
?>
    <html>
    <head>
    <title>Redirecting...</title>
    <SCRIPT LANGUAGE="JavaScript1.1">
<!-- Begin
function right(e) {
if (navigator.appName == 'Netscape' &&
(e.which == 3 || e.which == 2))
return false;
else if (navigator.appName == 'Microsoft Internet Explorer' &&
(event.button == 2 || event.button == 3)) {
alert("Sorry, you do not have permission to right click.");
return false;
}
return true;
}

document.onmousedown=right;
document.onmouseup=right;
if (document.layers) window.captureEvents(Event.MOUSEDOWN);
if (document.layers) window.captureEvents(Event.MOUSEUP);
window.onmousedown=right;
window.onmouseup=right;
//  End -->
</script>
    </head>
    <body
    onLoad="opener.location.href='<?php echo $sent_page; ?>'; window.close();">
  </body>
    You are being redirected, please wait...
<br><br><br><font size="1" face="Arial">Powered by <a href="http://www.sebflipper.com" target="_blank">PHPAntiSpamForm</a></font>
<?php
//foreach ($HTTP_POST_VARS as $var) {
foreach ($HTTP_POST_VARS as $key => $value) {
    $text .= "$key = $value \n";
}

$from = $email;
mail($admin_email,$subject,$text,"From: $from\nReply-To: $from\n");

// Print end and leave
    print $tail;
///////////////////

exit();


}

// This loop treats users who have not been to the site before.
if(!$$n_last) {
    if( ! isset($name)) { // if no name - display the form
    print $head;
?>

<?php echo $welcome_message; ?>
<!-- $PHP_SELF is the PHP way of referring to the current page -->
<form action="<?php echo $PHP_SELF ?>" method="POST" onSubmit='return ValidateForm()'>

<?php echo $javascript; ?>
<?php echo $input_form; ?>
    <br>
<!-- Submit button -->
<input type=submit value="Submit" name="submit" onclick="document.all.submit.style.visibility='hidden'"></form><br><br>
<br><br><br><font size="1" face="Arial">Powered by <a href="http://www.sebflipper.com" target="_blank">PHPAntiSpamForm</a></font>


<?php
        echo $tail;
        exit;
    } else {
        // Set cookies and continue
        Setcookie($n_name,$name,time()+$cookie_life);
        Setcookie($n_email,$email,time()+$cookie_life);
        $$n_name = $name;
        $$n_email = $email;
    }
}

// This loop treats repeat users.
Setcookie($n_last,Date("H:i d/m/Y"),time()+$cookie_life);
echo $head;
?>
<?php
// Stopping user from spaming webmaster!
if($$n_last)
    echo "You have already sent a message on " . $$n_last . ".";
?>
<br><br>
<?php echo $error_message; ?>
<br><br><br><font size="1" face="Arial">Powered by <a href="http://www.sebflipper.com" target="_blank">PHPAntiSpamForm</a></font>
<?php echo $tail ?>
