INSERT INTO `pet_country` VALUES ('AFG', 'Afghanistan');
INSERT INTO `pet_country` VALUES ('ALB', 'Albania');
INSERT INTO `pet_country` VALUES ('DZA', 'Algeria');
INSERT INTO `pet_country` VALUES ('ASM', 'American Samoa');
INSERT INTO `pet_country` VALUES ('AND', 'Andorra');
INSERT INTO `pet_country` VALUES ('AGO', 'Angola');
INSERT INTO `pet_country` VALUES ('AIA', 'Anguilla');
INSERT INTO `pet_country` VALUES ('ATG', 'Antigua and Barbuda');
INSERT INTO `pet_country` VALUES ('ARG', 'Argentina');
INSERT INTO `pet_country` VALUES ('ARM', 'Armenia');
INSERT INTO `pet_country` VALUES ('ABW', 'Aruba');
INSERT INTO `pet_country` VALUES ('AUS', 'Australia');
INSERT INTO `pet_country` VALUES ('AUT', 'Austria');
INSERT INTO `pet_country` VALUES ('AZE', 'Azerbaijan');
INSERT INTO `pet_country` VALUES ('BHS', 'Bahamas');
INSERT INTO `pet_country` VALUES ('BHR', 'Bahrain');
INSERT INTO `pet_country` VALUES ('BGD', 'Bangladesh');
INSERT INTO `pet_country` VALUES ('BRB', 'Barbados');
INSERT INTO `pet_country` VALUES ('BLR', 'Belarus');
INSERT INTO `pet_country` VALUES ('BEL', 'Belgium');
INSERT INTO `pet_country` VALUES ('BLZ', 'Belize');
INSERT INTO `pet_country` VALUES ('BEN', 'Benin');
INSERT INTO `pet_country` VALUES ('BMU', 'Bermuda');
INSERT INTO `pet_country` VALUES ('BTN', 'Bhutan');
INSERT INTO `pet_country` VALUES ('BOL', 'Bolivia');
INSERT INTO `pet_country` VALUES ('BIH', 'Bosnia and Herzegovina');
INSERT INTO `pet_country` VALUES ('BWA', 'Botswana');
INSERT INTO `pet_country` VALUES ('BRA', 'Brazil');
INSERT INTO `pet_country` VALUES ('VGB', 'British Virgin Islands');
INSERT INTO `pet_country` VALUES ('BRN', 'Brunei Darussalam');
INSERT INTO `pet_country` VALUES ('BGR', 'Bulgaria');
INSERT INTO `pet_country` VALUES ('BFA', 'Burkina Faso');
INSERT INTO `pet_country` VALUES ('BDI', 'Burundi');
INSERT INTO `pet_country` VALUES ('KHM', 'Cambodia');
INSERT INTO `pet_country` VALUES ('CMR', 'Cameroon');
INSERT INTO `pet_country` VALUES ('CAN', 'Canada');
INSERT INTO `pet_country` VALUES ('CPV', 'Cape Verde');
INSERT INTO `pet_country` VALUES ('CYM', 'Cayman Islands');
INSERT INTO `pet_country` VALUES ('CAF', 'Central African Republic');
INSERT INTO `pet_country` VALUES ('TCD', 'Chad');
INSERT INTO `pet_country` VALUES ('CHL', 'Chile');
INSERT INTO `pet_country` VALUES ('CHN', 'China');
INSERT INTO `pet_country` VALUES ('HKG', 'Hong Kong Special Administrative');
INSERT INTO `pet_country` VALUES ('MAC', 'Macao Special Administrative Region of China');
INSERT INTO `pet_country` VALUES ('COL', 'Colombia');
INSERT INTO `pet_country` VALUES ('COM', 'Comoros');
INSERT INTO `pet_country` VALUES ('COG', 'Congo');
INSERT INTO `pet_country` VALUES ('COK', 'Cook Islands');
INSERT INTO `pet_country` VALUES ('CRI', 'Costa Rica');
INSERT INTO `pet_country` VALUES ('CIV', 'Cote d\'Ivoire');
INSERT INTO `pet_country` VALUES ('HRV', 'Croatia');
INSERT INTO `pet_country` VALUES ('CUB', 'Cuba');
INSERT INTO `pet_country` VALUES ('CYP', 'Cyprus');
INSERT INTO `pet_country` VALUES ('CZE', 'Czech Republic');
INSERT INTO `pet_country` VALUES ('PRK', 'Democratic People\'s Republic of Korea');
INSERT INTO `pet_country` VALUES ('COD', 'Democratic Republic of the Congo');
INSERT INTO `pet_country` VALUES ('DNK', 'Denmark');
INSERT INTO `pet_country` VALUES ('DJI', 'Djibouti');
INSERT INTO `pet_country` VALUES ('DMA', 'Dominica');
INSERT INTO `pet_country` VALUES ('DOM', 'Dominican Republic');
INSERT INTO `pet_country` VALUES ('TMP', 'East Timor');
INSERT INTO `pet_country` VALUES ('ECU', 'Ecuador');
INSERT INTO `pet_country` VALUES ('EGY', 'Egypt');
INSERT INTO `pet_country` VALUES ('SLV', 'El Salvador');
INSERT INTO `pet_country` VALUES ('GNQ', 'Equatorial Guinea');
INSERT INTO `pet_country` VALUES ('ERI', 'Eritrea');
INSERT INTO `pet_country` VALUES ('EST', 'Estonia');
INSERT INTO `pet_country` VALUES ('ETH', 'Ethiopia');
INSERT INTO `pet_country` VALUES ('FRO', 'Faeroe Islands');
INSERT INTO `pet_country` VALUES ('FLK', 'Falkland Islands (Malvinas)');
INSERT INTO `pet_country` VALUES ('FJI', 'Fiji');
INSERT INTO `pet_country` VALUES ('FIN', 'Finland');
INSERT INTO `pet_country` VALUES ('FRA', 'France');
INSERT INTO `pet_country` VALUES ('GUF', 'French Guiana');
INSERT INTO `pet_country` VALUES ('PYF', 'French Polynesia');
INSERT INTO `pet_country` VALUES ('GAB', 'Gabon');
INSERT INTO `pet_country` VALUES ('GMB', 'Gambia');
INSERT INTO `pet_country` VALUES ('GEO', 'Georgia');
INSERT INTO `pet_country` VALUES ('DEU', 'Germany');
INSERT INTO `pet_country` VALUES ('GHA', 'Ghana');
INSERT INTO `pet_country` VALUES ('GIB', 'Gibraltar');
INSERT INTO `pet_country` VALUES ('GRC', 'Greece');
INSERT INTO `pet_country` VALUES ('GRL', 'Greenland');
INSERT INTO `pet_country` VALUES ('GRD', 'Grenada');
INSERT INTO `pet_country` VALUES ('GLP', 'Guadeloupe');
INSERT INTO `pet_country` VALUES ('GUM', 'Guam');
INSERT INTO `pet_country` VALUES ('GTM', 'Guatemala');
INSERT INTO `pet_country` VALUES ('GIN', 'Guinea');
INSERT INTO `pet_country` VALUES ('GNB', 'Guinea-Bissau');
INSERT INTO `pet_country` VALUES ('GUY', 'Guyana');
INSERT INTO `pet_country` VALUES ('HTI', 'Haiti');
INSERT INTO `pet_country` VALUES ('VAT', 'Holy See');
INSERT INTO `pet_country` VALUES ('HND', 'Honduras');
INSERT INTO `pet_country` VALUES ('HUN', 'Hungary');
INSERT INTO `pet_country` VALUES ('ISL', 'Iceland');
INSERT INTO `pet_country` VALUES ('IND', 'India');
INSERT INTO `pet_country` VALUES ('IDN', 'Indonesia');
INSERT INTO `pet_country` VALUES ('IRN', 'Iran (Islamic Republic of)');
INSERT INTO `pet_country` VALUES ('IRQ', 'Iraq');
INSERT INTO `pet_country` VALUES ('IRL', 'Ireland');
INSERT INTO `pet_country` VALUES ('ISR', 'Israel');
INSERT INTO `pet_country` VALUES ('ITA', 'Italy');
INSERT INTO `pet_country` VALUES ('JAM', 'Jamaica');
INSERT INTO `pet_country` VALUES ('JPN', 'Japan');
INSERT INTO `pet_country` VALUES ('JOR', 'Jordan');
INSERT INTO `pet_country` VALUES ('KAZ', 'Kazakhstan');
INSERT INTO `pet_country` VALUES ('KEN', 'Kenya');
INSERT INTO `pet_country` VALUES ('KIR', 'Kiribati');
INSERT INTO `pet_country` VALUES ('KWT', 'Kuwait');
INSERT INTO `pet_country` VALUES ('KGZ', 'Kyrgyzstan');
INSERT INTO `pet_country` VALUES ('LAO', 'Lao People\'s Democratic Republic');
INSERT INTO `pet_country` VALUES ('LVA', 'Latvia');
INSERT INTO `pet_country` VALUES ('LBN', 'Lebanon');
INSERT INTO `pet_country` VALUES ('LSO', 'Lesotho');
INSERT INTO `pet_country` VALUES ('LBR', 'Liberia');
INSERT INTO `pet_country` VALUES ('LBY', 'Libyan Arab Jamahiriya');
INSERT INTO `pet_country` VALUES ('LIE', 'Liechtenstein');
INSERT INTO `pet_country` VALUES ('LTU', 'Lithuania');
INSERT INTO `pet_country` VALUES ('LUX', 'Luxembourg');
INSERT INTO `pet_country` VALUES ('MDG', 'Madagascar');
INSERT INTO `pet_country` VALUES ('MWI', 'Malawi');
INSERT INTO `pet_country` VALUES ('MYS', 'Malaysia');
INSERT INTO `pet_country` VALUES ('MDV', 'Maldives');
INSERT INTO `pet_country` VALUES ('MLI', 'Mali');
INSERT INTO `pet_country` VALUES ('MLT', 'Malta');
INSERT INTO `pet_country` VALUES ('MHL', 'Marshall Islands');
INSERT INTO `pet_country` VALUES ('MTQ', 'Martinique');
INSERT INTO `pet_country` VALUES ('MRT', 'Mauritania');
INSERT INTO `pet_country` VALUES ('MUS', 'Mauritius');
INSERT INTO `pet_country` VALUES ('MEX', 'Mexico');
INSERT INTO `pet_country` VALUES ('FSM', 'Micronesia Federated States of,');
INSERT INTO `pet_country` VALUES ('MCO', 'Monaco');
INSERT INTO `pet_country` VALUES ('MNG', 'Mongolia');
INSERT INTO `pet_country` VALUES ('MSR', 'Montserrat');
INSERT INTO `pet_country` VALUES ('MAR', 'Morocco');
INSERT INTO `pet_country` VALUES ('MOZ', 'Mozambique');
INSERT INTO `pet_country` VALUES ('MMR', 'Myanmar');
INSERT INTO `pet_country` VALUES ('NAM', 'Namibia');
INSERT INTO `pet_country` VALUES ('NRU', 'Nauru');
INSERT INTO `pet_country` VALUES ('NPL', 'Nepal');
INSERT INTO `pet_country` VALUES ('NLD', 'Netherlands');
INSERT INTO `pet_country` VALUES ('ANT', 'Netherlands Antilles');
INSERT INTO `pet_country` VALUES ('NCL', 'New Caledonia');
INSERT INTO `pet_country` VALUES ('NZL', 'New Zealand');
INSERT INTO `pet_country` VALUES ('NIC', 'Nicaragua');
INSERT INTO `pet_country` VALUES ('NER', 'Niger');
INSERT INTO `pet_country` VALUES ('NGA', 'Nigeria');
INSERT INTO `pet_country` VALUES ('NIU', 'Niue');
INSERT INTO `pet_country` VALUES ('NFK', 'Norfolk Island');
INSERT INTO `pet_country` VALUES ('MNP', 'Northern Mariana Islands');
INSERT INTO `pet_country` VALUES ('NOR', 'Norway');
INSERT INTO `pet_country` VALUES ('PSE', 'Occupied Palestinian Territory');
INSERT INTO `pet_country` VALUES ('OMN', 'Oman');
INSERT INTO `pet_country` VALUES ('PAK', 'Pakistan');
INSERT INTO `pet_country` VALUES ('PLW', 'Palau');
INSERT INTO `pet_country` VALUES ('PAN', 'Panama');
INSERT INTO `pet_country` VALUES ('PNG', 'Papua New Guinea');
INSERT INTO `pet_country` VALUES ('PRY', 'Paraguay');
INSERT INTO `pet_country` VALUES ('PER', 'Peru');
INSERT INTO `pet_country` VALUES ('PHL', 'Philippines');
INSERT INTO `pet_country` VALUES ('PCN', 'Pitcairn');
INSERT INTO `pet_country` VALUES ('POL', 'Poland');
INSERT INTO `pet_country` VALUES ('PRT', 'Portugal');
INSERT INTO `pet_country` VALUES ('PRI', 'Puerto Rico');
INSERT INTO `pet_country` VALUES ('QAT', 'Qatar');
INSERT INTO `pet_country` VALUES ('KOR', 'Republic of Korea');
INSERT INTO `pet_country` VALUES ('MDA', 'Republic of Moldova');
INSERT INTO `pet_country` VALUES ('REU', 'Réunion');
INSERT INTO `pet_country` VALUES ('ROM', 'Romania');
INSERT INTO `pet_country` VALUES ('RUS', 'Russian Federation');
INSERT INTO `pet_country` VALUES ('RWA', 'Rwanda');
INSERT INTO `pet_country` VALUES ('SHN', 'Saint Helena');
INSERT INTO `pet_country` VALUES ('KNA', 'Saint Kitts and Nevis');
INSERT INTO `pet_country` VALUES ('LCA', 'Saint Lucia');
INSERT INTO `pet_country` VALUES ('SPM', 'Saint Pierre and Miquelon');
INSERT INTO `pet_country` VALUES ('VCT', 'Saint Vincent and the Grenadines');
INSERT INTO `pet_country` VALUES ('WSM', 'Samoa');
INSERT INTO `pet_country` VALUES ('SMR', 'San Marino');
INSERT INTO `pet_country` VALUES ('STP', 'Sao Tome and Principe');
INSERT INTO `pet_country` VALUES ('SAU', 'Saudi Arabia');
INSERT INTO `pet_country` VALUES ('SEN', 'Senegal');
INSERT INTO `pet_country` VALUES ('SYC', 'Seychelles');
INSERT INTO `pet_country` VALUES ('SLE', 'Sierra Leone');
INSERT INTO `pet_country` VALUES ('SGP', 'Singapore');
INSERT INTO `pet_country` VALUES ('SVK', 'Slovakia');
INSERT INTO `pet_country` VALUES ('SVN', 'Slovenia');
INSERT INTO `pet_country` VALUES ('SLB', 'Solomon Islands');
INSERT INTO `pet_country` VALUES ('SOM', 'Somalia');
INSERT INTO `pet_country` VALUES ('ZAF', 'South Africa');
INSERT INTO `pet_country` VALUES ('ESP', 'Spain');
INSERT INTO `pet_country` VALUES ('LKA', 'Sri Lanka');
INSERT INTO `pet_country` VALUES ('SDN', 'Sudan');
INSERT INTO `pet_country` VALUES ('SUR', 'Suriname');
INSERT INTO `pet_country` VALUES ('SJM', 'Svalbard and Jan Mayen Islands');
INSERT INTO `pet_country` VALUES ('SWZ', 'Swaziland');
INSERT INTO `pet_country` VALUES ('SWE', 'Sweden');
INSERT INTO `pet_country` VALUES ('CHE', 'Switzerland');
INSERT INTO `pet_country` VALUES ('SYR', 'Syrian Arab Republic');
INSERT INTO `pet_country` VALUES ('TWN', 'Taiwan Province of China');
INSERT INTO `pet_country` VALUES ('TJK', 'Tajikistan');
INSERT INTO `pet_country` VALUES ('THA', 'Thailand');
INSERT INTO `pet_country` VALUES ('MKD', 'The former Yugoslav Republic of Macedonia');
INSERT INTO `pet_country` VALUES ('TGO', 'Togo');
INSERT INTO `pet_country` VALUES ('TKL', 'Tokelau');
INSERT INTO `pet_country` VALUES ('TON', 'Tonga');
INSERT INTO `pet_country` VALUES ('TTO', 'Trinidad and Tobago');
INSERT INTO `pet_country` VALUES ('TUN', 'Tunisia');
INSERT INTO `pet_country` VALUES ('TUR', 'Turkey');
INSERT INTO `pet_country` VALUES ('TKM', 'Turkmenistan');
INSERT INTO `pet_country` VALUES ('TCA', 'Turks and Caicos Islands');
INSERT INTO `pet_country` VALUES ('TUV', 'Tuvalu');
INSERT INTO `pet_country` VALUES ('UGA', 'Uganda');
INSERT INTO `pet_country` VALUES ('UKR', 'Ukraine');
INSERT INTO `pet_country` VALUES ('ARE', 'United Arab Emirates');
INSERT INTO `pet_country` VALUES ('GBR', 'United Kingdom');
INSERT INTO `pet_country` VALUES ('TZA', 'United Republic of Tanzania');
INSERT INTO `pet_country` VALUES ('USA', 'United States');
INSERT INTO `pet_country` VALUES ('VIR', 'United States Virgin Islands');
INSERT INTO `pet_country` VALUES ('URY', 'Uruguay');
INSERT INTO `pet_country` VALUES ('UZB', 'Uzbekistan');
INSERT INTO `pet_country` VALUES ('VUT', 'Vanuatu');
INSERT INTO `pet_country` VALUES ('VEN', 'Venezuela');
INSERT INTO `pet_country` VALUES ('VNM', 'Viet Nam');
INSERT INTO `pet_country` VALUES ('WLF', 'Wallis and Futuna Islands');
INSERT INTO `pet_country` VALUES ('ESH', 'Western Sahara');
INSERT INTO `pet_country` VALUES ('YEM', 'Yemen');
INSERT INTO `pet_country` VALUES ('YUG', 'Yugoslavia');
INSERT INTO `pet_country` VALUES ('ZMB', 'Zambia');
INSERT INTO `pet_country` VALUES ('ZWE', 'Zimbabwe');
# --------------------------------------------------------


#
# Dumping data for table `pet_petition`
#

INSERT INTO `pet_petition` VALUES (1, 'SamplePetition', 0, 'Anonymous', 'name@example.org', 'Campaign Team', 1057118400, 1059688751, 1057118400, 0, 1272686400, 0, 0, 0, 0, 0, -1);


# Dumping data for table `pet_petitionText`
#

INSERT INTO `pet_petitionText` VALUES (2, 1, 'en', 'Sample Petition', NULL, 'Petition for Social Change', NULL, 'The text of the petition', NULL, '', NULL, '', NULL, '', NULL, '', '', '', 'Hello [FIRST_NAME],\r\n\r\nWe have record of you signing our petition at:\r\n   [HOME_URL]\r\n\r\nPlease click here to confirm and validate this record and your support:\r\n   [VERIFY_URL]\r\n\r\nThank you, \r\n\r\n', 'This appears at the top of an email2friend alert which your supporters may distribute', NULL, 0);

