<?php
/***************************************************************************
 * (c)2002-2004 Boesch IT-Consulting (info@boesch-it.de)
 ***************************************************************************/
$l_menus =
array(
	array(
		array("entry"=>$l_mainmenu,"url"=>"index.php?$langvar=$act_lang#top","level"=>0),
		array("entry"=>$l_logout,"url"=>"logout.php?$langvar=$act_lang","level"=>0)
	),
	array(
		array("entry"=>$l_general,"url"=>"index.php?$langvar=$act_lang#general","level"=>1),
		array("entry"=>$l_emoticons,"url"=>"emoticons.php?$langvar=$act_lang","level"=>3),
		array("entry"=>$l_icons,"url"=>"icons.php?$langvar=$act_lang","level"=>3),
		array("submenu"=>"1","entries"=>array(
			array("entry"=>$l_categories,"url"=>"index.php?$langvar=$act_lang#cats","level"=>1),
			array("entry"=>$l_edit_categories,"url"=>"categories.php?$langvar=$act_lang","level"=>1),
			array("entry"=>$l_wap_catlist,"url"=>"wap_catlist.php?$langvar=$act_lang","level"=>3),
			array("entry"=>$l_rss_catlist,"url"=>"rss_catlist.php?$langvar=$act_lang","level"=>3)
		)),
		array("submenu"=>"3","entries"=>array(
			array("entry"=>$l_files,"url"=>"index.php?$langvar=$act_lang#files","level"=>$attachlevel),
			array("entry"=>$l_adminfiles,"url"=>"attachs.php?$langvar=$act_lang","level"=>$attachlevel),
			array("entry"=>$l_files_cleanup,"url"=>"files_cleanup.php?$langvar=$act_lang","level"=>3),
			array("entry"=>$l_filetypes,"url"=>"mimetypes.php?$langvar=$act_lang","level"=>3)
		))
	),
	array(
		array("entry"=>$l_announce,"url"=>"index.php?$langvar=$act_lang#announce","level"=>$anlevel),
		array("entry"=>$l_editannouncements,"url"=>"announce.php?$langvar=$act_lang","level"=>$anlevel),
		array("entry"=>$l_viewcounts,"url"=>"anviews.php?$langvar=$act_lang","level"=>$anlevel),
		array("submenu"=>$anlevel,"entries"=>array(
			array("entry"=>$l_searching,"url"=>"index.php?$langvar=$act_lang#ansearch","level"=>$anlevel),
			array("entry"=>$l_search,"url"=>"ansearch.php?$langvar=$act_lang","level"=>$anlevel),
			array("entry"=>$l_rebuildsearch,"url"=>"rebuildansearch.php?$langvar=$act_lang","level"=>$anlevel)
		))
	),
	array(
		array("entry"=>$l_news,"url"=>"index.php?$langvar=$act_lang#news","level"=>1),
		array("entry"=>$l_editnews,"url"=>"news.php?$langvar=$act_lang","level"=>1),
		array("entry"=>$l_importnews,"url"=>"import_news.php?$langvar=$act_lang","level"=>$importlevel),
		array("entry"=>$l_reordernews,"url"=>"reordernews.php?$langvar=$act_lang","level"=>2),
		array("entry"=>$l_viewcounts,"url"=>"nviews.php?$langvar=$act_lang","level"=>2),
		array("entry"=>$l_topratings,"url"=>"ntop.php?$langvar=$act_lang","level"=>2),
		array("entry"=>$l_proposednews,"url"=>"proposes.php?$langvar=$act_lang","level"=>$nproplevel),
		array("entry"=>$l_listofcomments,"url"=>"clist.php?$langvar=$act_lang","level"=>2),
		array("submenu"=>2,"entries"=>array(
			array("entry"=>$l_searching,"url"=>"index.php?$langvar=$act_lang#newssearch","level"=>2),
			array("entry"=>$l_search,"url"=>"search.php?$langvar=$act_lang","level"=>2),
			array("entry"=>$l_rebuildsearch,"url"=>"rebuildsearch.php?$langvar=$act_lang","level"=>2)
		)),
		array("submenu"=>2,"entries"=>array(
			array("entry"=>$l_utils,"url"=>"index.php?$langvar=$act_lang#newsutils","level"=>2),
			array("entry"=>$l_purgenews,"url"=>"purgenews.php?$langvar=$act_lang","level"=>$pnlevel),
			array("entry"=>$l_synclinkdates,"url"=>"syncnewsld.php?$langvar=$act_lang","level"=>2)
		))
	),
	array(
		array("entry"=>$l_events,"url"=>"index.php?$langvar=$act_lang#events","level"=>1),
		array("entry"=>$l_editevents,"url"=>"events.php?$langvar=$act_lang","level"=>1),
		array("entry"=>$l_importevents,"url"=>"import_events.php?$langvar=$act_lang","level"=>$importlevel),
		array("entry"=>$l_viewcounts,"url"=>"evviews.php?$langvar=$act_lang","level"=>2),
		array("entry"=>$l_proposedevents,"url"=>"evproposes.php?$langvar=$act_lang","level"=>$evproplevel),
		array("submenu"=>2,"entries"=>array(
			array("entry"=>$l_searching,"url"=>"index.php?$langvar=$act_lang#evsearch","level"=>2),
			array("entry"=>$l_search,"url"=>"evsearch.php?$langvar=$act_lang","level"=>2),
			array("entry"=>$l_purgeevents,"url"=>"purgeevents.php?$langvar=$act_lang","level"=>$pevlevel)
		)),
		array("submenu"=>2,"entries"=>array(
			array("entry"=>$l_utils,"url"=>"index.php?$langvar=$act_lang#evutils","level"=>2),
			array("entry"=>$l_rebuildsearch,"url"=>"rebuildevsearch.php?$langvar=$act_lang","level"=>2),
			array("entry"=>$l_synclinkdates,"url"=>"syncevld.php?$langvar=$act_lang","level"=>2)
		))
	),
	array(
		array("entry"=>$l_settings,"url"=>"index.php?$langvar=$act_lang#set","level"=>$layoutlevel),
		array("entry"=>$l_layout,"url"=>$layoutlink,"level"=>$layoutlevel),
		array("entry"=>$l_syssettings,"url"=>"settings.php?$langvar=$act_lang","level"=>3),
		array("entry"=>$l_texts,"url"=>"texts.php?$langvar=$act_lang","level"=>3),
		array("entry"=>$l_defratings,"url"=>"ratings.php?$langvar=$act_lang","level"=>3),
		array("submenu"=>"3","entries"=>array(
			array("entry"=>$l_lists,"url"=>"index.php?$langvar=$act_lang#lists","level"=>3),
			array("entry"=>$l_freemailerlist,"url"=>"freemailer.php?$langvar=$act_lang","level"=>3),
			array("entry"=>$l_leacherlist,"url"=>"leacher.php?$langvar=$act_lang","level"=>3),
			array("entry"=>$l_badwordlist,"url"=>"badwords.php?$langvar=$act_lang","level"=>3)
		))
	),
	array(
		array("entry"=>$l_subscriptions,"url"=>"index.php?$langvar=$act_lang#subscriptions","level"=>$sublevel),
		array("entry"=>$l_subscribers,"url"=>"subscribers.php?$langvar=$act_lang","level"=>$sublevel),
		array("entry"=>$l_emailoldnews,"url"=>"sendoldnews.php?$langvar=$act_lang","level"=>$sublevel),
		array("entry"=>$l_emailnews,"url"=>"sendnews.php?$langvar=$act_lang","level"=>$nllevel)
	),
	array(
		array("entry"=>$l_user,"url"=>"index.php?$langvar=$act_lang#users","level"=>1),
		array("entry"=>$l_editusers,"url"=>"users.php?$langvar=$act_lang","level"=>1),
		array("entry"=>$l_pposter,"url"=>"poster.php?$langvar=$act_lang","level"=>$posterlevel),
		array("submenu"=>"3","entries"=>array(
			array("entry"=>$l_utils,"url"=>"index.php?$langvar=$act_lang#userutils","level"=>3),
			array("entry"=>$l_failed_logins,"url"=>"loginfailures.php?$langvar=$act_lang","level"=>3),
			array("entry"=>$l_ipbanlist,"url"=>"banlist.php?$langvar=$act_lang","level"=>3)
		))
	),
	array(
		array("entry"=>$l_administration2,"url"=>"index.php?$langvar=$act_lang#admin","level"=>3),
		array("entry"=>$l_admmsgs,"url"=>"admmsgs.php?$langvar=$act_lang","level"=>3),
		array("submenu"=>"3","entries"=>array(
			array("entry"=>$l_logs,"url"=>"index.php?$langvar=$act_lang#logs","level"=>$logaccess),
			array("entry"=>$l_emaillogs,"url"=>"emaillogs.php?$langvar=$act_lang","level"=>$emaillogaccess),
			array("entry"=>$l_searchlogs,"url"=>"searchlogs.php?$langvar=$act_lang","level"=>$searchlogaccess)
		)),
		array("submenu"=>"3","entries"=>array(
			array("entry"=>$l_utils,"url"=>"index.php?$langvar=$act_lang#adminutils","level"=>3),
			array("entry"=>$l_hostcache,"url"=>"hostcache.php?$langvar=$act_lang","level"=>3),
			array("entry"=>$l_cleansession,"url"=>"sessions.php?$langvar=$act_lang","level"=>3),
			array("entry"=>$l_shutdownsys,"url"=>"shutdown.php?$langvar=$act_lang","level"=>4),
			array("entry"=>$l_sys_stats,"url"=>"sys_stats.php?$langvar=$act_lang","level"=>3),
			array("entry"=>$l_internalinfo,"url"=>"internalinfo.php?$langvar=$act_lang","level"=>4)
		)),
		array("submenu"=>"3","entries"=>array(
			array("entry"=>$l_backup,"url"=>"index.php?$langvar=$act_lang#dbbackup","level"=>3),
			array("entry"=>$l_dbbackup,"url"=>"backup.php?$langvar=$act_lang","level"=>3),
			array("entry"=>$l_dbrestore,"url"=>"restore.php?$langvar=$act_lang","level"=>3)
		)),
		array("submenu"=>"3","entries"=>array(
			array("entry"=>$l_dbutils,"url"=>"index.php?$langvar=$act_lang#dbutils","level"=>4),
			array("entry"=>$l_repairtables,"url"=>"tblrepair.php?$langvar=$act_lang","level"=>4),
			array("entry"=>$l_optimizetables,"url"=>"tblpack.php?$langvar=$act_lang","level"=>4)
		)),
		array("submenu"=>"3","entries"=>array(
			array("entry"=>$l_codegens,"url"=>"index.php?$langvar=$act_lang#codegens","level"=>3),
			array("entry"=>$l_include_generator,"url"=>"inc_gen.php?$langvar=$act_lang","level"=>3),
			array("entry"=>$l_subscription_generator,"url"=>"inc_sub.php?$langvar=$act_lang","level"=>3)
		))
	)
);
?>