<?php

// skin_files.php
// Skin file auto generated by RW::Download v4.0 Beta 3 [14/05/04]
// It is highly recommended you do NOT edit this file
// Doing so could break the skinning engine and the script
// This skin can be edited by using the Skin Controls in the Admin CP

class skin_gallery
{
function thumb_table_head()
{
global $rwdInfo;
//--START--//
$SHTML = "<div class='tableborder'>
<table width='100%'  border='0' align='center' cellpadding='0' cellspacing='0'>
          <tr class='tabletitle'>
            <td width='18'><img src='{$rwdInfo->skinurl}/images/headerleft.gif' width='18' height='29'></td>
            <td background='{$rwdInfo->skinurl}/images/headerbg.gif'><b>&gt; {$rwdInfo->lang['screenshots']}</b></td>
            <td width='31'><img src='{$rwdInfo->skinurl}/images/headerright.gif' width='31' height='29'></td>
          </tr>
          <tr>
            <td colspan='3'><table width='100%'  border='0' cellspacing='1' cellpadding='3'><tr class='mainrow'>";
//--END--//
return $SHTML;
}

function thumb_plain($data)
{
global $rwdInfo;
//--START--//
$SHTML = <<<RWS
<center><a href='{$data['imageurl']}'>
<img src='{$data['thumburl']}' {$data['dims']} border=0></a>
</center>
RWS;
//--END--//
return $SHTML;
}

function thumb_table_foot()
{
global $rwdInfo;
//--START--//
$SHTML = "</table></td>
          </tr>
  </table>
</div>";
//--END--//
return $SHTML;
}

function thumb_end_row($data)
{
global $rwdInfo;
//--START--//
$SHTML = "</tr><tr class='mainrow'>";
//--END--//
return $SHTML;
}

function thumb_cell($data)
{
global $rwdInfo;
//--START--//
$SHTML = "<td width='{$data['cellwidth']}'>
<table border=0 cellspacing=0 cellpadding=2 width=100%>
<tr>
<td><center><a href='{$data['imageurl']}'>
<img src='{$data['thumburl']}' {$data['dims']} border=0></a>
</center>
</td></tr>
{$data['editrow']}
</table>";
//--END--//
return $SHTML;
}

function thumb_editrow($data)
{
global $rwdInfo;
//--START--//
$SHTML = "<tr>
<td><center>[ <a href='{$data['editlink']}'>{$rwdInfo->lang['delete']}</a> ]</center>
</td>
</tr>";
//--END--//
return $SHTML;
}


}

?>
