<?

/**************************************************************
 *                                                            *
 *                     Dellary                                *
 *            An easy to use Gallery Script                   *
 *                                                            *
 *              (c) 2001 by Marcus Proest                     *
 *                                                            *
 *   The script may be used and changed for private usage     *
 *         but this Header may not be removed                 *
 *                                                            *
 *                                                            *
 *                Component: footer.php3                      *
 *                                                            *
 **************************************************************/

?>



<hr><center>

<b><i>Dellary</i></b><br>

&copy; 2001 <a href="mailto:marcus@proest.net">Marcus Proest</a><br>

<a href="http://www.proest.net" target="_blank">www.proest.net</a>

</center>