<?php
/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/
/***************************************************************************
 * Created by: Boesch IT-Consulting (info@boesch-it.de)
 * (c)2002-2005 Boesch IT-Consulting
 * *************************************************************************/
echo "<script type=\"text/javascript\" language=\"JavaScript\" src=\"".$url_progsys."/jsFormCheck.js\"></script>";
?>
<script type="text/javascript" language="javascript">
<!--
function checkform()
{
	return true;
}
// -->
</script>
