<?
$li001 = "Upload Pictures";
$li002 = "Album Name";
$li003 = "New Album";
$li004 = "Picture";
$li005 = "Browse...";
$li006 = "Upload Pictures";
$li007 = "Wrong Password";
$li008 = "Back";
$li009 = "No Files or Files with 0 bytes chosen";
$li010 = "Password";
$li011 = "Status";
$li012 = "File %s too small (at least 15 Byte)";
$li013 = "Inernal Error (%s exists) Please inform <a href=\"mailto:dellary@proest.net?subject=li013\">dellary@proest.net</a>, and give information about the origin of the error.";
$li014 = "File %s was uploaded as %s.";
$li015 = "No Albumname specified.";
$li016 = "There is no directory \"$config[dir]\". Please create it or check your config.inc";



$ls001 = "Existing Albums";
$ls002 = "Untitled";
$ls003 = "Show";
$ls004 = "No existing Albums.";
?>