<?
$li001 = "Bilder Upload";
$li002 = "Album Name";
$li003 = "Neues Album";
$li004 = "Bild";
$li005 = "Durchsuchen";
$li006 = "Bilder hochladen";
$li007 = "Falsches Passwort";
$li008 = "Zur&uuml;ck";
$li009 = "Keine Dateien oder nur Dateien mit 0 Bytes Gr&ouml;&szlig;e ausgew&auml;hlt.";
$li010 = "Passwort";
$li011 = "Status";
$li012 = "Datei %s zu klein (mindestens 15 Byte)";
$li013 = "Interner Fehler (%s exisitert) Bitte informieren Sie <a href=\"mailto:dellary@proest.net?subject=li013\">dellary@proest.net</a>, und geben Sie möglichst detaillierte Einzelheiten über die Herkunft des Fehlers an.";
$li014 = "Datei %s wurde als %s. hochgeladen.";
$li015 = "Kein Albumname angegeben.";
$li016 = "Verzeichniss \"$config[dir]\" nicht gefunden. Bitte erstellen sie es oder &uuml;berpr&uuml;fen sie die Datei config.inc";

$ls001 = "Vorhandene Alben";
$ls002 = "Unbenannt";
$ls003 = "Anzeigen";
$ls004 = "Keine Alben vorhanden.";
?>          