DROP TABLE IF EXISTS
`CACHEDATA` ,
`UidNumber` ,
`active_sessions` ,
`active_sessions_split` ,
`auth_user` ,
`auth_user_md5` ,
`be_action` ,
`be_action2contact` ,
`be_action2section` ,
`be_actionText` ,
`be_actionType` ,
`be_article2section` ,
`be_articleText` ,
`be_articles` ,
`be_bib` ,
`be_bib2category` ,
`be_bib2country` ,
`be_bib2keywords` ,
`be_bib2profile2role` ,
`be_bib2region` ,
`be_bibMLA` ,
`be_bib_category` ,
`be_bib_country` ,
`be_bib_language` ,
`be_bib_region` ,
`be_bib_types` ,
`be_categories` ,
`be_category2item` ,
`be_contact` ,
`be_contactType` ,
`be_country2region` ,
`be_event` ,
`be_eventText` ,
`be_followup` ,
`be_followup2contact` ,
`be_followup2group` ,
`be_image2section` ,
`be_imageText` ,
`be_images` ,
`be_keywords` ,
`be_keyword2article` ,
`be_language` ,
`be_link` ,
`be_link2articlesGroup` ,
`be_link2articlesGroupText` ,
`be_link2section` ,
`be_linkText` ,
`be_linkTextValidation` ,
`be_profession` ,
`be_profile` ,
`be_profile2category` ,
`be_profile2country` ,
`be_profile2keywords` ,
`be_profile2nationality` ,
`be_profile2profession` ,
`be_profile2region` ,
`be_profile2spokenLanguages` ,
`be_profile2upload` ,
`be_profile_keywords` ,
`be_profile_photo` ,
`be_profile_role` ,
`be_publisher` ,
`be_rsstool` ,
`be_section2section` ,
`be_sectionText` ,
`be_sections` ,
`be_subsite_block_lut` ,
`be_subsite_types` ,
`be_subsites` ,
`be_target` ,
`be_targetType` ,
`be_upload` ,
`db_sequence` ,
`pet_alert` ,
`pet_country` ,
`pet_data` ,
`pet_letters` ,
`pet_main` ,
`pet_petition` ,
`pet_petition2contact` ,
`pet_petition2section` ,
`pet_petitionText` ,
`psl_author` ,
`psl_author_group_lut` ,
`psl_block` ,
`psl_blockText` ,
`psl_block_type` ,
`psl_comment` ,
`psl_commentcount` ,
`psl_glossary` ,
`psl_group` ,
`psl_group_group_lut` ,
`psl_group_permission_lut` ,
`psl_group_section_lut` ,
`psl_infolog` ,
`psl_mailinglist` ,
`psl_mailinglist_frequency` ,
`psl_permission` ,
`psl_poll_answer` ,
`psl_poll_question` ,
`psl_poll_voter` ,
`psl_quote` ,
`psl_section` ,
`psl_section_block_lut` ,
`psl_section_lut` ,
`psl_section_submission_lut` ,
`psl_story` ,
`psl_submission` ,
`psl_topic` ,
`psl_topic_lut` ,
`psl_topic_submission_lut` ,
`psl_variable`,
`be_image2articleText`,
`be_upload2article`,
`be_articleTextOptions`,
`be_history`,
`be_feedback`,
`be_blockcache`,
`Feedback`,
`be_hits`,
`be_catalog`,
`be_catalogText`,
`be_keyword2catalog`,
`be_target2participant`,
`be_targetFinder`,
`be_targetFinder2action`,
`be_mutex`,
`be_card`,
`be_card2action`,
`be_card2petition`,
`be_card2section`,
`be_cardText`;
