REPLACE INTO settings VALUES (94,'Use traditional Members Gallery configuration?','memformat','','yes',57,2);
REPLACE INTO settings VALUES (95,'Display headers during SlideShows?','slidehead','','yes',58,2);
REPLACE INTO settings VALUES (97,'Maximum multimedia upload size in kB','mmuploadsize','','2000',88,3);
REPLACE INTO settings VALUES (98,'Allow users to create Personal Albums?','allowpa','','yes',53,5);
REPLACE INTO settings VALUES (99,'Allow multimedia uploads?','allowmedia','','no',88,3);
REPLACE INTO settings VALUES (100,'Allow members to rate photos?','allowrate','','yes',54,5);
REPLACE INTO settings VALUES (101,'Display new comments/photos indicator on index?','displaynew','','no',58,2);
ALTER TABLE users ADD site VARCHAR(30) default NULL;
ALTER TABLE users ADD views int(10) NOT NULL default '0';
ALTER TABLE useralbums ADD isprivate varchar(4) NOT NULL default 'no';
ALTER TABLE useralbums ADD password VARCHAR(16) NOT NULL; 
ALTER TABLE users ADD offset SMALLINT(2) UNSIGNED DEFAULT '0' NOT NULL;
ALTER TABLE photos ADD watermarked varchar(5) NOT NULL default 'no';
CREATE TABLE favorites (id smallint(4) NOT NULL auto_increment, userid int(8) NOT NULL default '0', photo int(11) NOT NULL default '0', PRIMARY KEY  (id), KEY parent (photo)) TYPE=MyISAM;
CREATE TABLE laston (cat smallint(4) NOT NULL default '0', userid mediumint(9) NOT NULL default '0', laston int(11) unsigned default NULL, PRIMARY KEY  (cat,userid)) TYPE=MyISAM;
CREATE TABLE ipcache (id int(10) NOT NULL auto_increment,userid INT(25) NOT NULL, ipaddr VARCHAR(75) NOT NULL, date INT(11) UNSIGNED, type VARCHAR(4) NOT NULL, photo INT(10) NOT NULL, PRIMARY KEY (id)) TYPE=MyISAM;
REPLACE INTO sort VALUES (6, 'Random', 'ORDER BY RAND()');
REPLACE INTO sort VALUES (5, 'Least Popular', 'ORDER BY rating, views');
REPLACE INTO sort VALUES (4, 'Most Popular', 'ORDER BY rating DESC, views DESC');
REPLACE INTO sort VALUES (7, 'Alphabetical', 'ORDER BY bigimage');
DELETE FROM settings WHERE id=73;
DELETE FROM settings WHERE id=74;
DELETE FROM settings WHERE id=88;
DELETE FROM settings WHERE id=39;
DELETE FROM settings WHERE id=40;
DELETE FROM settings WHERE id=96;