// HE lang variables by Liron Newman, http://eesh.net

tinyMCE.addToLang('',{
theme_style_select : '-- ñéâðåðåú --',
theme_code_desc : 'òøåê àú ÷åã ä-HTML',
theme_code_title : 'òåøê ÷åã HTML',
theme_code_wordwrap : 'âìéùú ùåøåú',
theme_sub_desc : 'ëúá úçúé',
theme_sup_desc : 'ëúá òéìé',
theme_hr_desc : 'äëðñ ÷å àåô÷é',
theme_removeformat_desc : 'äñø òéöåá',
theme_custom1_desc : 'äúéàåø ùìê ëàï',
insert_image_border : 'âáåì',
insert_image_dimensions : 'îéîãéí',
insert_image_vspace : 'çìì àðëé',
insert_image_hspace : 'çìì àåô÷é',
insert_image_align : 'ééùåø',
insert_image_align_default : 'áøéøú îçãì',
insert_image_align_baseline : 'ì÷å äáñéñ',
insert_image_align_top : 'ìîòìä',
insert_image_align_middle : 'ìàîöò',
insert_image_align_bottom : 'ìîèä',
insert_image_align_texttop : 'ìøàù äè÷ñè',
insert_image_align_absmiddle : 'ìàîöò îåçìè',
insert_image_align_absbottom : 'ì÷öä úçúåï îåçìè',
insert_image_align_left : 'ìùîàì',
insert_image_align_right : 'ìéîéï',
theme_font_size : 'âåãì âåôï',
theme_fontdefault : '-- îùôçú âåôðéí --',
theme_block : '-- òéöåá --',
theme_paragraph : 'ôñ÷ä',
theme_div : '÷èò',
theme_address : 'ëúåáú',
theme_pre : 'îòåöá îøàù',
theme_h1 : 'ëåúøú 1',
theme_h2 : 'ëåúøú 2',
theme_h3 : 'ëåúøú 3',
theme_h4 : 'ëåúøú 4',
theme_h5 : 'ëåúøú 5',
theme_h6 : 'ëåúøú 6',
theme_colorpicker_title : 'áçø öáò',
theme_colorpicker_apply : 'äçì',
theme_forecolor_desc : 'áçø öáò è÷ñè',
theme_backcolor_desc : 'áçø öáò ø÷ò',
theme_charmap_title : 'áçø úå îéåçã',
theme_charmap_desc : 'äëðñ úå îéåçã',
theme_visualaid_desc : 'äçìó îöá ÷ååéí îðçéí/øëéáéí áìúé-ðøàéí',
insert_anchor_title : 'äëðñ/òøåê òåâï',
insert_anchor_name : 'ùí äòåâï',
theme_anchor_desc : 'äëðñ/òøåê òåâï',
theme_insert_link_titlefield : 'ëåúøú',
theme_clipboard_msg : 'ôòåìåú äòú÷ä/âæéøä/äãá÷ä àéðï ðúîëåú úçú Mozilla å-Firefox.\näàí áøöåðê ì÷áì îéãò ðåñó àåãåú ðåùà æä?',
theme_path : 'ðúéá',
cut_desc : 'âæåø',
copy_desc : 'äòú÷',
paste_desc : 'äãá÷',
link_list : 'øùéîú ÷éùåøéí',
image_list : 'øùéîú úîåðåú',
browse : 'ñééø',
image_props_desc : 'îàôééðé úîåðä',
newdocument_desc : 'îñîê çãù',
class_name : 'îçì÷ä',
newdocument : 'äàí àúä áèåç ùáøöåðê ìð÷åú àú ëì äúåëï?',
about_title : 'àåãåú TinyMCE',
about : 'àåãåú',
license : 'øéùéåï',
plugins : 'úåñôéí',
plugin : 'úåñó',
author : 'îçáø',
version : 'âøñä',
loaded_plugins : 'úåñôéí ôòéìéí',
help : 'òæøä',
not_set : '-- ìà îåâãø --',
close : 'ñâéøä',
toolbar_focus : 'òáåø àì ëôúåøé äëìéí - Alt+Q, òáåø àì äòåøê - Alt-Z, òáåø àì ðúéá òéöåá - Alt-X'
});
