// Russian lang variables cp1251

tinyMCE.addToLang('',{
theme_style_select : '-- Ñòèëè --',
theme_code_desc : 'Ðåäàêòèðîâàòü HTML êîäû',
theme_code_title : 'Ðåäàêòîð HTML êîäîâ',
theme_code_wordwrap : 'Ïåðåíîñ ïî ñëîâàì',
theme_sub_desc : 'Íèæíèé èíäåêñ',
theme_sup_desc : 'Âåðõíèé èíäåêñ',
theme_hr_desc : 'Âñòàâèòü ãîðèçîíòàëüíûé ðàçäåëèòåëü',
theme_removeformat_desc : 'Óáðàòü ôîðìàòèðîâàíèå',
theme_custom1_desc : 'Âàøå ïðîèçâîëüíîå îïèñàíèå',
insert_image_border : 'Ðàìêà',
insert_image_dimensions : 'Ðàçìåðû',
insert_image_vspace : 'Âåðòèêàëüíûé îòñòóï',
insert_image_hspace : 'Ãîðèçîíòàëüíûé îòñòóï',
insert_image_align : 'Âûðàâíèâàíèå',
insert_image_align_default : '-- Íå çàäàíî --',
insert_image_align_baseline : 'Ïî áàçîâîé ëèíèè',
insert_image_align_top : 'Ïî âåðõó',
insert_image_align_middle : 'Ïîñðåäèíå',
insert_image_align_bottom : 'Ïî íèçó',
insert_image_align_texttop : 'Ïî âåðõó òåêñòà',
insert_image_align_absmiddle : 'Àáñîëþòíî ïîñðåäèíå',
insert_image_align_absbottom : 'Àáñîëþòíî ñâåðõó',
insert_image_align_left : 'Âëåâî',
insert_image_align_right : 'Âïðàâî',
theme_font_size : '-- Ðàçìåð øðèôòà --',
theme_fontdefault : '-- Ñåìåéñòâî øðèôòîâ --',
theme_block : '-- Ôîðìàò --',
theme_paragraph : 'Àáçàö',
theme_div : 'Div',
theme_address : 'Ñòèëü àäðåñà',
theme_pre : ':`Ïðåäâàðèòåëüíî ôîðìàòèðîâàííûé',
theme_h1 : 'Çàãîëîâîê 1',
theme_h2 : 'Çàãîëîâîê 2',
theme_h3 : 'Çàãîëîâîê 3',
theme_h4 : 'Çàãîëîâîê 4',
theme_h5 : 'Çàãîëîâîê 5',
theme_h6 : 'Çàãîëîâîê 6',
theme_colorpicker_title : 'Âûáðàòü öâåò',
theme_colorpicker_apply : 'Ïðèìåíèòü',
theme_forecolor_desc : 'Âûáðàòü öâåò òåêñòà',
theme_backcolor_desc : 'Âûáðàòü öâåò ôîíà',
theme_charmap_title : 'Âûáîð ïðîèçâîëüíîãî ñèìâîëà',
theme_charmap_desc : 'Âñòàâèòü ïðîèçâîëüíûé ñèìâîë',
theme_visualaid_desc : 'Ïîêàçàòü ãðàíèöû ñêðûòûõ ýëåìåíòîâ',
insert_anchor_title : 'Âñòàâèòü/ðåäàêòèðîâàòü ÿêîðü',
insert_anchor_name : 'Èìÿ ÿêîðÿ',
theme_anchor_desc : 'Âñòàâèòü/ðåäàêòèðîâàòü ÿêîðü',
theme_insert_link_titlefield : 'Çàãîëîâîê',
theme_clipboard_msg : 'Êîïèðîâàòü/Âûðåçàòü/Âñòàâèòü íåäîñòóïíû äëÿ Mozilla è Firefox.\nÕîòèòå óçíàòü îá ýòîì ïîäðîáíåå?',
theme_path : 'Ïóòü',
cut_desc : 'Âûðåçàòü',
copy_desc : 'Êîïèðîâàòü',
paste_desc : 'Âñòàâèòü',
link_list : 'Ïåðå÷àíü ññûëîê',
image_list : 'Ïåðå÷åíü êàðòèíîê',
browse : 'Ïîäîáðàòü',
image_props_desc : 'Ñâîéñòâà êàðòèíêè',
newdocument_desc : 'Íîâûé äîêóìåíò',
class_name : 'Êëàññ',
newdocument : 'Âû óâåðåíû, ÷òî õîòèòå î÷èñòèòü âñ¸ ñîäåðæèìîå?',
about_title : 'Î TinyMCE',
about : 'Î TinyMCE',
license : 'Ëèöåíçèÿ',
plugins : 'Ïëàãèíû',
plugin : 'Ïëàãèí',
author : 'Àâòîð',
version : 'Âåðñèÿ',
loaded_plugins : 'Çàãðóæåííûå ïëàãèíû',
help : 'Ïîìîùü',
not_set : '-- íå óñòàíîâëåíî --',
close : 'Çàêðûòü',
toolbar_focus : 'Ïåðåìåñòèòü ôîêóñ íà ïàíåëü èíñòðóìåíòîâ - Alt+Q, Ïåðåìåñòèòü ôîêóñ â ðåäàêòîð - Alt-Z, Ïåðåìåñòèòü ôîêóñ íà ýëåìåíò ïóòè - Alt-X'
});
