// Russian lang variables KOI8-R

tinyMCE.addToLang('',{
theme_style_select : '-- óÔÉÌÉ --',
theme_code_desc : 'òÅÄÁËÔÉÒÏ×ÁÔØ HTML ËÏÄÙ',
theme_code_title : 'òÅÄÁËÔÏÒ HTML ËÏÄÏ×',
theme_code_wordwrap : 'ðÅÒÅÎÏÓ ÐÏ ÓÌÏ×ÁÍ',
theme_sub_desc : 'îÉÖÎÉÊ ÉÎÄÅËÓ',
theme_sup_desc : '÷ÅÒÈÎÉÊ ÉÎÄÅËÓ',
theme_hr_desc : '÷ÓÔÁ×ÉÔØ ÇÏÒÉÚÏÎÔÁÌØÎÙÊ ÒÁÚÄÅÌÉÔÅÌØ',
theme_removeformat_desc : 'õÂÒÁÔØ ÆÏÒÍÁÔÉÒÏ×ÁÎÉÅ',
theme_custom1_desc : '÷ÁÛÅ ÐÒÏÉÚ×ÏÌØÎÏÅ ÏÐÉÓÁÎÉÅ',
insert_image_border : 'òÁÍËÁ',
insert_image_dimensions : 'òÁÚÍÅÒÙ',
insert_image_vspace : '÷ÅÒÔÉËÁÌØÎÙÊ ÏÔÓÔÕÐ',
insert_image_hspace : 'çÏÒÉÚÏÎÔÁÌØÎÙÊ ÏÔÓÔÕÐ',
insert_image_align : '÷ÙÒÁ×ÎÉ×ÁÎÉÅ',
insert_image_align_default : '-- îÅ ÚÁÄÁÎÏ --',
insert_image_align_baseline : 'ðÏ ÂÁÚÏ×ÏÊ ÌÉÎÉÉ',
insert_image_align_top : 'ðÏ ×ÅÒÈÕ',
insert_image_align_middle : 'ðÏÓÒÅÄÉÎÅ',
insert_image_align_bottom : 'ðÏ ÎÉÚÕ',
insert_image_align_texttop : 'ðÏ ×ÅÒÈÕ ÔÅËÓÔÁ',
insert_image_align_absmiddle : 'áÂÓÏÌÀÔÎÏ ÐÏÓÒÅÄÉÎÅ',
insert_image_align_absbottom : 'áÂÓÏÌÀÔÎÏ Ó×ÅÒÈÕ',
insert_image_align_left : '÷ÌÅ×Ï',
insert_image_align_right : '÷ÐÒÁ×Ï',
theme_font_size : '-- òÁÚÍÅÒ ÛÒÉÆÔÁ --',
theme_fontdefault : '-- óÅÍÅÊÓÔ×Ï ÛÒÉÆÔÏ× --',
theme_block : '-- æÏÒÍÁÔ --',
theme_paragraph : 'áÂÚÁÃ',
theme_div : 'Div',
theme_address : 'óÔÉÌØ ÁÄÒÅÓÁ',
theme_pre : ':`ðÒÅÄ×ÁÒÉÔÅÌØÎÏ ÆÏÒÍÁÔÉÒÏ×ÁÎÎÙÊ',
theme_h1 : 'úÁÇÏÌÏ×ÏË 1',
theme_h2 : 'úÁÇÏÌÏ×ÏË 2',
theme_h3 : 'úÁÇÏÌÏ×ÏË 3',
theme_h4 : 'úÁÇÏÌÏ×ÏË 4',
theme_h5 : 'úÁÇÏÌÏ×ÏË 5',
theme_h6 : 'úÁÇÏÌÏ×ÏË 6',
theme_colorpicker_title : '÷ÙÂÒÁÔØ Ã×ÅÔ',
theme_colorpicker_apply : 'ðÒÉÍÅÎÉÔØ',
theme_forecolor_desc : '÷ÙÂÒÁÔØ Ã×ÅÔ ÔÅËÓÔÁ',
theme_backcolor_desc : '÷ÙÂÒÁÔØ Ã×ÅÔ ÆÏÎÁ',
theme_charmap_title : '÷ÙÂÏÒ ÐÒÏÉÚ×ÏÌØÎÏÇÏ ÓÉÍ×ÏÌÁ',
theme_charmap_desc : '÷ÓÔÁ×ÉÔØ ÐÒÏÉÚ×ÏÌØÎÙÊ ÓÉÍ×ÏÌ',
theme_visualaid_desc : 'ðÏËÁÚÁÔØ ÇÒÁÎÉÃÙ ÓËÒÙÔÙÈ ÜÌÅÍÅÎÔÏ×',
insert_anchor_title : '÷ÓÔÁ×ÉÔØ/ÒÅÄÁËÔÉÒÏ×ÁÔØ ÑËÏÒØ',
insert_anchor_name : 'éÍÑ ÑËÏÒÑ',
theme_anchor_desc : '÷ÓÔÁ×ÉÔØ/ÒÅÄÁËÔÉÒÏ×ÁÔØ ÑËÏÒØ',
theme_insert_link_titlefield : 'úÁÇÏÌÏ×ÏË',
theme_clipboard_msg : 'ëÏÐÉÒÏ×ÁÔØ/÷ÙÒÅÚÁÔØ/÷ÓÔÁ×ÉÔØ ÎÅÄÏÓÔÕÐÎÙ ÄÌÑ Mozilla É Firefox.\nèÏÔÉÔÅ ÕÚÎÁÔØ ÏÂ ÜÔÏÍ ÐÏÄÒÏÂÎÅÅ?',
theme_path : 'ðÕÔØ',
cut_desc : '÷ÙÒÅÚÁÔØ',
copy_desc : 'ëÏÐÉÒÏ×ÁÔØ',
paste_desc : '÷ÓÔÁ×ÉÔØ',
link_list : 'ðÅÒÅÞÁÎØ ÓÓÙÌÏË',
image_list : 'ðÅÒÅÞÅÎØ ËÁÒÔÉÎÏË',
browse : 'ðÏÄÏÂÒÁÔØ',
image_props_desc : 'ó×ÏÊÓÔ×Á ËÁÒÔÉÎËÉ',
newdocument_desc : 'îÏ×ÙÊ ÄÏËÕÍÅÎÔ',
class_name : 'ëÌÁÓÓ',
newdocument : '÷Ù Õ×ÅÒÅÎÙ, ÞÔÏ ÈÏÔÉÔÅ ÏÞÉÓÔÉÔØ ×Ó£ ÓÏÄÅÒÖÉÍÏÅ?',
about_title : 'ï TinyMCE',
about : 'ï TinyMCE',
license : 'ìÉÃÅÎÚÉÑ',
plugins : 'ðÌÁÇÉÎÙ',
plugin : 'ðÌÁÇÉÎ',
author : 'á×ÔÏÒ',
version : '÷ÅÒÓÉÑ',
loaded_plugins : 'úÁÇÒÕÖÅÎÎÙÅ ÐÌÁÇÉÎÙ',
help : 'ðÏÍÏÝØ',
not_set : '-- ÎÅ ÕÓÔÁÎÏ×ÌÅÎÏ --',
close : 'úÁËÒÙÔØ',
toolbar_focus : 'ðÅÒÅÍÅÓÔÉÔØ ÆÏËÕÓ ÎÁ ÐÁÎÅÌØ ÉÎÓÔÒÕÍÅÎÔÏ× - Alt+Q, ðÅÒÅÍÅÓÔÉÔØ ÆÏËÕÓ × ÒÅÄÁËÔÏÒ - Alt-Z, ðÅÒÅÍÅÓÔÉÔØ ÆÏËÕÓ ÎÁ ÜÌÅÍÅÎÔ ÐÕÔÉ - Alt-X'
});
