<?php

/***************************************************************************

 module.php
 -----------
 copyright : (C) 2005 - The iziContents Development Team

 iziContents version : 1.0
 fileversion : 1.0.1
 change date : 30 - 08 - 2005
 ***************************************************************************/

/***************************************************************************
 The iziContents Development Team offers no warranties on this script.
 The owner/licensee of the script is solely responsible for any problems
 caused by installation of the script or use of the script.

 All copyright notices regarding iziContents and ezContents must remain intact on the scripts and in the HTML for the scripts.

 For more info on iziContents,
 visit http://www.izicontents.com */
 
/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the License which can be found within the
 *   zipped package. Under the licence of GPL/GNU.
 *
 ***************************************************************************/
 
 /***************************************************************************
 *
 *   This file uses html2fpdf to generate the pdf-files
 *   goto: html2fpdf.sourceforge.net/  for more information
 *
 ***************************************************************************/

require_once ("./rootdatapath.php");


require_once ($GLOBALS["rootdp"]."include/content.php");
require ($GLOBALS["rootdp"]."include/html2fpdf/html2fpdf.php");
includeLanguageFiles('admin','main');


// getContents
if ($GLOBALS["gsLanguage"] == $GLOBALS["gsDefault_language"]) {
	$strQuery = "SELECT * FROM ".$GLOBALS["eztbContents"]." WHERE contentname ='".$_GET["article"]."' AND language='".$GLOBALS["gsLanguage"]."'";
} else {
	$lOrder = '';
	if ($GLOBALS["gsLanguage"] > $GLOBALS["gsDefault_language"]) { $lOrder = ' DESC'; }
	$strQuery = "SELECT * FROM ".$GLOBALS["eztbContents"]." WHERE contentname ='".$_GET["article"]."' AND (language='".$GLOBALS["gsLanguage"]."' OR language='".$GLOBALS["gsDefault_language"]."') ORDER BY language".$lOrder;
}
$result = dbRetrieve($strQuery,true,0,0);
// Creating Output Buffer
ob_start();

HTMLHeader($title);
StyleSheet();

?>
<body leftmargin="0" topmargin="0" rightmargin="0" bottommargin="0" marginwidth="0" marginheight="0">
<?php
$bEncodeHTML = true;
$nContentName = '';
$file = '';
while ($rsContent = dbFetch($result)) {
	if ($rsContent["contentname"] != $nContentName) {
		$nContentName = $rsContent["contentname"];
	}
	strGetAuthorGlobals($rsContent["authorid"]);
	$file = SetName($nContentName);
	PrintContent($rsContent);
}
dbFreeResult($result);




?>
<p align="center"><font size="-3">generated by iziContents using HTML2FPDF <?= HTML2FPDF_VERSION ?></font></p>
</body>
</html>
<?php
// copy Buffer into string and restore internal Buffer
$page = ob_get_contents();
ob_end_clean();


// creating new pdf-objekt

$pdf = new HTML2FPDF();
$pdf->AddPage();
$pdf->WriteHTML($page);
$pdf->Output($file, 'I');




function PrintContent($rsContent)
{
	SetHeader($rsContent["title"]);
	PrintContentBody($rsContent);
} // function PrintContent()

function SetHeader($header, $author){
?>
	<?= "<p align='center'><font size='-3'>Content taken from ".$GLOBALS["websiteurl"]." by ".$GLOBALS["authorname"]."</font></p>";?>	
	<?= "<p><b>".$header."</b></p>"; ?>
<?php
}//SetHeader

function PrintContentBody($rsContent)
{
	$bEncodeHTML = true;
	?>
	<?php 
	$contentpages = explode("[pagebreak]",$rsContent["cbody"]);
	$contentpage = implode('<hr style="border-style:dashed"/><p style="page-break-before:always"></p>',$contentpages);
	echo ext_print($contentpage, $bEncodeHTML, 'L', 'Y');
}//PrintContentBody

function SetName($name){
	$name = trim($name);
	$name = str_replace(' ', '_', $name);
	
	return $name;
}//SetName



?>
