CREATE TABLE al_email (
  login varchar(30) NOT NULL default '',
  title varchar(100) NOT NULL default '',
  content text NOT NULL,
  mailto varchar(10) NOT NULL default '',
  PRIMARY KEY  (login)
) TYPE=MyISAM;

INSERT INTO al_email VALUES ('invite', 'Link Exchange Request for [name]', 'Hi,\r\n\r\nWe checked your site, [name], and would like invite you to exchange links. We use AutoLinks, an automated link exchange system, which means you\'ll be sure to get a fair amount of visitors back. To prevent the hassle of signing up, we have already added an account for your site, so you just have to use the links below and your link will appear in our listing tomorrow.\r\n\r\n[links]\r\n\r\nWe have assigned a random password to access your account. You may change your password there, check your statistics and get more information about linking us:\r\n\r\n  Site Login: [login]\r\n  Password: [pass]\r\n  Link: [refarea]\r\n\r\nIn the advanced linking page (link at the top of the page), we also invite you to upload the images for your site. If you send us visitors, your images may have a chance to be featured!\r\n\r\n\r\nThanks!\r\n\r\n[admin_name]\r\n[admin_email]', 'referrer');
INSERT INTO al_email VALUES ('confirm', '[name] Successfully Added', 'Hi,\r\n\r\nThis is an automatic notification to confirm that [name] has been added in our database. The hits you send will now be counted and your link will show up the day after you start sending hits. Please use the following links only:\r\n\r\n[links]\r\n\r\nYou may check your statistics, update your site information and get more information about linking us by logging into your account using the login and password below. In the advanced linking, we also invite you to upload the images for your site if you haven\'t already done so. If you send us enough hits, your images may have a chance to be featured!\r\n\r\n  Site Login: [login]\r\n  Password: [pass]\r\n  Link: [refarea]\r\n\r\n\r\nThanks!\r\n\r\n[admin_name]\r\n[admin_email]', 'referrer');
INSERT INTO al_email VALUES ('mod_accept', '[name] Approved!', 'Hi,\r\n\r\nThis is an automatic notification to let you know that [name] has been approved in our database. The hits you send will now be counted and your link will show up (the day after you start sending hits). Please use the following links only:\r\n\r\n[links]\r\n\r\nYou may check your statistics, update your site information and get more information about linking us by logging into your account using the login and password below. In the advanced linking, we also invite you to upload the images for your site if you haven\'t already done so. If you send us enough hits, your images may have a chance to be featured!\r\n\r\n  Site Login: [login]\r\n  Password: [pass]\r\n  Link: [refarea]\r\n\r\n\r\nThanks,\r\n\r\n[admin_name]\r\n[admin_email]', 'referrer');
INSERT INTO al_email VALUES ('mod_refuse', '[name] Not Approved', 'Hi,\r\n\r\nThis is an automatic notification to let you know that [name] has been not been approved in our database. The hits you send will not be counted so if you were linking us already, please remove your links to the following sites.\r\n\r\n[sites]\r\n\r\n\r\n[admin_name]\r\n[admin_email]', 'referrer');
INSERT INTO al_email VALUES ('ban', 'Account for [name] Disabled', 'Hi,\r\n\r\nThis is an automatic notification to let you know that [name] has been removed from our database. The hits you send will no more be counted and your link won\'t show up. You may remove your links to the following site(s) now:\r\n\r\n[sites]\r\n\r\n\r\n[admin_name]\r\n[admin_email]', 'referrer');
INSERT INTO al_email VALUES ('pass_send', 'Password for [name]', 'Hi,\r\n\r\nYou or someone else requested the login information for [name]. If you didn\'t request these information, just ignore this email. Here they are:\r\n\r\n  Site Login: [login]\r\n  Password: [pass]\r\n  Link: [refarea]\r\n\r\n\r\n[admin_name]\r\n[admin_email]', 'referrer');
INSERT INTO al_email VALUES ('verify', 'Verification needed for [name]', 'Hi,\r\n\r\nYou recently signed up for a link exchange with our site(s). In order to verify that the email address you provided is correct, please click the link below:\r\n\r\n[refarea]verify.php?login=[login]&code=[code]\r\n\r\n\r\n[admin_name]\r\n[admin_email]', 'referrer');
INSERT INTO al_email VALUES ('new_ref', 'New Referrer ([name])', 'Hi,\r\n\r\nThis is an automatic notification to let you know a new referrer signed up at AutoLinks. Details are below, you can change them in the control panel and, if you chose moderation, approve or refuse this referrer.\r\n\r\n  Login: [login]\r\n  Name: [name]\r\n  URL: [url]\r\n  Email: [email]\r\n  Category: [category]\r\n', 'admin');