						<table width="500" border="0" cellpadding="2" cellspacing="0">
							<tr>
								<td colspan="3" bgcolor="#ffffcc">
									<p align="justify"><font size="2" face="verdana,arial,helvetica">
									Begin creating your doorway page by completing the form below. <b>Click on the question mark 
									for more information on any of the fields</b>. After submitting this form 
									you will be taken to a page which will display your doorway page code in a large text field. Then you 
									can make any changes to the code that you want (however, making manual changes to the code is not required), 
									click on Create Doorway Page, and your customized doorway page will be automatically created for you <b>right 
									on your server</b>!
									</font></p>
								</td>
							</tr>
							<tr>
								<td colspan="3">
									&nbsp;&nbsp;
								</td>
							</tr>
							<tr>
								<td colspan="3">
									<font face="verdana" size="3"><b>Choose the search engine you want to target:</b></font> <a href="javascript: var popUp=open('help.html#targetengines','help','width=400,height=200,scrollbars=yes,resizable=no');"><img src="images/help.gif" alt="More information" width="16" height="16" border="0"></a><br>
								</td>
							</tr>
							<tr>
								<td bgcolor="#eceaec">
									<form action="<?php echo $PHP_SELF;?>" method="post">
									<input type="hidden" name="doorwaymaker" value="yes">
									<input type="radio" name="page" value="alltheweb" checked><font size="2" face="verdana,arial,helvetica">All The Web</font><br>
									<input type="radio" name="page" value="altavista"><font size="2" face="verdana,arial,helvetica">Altavista</font><br>
									<input type="radio" name="page" value="aol"><font size="2" face="verdana,arial,helvetica">AOL Search</font><br>
									<input type="radio" name="page" value="directhit"><font size="2" face="verdana,arial,helvetica">Direct Hit</font><br>
									<input type="radio" name="page" value="excite"><font size="2" face="verdana,arial,helvetica">Excite</font><br>
								</td>
								<td>
									<input type="radio" name="page" value="generic"><font size="2" face="verdana,arial,helvetica">Generic</font><br>
									<input type="radio" name="page" value="google"><font size="2" face="verdana,arial,helvetica">Google</font><br>
									<input type="radio" name="page" value="goto"><font size="2" face="verdana,arial,helvetica">GoTo</font><br>
									<input type="radio" name="page" value="hotbot"><font size="2" face="verdana,arial,helvetica">HotBot</font><br>
									<input type="radio" name="page" value="infoseek"><font size="2" face="verdana,arial,helvetica">Infoseek</font><br>
								</td>
								<td bgcolor="whitesmoke">
									<input type="radio" name="page" value="iwon"><font size="2" face="verdana,arial,helvetica">IWon</font><br>
									<input type="radio" name="page" value="looksmart"><font size="2" face="verdana,arial,helvetica">LookSmart</font><br>
									<input type="radio" name="page" value="lycos"><font size="2" face="verdana,arial,helvetica">Lycos</font><br>
									<input type="radio" name="page" value="msn"><font size="2" face="verdana,arial,helvetica">MSN</font><br>
									<input type="radio" name="page" value="webcrawler"><font size="2" face="verdana,arial,helvetica">Webcrawler</font><br>
								</td>
							</tr>
							<tr>
								<td colspan="3">
									<br>
									<font face="Arial" size="2">Title of your new doorway page:</font> <a href="javascript: var popUp=open('help.html#title','help','width=400,height=200,scrollbars=yes,resizable=no');"><img src="images/help.gif" alt="More information" width="16" height="16" border="0"></a><br><input type="text" name="title" size="50"><br>
									<img src="images/px.gif" width="1" height="15" border="0"><br>
									<font face="Arial" size="2">Keywords (separated by commas, 3 or less recommended):</font> <a href="javascript: var popUp=open('help.html#keywords','help','width=400,height=200,scrollbars=yes,resizable=no');"><img src="images/help.gif" alt="More information" width="16" height="16" border="0"></a><br><input type="text" name="keywords" size="50"><br>
									<img src="images/px.gif" width="1" height="15" border="0"><br>
									<font face="Arial" size="2">Description of page (meta tag description):</font> <a href="javascript: var popUp=open('help.html#description','help','width=400,height=200,scrollbars=yes,resizable=no');"><img src="images/help.gif" alt="More information" width="16" height="16" border="0"></a><br><textarea cols="43" rows="5" name="desc"></textarea><br>
									<img src="images/px.gif" width="1" height="15" border="0"><br>
									<font face="Arial" size="2">Text you would like displayed on the page:</font> <a href="javascript: var popUp=open('help.html#bodytext','help','width=400,height=200,scrollbars=yes,resizable=no');"><img src="images/help.gif" alt="More information" width="16" height="16" border="0"></a><br><textarea cols="43" rows="5" name="body"></textarea><br>
									<img src="images/px.gif" width="1" height="15" border="0"><br>
									<font face="Arial" size="2">URL of the page you're linking to:</font> <a href="javascript: var popUp=open('help.html#link','help','width=400,height=200,scrollbars=yes,resizable=no');"><img src="images/help.gif" alt="More information" width="16" height="16" border="0"></a><br><input type="text" name="link" size="30" value="http://"><br>
									<img src="images/px.gif" width="1" height="15" border="0"><br>
									<font face="Arial" size="2">Link to your main page:</font> <a href="javascript: var popUp=open('help.html#mainpage','help','width=400,height=200,scrollbars=yes,resizable=no');"><img src="images/help.gif" alt="More information" width="16" height="16" border="0"></a><br><input type="text" name="home" size="30" value="http://"><br>
									<img src="images/px.gif" width="1" height="15" border="0"><br>
									<font face="Arial" size="2">Your website's logo URL:</font> <a href="javascript: var popUp=open('help.html#logourl','help','width=400,height=200,scrollbars=yes,resizable=no');"><img src="images/help.gif" alt="More information" width="16" height="16" border="0"></a><br><input type="text" name="logourl" size="30" value="http://"><br>
									<img src="images/px.gif" width="1" height="15" border="0"><br>
									<font face="Arial" size="2">Your company name:</font> <a href="javascript: var popUp=open('help.html#companyname','help','width=400,height=200,scrollbars=yes,resizable=no');"><img src="images/help.gif" alt="More information" width="16" height="16" border="0"></a><br><input type="text" name="coname" size="30"><br>
									<img src="images/px.gif" width="1" height="15" border="0"><br>
									<font face="Arial" size="2">File name of new doorway (including ".htm" or ".html"):</font> <a href="javascript: var popUp=open('help.html#filename','help','width=400,height=200,scrollbars=yes,resizable=no');"><img src="images/help.gif" alt="More information" width="16" height="16" border="0"></a><br><input type="text" name="file" size="30"><br>
									<img src="images/px.gif" width="1" height="15" border="0"><br>
									<input type="checkbox" name="redirect" value="yes"><font face="Arial" size="2">Add javascript redirect to page?</font> <a href="javascript: var popUp=open('help.html#redirect','help','width=400,height=200,scrollbars=yes,resizable=no');"><img src="images/help.gif" alt="More information" width="16" height="16" border="0"></a><br>
									<img src="images/px.gif" width="1" height="15" border="0"><br>
									<input type="submit" name="submit" value="Continue to Step 2">
									</form>
								</td>
							</tr>
						</table>
