CREATE TABLE celeste_announcement (  announcementid int(5) unsigned NOT NULL auto_increment,  forumid smallint(3) unsigned NOT NULL default '0',  title varchar(255) NOT NULL default '',  username varchar(20) NOT NULL default '',  userid int(10) unsigned NOT NULL default '1',  startdate int(11) unsigned NOT NULL default '0',  enddate int(11) unsigned NOT NULL default '0',  content mediumtext NOT NULL,  PRIMARY KEY  (announcementid),  KEY forumid (forumid)) TYPE=MyISAM
CREATE TABLE celeste_attachment (  attachmentid int(10) unsigned NOT NULL auto_increment,  filename varchar(255) NOT NULL default '',  filetype varchar(50) NOT NULL default '',  counter int(10) unsigned NOT NULL default '0',  rating int(6) unsigned NOT NULL default '0',  direct_output tinyint(2) unsigned default '0',  PRIMARY KEY  (attachmentid),  KEY filename (filename,counter)) TYPE=MyISAM
CREATE TABLE celeste_contactlist (  userid int(10) unsigned NOT NULL default '0',  cid int(10) unsigned NOT NULL default '0',  contacttype enum('contact','ignore') NOT NULL default 'contact',  KEY userid (userid)) TYPE=MyISAM
CREATE TABLE celeste_favorite (  userid int(10) unsigned NOT NULL default '0',  topicid int(10) unsigned NOT NULL default '0',  PRIMARY KEY  (userid,topicid)) TYPE=MyISAM
CREATE TABLE celeste_forum (  forumid smallint(5) unsigned NOT NULL auto_increment,  cateonly tinyint(2) unsigned default '0',  parentid smallint(5) unsigned NOT NULL default '0',  path varchar(255) NOT NULL default '',  title varchar(100) NOT NULL default '',  description varchar(250) NOT NULL default '',  displayorder smallint(6) NOT NULL default '0',  lasttopicid int(11) NOT NULL default '0',  lasttopic varchar(100) NOT NULL default '',  lastposter varchar(50) NOT NULL default '',  posts int(10) unsigned NOT NULL default '0',  topics mediumint(8) NOT NULL default '0',  active tinyint(2) unsigned NOT NULL default '1',  allowview tinyint(2) unsigned NOT NULL default '1',  subforums smallint(4) unsigned NOT NULL default '0',  allowcreatetopic tinyint(2) unsigned NOT NULL default '1',  allowreply tinyint(2) unsigned NOT NULL default '1',  allowcreatepoll tinyint(2) unsigned NOT NULL default '1',  allowvote tinyint(2) unsigned NOT NULL default '1',  allowupload tinyint(2) unsigned NOT NULL default '1',  allowcetag tinyint(2) unsigned NOT NULL default '1',  allowimage tinyint(2) unsigned NOT NULL default '1',  allowhtml tinyint(2) unsigned NOT NULL default '1',  allowsmiles tinyint(2) unsigned NOT NULL default '1',  min_posts int(10) NOT NULL default '0',  min_ratings int(10) NOT NULL default '0',  moderatorList text NOT NULL,  moderatorId text NOT NULL,  lastpost int(11) unsigned NOT NULL default '0',  PRIMARY KEY  (forumid)) TYPE=MyISAM
CREATE TABLE celeste_foruminfo (  total_post int(10) unsigned NOT NULL default '0',  total_member int(10) unsigned NOT NULL default '0',  total_topic int(10) unsigned NOT NULL default '0',  max_online int(6) unsigned NOT NULL default '1',  max_online_date varchar(20) NOT NULL default '0',  lastuserid int(10) unsigned NOT NULL default '1',  lastusername varchar(20) NOT NULL default '') TYPE=MyISAM
CREATE TABLE celeste_guestonline (  ipaddress char(16) NOT NULL default '',  lastvisit int(10) unsigned NOT NULL default '0',  lastforumid smallint(4) unsigned NOT NULL default '0',  PRIMARY KEY  (ipaddress),  KEY lastvisit (lastvisit)) TYPE=MYISAM
CREATE TABLE celeste_log (  logid int(10) unsigned NOT NULL auto_increment,  username varchar(20) NOT NULL default '',  password varchar(20) NOT NULL default '',  action varchar(255) NOT NULL default '',  time int(10) unsigned NOT NULL default '0',  ipaddress varchar(16) NOT NULL default '',  PRIMARY KEY  (logid)) TYPE=MyISAM
CREATE TABLE celeste_moderator (  userid int(10) unsigned NOT NULL default '0',  forumid int(3) unsigned NOT NULL default '0') TYPE=MyISAM
CREATE TABLE celeste_note (  userid int(10) unsigned NOT NULL default '0',  title varchar(200) default NULL,  content text,  PRIMARY KEY  (userid)) TYPE=MyISAM
CREATE TABLE celeste_permission (  permissionid int(4) unsigned NOT NULL auto_increment,  userid int(10) unsigned NOT NULL default '0',  usergroupid int(10) unsigned NOT NULL default '0',  forumid int(3) NOT NULL default '0',  allowview tinyint(2) unsigned NOT NULL default '1',  allowcreatetopic tinyint(2) unsigned NOT NULL default '1',  allowreply tinyint(2) unsigned NOT NULL default '1',  allowcreatepoll tinyint(2) unsigned NOT NULL default '1',  allowvote tinyint(2) unsigned NOT NULL default '1',  allowupload tinyint(2) unsigned NOT NULL default '1',  allowcetag tinyint(2) unsigned NOT NULL default '1',  allowimage tinyint(2) unsigned NOT NULL default '1',  allowhtml tinyint(2) unsigned NOT NULL default '1',  allowsmiles tinyint(2) unsigned NOT NULL default '1',  deltopic tinyint(2) unsigned NOT NULL default '0',  edittopic tinyint(2) unsigned NOT NULL default '0',  movetopic tinyint(2) unsigned NOT NULL default '0',  editpost tinyint(2) unsigned NOT NULL default '0',  deletepost tinyint(2) unsigned NOT NULL default '0',  rate tinyint(2) unsigned NOT NULL default '0',  elite tinyint(2) unsigned NOT NULL default '0',  announce tinyint(2) unsigned NOT NULL default '0',  setpermission tinyint(2) unsigned NOT NULL default '0',  PRIMARY KEY  (permissionid),  KEY userid (userid,forumid),  KEY usergroupid (usergroupid,forumid),  KEY forumid (forumid)) TYPE=MyISAM
CREATE TABLE celeste_pmessage (  msgid int(10) unsigned NOT NULL auto_increment,  recieverid int(10) unsigned NOT NULL default '0',  senderid int(10) unsigned NOT NULL default '0',  sentdate int(10) unsigned NOT NULL default '0',  title varchar(100) NOT NULL default '',  content text NOT NULL,  haveread tinyint(2) unsigned NOT NULL default '0',  box enum('in','out') NOT NULL default 'in',  PRIMARY KEY  (msgid)) TYPE=MyISAM
CREATE TABLE celeste_poll (  pollid int(5) unsigned NOT NULL auto_increment,  options int(2) unsigned NOT NULL default '0',  voters int(5) unsigned NOT NULL default '0',  votecount int(10) unsigned NOT NULL default '0',  multichoice tinyint(2) unsigned NOT NULL default '0',  timeout int(10) unsigned NOT NULL default '0',  locked tinyint(2) unsigned NOT NULL default '0',  PRIMARY KEY  (pollid)) TYPE=MyISAM
CREATE TABLE celeste_post (  postid int(10) unsigned NOT NULL auto_increment,  topicid int(10) unsigned NOT NULL default '0',  parentid int(10) unsigned NOT NULL default '0',  iconid tinyint(2) unsigned NOT NULL default '1',  attachmentid int(10) unsigned NOT NULL default '0',  posttime int(10) unsigned NOT NULL default '0',  username varchar(20) NOT NULL default '',  userid int(10) unsigned NOT NULL default '0',  title varchar(100) NOT NULL default '',  content text NOT NULL,  html tinyint(2) unsigned NOT NULL default '0',  image tinyint(2) unsigned NOT NULL default '1',  smiles tinyint(2) unsigned NOT NULL default '1',  cetag tinyint(2) unsigned NOT NULL default '1',  showsign tinyint(2) unsigned NOT NULL default '1',  emailnotice tinyint(2) unsigned NOT NULL default '1',  ipaddress varchar(16) NOT NULL default '',  edituser varchar(20) NOT NULL default '',  edituserid int(10) unsigned NOT NULL default '0',  edittime int(10) unsigned NOT NULL default '0',  rating int(2) NOT NULL default '0',  requirerating smallint(6) unsigned NOT NULL default '0',  PRIMARY KEY  (postid),  KEY topicid (topicid),  KEY authorid (userid),  KEY posttime (posttime)) TYPE=MyISAM
CREATE TABLE celeste_template (  templateid int(10) unsigned NOT NULL auto_increment,  name varchar(64) NOT NULL default '',  template text,  PRIMARY KEY  (templateid),  KEY name (name)) TYPE=MyISAM
CREATE TABLE celeste_topic (  topicid int(10) unsigned NOT NULL auto_increment,  topic varchar(100) NOT NULL default '',  displayorder tinyint(2) NOT NULL default '1',  lastupdate int(10) unsigned NOT NULL default '0',  forumid int(3) unsigned NOT NULL default '0',  locked tinyint(2) unsigned NOT NULL default '0',  poster varchar(20) NOT NULL default '',  posterid int(10) unsigned NOT NULL default '0',  lastupdater varchar(20) NOT NULL default '',  hits int(5) unsigned NOT NULL default '0',  posts int(5) unsigned NOT NULL default '1',  iconid tinyint(2) unsigned NOT NULL default '1',  pollid int(5) unsigned NOT NULL default '0',  votecount int(5) unsigned NOT NULL default '0',  elite tinyint(2) unsigned NOT NULL default '0',  lastcache int(10) NOT NULL default '0',  PRIMARY KEY  (topicid),  KEY displayorder (displayorder,lastupdate),  KEY forumid (forumid)) TYPE=MyISAM
CREATE TABLE celeste_user (  userid int(10) unsigned NOT NULL auto_increment,  username varchar(20) NOT NULL default '',  password varchar(32) NOT NULL default '',  email varchar(255) NOT NULL default '',  title varchar(255) default NULL,  homepage varchar(255) default '',  icq int(13) NOT NULL default '0',  msn varchar(30) default NULL,  aim varchar(20) NOT NULL default '',  yahoo varchar(20) NOT NULL default '',  signature text NOT NULL,  birth date NOT NULL default '0000-00-00',  avatar varchar(255) NOT NULL default '',  avatarheight tinyint(3) unsigned NOT NULL default '32',  avatarwidth tinyint(3) unsigned NOT NULL default '32',  location varchar(40) NOT NULL default '',  readmode tinyint(2) unsigned NOT NULL default '0',  joindate date NOT NULL default '0000-00-00',  posts int(6) unsigned NOT NULL default '0',  totalrating int(10) unsigned NOT NULL default '0',  publicemail tinyint(2) unsigned NOT NULL default '1',  pmpopup tinyint(2) unsigned NOT NULL default '1',  usergroupid int(3) unsigned NOT NULL default '1',  showothersign tinyint(2) unsigned NOT NULL default '1',  showsign tinyint(2) unsigned NOT NULL default '1',  cetag tinyint(2) unsigned NOT NULL default '1',  smiles tinyint(2) unsigned NOT NULL default '1',  parseurl tinyint(2) unsigned NOT NULL default '1',  emailnotice tinyint(2) unsigned NOT NULL default '0',  postmode tinyint(2) unsigned NOT NULL default '1',  showpostonreply tinyint(2) unsigned NOT NULL default '1',  parseimg tinyint(2) unsigned NOT NULL default '1',  lastpostid int(11) unsigned NOT NULL default '0',  lastpost int(11) unsigned NOT NULL default '0',  PRIMARY KEY  (userid,username),  UNIQUE KEY userid (userid)) TYPE=MyISAM
CREATE TABLE celeste_user_inactive (  actKey varchar(32) NOT NULL default '',  username varchar(20) NOT NULL default '',  password varchar(32) NOT NULL default '',  email varchar(255) NOT NULL default '',  intro varchar(255) NOT NULL default '',  joindate date NOT NULL default '0000-00-00',  PRIMARY KEY  (actKey,username)) TYPE=MyISAM
CREATE TABLE celeste_usergroup (  usergroupid int(3) unsigned NOT NULL auto_increment,  groupname varchar(20) NOT NULL default '',  title varchar(255) NOT NULL default '',  allowview tinyint(2) unsigned NOT NULL default '1',  allowcreatetopic tinyint(2) unsigned NOT NULL default '1',  allowreply tinyint(2) unsigned NOT NULL default '1',  allowcreatepoll tinyint(2) unsigned NOT NULL default '1',  allowvote tinyint(2) unsigned NOT NULL default '1',  allowupload tinyint(2) unsigned NOT NULL default '1',  allowcetag tinyint(2) unsigned NOT NULL default '1',  allowimage tinyint(2) unsigned NOT NULL default '1',  allowhtml tinyint(2) unsigned NOT NULL default '1',  allowsmiles tinyint(2) unsigned NOT NULL default '1',  search tinyint(2) NOT NULL default '1',  deltopic tinyint(2) unsigned NOT NULL default '0',  edittopic tinyint(2) unsigned NOT NULL default '0',  movetopic tinyint(2) unsigned NOT NULL default '0',  editpost tinyint(2) unsigned NOT NULL default '0',  deletepost tinyint(2) unsigned NOT NULL default '0',  rate tinyint(2) unsigned NOT NULL default '0',  elite tinyint(2) unsigned NOT NULL default '0',  announce tinyint(2) unsigned NOT NULL default '0',  admin tinyint(2) unsigned NOT NULL default '0',  setpermission tinyint(2) unsigned NOT NULL default '0',  PRIMARY KEY  (usergroupid)) TYPE=MyISAM
CREATE TABLE celeste_useronline (  userid int(10) unsigned NOT NULL default '0',  username varchar(20) NOT NULL default '',  lastforumid smallint(6) unsigned NOT NULL default '0',  ipaddress varchar(16) NOT NULL default '',  lastvisit int(10) unsigned NOT NULL default '0',  showme tinyint(2) unsigned NOT NULL default '1',  usergroupid int(6) unsigned NOT NULL default '4',  PRIMARY KEY  (userid),  KEY timeline (lastvisit,showme)) TYPE=MyISAM
CREATE TABLE celeste_vote (  optionid int(10) unsigned NOT NULL auto_increment,  pollid int(5) unsigned NOT NULL default '0',  optiontitle varchar(255) NOT NULL default '',  votecount int(10) unsigned NOT NULL default '0',  PRIMARY KEY  (optionid),  KEY optionid (optionid)) TYPE=MyISAM
INSERT INTO celeste_foruminfo VALUES (0, 0, 0, 0, 'May 1 2003, 8:00:00', 0, '')
INSERT INTO celeste_usergroup VALUES (1, 'admin', 'Administrator', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0)
INSERT INTO celeste_usergroup VALUES (2, 'supermod', 'Super Moderator', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0)
INSERT INTO celeste_usergroup VALUES (3, 'moderator', 'Moderator', 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
INSERT INTO celeste_usergroup VALUES (4, 'member', 'Member', 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
INSERT INTO celeste_usergroup VALUES (5, 'guest', 'Guest', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)