<?php

//adminheader.php

define ("_HOME", "Home");
define ("_CATEGORIES", "Categories");
define ("_RECENTLYADDED", "Recently Added");
define ("_AUTHORS", "Authors");
define ("_HELP", "Help");
define ("_SEARCH", "Search");
define ("_YOURACCOUNT", "Your Account");
define ("_ADMIN", "Admin");
define ("_LOGIN", "Log In");
define ("_TITLES", "Titles");
define ("_LOGOUT", "Logout");

//admin.php

define ("_ADMINLOGIN", "Admin Login");
define ("_WRONGPASSWORD", "That password doesn't match the one in the system. Please <a href=\"admin.php\">try again</a>.");
define ("_LOGIN", "Login");
define ("_PASSWORD", "Password");
define ("_ADMINAREA", "Admin Area");
define ("_PLEASELOGIN", "Please <a href=\"user.php\">Log in</a>.");
define ("_NOTALLOWED", "You are not allowed to be in this area.");
define ("_SEARCHFORM", "Search Form");
define ("_EDIT", "Edit");
define ("_DELETE", "Delete");
define ("_ADDCHAPTER", "Add Chapter");
define ("_NORESULTS", "No results found.");
define ("_YES", "Yes");
define ("_NO", "No");
define ("_PENNAME", "Penname");
define ("_STORYTITLE", "Story Title");
define ("_CHAPTERTITLE", "Chapter Title");
define ("_SUMMARY", "Summary");
define ("_FULLTEXT", "Full Text");
define ("_SETTINGS", "Settings");
define ("_BTSETTINGS", "Your changes have been made. <a href=\"admin.php?action=settings\">Back to Settings</a>");
define ("_SITENAME", "Sitename");
define ("_SITESLOGAN", "Site Slogan");
define ("_SITEURL", "Site URL");
define ("_ADMINEMAIL", "Admin E-mail");
define ("_DBPATH", "Database Config Path");
define ("_HOWSTORE", "How to store stories");
define ("_FILES", "Files on Server");
define ("_MYSQL", "In MySQL Database");
define ("_AUTOVALIDATE", "Automatically validate all stories");
define ("_NUMCATS", "Number of categories");
define ("_ONLYONE", "Only one");
define ("_MORETHANONE", "More than one");
define ("_ONREVIEWS", "Turn on reviews");
define ("_ANONREVIEWS", "Allow anonymous reviews");
define ("_WHATRATINGS", "What kind of ratings system");
define ("_LIKE", "Like/Dislike");
define ("_STARS", "Stars");
define ("_NONE", "None");
define ("_ALLOWRR", "Allow round robins");
define ("_NOSUBS", "Turn off unsolicited submissions completely");
define ("_NUMITEMS", "Default items per page");
define ("_IMAGEUPLOADS", "Allow image uploads with stories");
define ("_MAXWIDTH", "Max image width");
define ("_MAXHEIGHT", "Max image height");
define ("_DEFAULTSKIN", "Default Skin");
define ("_WELCOME", "Front page message");
define ("_RULES", "Submission Rules");
define ("_THANKYOU", "Thank you letter (default)");
define ("_NOTHANKYOU", "No thank you letter (default)");
define ("_COPYRIGHT", "Copyright Footer");
define ("_HELPPAGE", "Help Page Text");
define ("_CONFIGERROR", "There was an error writing to the config file. Are you sure it's chmoded to 666?");
define ("_CATEGORIES", "Categories");
define ("_CHARACTERS", "Characters");
define ("_RATINGS", "Ratings");
define ("_GENRES", "Genres");
define ("_WARNINGS", "Warnings");
define ("_AUTHORS", "Authors");
define ("_SETTINGS", "Settings");
define ("_ADMINS", "Admins");
define ("_SUBMITTED", "View Submitted");
define ("_ADDSTORY", "Add Story");
define ("_NEWS", "News");
define ("_SEARCH", "Search/Edit");
define ("_CATSCOLUMN", "Number of Category Columns");
define ("_TABLEPREFIX", "Table Prefix");
define ("_NEWSCOMMENTS", "Turn on News Comments?");
define ("_FAVORITES", "Allow Favorites");
define ("_NUMUPDATED", "Number of Updated Stories");
define ("_DATEFORMAT", "Date Format (Stories)");
define ("_NEWSDATE", "Date Format (News)");
define ("_MAILUSERS", "Mail Users");
define ("_STORIESPATH", "Stories Path");
define ("_COMPLETED", "Completed");
define ("_FIRSTCHAPTER", "first chapter");
define ("", "");
define ("", "");
define ("", "");
define ("", "");

//adminfunctions.php

define ("_CATMAINT", "Categories Maintenance");
define ("_BTCATMAINT", "Your changes have been made. <a href=\"admin.php?action=categories\">Back to Categories Maintenance</a>");
define ("_NEWCAT", "New Category");
define ("_CATNAME", "Category Name");
define ("_CATDESC", "Category Description");
define ("_CATLEVEL", "Subcategory of?");
define ("_ORDER", "Order");
define ("_ORDERAFTER", "Place in Order After");
define ("_TOPLEVEL", "Top Level Category");
define ("_LOCKED", "Locked");
define ("_IMAGE", "Image");
define ("_CURRENTCATS", "Current Categories");
define ("_CATEGORY", "Category");
define ("_MOVE", "Move");
define ("_OPTIONS", "Options");
define ("_EDITCAT", "Edit Category");
define ("_DELETECAT", "Delete Category");
define ("_CATNOTDELETED", "The category has not been deleted. <a href=\"admin.php?action=categories\">Back to Categories Maintenance</a>");
define ("_CATSUREDEL", "Are you sure you want to delete this category? All sub-categories will be deleted as well!");
define ("_CHARMAINT", "Characters Maintenance");
define ("_BTCHARMAINT", "Your changes have been made. <a href=\"admin.php?action=characters\">Back to Characters Maintenance</a>");
define ("_SELECTCOPY", "Select the characters you would like to copy over to the category you selected.");
define ("_CHARSCOPIED", "The characters you selected have been copied over to the category. <a href=\"admin.php?action=characters\">Back to Characters Maintenance</a>");
define ("_NEWCHAR", "New Character");
define ("_CHARACTER", "Character");
define ("_CHARCAT", "Character Category");
define ("_COPYCHARS", "Copy Characters to Category");
define ("_CATTOCOPY", "Category to copy to");
define ("_CURRENTCHARS", "Current Characters");
define ("_EDITCHAR", "Edit Character");
define ("_CHAREDITED", "Your changes have been made. If you moved a character to a new category, you should make an announcement to your members, as it may affect some of their stories. <a href=\"admin.php?action=characters\">Back to Characters Maintenance</a>");
define ("_DELETECHAR", "Delete Character");
define ("_CHARNOTDEL", "The character has not been deleted. <a href=\"admin.php?action=characters\">Back to Characters Maintenance</a>");
define ("_CHARSUREDEL", "Are you sure you want to delete this character?");
define ("_RATMAINT", "Ratings Maintenance");
define ("_BTRATMAINT", "Your changes have been made. <a href=\"admin.php?action=ratings\">Back to Ratings Maintenance</a>");
define ("_NEWRAT", "New Rating");
define ("_RATING", "Rating");
define ("_WARNINGPOP", "Warning Pop-up");
define ("_WARNINGTEXT", "Warning Pop-up Text");
define ("_CURRENTRATS", "Current Ratings");
define ("_WARNING", "Warning");
define ("_EDITRAT", "Edit Rating");
define ("_DELETERAT", "Delete Rating");
define ("_RATNOTDEL", "The rating has not been deleted. <a href=\"admin.php?action=ratings\">Back to Ratings Maintenance</a>");
define ("_RATSUREDEL", "Are you sure you want to delete this rating?");
define ("_GENMAINT", "Genres Maintenance");
define ("_BTGENMAINT", "Your changes have been made. <a href=\"admin.php?action=genres\">Back to Genres Maintenance</a>");
define ("_NEWGENRE", "New Genre");
define ("_GENRE", "Genre");
define ("_CURRENTGENS", "Current Genres");
define ("_EDITGEN", "Edit Genre");
define ("_DELETEGEN", "Delete Genre");
define ("_GENNOTDEL", "The genre has not been deleted. <a href=\"admin.php?action=genres\">Back to Genres Maintenance</a>");
define ("_GENSUREDEL", "Are you sure you want to delete this genre?");
define ("_WARNMAINT", "Warnings Maintenance");
define ("_BTWARNMAINT", "Your changes have been made. <a href=\"admin.php?action=warnings\">Back to Warnings Maintenance</a>");
define ("_NEWWARNING", "New Warning");
define ("_WARNING", "Warning");
define ("_CURRENTWARNINGS", "Current Warnings");
define ("_EDITWARNING", "Edit Warning");
define ("_DELETEWARNING", "Delete Warning");
define ("_WARNNOTDEL", "The warning has not been deleted. <a href=\"admin.php?action=warnings\">Back to Warnings Maintenance</a>");
define ("_WARNSUREDEL", "Are you sure you want to delete this warning?");

//adminnews.php

define ("_NEWSCENTER", "News Center");
define ("_NEWSADDED", "The news story has been added. <a href=\"admin.php?action=news\">Back to News</a>");
define ("_ADDNEWS", "Add News Story");
define ("_AUTHOR", "Author");
define ("_TITLE", "Title");
define ("_STORYTEXT", "Story Text");
define ("_DATE", "Date");
define ("_PREVIOUS", "Previous");
define ("_NEXT", "Next");
define ("_EDITNEWS", "Edit News Story");
define ("_NEWSEDITED", "The news story has been edited. <a href=\"admin.php?action=news\">Back to News</a>");
define ("_DELETENEWS", "Delete News Story");
define ("_NEWSDELETED", "The news story has been deleted. <a href=\"admin.php?action=news\">Back to News</a>");
define ("_NEWSNOTDEL", "The news story has not been deleted. <a href=\"admin.php?action=news\">Back to News</a>");
define ("_NEWSSUREDEL", "Are you sure you want to delete this news story?");

//adminusers.php

define ("_AUTHMAINT", "Authors Maintenance");
define ("_BTAUTHMAINT", "Your changes have been made. <a href=\"admin.php?action=authors\">Back to Authors Maintenance</a>");
define ("_PENNAME", "Penname");
define ("_REALNAME", "Real Name");
define ("_EMAIL", "E-mail");
define ("_WEBSITE", "Website");
define ("_INPUTBYADMIN", "Authors Input by Admin");
define ("_VALAUTHOR", "Validate Author");
define ("_CURRENTVALAUTHORS", "Current Validated Authors");
define ("_DELETEVAL", "Delete Author From Validated List");
define ("_VALDELETED", "The author has been deleted from the validated list. <a href=\"admin.php?action=authors\">Back to Authors Maintenance</a>");
define ("_VALNOTDELETED", "The author has not been deleted from the validated list. <a href=\"admin.php?action=authors\">Back to Authors Maintenance</a>");
define ("_VALSUREDEL", "Are you sure you want to delete this author from the validated list?");
define ("_RELEASEAUTHOR", "Release Author");
define ("_AUTHORELEASED", "The author has been removed from the admin created list, and an e-mail has been sent to them with their temporary password. <a href=\"admin.php?action=authors\">Back to Authors Maintenance</a>");
define ("_AUTHORNOTRELEASED", "The author has not been removed from the admin created list. <a href=\"admin.php?action=authors\">Back to Authors Maintenance</a>");
define ("_AUTHORSUREREL", "Are you sure you want to release this author?");
define ("_ADMINMAINT", "Admin Maintenance");
define ("_ADMINCREATED", "The admin has been created. <a href=\"admin.php?action=admins\">Back to Admin Maintenance</a>");
define ("_NEWADMIN", "New Admin");
define ("_LEVEL", "Level");
define ("_CONTACT", "Contact when new fanfics submitted");
define ("_CURRENTADMINS", "Current Admins");
define ("_EDITADMIN", "Edit Admin");
define ("_BADPASSWORDS", "The two passwords do not match. <a href=\"admin.php?action=adminedit&aid=$aid\">Go back and try again</a>");
define ("_BTADMINMAINT", "Your changes have been made. <a href=\"admin.php?action=admins\">Back to Admin Maintenance</a>");
define ("_DELADMIN", "Delete Admin");
define ("_ADMINNOTDEL", "The admin has not been deleted. <a href=\"admin.php?action=admins\">Back to Admin Maintenance</a>");
define ("_ADMINSUREDEL", "Are you sure you want to delete this admin?");
define ("_DELETEUSER", "Delete User");
define ("_USERDELETED", "The user and their stories have been deleted. <a href=\"admin.php?action=searchbox\">Back to Search</a>");
define ("_USERNOTDEL", "The user has not been deleted. <a href=\"admin.php?action=searchbox\">Back to Search</a>");
define ("_USERSUREDEL", "Are you sure you want to delete this user? All their stories will be deleted, too!");
define ("_SUBJECT", "Subject");
define ("_TEXT", "Email Text");
define ("_CATOVERSEE", "Categories to Oversee");
define ("_EMAILWARNING", "Please be warned: using this form will send out an e-mail to every person who is a member on your site. Because the script uses PHP's mail() function to do this, it could cause substantial server load if you have more than 1000 site members.");
define ("_VALIDATEAUTHOR", "Validate Author");
define ("_BADCHAR", "You must enter a Penname, and it can only contain letters, numbers and spaces.");
define ("_RELEASE", "Release");
define ("_REMOVE", "Remove");
define ("_ALLCATEGORIES", "All Categories");
define ("_ADDADMIN", "Add Admin");
define ("_REMOVEADMIN", "Remove as Admin");
define ("_ADDAUTHOR", "Add Author");
define ("", "");
define ("", "");
define ("", "");
define ("", "");
define ("", "");

//adminstories.php

define ("_ADDSTORY", "Add Story");
define ("_MISSINGFIELDS", "Required fields in red.");
define ("_NOSTORYTEXT", "You must have an actual story included, either as an upload or input into the textarea. Please <a href=\"admin.php?action=addstory\">try again</a>  and make sure these fields are filled out.");
define ("_INVALIDUPLOAD", "Invalid Upload");
define ("_SUMMARY", "Summary");
define ("_TITLE", "Title");
define ("_CHAPTERTITLE", "Chapter Title");
define ("_CHARACTERS", "Characters");
define ("_GENRES", "Genres");
define ("_WARNINGS", "Warnings");
define ("_ROUNDROBIN", "Roundrobin");
define ("_STORYTEXTTEXT", "Story Text (text)");
define ("_STORYTEXTFILE", "Story Text (file)");
define ("_STORYTEXTINFO", "You may copy the text of your story here, or upload a text or html file. Once you choose one, the other form option will gray out, and not be choosable.<br><br>
						The following html codes are allowed: &lt;b&gt; &lt;i&gt; &lt;u&gt; &lt;center&gt; &lt;img&gt; &lt;a&gt; &lt;hr&gt; <br><br>
						The script understands carriage returns so, &lt;br&gt; tags are not required. Some html tags such as &lt;p&gt; tags may cause your story to space oddly.");
define ("_STORYTEXTCLEANUP", "This is the text of your story. Go ahead and make any changes here.<br><br>The following html codes are allowed: &lt;b&gt; &lt;i&gt; &lt;u&gt; &lt;center&gt; &lt;img&gt; &lt;a&gt; &lt;hr&gt;");
define ("_STORYADDED", "The story has been added.");
define ("_STORYCHAPTER", "The story has been added.");
define ("_ADDCHAPTER", "Add Chapter");
define ("_TITLES", "Titles");
define ("_SUBMITTED", "Submitted Stories");
define ("_VALIDATE", "Validate/View");
define ("_YESLETTER", "Yes Letter");
define ("_NOLETTER", "No Letter");
define ("_VIEWSUBMITTED", "View Submitted Story");
define ("_STORYVALIDATED", "The story has been validated.");
define ("_VALIDATEYES", "Validate");
define ("_EMAILSENT", "The email has been sent.");
define ("_DELETESTORY", "Delete Submitted Story");
define ("_STORYDELETED", "The story has been deleted. <a href=\"admin.php?action=submitted\">Back to Submitted Stories</a>");
define ("_STORYNOTDEL", "The story has not been deleted. <a href=\"admin.php?action=submitted\">Back to Submitted Stories</a>");
define ("_STORYSUREDEL", "Are you sure you want to delete this story?");
define ("_PREVIEW", "Preview");
define ("_SELECT", "Select");
define ("", "");
define ("", "");


define ("_EMAILSENT", "E-mail Sent");
define ("_SUBMIT", "Submit");
define ("_CATCOUNTSUPDATED", "Category counts updated.");
define ("_FIXCATCOUNTS", "Click the following button to fix your category counts.");
define ("_COUNTCATS", "Fix Category Counts");
define ("", "");


?>