<?php

  $maxlen=175;
  $dy=getdate($conf->dtime-40000);
  $ydtime=mktime(0,0,0,$dy['mon'],$dy['mday'],$dy['year'],0);
  $lyear=(int)(date('y',$conf->ctime))-(int)(date('y',$conf->btime))+1;
  $values='IF(modify>='.$conf->dtime.',vt,0) AS vt,IF(modify>='.$conf->dtime.',hst,0) AS hst,IF(modify>='.$conf->dtime.',(htt-vt),0) AS rt,IF(modify>='.$conf->dtime.',htt,0) AS htt';
  $values.=',IF(modify>='.$conf->dtime.',vy,vt) AS vy,IF(modify>='.$conf->dtime.',hsy,hst) AS hsy,IF(modify>='.$conf->dtime.',hty-vy,htt-vt) AS ry,IF(modify>='.$conf->dtime.',hty,htt) AS hty';
  $values.=',IF(modify>='.$conf->wtime.',vw,0) AS vw,IF(modify>='.$conf->wtime.',hsw,0) AS hsw,IF(modify>='.$conf->wtime.',(htw-vw),0) AS rw,IF(modify>='.$conf->wtime.',htw,0) AS htw';
  $values.=',IF(modify>='.$conf->wtime.',vlw,vw) AS vlw,IF(modify>='.$conf->wtime.',hslw,hsw) AS hslw,IF(modify>='.$conf->wtime.',htlw-vlw,htw-vw) AS rlw,IF(modify>='.$conf->wtime.',htlw,htw) AS htlw';
  $values.=',IF(modify>='.$conf->mtime.',vm,0) AS vm,IF(modify>='.$conf->mtime.',hsm,0) AS hsm,IF(modify>='.$conf->mtime.',(htm-vm),0) AS rm,IF(modify>='.$conf->mtime.',htm,0) AS htm';
  $values.=',IF(modify>='.$conf->mtime.',vlm,vm) AS vlm,IF(modify>='.$conf->mtime.',hslm,hsm) AS hslm,IF(modify>='.$conf->mtime.',htlm-vlm,htm-vm) AS rlm,IF(modify>='.$conf->mtime.',htlm,htm) AS htlm';
  $vvalues='v1'; $hsvalues='hs1'; $htvalues='ht1';
  for($i=2;$i<=$lyear;$i++) { $vvalues.='+v'.$i; $hsvalues.='+hs'.$i; $htvalues.='+ht'.$i; }
  $values.=',('.$vvalues.') AS v,('.$hsvalues.') AS hs,(('.$htvalues.')-('.$vvalues.')) AS r,('.$htvalues.') AS ht';

  if($page_id>200) $request='LOCK TABLES aa_points READ,aa_groups READ';
  else $request='LOCK TABLES aa_points READ,aa_pages READ';
  $result=mysql_query($request,$conf->link);
  if(!$result) {$err->reason('vdb.php|points_tim|blocking of tables has failed -- '.mysql_error());return;}

  $request='SELECT '.$values.' FROM aa_points WHERE id='.$page_id.' AND flag='.$flag;
  $result=mysql_query($request,$conf->link);
  if(!$result) {$err->reason('vdb.php|points_tim|the request \''.$request.'\' has failed -- '.mysql_error());return;}

  //for average
  if($page_id>200) $request='SELECT added FROM aa_groups WHERE id='.$page_id;
  else $request='SELECT added,name,id FROM aa_pages WHERE id='.$page_id;
  $resultpg=mysql_query($request,$conf->link);
  if(!$resultpg) {$err->reason('vdb.php|points_tim|the request \''.$request.'\' has failed -- '.mysql_error());return;}

  $request='UNLOCK TABLES';
  $resultu=mysql_query($request,$conf->link);
  if(!$resultu) {$err->reason('vdb.php|points_tim|the request \''.$request.'\' has failed -- '.mysql_error());return;}

  // get quantity day since adding of page/group to calculate correctly average values
  while($row=mysql_fetch_object($resultpg)) {
      $db=getdate($row->added);
      $hbtime=mktime(0,0,0,$db['mon'],$db['mday'],$db['year'],0);
      $tdays=(int)sprintf("%d",($conf->dtime-$hbtime)/$conf->time1)+1;
      if($conf->lmtime>$hbtime) $lmdays=(int)sprintf("%d",($conf->dtime-$conf->lmtime)/$conf->time1)+1;
      else $lmdays=(int)sprintf("%d",($conf->dtime-$hbtime)/$conf->time1)+1;
      if($conf->mtime>$hbtime) $mdays=(int)sprintf("%d",($conf->dtime-$conf->mtime)/$conf->time1)+1;
      else $mdays=(int)sprintf("%d",($conf->dtime-$hbtime)/$conf->time1)+1;
      if($conf->lwtime>$hbtime) $lwdays=(int)sprintf("%d",($conf->dtime-$conf->lwtime)/$conf->time1)+1;
      else $lwdays=(int)sprintf("%d",($conf->dtime-$hbtime)/$conf->time1)+1;
      if($conf->wtime>$hbtime) $wdays=(int)sprintf("%d",($conf->dtime-$conf->wtime)/$conf->time1)+1;
      else $wdays=(int)sprintf("%d",($conf->dtime-$hbtime)/$conf->time1)+1;
  }
  mysql_free_result($resultpg);

  require './style/'.$conf->style.'/template/vti_ps_a.php';
  $vars['HEADER']=_SUMMARY.' / ';
  if($flag==1) $vars['RHEADER']=_ENTRYGRPG;
  elseif($flag==2) $vars['RHEADER']=_EXITGRPG;
  elseif($flag==3) $vars['RHEADER']=_SINGLE;
  $vars['THEADER']=_ALLTIME.' ('.date($conf->dmas[$conf->dformat],$conf->btime).' - '.date($conf->dmas[$conf->dformat],$conf->ctime).')';
  $vars['SHOWING']=_SHOWING.' 7 '._INTERVAL_S;
  $fname=$name;
  if(strlen($fname)>_VS_PGSTITLINT) $sname=substr($fname,0,_VS_PGSTITLINT-3).'...';
  else $sname=$fname;
  if($page_id>200) $vars['FPG']=_FORGR." '<b><i>".$name."</i></b>'";
  else $vars['FPG']=_FORPG.' \'<b><i><a href="'.$url.'" title="'.$fname.'" target=_blank><code>'.$sname."</code></a></i></b>'";
  $vars['BACKTT']=_BACKTOTOP;
  $vars['PERIOD']=_TIMEINT;
  $vars['VISITORS']=_VISITORS;
  $vars['HOSTS']=_HOSTS;
  $vars['RELOADS']=_RELOADS;
  $vars['HITS']=_HITS;
  $vars['REF']='summary';
  $vars['DETAIL']=_DETAILED;
  tparse($top,$vars);
  $av=array();
  $maxv=0;
  $maxhs=0;
  $maxr=0;
  $maxht=0;
  mysql_data_seek($result,0);
  while($row=mysql_fetch_object($result)) {
      $vars['INTERVAL']='total';
      $vars['PERIOD']=_TOTAL.' ('.date($conf->dmas[$conf->dformat],$conf->btime).' - '.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      $vars['VISITORS']=$row->v;
      $vars['HOSTS']=$row->hs;
      $vars['RELOADS']=$row->r;
      $vars['HITS']=$row->ht;
      $av['v']=sprintf("%.0f",$row->v/$tdays);
      $av['hs']=sprintf("%.0f",$row->hs/$tdays);
      $av['r']=sprintf("%.0f",$row->r/$tdays);
      $av['ht']=sprintf("%.0f",$row->ht/$tdays);
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='lastmonth';
      if($conf->btime>=$conf->lmtime&&$conf->btime<$conf->mtime) $vars['PERIOD']=_LASTMONTH.' ('.date($conf->dmas[$conf->dformat],$conf->btime).' - '.date($conf->dmas[$conf->dformat],$conf->mtime-7200).')';
      else $vars['PERIOD']=_LASTMONTH.' ('.date($conf->dmas[$conf->dformat],$conf->lmtime).' - '.date($conf->dmas[$conf->dformat],$conf->mtime-7200).')';
      $vars['VISITORS']=$row->vlm;
      $vars['HOSTS']=$row->hslm;
      $vars['RELOADS']=$row->rlm;
      $vars['HITS']=$row->htlm;
      $av['vlm']=sprintf("%.0f",$row->vlm/$lmdays);
      $av['hslm']=sprintf("%.0f",$row->hslm/$lmdays);
      $av['rlm']=sprintf("%.0f",$row->rlm/$lmdays);
      $av['htlm']=sprintf("%.0f",$row->htlm/$lmdays);
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='month';
      if($conf->btime>$conf->mtime) $vars['PERIOD']=_MONTH.' ('.date($conf->dmas[$conf->dformat],$conf->btime).' - '.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      else $vars['PERIOD']=_MONTH.' ('.date($conf->dmas[$conf->dformat],$conf->mtime).' - '.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      $vars['VISITORS']=$row->vm;
      $vars['HOSTS']=$row->hsm;
      $vars['RELOADS']=$row->rm;
      $vars['HITS']=$row->htm;
      $av['vm']=sprintf("%.0f",$row->vm/$mdays);
      $av['hsm']=sprintf("%.0f",$row->hsm/$mdays);
      $av['rm']=sprintf("%.0f",$row->rm/$mdays);
      $av['htm']=sprintf("%.0f",$row->htm/$mdays);
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='lastweek';
      if($conf->btime>=$conf->lwtime&&$conf->btime<$conf->wtime) $vars['PERIOD']=_LASTWEEK.' ('.date($conf->dmas[$conf->dformat],$conf->btime).' - '.date($conf->dmas[$conf->dformat],$conf->wtime-7200).')';
      else $vars['PERIOD']=_LASTWEEK.' ('.date($conf->dmas[$conf->dformat],$conf->lwtime).' - '.date($conf->dmas[$conf->dformat],$conf->wtime-7200).')';
      $vars['VISITORS']=$row->vlw;
      $vars['HOSTS']=$row->hslw;
      $vars['RELOADS']=$row->rlw;
      $vars['HITS']=$row->htlw;
      $av['vlw']=sprintf("%.0f",$row->vlw/$lwdays);
      $av['hslw']=sprintf("%.0f",$row->hslw/$lwdays);
      $av['rlw']=sprintf("%.0f",$row->rlw/$lwdays);
      $av['htlw']=sprintf("%.0f",$row->htlw/$lwdays);
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='week';
      if($conf->btime>$conf->wtime) $vars['PERIOD']=_WEEK.' ('.date($conf->dmas[$conf->dformat],$conf->btime).' - '.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      else $vars['PERIOD']=_WEEK.' ('.date($conf->dmas[$conf->dformat],$conf->wtime).' - '.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      $vars['VISITORS']=$row->vw;
      $vars['HOSTS']=$row->hsw;
      $vars['RELOADS']=$row->rw;
      $vars['HITS']=$row->htw;
      $av['vw']=sprintf("%.0f",$row->vw/$wdays);
      $av['hsw']=sprintf("%.0f",$row->hsw/$wdays);
      $av['rw']=sprintf("%.0f",$row->rw/$wdays);
      $av['htw']=sprintf("%.0f",$row->htw/$wdays);
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='yesterday';
      $vars['PERIOD']=_YESTERDAY.' ('.date($conf->dmas[$conf->dformat],$ydtime).')';
      $vars['VISITORS']=$row->vy;
      $vars['HOSTS']=$row->hsy;
      $vars['RELOADS']=$row->ry;
      $vars['HITS']=$row->hty;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='today';
      $vars['PERIOD']=_TODAY.' ('.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      $vars['VISITORS']=$row->vt;
      $vars['HOSTS']=$row->hst;
      $vars['RELOADS']=$row->rt;
      $vars['HITS']=$row->htt;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $maxv=max($maxv,$av['v'],$av['vlm'],$av['vm'],$av['vlw'],$av['vw']);
      $maxhs=max($maxhs,$av['hs'],$av['hslm'],$av['hsm'],$av['hslw'],$av['hsw']);
      $maxr=max($maxr,$av['r'],$av['rlm'],$av['rm'],$av['rlw'],$av['rw']);
      $maxht=max($maxht,$av['ht'],$av['htlm'],$av['htm'],$av['htlw'],$av['htw']);
  }
  tparse($bottom,$vars);

  require './style/'.$conf->style.'/template/vti_ps_d.php';
  // VISITORS
  $vars['PERIOD']=_TIMEINT;
  $vars['TOTAL']=_VISITORS;
  $vars['AVERAGE']=_AVERAGE;
  $vars['GRAPHIC']=_GRAPHICFORA;
  $vars['HEADER']=_VISITORS.' / ';
  $vars['REF']='visitors';
  $vars['DETAIL']=_DETAILED;
  tparse($top,$vars);
  mysql_data_seek($result,0);
  while($row=mysql_fetch_object($result)) {
      $vars['INTERVAL']='total';
      $vars['PERIOD']=_TOTAL.' ('.date($conf->dmas[$conf->dformat],$conf->btime).' - '.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      $vars['TOTAL']=$row->v;
      $vars['AVERAGE']=$av['v'];
      $vars['GRAPHIC']=$maxv?$maxlen*$av['v']/$maxv:0;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='lastmonth';
      if($conf->btime>=$conf->lmtime&&$conf->btime<$conf->mtime) $vars['PERIOD']=_LASTMONTH.' ('.date($conf->dmas[$conf->dformat],$conf->btime).' - '.date($conf->dmas[$conf->dformat],$conf->mtime-7200).')';
      else $vars['PERIOD']=_LASTMONTH.' ('.date($conf->dmas[$conf->dformat],$conf->lmtime).' - '.date($conf->dmas[$conf->dformat],$conf->mtime-7200).')';
      $vars['TOTAL']=$row->vlm;
      $vars['AVERAGE']=$av['vlm'];
      $vars['GRAPHIC']=$maxv?$maxlen*$av['vlm']/$maxv:0;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='month';
      if($conf->btime>$conf->mtime) $vars['PERIOD']=_MONTH.' ('.date($conf->dmas[$conf->dformat],$conf->btime).' - '.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      else $vars['PERIOD']=_MONTH.' ('.date($conf->dmas[$conf->dformat],$conf->mtime).' - '.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      $vars['TOTAL']=$row->vm;
      $vars['AVERAGE']=$av['vm'];
      $vars['GRAPHIC']=$maxv?$maxlen*$av['vm']/$maxv:0;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='lastweek';
      if($conf->btime>=$conf->lwtime&&$conf->btime<$conf->wtime) $vars['PERIOD']=_LASTWEEK.' ('.date($conf->dmas[$conf->dformat],$conf->btime).' - '.date($conf->dmas[$conf->dformat],$conf->wtime-7200).')';
      else $vars['PERIOD']=_LASTWEEK.' ('.date($conf->dmas[$conf->dformat],$conf->lwtime).' - '.date($conf->dmas[$conf->dformat],$conf->wtime-7200).')';
      $vars['TOTAL']=$row->vlw;
      $vars['AVERAGE']=$av['vlw'];
      $vars['GRAPHIC']=$maxv?$maxlen*$av['vlw']/$maxv:0;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='week';
      if($conf->btime>$conf->wtime) $vars['PERIOD']=_WEEK.' ('.date($conf->dmas[$conf->dformat],$conf->btime).' - '.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      else $vars['PERIOD']=_WEEK.' ('.date($conf->dmas[$conf->dformat],$conf->wtime).' - '.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      $vars['TOTAL']=$row->vw;
      $vars['AVERAGE']=$av['vw'];
      $vars['GRAPHIC']=$maxv?$maxlen*$av['vw']/$maxv:0;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='yesterday';
      $vars['PERIOD']=_YESTERDAY.' ('.date($conf->dmas[$conf->dformat],$ydtime).')';
      $vars['TOTAL']=$row->vy;
      $vars['AVERAGE']='-';
      $vars['GRAPHIC']=0;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='today';
      $vars['PERIOD']=_TODAY.' ('.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      $vars['TOTAL']=$row->vt;
      $vars['AVERAGE']='-';
      $vars['GRAPHIC']=0;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
  }
  tparse($bottom,$vars);
  // HOSTS
  $vars['PERIOD']=_TIMEINT;
  $vars['TOTAL']=_HOSTS;
  $vars['AVERAGE']=_AVERAGE;
  $vars['GRAPHIC']=_GRAPHICFORA;
  $vars['HEADER']=_HOSTS.' / ';
  $vars['REF']='hosts';
  $vars['DETAIL']=_DETAILED;
  tparse($top,$vars);
  mysql_data_seek($result,0);
  while($row=mysql_fetch_object($result)) {
      $vars['INTERVAL']='total';
      $vars['PERIOD']=_TOTAL.' ('.date($conf->dmas[$conf->dformat],$conf->btime).' - '.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      $vars['TOTAL']=$row->hs;
      $vars['AVERAGE']=$av['hs'];
      $vars['GRAPHIC']=$maxhs?$maxlen*$av['hs']/$maxhs:0;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='lastmonth';
      if($conf->btime>=$conf->lmtime&&$conf->btime<$conf->mtime) $vars['PERIOD']=_LASTMONTH.' ('.date($conf->dmas[$conf->dformat],$conf->btime).' - '.date($conf->dmas[$conf->dformat],$conf->mtime-7200).')';
      else $vars['PERIOD']=_LASTMONTH.' ('.date($conf->dmas[$conf->dformat],$conf->lmtime).' - '.date($conf->dmas[$conf->dformat],$conf->mtime-7200).')';
      $vars['TOTAL']=$row->hslm;
      $vars['AVERAGE']=$av['hslm'];
      $vars['GRAPHIC']=$maxhs?$maxlen*$av['hslm']/$maxhs:0;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='month';
      if($conf->btime>$conf->mtime) $vars['PERIOD']=_MONTH.' ('.date($conf->dmas[$conf->dformat],$conf->btime).' - '.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      else $vars['PERIOD']=_MONTH.' ('.date($conf->dmas[$conf->dformat],$conf->mtime).' - '.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      $vars['TOTAL']=$row->hsm;
      $vars['AVERAGE']=$av['hsm'];
      $vars['GRAPHIC']=$maxhs?$maxlen*$av['hsm']/$maxhs:0;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='lastweek';
      if($conf->btime>=$conf->lwtime&&$conf->btime<$conf->wtime) $vars['PERIOD']=_LASTWEEK.' ('.date($conf->dmas[$conf->dformat],$conf->btime).' - '.date($conf->dmas[$conf->dformat],$conf->wtime-7200).')';
      else $vars['PERIOD']=_LASTWEEK.' ('.date($conf->dmas[$conf->dformat],$conf->lwtime).' - '.date($conf->dmas[$conf->dformat],$conf->wtime-7200).')';
      $vars['TOTAL']=$row->hslw;
      $vars['AVERAGE']=$av['hslw'];
      $vars['GRAPHIC']=$maxhs?$maxlen*$av['hslw']/$maxhs:0;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='week';
      if($conf->btime>$conf->wtime) $vars['PERIOD']=_WEEK.' ('.date($conf->dmas[$conf->dformat],$conf->btime).' - '.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      else $vars['PERIOD']=_WEEK.' ('.date($conf->dmas[$conf->dformat],$conf->wtime).' - '.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      $vars['TOTAL']=$row->hsw;
      $vars['AVERAGE']=$av['hsw'];
      $vars['GRAPHIC']=$maxhs?$maxlen*$av['hsw']/$maxhs:0;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='yesterday';
      $vars['PERIOD']=_YESTERDAY.' ('.date($conf->dmas[$conf->dformat],$ydtime).')';
      $vars['TOTAL']=$row->hsy;
      $vars['AVERAGE']='-';
      $vars['GRAPHIC']=0;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='today';
      $vars['PERIOD']=_TODAY.' ('.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      $vars['TOTAL']=$row->hst;
      $vars['AVERAGE']='-';
      $vars['GRAPHIC']=0;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
  }
  tparse($bottom,$vars);
  // RELOADS
  $vars['PERIOD']=_TIMEINT;
  $vars['TOTAL']=_RELOADS;
  $vars['AVERAGE']=_AVERAGE;
  $vars['GRAPHIC']=_GRAPHICFORA;
  $vars['HEADER']=_RELOADS.' / ';
  $vars['REF']='reloads';
  $vars['DETAIL']=_DETAILED;
  tparse($top,$vars);
  mysql_data_seek($result,0);
  while($row=mysql_fetch_object($result)) {
      $vars['INTERVAL']='total';
      $vars['PERIOD']=_TOTAL.' ('.date($conf->dmas[$conf->dformat],$conf->btime).' - '.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      $vars['TOTAL']=$row->r;
      $vars['AVERAGE']=$av['r'];
      $vars['GRAPHIC']=$maxr?$maxlen*$av['r']/$maxr:0;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='lastmonth';
      if($conf->btime>=$conf->lmtime&&$conf->btime<$conf->mtime) $vars['PERIOD']=_LASTMONTH.' ('.date($conf->dmas[$conf->dformat],$conf->btime).' - '.date($conf->dmas[$conf->dformat],$conf->mtime-7200).')';
      else $vars['PERIOD']=_LASTMONTH.' ('.date($conf->dmas[$conf->dformat],$conf->lmtime).' - '.date($conf->dmas[$conf->dformat],$conf->mtime-7200).')';
      $vars['TOTAL']=$row->rlm;
      $vars['AVERAGE']=$av['rlm'];
      $vars['GRAPHIC']=$maxr?$maxlen*$av['rlm']/$maxr:0;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='month';
      if($conf->btime>$conf->mtime) $vars['PERIOD']=_MONTH.' ('.date($conf->dmas[$conf->dformat],$conf->btime).' - '.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      else $vars['PERIOD']=_MONTH.' ('.date($conf->dmas[$conf->dformat],$conf->mtime).' - '.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      $vars['TOTAL']=$row->rm;
      $vars['AVERAGE']=$av['rm'];
      $vars['GRAPHIC']=$maxr?$maxlen*$av['rm']/$maxr:0;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='lastweek';
      if($conf->btime>=$conf->lwtime&&$conf->btime<$conf->wtime) $vars['PERIOD']=_LASTWEEK.' ('.date($conf->dmas[$conf->dformat],$conf->btime).' - '.date($conf->dmas[$conf->dformat],$conf->wtime-7200).')';
      else $vars['PERIOD']=_LASTWEEK.' ('.date($conf->dmas[$conf->dformat],$conf->lwtime).' - '.date($conf->dmas[$conf->dformat],$conf->wtime-7200).')';
      $vars['TOTAL']=$row->rlw;
      $vars['AVERAGE']=$av['rlw'];
      $vars['GRAPHIC']=$maxr?$maxlen*$av['rlw']/$maxr:0;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='week';
      if($conf->btime>$conf->wtime) $vars['PERIOD']=_WEEK.' ('.date($conf->dmas[$conf->dformat],$conf->btime).' - '.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      else $vars['PERIOD']=_WEEK.' ('.date($conf->dmas[$conf->dformat],$conf->wtime).' - '.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      $vars['TOTAL']=$row->rw;
      $vars['AVERAGE']=$av['rw'];
      $vars['GRAPHIC']=$maxr?$maxlen*$av['rw']/$maxr:0;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='yesterday';
      $vars['PERIOD']=_YESTERDAY.' ('.date($conf->dmas[$conf->dformat],$ydtime).')';
      $vars['TOTAL']=$row->ry;
      $vars['AVERAGE']='-';
      $vars['GRAPHIC']=0;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='today';
      $vars['PERIOD']=_TODAY.' ('.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      $vars['TOTAL']=$row->rt;
      $vars['AVERAGE']='-';
      $vars['GRAPHIC']=0;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
  }
  tparse($bottom,$vars);
  // HITS
  $vars['PERIOD']=_TIMEINT;
  $vars['TOTAL']=_HITS;
  $vars['AVERAGE']=_AVERAGE;
  $vars['GRAPHIC']=_GRAPHICFORA;
  $vars['HEADER']=_HITS.' / ';
  $vars['REF']='hits';
  $vars['DETAIL']=_DETAILED;
  tparse($top,$vars);
  mysql_data_seek($result,0);
  while($row=mysql_fetch_object($result)) {
      $vars['INTERVAL']='total';
      $vars['PERIOD']=_TOTAL.' ('.date($conf->dmas[$conf->dformat],$conf->btime).' - '.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      $vars['TOTAL']=$row->ht;
      $vars['AVERAGE']=$av['ht'];
      $vars['GRAPHIC']=$maxht?$maxlen*$av['ht']/$maxht:0;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='lastmonth';
      if($conf->btime>=$conf->lmtime&&$conf->btime<$conf->mtime) $vars['PERIOD']=_LASTMONTH.' ('.date($conf->dmas[$conf->dformat],$conf->btime).' - '.date($conf->dmas[$conf->dformat],$conf->mtime-7200).')';
      else $vars['PERIOD']=_LASTMONTH.' ('.date($conf->dmas[$conf->dformat],$conf->lmtime).' - '.date($conf->dmas[$conf->dformat],$conf->mtime-7200).')';
      $vars['TOTAL']=$row->htlm;
      $vars['AVERAGE']=$av['htlm'];
      $vars['GRAPHIC']=$maxht?$maxlen*$av['htlm']/$maxht:0;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='month';
      if($conf->btime>$conf->mtime) $vars['PERIOD']=_MONTH.' ('.date($conf->dmas[$conf->dformat],$conf->btime).' - '.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      else $vars['PERIOD']=_MONTH.' ('.date($conf->dmas[$conf->dformat],$conf->mtime).' - '.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      $vars['TOTAL']=$row->htm;
      $vars['AVERAGE']=$av['htm'];
      $vars['GRAPHIC']=$maxht?$maxlen*$av['htm']/$maxht:0;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='lastweek';
      if($conf->btime>=$conf->lwtime&&$conf->btime<$conf->wtime) $vars['PERIOD']=_LASTWEEK.' ('.date($conf->dmas[$conf->dformat],$conf->btime).' - '.date($conf->dmas[$conf->dformat],$conf->wtime-7200).')';
      else $vars['PERIOD']=_LASTWEEK.' ('.date($conf->dmas[$conf->dformat],$conf->lwtime).' - '.date($conf->dmas[$conf->dformat],$conf->wtime-7200).')';
      $vars['TOTAL']=$row->htlw;
      $vars['AVERAGE']=$av['htlw'];
      $vars['GRAPHIC']=$maxht?$maxlen*$av['htlw']/$maxht:0;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='week';
      if($conf->btime>$conf->wtime) $vars['PERIOD']=_WEEK.' ('.date($conf->dmas[$conf->dformat],$conf->btime).' - '.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      else $vars['PERIOD']=_WEEK.' ('.date($conf->dmas[$conf->dformat],$conf->wtime).' - '.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      $vars['TOTAL']=$row->htw;
      $vars['AVERAGE']=$av['htw'];
      $vars['GRAPHIC']=$maxht?$maxlen*$av['htw']/$maxht:0;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='yesterday';
      $vars['PERIOD']=_YESTERDAY.' ('.date($conf->dmas[$conf->dformat],$ydtime).')';
      $vars['TOTAL']=$row->hty;
      $vars['AVERAGE']='-';
      $vars['GRAPHIC']=0;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
      $vars['INTERVAL']='today';
      $vars['PERIOD']=_TODAY.' ('.date($conf->dmas[$conf->dformat],$conf->ctime).')';
      $vars['TOTAL']=$row->htt;
      $vars['AVERAGE']='-';
      $vars['GRAPHIC']=0;
      if($page_id<201) tparse($centerp,$vars);
      else tparse($centerg,$vars);
  }
  tparse($bottom,$vars);
  mysql_free_result($result);

?>
