CREATE TABLE favorites (id smallint(4) NOT NULL auto_increment, userid int(8) NOT NULL default '0', photo int(11) NOT NULL default '0', PRIMARY KEY  (id), KEY parent (photo)) TYPE=MyISAM;
CREATE TABLE laston (cat smallint(4) NOT NULL default '0', userid mediumint(9) NOT NULL default '0', laston int(11) unsigned default NULL, PRIMARY KEY  (cat,userid)) TYPE=MyISAM;
CREATE TABLE useralbums (id smallint(4) NOT NULL auto_increment,albumname varchar(255) NOT NULL default '',parent int(5) NOT NULL default '0',description varchar(255) default NULL,isprivate varchar(4) NOT NULL default 'no',password VARCHAR(16) NOT NULL,PRIMARY KEY (id),KEY parent(parent)) TYPE=MyISAM;
CREATE TABLE categories (id smallint(4) NOT NULL auto_increment,catname varchar(255) NOT NULL default '',description varchar(255) default NULL,catorder tinyint(4) NOT NULL default '0',thumbs varchar(4) NOT NULL default 'yes',parent int(5) NOT NULL default '0',header varchar(200) default NULL,footer varchar(200) default NULL,headtags varchar(200) default NULL,private varchar(5) NOT NULL default 'no',ugnoview VARCHAR(255) NULL,ugnoupload VARCHAR(255) NULL,ugnopost VARCHAR(255) NULL,ugnoanno VARCHAR(255) NULL,PRIMARY KEY (id),KEY parent(parent)) TYPE=MyISAM;
INSERT INTO categories VALUES (1,'Main','',2,'no',0,NULL,NULL,NULL,'no',NULL,NULL,NULL,NULL);
INSERT INTO categories VALUES (2,'A Category','Photos of a particular subject.',1,'yes',1,NULL,NULL,NULL,'no',NULL,NULL,NULL,NULL);
INSERT INTO categories VALUES (500,'Member Galleries','Individual user galleries - any photo category.',1,'yes',0,NULL,NULL,NULL,'no',NULL,NULL,NULL,NULL);
CREATE TABLE comments (id int(11) NOT NULL auto_increment,username tinytext NOT NULL,userid mediumint(9) NOT NULL default '0',date int(15) NOT NULL default '0',rating tinyint(4) default NULL,comment text NOT NULL,photo int(11) NOT NULL default '0',cat smallint(4) NOT NULL default '0',PRIMARY KEY (id),KEY photo(photo),KEY cat(cat)) TYPE=MyISAM;
CREATE TABLE perpage (id int(11) NOT NULL auto_increment,perpage tinyint(3) NOT NULL default '0',PRIMARY KEY (id)) TYPE=MyISAM;
INSERT INTO perpage VALUES (1,4);
INSERT INTO perpage VALUES (2,8);
INSERT INTO perpage VALUES (3,16);
INSERT INTO perpage VALUES (4,24);
CREATE TABLE photos (id int(10) NOT NULL auto_increment,user varchar(50) NOT NULL default '',userid int(8) NOT NULL default '0',cat int(11) NOT NULL default '0',date int(15) NOT NULL default '0',title varchar(75) NULL default '',description text NULL,keywords varchar(150) default NULL,bigimage varchar(100) NOT NULL default '',width smallint(6) default NULL,height smallint(4) default NULL,filesize mediumint(9) default '0',views int(10) NOT NULL default '0',medwidth int(12) default '0',medheight smallint(6) default '0',medsize mediumint(9) default '0',approved tinyint(2) NOT NULL default '0',lastpost int(15) NOT NULL default '0',rating int(2) NOT NULL default '0',watermarked varchar(5) NOT NULL default 'no',PRIMARY KEY (id),KEY userid(userid),KEY cat(cat),KEY bigimage(bigimage,cat)) TYPE=MyISAM;
CREATE TABLE settings (id int(11) NOT NULL auto_increment,title varchar(255) NOT NULL default '',varname varchar(25) NOT NULL default '',description varchar(150) NOT NULL default '',setting varchar(200) NOT NULL default '',optionorder int(3) NOT NULL default '0',section int(3) NOT NULL default '0', PRIMARY KEY (id)) TYPE=MyISAM;
INSERT INTO settings VALUES (1,'Title for your PhotoPost Application','galleryname','','My Photo Gallery',1,1);
INSERT INTO settings VALUES (2,'Web site name','webname','','My Website',2,1);
INSERT INTO settings VALUES (3,'Your Website URL (include http://)','domain','','http://www.domain.com',3,1);
INSERT INTO settings VALUES (4,'Administrator Email Address','adminemail','','admin@domain.com',4,1);
INSERT INTO settings VALUES (5,'Data directory virtual path','datadir','This is the web / virtual path to the data directory.','http://www.domain.com/photopost/data',25,1);
INSERT INTO settings VALUES (6,'Full path to PhotoPost data directory','datafull','Full path to the image files directory.','/path/to/your/photopost/data',26,1);
INSERT INTO settings VALUES (7,'URL to your forums main directory (optional)','vbulletin','This is the virtual path to your forum installation.','http://www.domain.com/forum',27,1);
INSERT INTO settings VALUES (8,'Full path to Header Include File','header','To include an HTML file as the header, enter the full path.','/path/to/php/header.htm',28,1);
INSERT INTO settings VALUES (9,'Full path to the footer include file','footer','To include an HTML file as the footer, enter the full path.','/path/to/php/footer.htm',29,1);
INSERT INTO settings VALUES (10,'Full path to HTML file containing head tags','headtags','','/path/to/php/headtags.htm',30,1);
INSERT INTO settings VALUES (11,'URL to PhotoPost PHP directory','maindir','','http://www.domain.com/photopost',31,1);
INSERT INTO settings VALUES (13,'Default number of comments per page','defaultposts','','15',53,2);
INSERT INTO settings VALUES (14,'Show Most Recent Additions on Index page?','mostrecent','','yes',54,2);
INSERT INTO settings VALUES (15,'Number of columns for thumbnail pages','thumbcols','','4',55,2);
INSERT INTO settings VALUES (16,'Default max diskspace for each user in Kb','maxspace','','1024',86,3)
INSERT INTO settings VALUES (17,'Default maximum file upload size in kB','uploadsize','','250',87,3);
INSERT INTO settings VALUES (18,'Thumbnail image max width and height in pixels','previewwidth','','100',88,3);
INSERT INTO settings VALUES (19,'Max allowable image width in pixels','maxwidth','','2500',89,3);
INSERT INTO settings VALUES (20,'Max allowable image height in pixels','maxheight','','2500',90,3);
INSERT INTO settings VALUES (21,'Trigger medium graphic height and width','biggraphic','An uploaded larger than this will create a medium image of this size.','600',91,3);
INSERT INTO settings VALUES (22,'Uploaded photos require admin approval?','moderation','','yes',92,4);
INSERT INTO settings VALUES (23,'Head bar Color','headcolor','','#BCBDBD',193,6);
INSERT INTO settings VALUES (24,'Head bar Font','verdana,arial','','verdana',194,6);
INSERT INTO settings VALUES (25,'Search bar text color','searchtext','','#000000',195,6);
INSERT INTO settings VALUES (26,'Category navigation text color','catnavcolor','','#000000',196,6);
INSERT INTO settings VALUES (27,'Search bar background color','navbarcolor','','#BCBDBD',197,6);
INSERT INTO settings VALUES (28,'Heading font color','headfontcolor','','#000000',198,6);
INSERT INTO settings VALUES (29,'Heading font type','headfont','','verdana',199,6);
INSERT INTO settings VALUES (30,'Table main background color','maincolor','','#FFFFFF',200,6);
INSERT INTO settings VALUES (31,'Table border color','bordercolor','','#660000',201,6);
INSERT INTO settings VALUES (32,'Main table text color','maintext','','#000000',202,6);
INSERT INTO settings VALUES (33,'Display photo and diskspace stats on index page?','stats','','yes',203,2);
INSERT INTO settings VALUES (34,'Comments alternating color number 1','altcolor1','','#F1F1F1',204,6);
INSERT INTO settings VALUES (35,'Comments alternating color number 2','altcolor2','','#DFDFDF',205,6);
INSERT INTO settings VALUES (36,'Comments main text color','commentstext','','#000000',206,6);
INSERT INTO settings VALUES (37,'cright','cright','','<Center><font size=\"1\" face=\"verdana\">Powered by: <!--CyKuH [WTN]-->PhotoPost --replaceme-- <Br>Copyright 2002 All Enthusiast, Inc.</font></center>',300,'0');
INSERT INTO settings VALUES (38,'Use email to notify users?','useemail','Users can be notified of photo approvals and deletions.','yes',301,5);
INSERT INTO settings VALUES (41,'User Registration System','vbversion','','2.2.0',304,1);
INSERT INTO settings VALUES (42,'Comments increment user post count?','cpostcount','','yes',93,5);
INSERT INTO settings VALUES (43,'Photo uploads increment user post count?','ppostcount','','yes',94,5);
INSERT INTO settings VALUES (44,'Save and display medium and large images?','bigsave','','yes',95,3);
INSERT INTO settings VALUES (45,'Number of columns for most recent additions section?','recentcols','','4',96,2);
INSERT INTO settings VALUES (46,'Number of photos to display in the most recent additions section?','recentnum','','12',97,2);
INSERT INTO settings VALUES (47,'Allow users to send e-Cards?','enablecard','','no',98,5);
INSERT INTO settings VALUES (49,'URL to PhotoPost images directory','idir','','http://www.domain.com/images',33,1);
INSERT INTO settings VALUES (50,'Depth (number of levels) of categories to display.','catdepth','','1',34,2);
INSERT INTO settings VALUES (51,'Allow users to be notified of new posts via email?','usenotify','','yes',305,5);
INSERT INTO settings VALUES (52,'Border color for photo details table.','detailbgcolor','','#E6E6E6',207,6);
INSERT INTO settings VALUES (53,'Background color for photo details table.','detailcolor','','#FFFFFF',208,6);
INSERT INTO settings VALUES (54,'Font color for photo details table.','detailfontcolor','','#000000',209,6);
INSERT INTO settings VALUES (55,'Remove upload file size and disk space limits for admins?','adminnolimit','','yes',100,4);
INSERT INTO settings VALUES (56,'Body color for forwarding page.','forwardbody','','#FFCC33',210,6);
INSERT INTO settings VALUES (57,'Exclude admin uploads from photo approval process?','adminexclude','','yes',101,4);
INSERT INTO settings VALUES (58,'Show post count and photo details for cats without thumbs?','catdetails','','no',211,2);
INSERT INTO settings VALUES (59,'Top level category (cats that do not contain thumbs) bg color.','topcatcolor','','#BCBDBD',212,6);
INSERT INTO settings VALUES (60,'Top level category (cats that do not contain thumbs) font color.','topcatfcolor','','#FFFFFF',213,6);
INSERT INTO settings VALUES (61,'Use COPPA for registration?','coppa','','yes',350,5);
INSERT INTO settings VALUES (62,'Full Path to Registration Rules, or leave blank for default','rules','','',351,5);
INSERT INTO settings VALUES (63,'Require verification of email address upon registration?','emailverify','','yes',353,5);
INSERT INTO settings VALUES (64,'Your mailing address to receive COPPA permission forms?','address','','',354,5);
INSERT INTO settings VALUES (65,'Full path to COPPA rules file, or leave blank for default?','copparules','','',352,5);
INSERT INTO settings VALUES (66,'Allow new user registrations?','allowregs','','yes',349,5);
INSERT INTO settings VALUES (67,'Allow users to upload photos?','allowup','','yes',84,5);
INSERT INTO settings VALUES (68,'Allow users to post comments?','allowpost','','yes',85,5);
INSERT INTO settings VALUES (69,'Show recent photos in default location (bottom)? (if no, will display at top)','recentdefault','','yes',56,2);
INSERT INTO settings VALUES (70,'Your Commission Junction<!--CyKuH [WTN]--> click-through URL','cjurl','','',5,1);
INSERT INTO settings VALUES (71,'Notify Admin of New Uploads?','uploadnotify','','yes',93,4);
INSERT INTO settings VALUES (72,'Show last photo thumbnail in member galleries listing?','membthumb','','yes',102,2);
INSERT INTO settings VALUES (75,'PhotoPost main table width, percent or pixels.','tablewidth','','100%',192,2);
INSERT INTO settings VALUES (76,'Require unique email addresses for user registration?','emailunique','','no',103,5);
INSERT INTO settings VALUES (78,'Show Random images on Index page?','disrandom','','no',55,2);
INSERT INTO settings VALUES (79,'Show Most Popular images on Index page?','dispopular','','no',55,2);
INSERT INTO settings VALUES (80,'Do you want to allow ZIP uploads?','allowzip','','no',53,5);
INSERT INTO settings VALUES (81,'PATH to ZIP upload directory? (If allowed)','zipuploaddir','','/path/to/uploads',53,5);
INSERT INTO settings VALUES (82,'URL to ZIP uploads directory?','zipuploadurl','','http://www.yoursite.com/uploads',53,5);
INSERT INTO settings VALUES (83,'Forum database table prefix','dprefix','','',53,1);
INSERT INTO settings VALUES (84,'PhotoPost Version','pversion','','3.1.0',53,0);
INSERT INTO settings VALUES (85,'Font size for category links','catfontsize','','2',53,6);
INSERT INTO settings VALUES (86,'Enable watermarking of photos with overlay image?','annotate','','no',60,3);
INSERT INTO settings VALUES (87,'If enabled, position of overlay watermark on images.','gravity','','SouthEast',61,3);
INSERT INTO settings VALUES (89,'If photo upload width or height exceeds maximums, resize upload down to max dimensions?','resizeorig','','yes',59,3);
INSERT INTO settings VALUES (90,'Full server path to watermark overlay image.','watermark','','',63,3);
INSERT INTO settings VALUES (91,'Allow users to move/delete their own images?','userdel','','no',58,5);
INSERT INTO settings VALUES (92,'Display Members Gallery on the main index page?','showmem','','yes',55,2)
INSERT INTO settings VALUES (93,'Require users to be registered to view images?','reqregister','','no',56,2);
INSERT INTO settings VALUES (94,'Use traditional Members Gallery configuration?','memformat','','yes',57,2);
INSERT INTO settings VALUES (95,'Display headers during SlideShows?','slidehead','','yes',58,2);
INSERT INTO settings VALUES (97,'Maximum multimedia upload size in Kb','mmuploadsize','','2000',88,3);
INSERT INTO settings VALUES (98,'Allow users to create Personal Albums?','allowpa','','yes',53,5);
INSERT INTO settings VALUES (99,'Allow multimedia uploads?','allowmedia','','no',88,3);
INSERT INTO settings VALUES (100,'Allow members to rate photos?','allowrate','','yes',54,5);
CREATE TABLE sort (sortid int(15) NOT NULL auto_increment, name varchar(35) NOT NULL default '', code varchar(75) NOT NULL default '', PRIMARY KEY (sortid)) TYPE=MyISAM;
INSERT INTO sort VALUES (2,'Latest','ORDER BY date DESC');
INSERT INTO sort VALUES (3,'Most Views','ORDER BY views DESC');
INSERT INTO sort VALUES (1,'Most Active','ORDER BY lastpost DESC');
INSERT INTO sort VALUES (4,'Most Popular','ORDER BY rating DESC, views DESC');
INSERT INTO sort VALUES (6, 'Random', 'ORDER BY RAND()');
INSERT INTO sort VALUES (5, 'Least Popular', 'ORDER BY views');
INSERT INTO sort VALUES (7, 'Alphabetical', 'ORDER BY bigimage');
CREATE TABLE admingroups (id int(3) NOT NULL auto_increment,name varchar(35) NOT NULL default '',PRIMARY KEY (id)) TYPE=MyISAM;
INSERT INTO admingroups VALUES (1,'Titles, Paths and Configuration');
INSERT INTO admingroups VALUES (2,'Index Display Options');
INSERT INTO admingroups VALUES (3,'Image and Diskspace Options');
INSERT INTO admingroups VALUES (4,'Admin Options');
INSERT INTO admingroups VALUES (5,'User and User Registration options');
INSERT INTO admingroups VALUES (6,'Colors and Fonts');
CREATE TABLE sortmemb (sortid int(15) NOT NULL auto_increment,name varchar(35) NOT NULL default '',code varchar(75) NOT NULL default '',PRIMARY KEY (sortid)) TYPE=MyISAM;
INSERT INTO sortmemb VALUES (2,'Date (newest first)','ORDER BY maxdate DESC');
INSERT INTO sortmemb VALUES (3,'Views (high to low)','ORDER BY tviews DESC');
INSERT INTO sortmemb VALUES (1,'Most Active','ORDER BY maxlast DESC');
INSERT INTO sortmemb VALUES (4,'Alphabetical Order','ORDER BY user ASC');
CREATE TABLE ecards (id int(25) NOT NULL auto_increment,fromname varchar(100) NOT NULL default '',toname varchar(100) NOT NULL default '',subject varchar(150) NOT NULL default '',message text NOT NULL,photoid int(25) NOT NULL default '0',date int(25) NOT NULL default '0',PRIMARY KEY (id)) TYPE=MyISAM;
CREATE TABLE notify (id int(15) NOT NULL auto_increment,userid int(25) NOT NULL default '0',photo int(25) NOT NULL default '0',PRIMARY KEY (id),KEY photo(photo)) TYPE=MyISAM;
CREATE TABLE users (userid int(25) NOT NULL auto_increment,usergroupid int(5) NOT NULL default '0',username varchar(100) NOT NULL default '',password varchar(100) NOT NULL default '',email varchar(150) NOT NULL default '',homepage varchar(250) default NULL,icq varchar(50) default NULL,aim varchar(100) default NULL,yahoo varchar(100) default NULL,joindate int(25) NOT NULL default '0',posts int(20) NOT NULL default '0',birthday date NOT NULL default '0000-00-00',ipaddress varchar(75) default NULL,location varchar(250) default NULL,interests varchar(250) default NULL,occupation varchar(250) default NULL,bio varchar(250) default NULL,site VARCHAR(30) default NULL,offset SMALLINT(2) UNSIGNED DEFAULT '0' NOT NULL,views int(10) NOT NULL default '0',PRIMARY KEY (userid)) TYPE=MyISAM;
CREATE TABLE ipcache (id int(10) NOT NULL auto_increment,userid INT(25) NOT NULL, ipaddr VARCHAR(75) NOT NULL, date INT(11) UNSIGNED, type VARCHAR(4) NOT NULL, photo INT(10) NOT NULL, PRIMARY KEY (id)) TYPE=MyISAM;