<?
/*
** ModernBill [TM] (Copyright::2001)
** Questions? webmaster@modernbill.com
**
**
**          Always save a backup before your upgrade!
**          Proceed with caution. You have been warned.
*/
 /* ----------------- AUTHNET_BATCH ---------------------*/
      $title = AUTHNETBATCH;
      $parent = array(1=>"client_info",2=>"client_invoice");
      $args = array(array("column"         => "an_id",
                           "required"      => 0,
                           "title"         => ID,
                           "type"          => "HIDDEN"),
                    array("column"         => "x_Invoice_Num",
                           "required"      => 0,
                           "size"          => 8,
                           "link_to_parent"=> 2,
                           "parent_op"     => "client_invoice",
                           "title"         => INVNUM,
                           "type"          => "TEXT"),
                    array("column"         => "x_Description",
                           "required"      => 0,
                           "size"          => 40,
                           "title"         => DESCRIPTION,
                           "type"          => "TEXT"),
                    array("column"         => "x_Amount",
                           "required"      => 0,
                           "size"          => 8,
                           "title"         => AMOUNT,
                           "type"          => "TEXT"),
                    array("column"         => "x_Method",
                           "required"      => 0,
                           "size"          => 8,
                           "title"         => METHOD,
                           "type"          => "TEXT"),
                    array("column"         => "x_Type",
                           "required"      => 0,
                           "size"          => 25,
                           "title"         => TYPE,
                           "type"          => "TEXT"),
                    array("column"         => "x_Card_Num",
                           "required"      => 0,
                           "size"          => 40,
                           "title"         => CCNUM,
                           "type"          => "TEXT"),
                    array("column"         => "x_Exp_Date",
                           "required"      => 0,
                           "size"          => 8,
                           "title"         => EXPIRATIONDATE2,
                           "type"          => "TEXT"),
                    array("column"         => "x_CC_Code",
                           "required"      => 0,
                           "size"          => 4,
                           "title"         => "CVV2/CVC2",
                           "type"          => "TEXT"),
                    array("column"         => "x_Cust_ID",
                           "required"      => 0,
                           "size"          => 8,
                           "title"         => CLIENTID,
                           "type"          => "HIDDEN",
                           "link_to_parent"=> 1),
                    array("column"         => "x_First_Name",
                           "required"      => 0,
                           "size"          => 25,
                           "title"         => FIRSTNAME,
                           "type"          => "TEXT"),
                    array("column"         => "x_Last_Name",
                           "required"      => 0,
                           "size"          => 25,
                           "title"         => LASTNAME,
                           "type"          => "TEXT"),
                    array("column"         => "x_Company",
                           "required"      => 0,
                           "size"          => 25,
                           "title"         => COMPANY,
                           "type"          => "TEXT"),
                    array("column"         => "x_Address",
                           "required"      => 0,
                           "size"          => 25,
                           "title"         => ADDRESS,
                           "type"          => "TEXT"),
                    array("column"         => "x_City",
                           "required"      => 0,
                           "size"          => 25,
                           "title"         => CITY,
                           "type"          => "TEXT"),
                    array("column"         => "x_State",
                           "required"      => 0,
                           "size"          => 25,
                           "title"         => STATEREGION,
                           "type"          => "TEXT"),
                    array("column"         => "x_Zip",
                           "required"      => 0,
                           "title"         => ZIP,
                           "size"          => 10,
                           "type"          => "HIDDEN"),
                    array("column"         => "x_Phone",
                           "required"      => 0,
                           "size"          => 10,
                           "title"         => PHONE,
                           "type"          => "TEXT"),
                    array("column"         => "x_Email",
                           "required"      => 0,
                           "size"          => 40,
                           "title"         => EMAIL,
                           "type"          => "TEXT"),
                    array("column"         => "an_stamp",
                           "required"      => 0,
                           "title"         => TIMESTAMP,
                           "type"          => "FUNCTION_CALL",
                           "no_edit"       => 1,
                           "function_call" => date_input_generator($an_stamp,"an_stamp")));

      $select_sql = "SELECT an_id, x_Invoice_Num, x_Amount, x_Type, x_Cust_ID, x_First_Name, x_Last_Name, x_Email, an_stamp FROM $db_table ";
      $insert_sql = "INSERT INTO $db_table (an_id, x_Invoice_Num, x_Description, x_Amount, x_Method, x_Type, x_Card_Num, x_Exp_Date, x_CC_Code, x_Cust_ID, x_First_Name, x_Last_Name, x_Company, x_Address, x_City, x_State, x_Zip, x_Phone, x_Email, an_stamp) VALUES (NULL, '$x_Invoice_Num', '$x_Description', '$x_Amount', '$x_Method', '$x_Type', '$x_Card_Num', '$x_Exp_Date', '$x_CC_Code', '$x_Cust_ID', '$x_First_Name', '$x_Last_Name', '$x_Company', '$x_Address', '$x_City', '$x_State', '$x_Zip', '$x_Phone', '$x_Email', '".mktime()."')";
      $update_sql = "UPDATE $db_table SET x_Invoice_Num='$x_Invoice_Num',
                                          x_Description='$x_Description',
                                          x_Amount='$x_Amount',
                                          x_Method='$x_Method',
                                          x_Type='$x_Type',
                                          x_Card_Num='$x_Card_Num',
                                          x_Exp_Date='$x_Exp_Date',
                                          x_CC_Code='$x_CC_Code',
                                          x_Cust_ID='$x_Cust_ID',
                                          x_First_Name='$x_First_Name',
                                          x_Last_Name='$x_Last_Name',
                                          x_Company='$x_Company',
                                          x_Address='$x_Address',
                                          x_City='$x_City',
                                          x_State='$x_State',
                                          x_Zip='$x_Zip',
                                          x_Phone='$x_Phone',
                                          x_Email='$x_Email',
                                          an_stamp='".mktime()."' WHERE an_id=$an_id ";
      $delete_sql = array("DELETE FROM $db_table WHERE an_id='$an_id'");
?>