<? 
mysql_query("
CREATE TABLE CAC_import_users_tmp (
  u char(64) NOT NULL default '',
  email char(64) NOT NULL default '',
  upline char(64) NOT NULL default '',
  status char(7) NOT NULL default '',
  ip char(12) NOT NULL default '',
  debit int(11) NOT NULL default '0',
  credit int(11) NOT NULL default '0',
  clicks bigint(20) NOT NULL default '0',
  first_name char(32) NOT NULL default '',
  last_name char(32) NOT NULL default '',
  address char(128) NOT NULL default '',
  city char(64) NOT NULL default '',
  state char(64) NOT NULL default '',
  zipcode char(16) NOT NULL default '',
  password char(16) NOT NULL default '',
  country char(32) NOT NULL default '',
  leads char(32) NOT NULL default '',
  joindate char(32) not null,
  upline2 char(64) NOT NULL default '',
  upline3 char(64) NOT NULL default '',
  upline4 char(64) NOT NULL default '',
  upline5 char(64) NOT NULL default '',
  upline6 char(64) NOT NULL default '',
  PRIMARY KEY  (u),
  KEY email (email),
  KEY upline (upline),
  KEY status (status),
  KEY ip (ip),
  KEY debit (debit),
  KEY credit (credit),
  KEY clicks (clicks),
  KEY first_name (first_name),
  KEY last_name (last_name),
  KEY address (address),
  KEY city (city),
  KEY state (state),
  KEY zipcode (zipcode),
  KEY password (password),
  KEY country (country),
  KEY leads (leads),
  KEY upline2 (upline2),
  KEY upline3 (upline3),
  KEY upline4 (upline4),
  KEY upline5 (upline5),
  KEY upline6 (upline6)
) TYPE=MyISAM");
