<?php
// If you want to provide your own header data, please place in this file.
// If you want to use the headerdata generated by FAQEngine, please delete this file.
// Remark: this file is ignored for the ASCII list output
?>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title><?php echo $l_heading?></title>
