// Greek lang variables by Jacaranda Bill

tinyMCE.addToLang('',{
table_desc : '&Aring;éóáãùãÞ ðßíáêá',
table_insert_row_before_desc : '&Aring;éóáãùãÞ ãñáììÞò &aring;ðÜíù',
table_insert_row_after_desc : '&Aring;éóáãùãÞ ãñáììÞò êÜôù',
table_delete_row_desc : '&Auml;éáãñá&ouml;Þ ãñáììÞò',
table_insert_col_before_desc : '&Aring;éóáãùãÞ óôÞëçò áñéóô&aring;ñÜ',
table_insert_col_after_desc : '&Aring;éóáãùãÞ óôÞëçò &auml;&aring;îéÜ',
table_delete_col_desc : '&Auml;éáãñá&ouml;Þ óôÞëçò',
insert_table_title : '&Aring;éóáãùãÞ/&Auml;éüñèùóç ðßíáêá',
insert_table_width : 'ÐëÜôïò',
insert_table_height : '¾øïò',
insert_table_cols : 'ÓôÞë&aring;ò',
insert_table_rows : 'ÃñáììÝò',
insert_table_cellspacing : '&Auml;éÜóôé÷ï',
insert_table_cellpadding : 'ÃÝìéóìá',
insert_table_border : 'Ð&aring;ñßãñáììá',
insert_table_align : 'Óôïß÷éóç',
insert_table_align_default : 'Ðñïêáè.',
insert_table_align_left : 'Áñéóô&aring;ñÜ',
insert_table_align_right : '&Auml;&aring;îéÜ',
insert_table_align_middle : 'Óôï êÝíôñï',
insert_table_class : 'ÊëÜóç',
table_row_title : 'Table row properties',
table_cell_title : 'Table cell properties',
table_row_desc : 'Table row properties',
table_cell_desc : 'Table cell properties',
insert_table_valign : 'Vertical alignment',
insert_table_align_top : 'Top',
insert_table_align_bottom : 'Bottom',
table_props_desc : 'Table properties',
table_bordercolor : 'Border color',
table_bgcolor : 'Bg color',
table_merge_cells_title : 'Merge table cells',
table_split_cells_desc : 'Split table cells',
table_merge_cells_desc : 'Merge table cells',
table_cut_row_desc : 'Cut table row',
table_copy_row_desc : 'Copy table row',
table_paste_row_before_desc : 'Paste table row before',
table_paste_row_after_desc : 'Paste table row after',
table_insert_desc : 'Insert a new table'
});
