// HE lang variables

tinyMCE.addToLang('table',{
general_tab : 'ëììé',
advanced_tab : 'îú÷ãí',
general_props : 'îàôééðéí ëììééí',
advanced_props : 'îàôééðéí îú÷ãîéí',
desc : 'îëðéñ èáìä çãùä',
row_before_desc : 'äëðñ ùåøä ìôðé',
row_after_desc : 'äëðñ ùåøä àçøé',
delete_row_desc : 'îç÷ ùåøä',
col_before_desc : 'äëðñ èåø ìôðé',
col_after_desc : 'äëðñ èåø àçøé',
delete_col_desc : 'îç÷ èåø',
rowtype : 'ùåøä áçì÷ ùì äèáìä',
title : 'äëðñ/ùðä èáìä',
width : 'øåçá',
height : 'âåáä',
cols : 'èåøéí',
rows : 'ùåøåú',
cellspacing : 'øéååç áéï úàéí',
cellpadding : 'øéôåã úàéí',
border : 'âáåì',
align : 'éùåø',
align_default : 'áøéøú îçãì',
align_left : 'ùîàì',
align_right : 'éîéï',
align_middle : 'îøëæ',
row_title : 'îàôééðé ùåøä áèáìä',
cell_title : 'îàôééðé úà áèáìä',
cell_type : 'ñåâ úà',
row_desc : 'îàôééðé ùåøä áèáìä',
cell_desc : 'îàôééðé úà áèáìä',
valign : 'éùåø àðëé',
align_top : 'ìîòìä',
align_bottom : 'ìîèä',
props_desc : 'îàôééðé èáìä',
bordercolor : 'öáò âáåì',
bgcolor : 'öáò ø÷ò',
merge_cells_title : 'îæâ úàéí áèáìä',
split_cells_desc : 'ôöì úàéí áèáìä',
merge_cells_desc : 'îæâ úàéí áèáìä',
cut_row_desc : 'âæåø ùåøä îäèáìä',
copy_row_desc : 'äòú÷ ùåøä îäèáìä',
paste_row_before_desc : 'äãá÷ ùåøä ìôðé',
paste_row_after_desc : 'äãá÷ ùåøä àçøé',
id : 'Id',
style: 'ñâðåï',
langdir : 'ëéååï ùôä',
langcode : '÷åã ùôä',
mime : 'ñåâ MIME ùì äéòã',
ltr : 'ùîàì ìéîéï',
rtl : 'éîéï ìùîàì',
bgimage : 'úîåðú ø÷ò',
summary : 'ñéëåí',
td : "îéãò",
th : "ëåúøú",
cell_cell : 'òãëï úà ðåëçé',
cell_row : 'òãëï àú ëì äúàéí áùåøä',
cell_all : 'òãëï àú ëì äúàéí áèáìä',
row_row : 'òãëï ùåøä ðåëçéú',
row_odd : 'òãëï ùåøåú àé-æåâéåú áèáìä',
row_even : 'òãëï ùåøåú æåâéåú áèáìä',
row_all : 'òãëï àú ëì äùåøåú áèáìä',
thead : 'ëåúøú äèáìä',
tbody : 'âåó äèáìä',
tfoot : 'ñéëåí äèáìä',
del : 'îç÷ èáìä',
scope : 'úçåí',
row : 'ùåøä',
col : 'èåø',
rowgroup : '÷áåöú ùåøåú',
colgroup : '÷áåöú èåøéí',
missing_scope: 'äàí àúä áèåç ùáøöåðê ìäîùéê îáìé ìöééï àú úçåí äëåúøú ùì äèáìä? áìé ëåúøú îåâãøú, éúëï ëé îùúîùéí áòìé îåâáìåéåú éú÷ùå ìäáéï àú äúåëï àå äîéãò äîåöâéí áèáìä.'
});
