<?php
$table_color[0]="#cccccc";
$table_color[1]="#dddddd";
$thumb_dir_color["r"]=204;
$thumb_dir_color["g"]=204;
$thumb_dir_color["b"]=204;
$thumb_text_color["r"]=100;
$thumb_text_color["g"]=10;
$thumb_text_color["b"]=10;
?>